### ISSUE TITLE
Paypal Overlay stays blank for *some* customers - v3.23.0, "this.resolve is not a function" and "invalid action" 

### ISSUE THREAD

**Issue by riftshadow** [Adyen/adyen-web#1007]
**Describe the bug**
A handful of customers are reporting that the PayPal Overlay open up without redirecting them to the login form (blank), currently i cannot provide any more details but this seems to only happen for *some* customers (~ ,5 - 1% of our overall paypal payments). I already forwarded this as ticket yesterday but since this is very technical and might be related to the `component.handleAction` method i would like to also have some feedback from actual devs. Our Sentry is reporting *some* cases where the `handleAction`fails with the following error messages (see the screenshot attached). We are still unsure if this is causes the issue...

**To Reproduce**
We current have *NO* way to reproduce it

**Expected behavior**
The customer should see the PayPal overlay which should actually load PayPal (but stays blank) so he can login and pay.

**Screenshots**
![CleanShot 2021-04-23 at 14 26 07](https://user-images.githubusercontent.com/15097024/115871013-4eb0bd80-a440-11eb-8027-9c1bd56deeb9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox 
 - Version: latest or "not that old"

**Smartphone (please complete the following information):**

**Additional context**
We are using the Adyen Web SDK v3.23.0 and the Adyen PHP SDK v9.0.0

**Comment by pabloai** [comment]
Hi @riftshadow,

Thanks for reaching out. I'm not being able to reproduce the issue but it could happen that you're not getting the right response from the backend, and that's the reason the component cannot pass the right information to the PayPal SDK. In order to find what's going wrong I'd need more information about those requests as well as more details about your implementation. If you're in contact with out Support team, feel free to mention my name and ask them to contact me to share the information you have so far.

**Comment by riftshadow** [comment]
Well i haven´t received any update yet (ticket has been created yesterday) and i doubt that someone will take care of it in time (usually tickets take 3-4 days for us to get any feedback). I can see that those payment has been created in the "Offers" view in the Adyen Backend which means that the `/payment` received all the required informations. 

1. Is there a way to close the PayPal Modal programmatically?
2. Does it help providing pspReferences inside of this issue?
3. We are also getting a error message which seems to be related to the adyen.js file, `this.resolve` is undefined *BUT* only for PayPal none other payment method
![CleanShot 2021-04-23 at 15 41 10](https://user-images.githubusercontent.com/15097024/115879909-7442c480-a44a-11eb-8b32-e0bdd79025ed.png)

**Comment by pabloai** [comment]
1. Not at the moment. This is something we could add but we'd need to find what's causing the issue anyway.
2. Sure, that would be really helpful, feel free to send them here and/or in the Support ticket.
3. That's indeed related to the PayPal component. The `Invalid action` message could be related to an unexpected response from the API which the BE is forwarding, but the error about `this.resolve` being undefined is odd. It seems on those cases the component handling the action is not the same which started it. Are you for example showing 2 PayPal buttons in different parts of the page?

**Comment by riftshadow** [comment]
@pabloai Thanks for your support,

i found out that this issue might not be related to the `Invalid Action` which is thrown by the `adyen/web` package, i updated the package from v3.23 to the latest available version. Sadly we still have customers which get a blank paypal overlay.

Also i cannot find ANY Sentry JS Error Reporting regarding those customers, which most likely means that the error is being thrown in the PayPal Button SDK. 

When the Adyen PayPal Component gets submitted it always "spams" our console with `console.info` (not sure if this is intended)
![CleanShot 2021-04-29 at 11 28 26](https://user-images.githubusercontent.com/15097024/116530337-32000400-a8de-11eb-8665-2506eafd6f30.png)

After reading this documentation regarding the PayPal Checkout Integration
https://developer.paypal.com/docs/checkout/integration-features/handle-errors/
it seems like PayPal have there own `onError` callback, is the `adyen/web` package using it? 
I´m pretty sure that those customers are getting PayPal Error Messages but as `console.error` or `console.log`.

Questions:
1.) Is there a way to handle every thrown error by the PayPal SDK?
2.) Is there a way to use the `onError` callback to report those errors to our Backend for the PayPal SDK ?

JFYI: we are also logging the `action` from the `/payments` responses, they totally work for me if i use them inside of the `handleAction` method.

Greetings

**Comment by riftshadow** [comment]
i mean these kind of errors, the adyen/web package does not seem to handle them in there own `onError` callback
![image](https://user-images.githubusercontent.com/15097024/116536595-6cb96a80-a8e5-11eb-82bc-cc6cba0fbdc1.png)

**Comment by riftshadow** [comment]
Sorry for bumping but i pretty sure i have a reproducable example which "seems" to be related to the PayPal Button Integration, we are logging the actual `action` which our frontend processes.

Action
`{
                "paymentData": "Ab02b4c0!BQABAgAuT08VbYM8Ej0LFne+TtwpWUUbC1UJJQ1j21lZHVcjkxsl+6nk4666GsHHqM98T+/LiaRNqy9t9P+dnSl5BWqBpwKOcqI4PjuG9QFObltT5cgEFrfBkkUcU0GDDkZn1NlfvUh/G4zYGfKUqBdKe2YxP0P4dvdXQTI8eZwymrc6VWxrBz/8vvJ/lUldEMEzEVpWF7DzHTKOQ4XGIZJizZ4m33CSq8ioQXs9hJa0/O7GCYRbKM2LJyg2iTZKJrGXasJ9JzB9zerX5LdbisL/mGp45Wj9IXwkjp3GYChHc+todlxCIanFfoTCHDFPgxfdGCrGxrOhEcJhx/9/cADHXwXUWXdH6PA/WTxbZSiQbhxH5CyU3rF1gPqmcU+OQhsYl/WhMHfzsDTq8oP4p7sqfDU3xtqk8+gm3WIe1n6KFRybQyEJwb5ESMByAMbgswq8BPhy7egtte7rPhWU6iClHa4bLgqDUXmigux/VWSY3kjqjXw2WYIJxWwKQmS97CK5IW88USGyQGT3ZtFdIt6RA7/YdOnd1To9OtN1vnJ+kyZNJi8rx+bLc0Z7sSnQ9XGdnYGrz6kLGaxVaoEkPabUmPilbLcDitlpWW/XSariuBEmotjx/Hl/s4uwkk30Y/v05+BbduPrO8oWKgcpZdibKjJGovkNQ6nvqGew3Dadf/5IoRBXyR9E0GF9u1BiwBBjHcqsAEp7ImtleSI6IkNDMkQ1Q0FEMEVDNjFDRDE0QUJCRkQyMThBMTFBNTE4QUFFNEMyNTI5MEZFOTlCN0MzMEJBNkMyOTJDNEZFQUYifSeJ15ahsqt6IIYhdOSSrEcAAGgCJRL6fRRyXeGZk5xER4SLJeBo2fnBco7GbOy0axOhnat4GdBWL2/ixdPr5EdLR39kXc0ZMGNxWIR0ouzJu1SJmzenJZmYpmCn3+aEGeNCFEKfUNhJgXkmt6+67PBwtnIQ29wo0PQUnyrzVooNMQAKacgthK1QXkn5wDA+ikdWzvsXOJHfJHJpUT00c2GpDT9qaUb2k3PUwMnaQcO3vGrz2yiuh7X7mpJKZg0FK4l0b8XetE5X7ulLtRuBcCUanZtIDyHLjGiAhmusrCYNpjyReRcWr5bKZmi7HS2DhHmZfdy9WzYY+aYhC7NoYMk9pWe5ZDV86Oa/cJE4J1k6Vaw877pukl2CUTgsJ2pAGmw2GT9mTFm7NvxqxjKP7Mo/k5rpuhPWuuSt+ThHZtgMsJnjqy+XKy3incAabWopw5VqHBnnOB/PHKyTAd3HpNfjoqXKFQbBlKSBkmY2PBeq/h+z6HzmfpX18lRHFWfSYzVcT2LZYqGDNYZpr1slhcIxF2lXmZJwCcBVIDK1oe/oq1QhUoniCGtNnUGBHOYJVHkK6mYpkNJ1qTsAiLOxL4pY3Do9rpccnmIH+uhrT01YCx1AbRRT7EqKnHHW4z6KkDie75I+/QTtxtmlI+f3V5sKSuwN6p6TjkOhZ+Au+6zmn4NzUyTDnXj4y/ATZkwF3cnLn+mG2SDh8C28AvaqVGIucN4P4F6lzx81f/i59d5IlvmlfC9A8GqVqWAbzaH7M4VioOqO8J9F9Db30etbwgCssrOYzA==",
                "paymentMethodType": "paypal",
                "sdkData": {
                    "token": "EC-9TJ69374UD310751D"
                },
                "type": "sdk"
            }`

Error Message(s) (JS):
![image](https://user-images.githubusercontent.com/15097024/116662924-b1e9a500-a996-11eb-85a0-1565e8b02539.png)


When this happends the overlay never stops loading

**Comment by EduardoMateos** [comment]
> Perdón por los golpes, pero estoy bastante seguro de que tengo un ejemplo reproducible que "parece" estar relacionado con la integración del botón de PayPal, estamos registrando lo `action`que procesa nuestra interfaz.
> 
> Acción
> `{ "paymentData": "Ab02b4c0!BQABAgAuT08VbYM8Ej0LFne+TtwpWUUbC1UJJQ1j21lZHVcjkxsl+6nk4666GsHHqM98T+/LiaRNqy9t9P+dnSl5BWqBpwKOcqI4PjuG9QFObltT5cgEFrfBkkUcU0GDDkZn1NlfvUh/G4zYGfKUqBdKe2YxP0P4dvdXQTI8eZwymrc6VWxrBz/8vvJ/lUldEMEzEVpWF7DzHTKOQ4XGIZJizZ4m33CSq8ioQXs9hJa0/O7GCYRbKM2LJyg2iTZKJrGXasJ9JzB9zerX5LdbisL/mGp45Wj9IXwkjp3GYChHc+todlxCIanFfoTCHDFPgxfdGCrGxrOhEcJhx/9/cADHXwXUWXdH6PA/WTxbZSiQbhxH5CyU3rF1gPqmcU+OQhsYl/WhMHfzsDTq8oP4p7sqfDU3xtqk8+gm3WIe1n6KFRybQyEJwb5ESMByAMbgswq8BPhy7egtte7rPhWU6iClHa4bLgqDUXmigux/VWSY3kjqjXw2WYIJxWwKQmS97CK5IW88USGyQGT3ZtFdIt6RA7/YdOnd1To9OtN1vnJ+kyZNJi8rx+bLc0Z7sSnQ9XGdnYGrz6kLGaxVaoEkPabUmPilbLcDitlpWW/XSariuBEmotjx/Hl/s4uwkk30Y/v05+BbduPrO8oWKgcpZdibKjJGovkNQ6nvqGew3Dadf/5IoRBXyR9E0GF9u1BiwBBjHcqsAEp7ImtleSI6IkNDMkQ1Q0FEMEVDNjFDRDE0QUJCRkQyMThBMTFBNTE4QUFFNEMyNTI5MEZFOTlCN0MzMEJBNkMyOTJDNEZFQUYifSeJ15ahsqt6IIYhdOSSrEcAAGgCJRL6fRRyXeGZk5xER4SLJeBo2fnBco7GbOy0axOhnat4GdBWL2/ixdPr5EdLR39kXc0ZMGNxWIR0ouzJu1SJmzenJZmYpmCn3+aEGeNCFEKfUNhJgXkmt6+67PBwtnIQ29wo0PQUnyrzVooNMQAKacgthK1QXkn5wDA+ikdWzvsXOJHfJHJpUT00c2GpDT9qaUb2k3PUwMnaQcO3vGrz2yiuh7X7mpJKZg0FK4l0b8XetE5X7ulLtRuBcCUanZtIDyHLjGiAhmusrCYNpjyReRcWr5bKZmi7HS2DhHmZfdy9WzYY+aYhC7NoYMk9pWe5ZDV86Oa/cJE4J1k6Vaw877pukl2CUTgsJ2pAGmw2GT9mTFm7NvxqxjKP7Mo/k5rpuhPWuuSt+ThHZtgMsJnjqy+XKy3incAabWopw5VqHBnnOB/PHKyTAd3HpNfjoqXKFQbBlKSBkmY2PBeq/h+z6HzmfpX18lRHFWfSYzVcT2LZYqGDNYZpr1slhcIxF2lXmZJwCcBVIDK1oe/oq1QhUoniCGtNnUGBHOYJVHkK6mYpkNJ1qTsAiLOxL4pY3Do9rpccnmIH+uhrT01YCx1AbRRT7EqKnHHW4z6KkDie75I+/QTtxtmlI+f3V5sKSuwN6p6TjkOhZ+Au+6zmn4NzUyTDnXj4y/ATZkwF3cnLn+mG2SDh8C28AvaqVGIucN4P4F6lzx81f/i59d5IlvmlfC9A8GqVqWAbzaH7M4VioOqO8J9F9Db30etbwgCssrOYzA==", "paymentMethodType": "paypal", "sdkData": { "token": "EC-9TJ69374UD310751D" }, "type": "sdk" }`
> 
> Mensaje (s) de error (JS):
> ![imagen](https://user-images.githubusercontent.com/15097024/116662924-b1e9a500-a996-11eb-85a0-1565e8b02539.png)
> 
> Cuando esto sucede, la superposición nunca deja de cargarse

We have the same problem. We use vue (nuxtjs)

Did you solve it?

thanks!

**Comment by ribeiroguilherme** [comment]
Hi @riftshadow ,

>Sorry for bumping but i pretty sure i have a reproducable example which "seems" to be related to the PayPal Button Integration, we are logging the actual action which our frontend processes.


This error that you mentioned is thrown by the PayPal SDK and not by `adyen-web`. Please double check your PayPal configuration on PayPal account and also on Adyen Customer Area.

> Questions:
1.) Is there a way to handle every thrown error by the PayPal SDK?
2.) Is there a way to use the onError callback to report those errors to our Backend for the PayPal SDK ?

Yes, you can pass `onError` callback to the PayPal configuration object and handle its errors there. I recommend to use the latest `adyen-web` version for it.

I am going to close this issue for now as it seems to be stale, but feel free to reach out if you need help. We can also reopen it if the problem is not solved yet.
