### ISSUE TITLE
Credit card number / brand validation

### ISSUE THREAD

**Issue by avgeeklucky** [Adyen/adyen-web#1018]
**Describe the bug**
Certain credit card brands are validated as false positive.

**To Reproduce**
1. Go to the customer area and configure the credit card payment method so that the  `"amex","bcmc","maestro","mc","visa"` brands are enabled.
2. Create a payment form using this library and the credit credit card payment method object from the `paymentMethods` API call (`type = scheme` and `fundingSource=credit`.)
3. Enter one of the following credit card numbers form the [Test Credit Card Numbers](https://docs.adyen.com/development-resources/test-cards/test-card-numbers#credit-and-debit-cards) documentation page.
    - 5019 5555 4444 5555 Dankort
    - 1354 1001 4004 955 UATP
    - 6011 1111 1111 1117 Discover 3DS2
4. Submit the details through the `payments` api call. This will result in an error response from the API:
```json
{
    "status": 500,
    "errorCode": "905",
    "message": "Payment details are not supported",
    "errorType": "configuration",
    "pspReference": "xxx"
}
```

**Expected behavior**
Cards of unsupported brands should not be deemed valid in the credit card form and therefore the form should not be submittable. The same as the hipercard screenshot below.

**Screenshots**
False-positive valid credit  card number (discover misidentified as maestro card):
![image](https://user-images.githubusercontent.com/30637897/116389555-6069da80-a81d-11eb-8226-9837199bfe43.png)

Invalid credit card  (hipercard)
![image](https://user-images.githubusercontent.com/30637897/116389725-927b3c80-a81d-11eb-9d77-48c1addfe969.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 90

**Smartphone (please complete the following information):**
 - n/a

**Additional context**
I if manually add `discover` to the `brands` option of `paymentMethods`, the example Discover 3DS2 number does identify correctly.
![image](https://user-images.githubusercontent.com/30637897/116391785-dec77c00-a81f-11eb-9378-18e8734223ab.png)

**Comment by pabloai** [comment]
Hi @avgeeklucky,

You can indeed pass an array of `brands` or you can make a call to the `/paymentMethods` endpoint and pass the response of that call as `paymentMethodsResponse` when creating the instance of `AdyenCheckout`, as described in the Add [Components to your payments form](https://docs.adyen.com/online-payments/components-web#step-2-add-components) section. The reason for doing this, is that said response will include the list of brands you have configured in your account.

Hope this helps!

**Comment by avgeeklucky** [comment]
Thanks @pabloai, I can confirm that is what we are doing. However my bug report is that some card numbers are misidentified as a different card type and validated when they shouldn't be.

**Comment by rowolff** [comment]
We recently had a similar issue that a card has been recognised as `brand=MASTER_CARD` where as in our backend and on our account we accept Mastercard as `mc`.

Is this related?

**Comment by sponglord** [comment]
Hello @avgeeklucky ,

What's happening here, I suspect, is that you are testing against our Test environment.
The databases here are not as well populated as on on Live environment.

If I test with these numbers (Dankort, UATP, Discover) on Test I can see that the responses to our `binLookup` API only contain `requestId` properties. This means the numbers are not in the DBs and we have had to fallback to our (fallable) internal regexs. (We know they are fallable - that's why we invented the binLookup endpoint!)

I will ask someone to look into making sure that our Test DBs are properly populated with our test card numbers.

**Comment by morcoteg** [comment]
@sponglord ignore that actually^, it looks like now I'm able to use the Test card numbers from the Adyen docs, and `onBrand` is now being triggered with the correct brands. Thanks if something happened behind the scenes! 🙏 🙇‍♂️

**Comment by morcoteg** [comment]
@sponglord but if I have "visa" in my `brands:` array (which I pass to the component), and I enter an Amex card, shouldn't the form throw validation errors? Or is that currently not functionality that exists since those other card numbers pass the Luhn check?

**Comment by sponglord** [comment]
@morcoteg - what version of Adyen Web are you using?
If you pass a brands array that doesn't contain Amex then when typing am Amex number in you should see an "unsupported card error":
![image](https://user-images.githubusercontent.com/22219050/140063978-7d37d1a1-a2d2-4b2c-aa29-4327201ac1e2.png)

**Comment by sponglord** [comment]
I am closing this ticket. If you feel that it is still an issue, and still happening with the latest versions, feel free to create a new issue

**Comment by pieczarkazsolt** [comment]
I tried a TEST amex card (3700 0000 0000 002) on TEST env and we got a: _not supported card message_, but when I test it on PROD env I don't get any error message. The supportedBrands are ["mc", "visa", "bcmc", "maestro"] in the conf

**Comment by sponglord** [comment]
@pieczarkazsolt - This is expected behaviour. Since it is a TEST card, 3700 0000 0000 002, won’t be present in the PROD databases, so it won’t be recognised. 
By default, in this situation, the frontend considers the card number to be valid (and lets the backend make the final decision as to whether to allow the payment.)
