### ISSUE TITLE
Apple Pay component onError is not called when I try to pay on non-enabled domain

### ISSUE THREAD

**Issue by MichalKalita** [Adyen/adyen-web#1069]
**Describe the bug**
I have a Apple Pay component and domain is not configured in apple pay adyen admin.

**To Reproduce**
1. Try to pay
2. Payment cancel automatically, because domain is wrong
In JS console is error log, but component didn't throw error, or onError callback. Actually it didn't call any callback when domain is wrong.

I cannot stop loading state in order, because I don't know if payment failed.

**Expected behavior**
onError should be triggered

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 14.5.1
 - Browser: safari

**Additional context**
Test environment

**Comment by marcperez** [comment]
Hi @MichalKalita,

Thanks for your feedback. This seems indeed like a good idea, we will add it to our backlog and come back to you once it's ready.

**Comment by ribeiroguilherme** [comment]
Hi @MichalKalita . We released the fix for this on 5.39.0.  Cheers
