### ISSUE TITLE
Initialization into Angular project

### ISSUE THREAD

**Issue by victorbadila** [Adyen/adyen-web#1080]
**Describe the bug**
Trying to add @adyen/adyen-web to my angular app and following the drop-in guide, but I get an error when initializing the component where it lives.

**To Reproduce**

1. In an Angular app install @ayden/ayden-web: npm i @ayden/ayden-web --save
2. In a component controller file have the following code:
```
// .component.ts
import AdyenCheckout from '@adyen/adyen-web';
import '@adyen/adyen-web/dist/adyen.css';

...

const configuration = { ... } // valid configuration and apiKey for all I know
const checkout = new AdyenCheckout(this.configuration);
const dropin = checkout
        .create('dropin', { openFirstPaymentMethod: false })
        .mount('#dropin');
```
3. In the view that belong to the same component have:
```
<div id="dropin"></div>
```
4. On page load there is the following error:
```
ERROR Error: Component could not mount. Root node was not found.
    at e.t.mount (adyen.js:1)
```

**Expected behavior**
I would expect the component to mount successfully. I have read on https://docs.adyen.com/online-payments/components-web/ that "If you are using JavaScript frameworks such as Vue or React, make sure that you use references instead of selectors and that you don't re-render the DOM element." and I have tried to target the dom element in other ways, with a @ViewChild angular decorator + # notation in the view for example, but to no success and I didn't find an example or documentation that applies to angular.

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Version: latest

**Comment by marcperez** [comment]
Hi @victorbadila,

Thanks for reaching out. It seems like the node where the component is trying to mount doesn't exist at the time `mount()` is called. I would suggest double checking that the `mount()` method is called after the view is fully rendered and that a reference is used instead of a selector to the DOM element. Hope this helps!

**Comment by marcperez** [comment]
Hopefully this example will help too:

https://github.com/adyen-examples/adyen-angular-online-payments/blob/master/checkout/src/app/components/checkout/checkout.component.ts

**Comment by victorbadila** [comment]
Looks like it worked. Thanks!
