### ISSUE TITLE
Unlisted Amazon Pay error code 5_616

### ISSUE THREAD

**Issue by gndk** [Adyen/adyen-web#1081]
**Describe the bug**
We followed the docs for integrating Amazon Pay at https://docs.adyen.com/payment-methods/amazon-pay/web-component exactly, but on `checkout.create` we get a "Could not get AmazonPay signature" error and this response:

```
{
   "status":500,
   "errorCode":"5_616",
   "message":"Amazon Pay Payment Token key hash does not match",
   "errorType":"configuration"
}
```

This error code is not listed on https://docs.adyen.com/development-resources/error-codes#amazon-pay-error-codes
They only go up to 615 :-).

**Expected behavior**
Integration works or the error is documented.

**Additional context**
I verified that MerchantId, PublicKeyId and StoreId all match between the `checkout.paymentMethodsResponse` and Amazon Pay backend.

The key pair was set up by Adyen support according to https://docs.adyen.com/payment-methods/amazon-pay/web-component#step-3.

**Comment by gndk** [comment]
The support was quick to help us :-)

We had multiple API users for each dev / environment, but the keypair for Amazon Pay was only set up for the main user.

Unfortunately we weren't aware of that and assumed it was account-wide 🙃

**Comment by marcperez** [comment]
Hi @gndk, happy this was resolved by our support team, thanks for reaching anyway!
