### ISSUE TITLE
Google Play icon outdated

### ISSUE THREAD

**Issue by xevichg** [Adyen/adyen-web#1091]
Hi,

Google is refusing the integration arguing that icon is outdated:

From Google:
Please refer to the attached screenshot. Please update the Google Pay mark  for each integration and resubmit through the Business Console. 

Please make or provide the appropriate updates, and re-submit your integration again through Business Console. If the above marketing review feedback cannot be implemented because you are using a dedicated Plugin or provided hosted checkout solution from your Payment Service Provider, please reach out to us by responding to this email. 

![g-pay-complain](https://user-images.githubusercontent.com/71013446/119109881-df6bc080-ba21-11eb-8a6f-83476f3aed8e.jpg)

**Comment by marcperez** [comment]
Hi @xevichg,

Thanks for reaching out. We're in the process of updating this icon and it should be live next week. No library update is required since it's an image hosted on Adyen's servers. Hope this helps!

**Comment by marcperez** [comment]
Hi @xevichg,

The fix for this has been released on v4.6.0. I'll close this issue, but feel free to reopen if you still have further questions. Thanks!
