### ISSUE TITLE
Swish flow

### ISSUE THREAD

**Issue by bitbytebit1** [Adyen/adyen-web#1093]
**Describe the bug**
When paying with Swish a new tab is opened regardless of outcome. 

**To Reproduce**
(In Live environment)
1. Pay with Swish
2. Click cancel OR complete payment

**Expected behavior**
The user should be returned to the the page where they initiated the payment instead of a new tab being opened

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser: Chrome

**Additional context**
There could potentially be a configuration option to toggle this behaviour. 
Swish has the capability to work without opening a new tab, however the flow is slightly different, instead of opening a "swish://" link you iniate a payment request and ask the user to open Swish themselves. This behaviour can be seen for example here: http://sj.se.

Would be very nice to see adyen offer support for both flows.

**Comment by H4ckint0sh** [comment]
Did you ever find a solution for this? I am having  the same problem now.

**Comment by DavidVujic** [comment]
I think this is also an issue on iOS. When navigated back from the Swish app to the browser (iOS Safari) there are two tabs.

**Comment by ribeiroguilherme** [comment]
Hi @bitbytebit1 @DavidVujic @H4ckint0sh - is this issue still relevant? is the new tab being opened after paying through the app? I am afraid that this might be something out of Adyen control.

**Comment by Stensfelt** [comment]
Hi @ribeiroguilherme ,
We experience this issue as well. I'm using Chrome on iPhone, getting sent to the Swish-app. When getting redirected back to Chrome there is a second tab opened. This leads to us doing two requests to payment/details:
1. The old tab gets the payment info through onAdditionalDetails
2. The new tab gets redirectResult appended to the url

We are using V70 and 5.38.

**Comment by mantono** [comment]
We contacted Adyen support about this issue in the past. Their response was

> This is indeed a known issue on our end and we are working on a fix for this.
> ...
> Unfortunately I cannot provide you with a precise ETA, but it is sure that our developers are aware and are working on a fix.

They provided us with instructions for a work around, I can share it with you. We never implemented this ourselves, but we went with a different solution.

![screenshot-1682681512](https://user-images.githubusercontent.com/7093365/235136651-37e409ec-8f8d-494c-8018-e162080df389.png)

**Comment by sponglord** [comment]
> we went with a different solution

@mantono - Can I close this issue then?

**Comment by mantono** [comment]
@sponglord If you are happy with the work around. It "works" for us now (with a different solution), but it would be nice with a solution that solves this problem properly.

**Comment by sponglord** [comment]
@mantono - can you share what solution you used?

**Comment by mantono** [comment]
> @mantono - can you share what solution you used?

So we were not able to prevent a new tab from being opened. What we did instead was that whenever a new checkout session was created in the browser, we check if a Swish payment is already in progress. If that is the case we will not accept any new payment attempts in the new tab, and rather inform the consumer that a payment is either in progress or completed.

Obviously, this does not fix the core issue with multiple tabs being opened, but it does (for us) fix the issue with the consumers potentially paying twice.

**Comment by ribeiroguilherme** [comment]
We discussed internally with the team and it seems that this issue got fixed in the API v70, therefore I am closing this ticket. If the problem persists, please reach out to our support team so they can investigate it further. Cheers
