### ISSUE TITLE
Cannot test Maestro stored card with optional CVC/CVV

### ISSUE THREAD

**Issue by Dryunya** [Adyen/adyen-web#1132]
**Describe the bug**
Payment (for Maestro stored card without CVV) fails with error: {"status":422,"errorCode":"14_029","message":"Required field 'cvc' is not provided.","errorType":"validation"}

**To Reproduce**
1. Start payment with Maestro test card:  5000 5500 0000 0029 | 03/2030 | n/a
2. Finalize payment with the 'Save for my next payment' option and empty CVV
3. Start new payment with a previously saved card.
4. Finalize payment with empty CVV
5. Result: Error in the /payments response: {"status":422,"errorCode":"14_029","message":"Required field 'cvc' is not provided.","errorType":"validation"}

**Expected behavior**
Payment finished without errors like for the new Credit cards.

**Screenshots**
![Maestro](https://user-images.githubusercontent.com/28042851/120645222-d8f93200-c480-11eb-9b0e-ad6a7dd715b1.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 90

**Smartphone (please complete the following information):**
n/a

**Additional context**
The problem was tested with my integration and with [example on github](https://github.com/adyen-examples/adyen-dotnet-online-payments) (results are the same)

**Comment by ribeiroguilherme** [comment]
Hi @Dryunya. Does this issue still relevant?

**Comment by ribeiroguilherme** [comment]
Closing this issue for now. Feel free to reach out to us again if the problem persists.
