### ISSUE TITLE
Google Pay currency is not visible on overlay

### ISSUE THREAD

**Issue by SAgrawa9** [Adyen/adyen-web#1141]
This request is on-behalf of **IAG Limited** Australia.

While making a payment using GooglePay, the amount value is visible on the GooglePay overlay only for EUR not for other currencies.

<img width="747" alt="Screen Shot 2021-06-01 at 4 51 07 pm" src="https://user-images.githubusercontent.com/35677401/120961264-d1979880-c7a0-11eb-843f-554f04076dca.png">

We are using the latest adyen-web library 4.5.0.

Can you please help us to resolve this issue?

Thanks,
Sagar Agrawal

**Comment by marcperez** [comment]
Hi @SAgrawa9,

Thanks for reaching out. This behavior appears to be connected to the `countryCode` property. Could you try adding the `countryCode` as shown in the [Google Pay component documentation](https://docs.adyen.com/payment-methods/google-pay/web-component#show-google-pay-in-your-payment-form)? Hope this solves the issue!

**Comment by SAgrawa9** [comment]
Hi Marc,

PFA, screenshot, I am using all the possible configurations still I am facing same issue.

[Image.jpeg]

Thanks,
Sagar Agrawal
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by marcperez** [comment]
Hi @SAgrawa9,

Unfortunately I can't see the screenshot. Could you verify you're sending the `countryCode` as in the [documentation example](https://docs.adyen.com/payment-methods/google-pay/web-component)?

```js
const googlepay = checkout.create("paywithgoogle", {
    environment: "TEST", //Change this to PRODUCTION when you're ready to accept live Google Pay payments.
    amount: {
      currency: "EUR",
      value: 1000
    },
    countryCode: "NL"
});
```

Thanks!

**Comment by SAgrawa9** [comment]
Hi Marc,

I have the same config. Currency is AUD and countryCode is AU.

Thanks,
Sagar Agrawal

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ribeiroguilherme** [comment]
@SAgrawa9 Are you still having problems with GooglePay?

**Comment by SAgrawa9** [comment]
Hi Team,

I moved out of the client who were using Adyen. This is not required to me now.

Thanks,
Sagar Agrawal

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
