### ISSUE TITLE
[Accessibility] - iOS VoiceOver prevents customers from selecting payment methods

### ISSUE THREAD

**Issue by johndoeblocks** [Adyen/adyen-web#1147]
**Describe the bug**
At the checkout, it is not possible to change the payment method to something else than what is already selected. Since credit card is the default option, that is the only choice given to someone using VoiceOver. Any screen reader user who wishes to use another payment method will be unsuccessful in completing the order. 

By inspecting the code, we can see that these radio buttons are not native HTML radio buttons. And as such different screen readers might have problem getting focus. 

**Steps to reproduce the behavior:**

With an iPhone with VoiceOver on:
Settings > Accessibility > VoiceOver

1. Go to https://www.mystoredemo.io/#/ 
2. Add an item
3. Open cart and select checkout
4. Try switch between payment methods
5. See error

**Expected behavior**
As other screen readers the expected behavior would be to be able to switch between payment methods with a simple slide on the screen.

**Video**
Video displaying the bug.
https://user-images.githubusercontent.com/85570868/121215884-4e497600-c878-11eb-87a5-ea83610f3771.mp4

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS14.5
 - Browser: Chrome 

**Additional Context**
We are using the Adyen Web SDK v3.15.1 

Thank you in advance.

**Comment by marcperez** [comment]
Hi @joaooliveiramanteigas,

Thanks for reaching out.

We're currently reviewing the accessibility of our Drop-in component. Your comment is very useful to us and we have added this issue to our internal backlog. Please let us know if you have any other accessibility feedback.
