### ISSUE TITLE
Drop-in form loading spinner keeps spinning after initiate payment request is over

### ISSUE THREAD

**Issue by victorbadila** [Adyen/adyen-web#1162]
**Describe the bug**
I implemented a dropin in an Angular poject, was able to integrate with the server, list payment methods -> the dropin gets initialized, use a test credit card then press pay. I get the response and I can see that the loading spinner in the button is still spinning.

In the case of failure I would like the user to be able to retry the action, maybe they got the CVC or expiry date wrong, etc., however the form is locked in the loading state.

**To Reproduce**
1. Implement drop in, fill in card details press "pay"
2. Wait for response to come back
3. See that the loading spinner on the dropin button is still spinning

**Expected behavior**
I would expect the loading spinner to stop, or to have some control over it and stop it and reset the form if it fits the case.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome / Opera
 - Version latest

**Comment by marcperez** [comment]
Hi @victorbadila,

Thanks for reaching out. After a payment is completed with the Drop-in, you can either show your own success/error message, or use our success and error Drop-in statuses:

```js
// Show a success message
dropin.setStatus('success');
dropin.setStatus('success', { message: 'Payment successful!' });

// Show an error message
dropin.setStatus('error');
dropin.setStatus('error', { message: 'Something went wrong.'});

// Set a loading state
dropin.setStatus('loading'); // start the loading state
dropin.setStatus('ready'); // set back to the initial state
```
You can find all this information in our [Drop-in integration guide](https://docs.adyen.com/online-payments/drop-in-web#step-6-present-payment-result). Hope this helps!

**Comment by victorbadila** [comment]
Thanks for the answer. Given the context of angular I guess that the "dropin" referenced here is what gets mounted in the hook as a view child? In the angular example there's no mention of this and it isn't clear from the documentation above how exactly to get hold of it.

**Comment by asfo** [comment]
> Thanks for the answer. Given the context of angular I guess that the "dropin" referenced here is what gets mounted in the hook as a view child? In the angular example there's no mention of this and it isn't clear from the documentation above how exactly to get hold of it.

If someone need it, its on the component response.

In the examples of Angular its something like this:
```
handleServerResponse(res: any, component: any) {
```

The `component` parameter is allowed to use the `.setStatus()` function.

It worked for us.

**Comment by LukasDrP** [comment]
i ran into an similar problem and made this to reload but not remount the dropin:
```
this.dropin.setStatus('loading');
setTimeout(()=>{this.dropin.setStatus('ready');}, 500);
```
also gives a nice fade effect

**Comment by ribeiroguilherme** [comment]
@victorbadila the `dropin` is referenced by the `onSubmit(state, component)`, which `component` refers to the `dropin` instance 😃  In our Angular example it is named as `component` though.

You can achieve what you want by doing:

```javascript
onSubmit: (state, dropin) => {
    ...
    dropin.setStatus('ready');
    ...
},
```

I hope this helps!
