### ISSUE TITLE
onAdditionalDetails called twice when aborting threeds2 once

### ISSUE THREAD

**Issue by haelbichalex** [Adyen/adyen-web#1171]
**Describe the bug**
I'm using Vue, so I was able to reproduce this issue with this repository: https://github.com/adyen-examples/adyen-vue-online-payments
When using a credit card with 3D Secure 2 enabled (https://docs.adyen.com/development-resources/test-cards/test-card-numbers#test-3d-secure-2-authentication) and aborting the threeds2 step once, the `onAdditonalDetails` event is fired twice, with the first one (which tries to handle the first order) fails and the second one is successful. I think it should only try to call this event once.
Can this event handler be destroyed somehow?

**To Reproduce**
1. Use dropin or card component
2. Use 3d secure 2 card (https://docs.adyen.com/development-resources/test-cards/test-card-numbers#test-3d-secure-2-authentication)
3. Make order and you will be redirected to 3d secure page 
![Bildschirmfoto 2021-06-18 um 16 00 14](https://user-images.githubusercontent.com/15052352/122572746-552d7100-d04e-11eb-9c36-3542a5c2f0fb.png)
4. Don't continue and go to homepage by clicking on the logo for example (and don't reload!)
5. Go to checkout again and order again
6. Complete threeds2 step by clicking `Submit`
7. `onAdditonalDetails` fired twice

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by haelbichalex** [comment]
I got this nice solution from the adyen support team, which fixed it for our own integration, as well as the vue example:

<hr>

in `components/Navbar.vue`:

`+ id="home" to <img src="~/assets/images/mystore-logo.svg" alt="Mystore logo" />​`

Then in `pages/checkout/_payment.vue` on Line 121:
```js
 const integration = checkout.create(ref.type).mount(ref.$refs[ref.type]);
 function unmountChallenge (){
     console.log("Unmounting to prevent duplicate /api/submitAdditionalDetails call")
     integration.unmount()
    };
 document.getElementById("home").addEventListener('click', function () {
     unmountChallenge()
 });
```

This unmounts dropin, thus where the native challenge is hosted and cancels the transaction meaning when the shopper returns, there won't be a duplicate onAdditionalDetails​ call made.

<hr>

So `integration.unmount()` is what is needed for this kind of behavior.

**Comment by st3r30t1p** [comment]
I have the same issue on v3.18.2 I use react and method remove() not help with this.
Can anyone tell me what I do wrong ?
