### ISSUE TITLE
Paypal SDK Intent error

### ISSUE THREAD

**Issue by NickCirculy** [Adyen/adyen-web#1172]
**Describe the bug**
Paypal "Authorize" issue. When adding Paypal as a Payment method and selecting the "authorize and capture" flow. This will cause the SDK to be loaded from the package incorrectly when the capture setting in our merchant is set to **manual**

**To Reproduce**
use the latest NPM package. Set the capture method to **manual**. Make sure that when adding the payment method to Paypal is set to **Authorize and Capture** so we can have this in a separate flow.

**Expected behavior**
When asking the user to Authorize a payment, that they are taken to Paypal.

**Bug**
After clicking the smart button there is an error message coming from the Paypal SDK stating:
**Expected intent from order api call to be capture, got authorize. Please ensure you are passing intent=authorize to the sdk url. https://developer.paypal.com/docs/checkout/reference/customize-sdk/**

As stated in the docs, we are loading the component correctly:
`configuration: {
          merchantId: 'merchant-id',
          intent: 'authorize',
        },`

**solution**
We were able to get this working by simply adding this within the SDK loading URL: `intent=authorize&`
It seems that the "configuration" setting that can be added to the Component is not accounted for, so would be great if you can provide a fix for this.

**Comment by fhaertig** [comment]
Hi,

I'm experiencing the same issue, would be nice to get a fast fix for this. Meanwhile, I wonder how you managed to change the SDK loading url - could you give me a hint?

Thanks in advance!

**Comment by ribeiroguilherme** [comment]
Hi @NickCirculy ,

Thanks for reaching out. The `configuration` property is working as expected on the current version (v5.5.0). You should be able to configure the `merchantId` and the `intent` there, although It is recommended to use the configuration that comes from the `/paymentMethods` API call.  I hope it helps!
