### ISSUE TITLE
Extend Pay button component to have a disabled state 

### ISSUE THREAD

**Issue by guidosreis** [Adyen/adyen-web#1175]
**Is your feature request related to a problem? Please describe.**
Currently, in our website, we show two PayPal buttons on the same page (two different instances of the component), one on the top of the page, and another one on the bottom, and depending on how big is the screen of the customer, both buttons can be visible at the same time.
When the customer interacts with the top button, of vice versa, and pays for the order, the button will have a loading state, until it gets the response with the redirect action, meanwhile, the other button remains on its initial state, so the customer can also click on it.

**Describe the solution you'd like**
I would like to know if it is possible to implement a way to disable a given Pay button, so in the case I've described above, we could easily disable the button that didn't receive the interaction from the customer, preventing it from being clicked, while the other is on its loading state.

**Comment by ribeiroguilherme** [comment]
@guidosreis thanks for reaching out.

Our solution already provides the loading state for the components/dropin. If you would like to use multiple instances in the same page, and block one of them while the other is performing the payment, you need to do that by yourself through CSS.

You can achieve that by applying `pointer-events:none` to the button, and also add some overlay on top of it to simulate the disabled state. I hope it helps!
