### ISSUE TITLE
Change the italian holderName translation

### ISSUE THREAD

**Issue by dambrosid** [Adyen/adyen-web#1176]
**Is your feature request related to a problem? Please describe.**
In Italy, at least, very often the prepaid cards don't have the name on the card.
The label "creditCard.holderName": "Name on card" is literally translated with "Nome sulla carta".
Very often happens that the customer doesn't fill that field because of any name is on the card and this will generate errors.
Instead, a card owner always exists.

**Describe the solution you'd like**
I suggest to change the italian translation from "Nome sulla carta" to "Titolare carta".
Indeed, the label "creditCard.holderName.invalid": "Nome del titolare della carta non valido" is already corrected.

**Describe alternatives you've considered**
The alternative solution I'm considering is to follow that guide:
https://docs.adyen.com/online-payments/components-web/localization-components
That solution should be ok for us but I guess this enhancement could help other merchants too.

**Comment by marcperez** [comment]
Hi @dambrosid,

Thanks for reaching out. This is very good feedback and we agree "Titolare carta" makes much more sense in this context.
Therefore we've updated our source strings and we'll publish the updated translation in a future release. In the meantime, you can always customize any translation using the following guide: 
https://docs.adyen.com/online-payments/drop-in-web/customization#customizing-a-localization.

Hope this helps!

**Comment by dambrosid** [comment]
Hello @marcperez 

Thank you for you reply. This is great you have updated the source string.
Please let me know when will be deployed.

Best Regards

**Comment by ribeiroguilherme** [comment]
I confirm that the translation is updated on our i18n file. Thanks for your input.
