### ISSUE TITLE
On Paypal window close  - no onCancel event is received 

### ISSUE THREAD

**Issue by kappy904** [Adyen/adyen-web#1177]
When using web drop in, clicking on the paypal button opens a new window. Closing it shortly after results in the web drop in button stuck in a non-functional state. This is a smilar/if not the same issue mentioned in https://github.com/Adyen/adyen-web/issues/290 hence the same steps can be used to reproduce;

1. Load the web drop in with PayPal
2. Click the PayPal button
3. Wait for the window to open
4. Close the window

**Expected behavior**
At least an event to be triggered so that we can refresh the web drop in state and the user can attempt the payment flow again

Experienced on desktop Mac OSX Chrome

**Comment by ribeiroguilherme** [comment]
Hi @kappy904 

Thanks for reaching out. The Paypal `onCancel` on `adyen-web` goes through the `onError` callback. As documented [here](https://docs.adyen.com/online-payments/web-drop-in#drop-in-error-handling),  `onError` manages different types of errors, which one of them is the `CANCEL` one.

When PayPal triggers the `onCancel` on its SDK, `adyen-web` will trigger the `onError` with that error type. 

Regardless of that, I discussed with the team and we are going to update the docs to make it clear how is the flow for this case. I hope it helps!
