### ISSUE TITLE
holderName should be ownerName (ACH)

### ISSUE THREAD

**Issue by Dashti81** [Adyen/adyen-web#1191]
**Describe the bug**
I'm using ACH web component. According to the adyen documentation, I should get 'ownerName' from 'state.data'.

**To Reproduce** 
Follow these steps in section 'Show ACH Direct Debit in your payment form'
https://docs.adyen.com/payment-methods/ach-direct-debit/web-component
and then console.log(achDirectDebit.state.data)

**Expected behavior**
I expect ownerName instead of holderName

**Screenshots**
Test output:
![Screenshot 2021-06-28 at 15 27 47](https://user-images.githubusercontent.com/84127880/123644237-7ac43280-d825-11eb-8c59-fa8f1515bc26.png)

Adyen documentation:
![Screenshot 2021-06-28 at 15 29 53](https://user-images.githubusercontent.com/84127880/123644513-ba8b1a00-d825-11eb-97f9-d9cc34ed235e.png)

**Comment by marcperez** [comment]
Hi @Dashti81,

Thanks for reaching out. I can see this was fixed back in `v3.15.0` (#340). Could you confirm which version are you encountering this issue in? If this is happening in a prior version, updating should resolve the issue.

Let us know, thanks!

**Comment by Dashti81** [comment]
Hi @marcperez ,

Thank you for your response.

I'm on version 4.7.0

I see the issue. When I use `this.achDirectDebit.state.data` (as explained in adyen documentation) then I get holderName.
However if I use `this.achDirectDebit.formatData()` this function returns an object and this object has paymentMethod.ownerName property.

thanks for sharing the pull request, it clarified the issue, the solution is using formatDate() :)  

I'll close the tickets.

**Comment by marcperez** [comment]
Hey @Dashti81,

One small comment, we recommend using the `component.data` attribute (`this.achDirectDebit.data` in your case). That should bring all the necessary data (and in the correct format).

Thanks again, hope this helps!
