### ISSUE TITLE
Rejection of digits in CardHolderName

### ISSUE THREAD

**Issue by LukasDrP** [Adyen/adyen-web#1211]
**Describe the bug**
The CardholderName-Input rejects names with digits. However, there's the test-scenario for Chargebacks, that requires to insert "Chargeback:{reason_code}" where reason_code consists of digits and an underscore as described here: https://docs.adyen.com/risk-management/disputes-api/test-applicable-dispute-reasons 

**Expected behavior**
The Chargeback-Test should work as expected.

**Comment by pabloai** [comment]
Hi @LukasDrP, and thanks for reaching out.

While it's true that some tests require digits to be entered as the holder name, this is not something we would expect the shopper to do. I think we shouldn't compromise the frontend validation just to make it easier to run these kind of tests.
For those scenarios, I would just add the holder name in the backend when creating the payments request.

Let me know if this would work for you.

**Comment by marcperez** [comment]
Hi @LukasDrP,

After some internal discussion we've decided to allow all characters back in the holder name field (see #1216). This will be available on the next release. Hope this helps!

**Comment by LukasDrP** [comment]
Hi @marcperez,

sounds good, thanks for the update!

**Comment by marcperez** [comment]
Hi @LukasDrP,

This has been released as part of `v4.7.2`, cheers! 🚀
