### ISSUE TITLE
challengeWindowSize seems not in the offical documentation

### ISSUE THREAD

**Issue by JustinLiang90** [Adyen/adyen-web#1217]
**Describe the bug**
Config: `{size: '05'}` is not working for `handleAction` method.

Base on the [official document](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/web-component#3ds2-component): 
`If you are using the Card Component, pass the action object to the handleAction event of your existing Card Component and skip to step 5`

and
```js
// Optional configuration for the challenge window size
--
  | const threeDSConfiguration = {
  | size: '01'
  | // Set to any of the following:
  | // '02': ['390px', '400px'] -  The default window size
  | // '01': ['250px', '400px']
  | // '03': ['500px', '600px']
  | // '04': ['600px', '400px']
  | // '05': ['100%', '100%']
  | }
```
and the PR: https://github.com/Adyen/adyen-web/pull/620,
We thought pass `{size: '05'}` to `handleAction` method will make the 3DS challenge window responsive, but it doesn't.

And after we dug into the [source code](https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/core/ProcessResponse/PaymentAction/actionTypes.ts#L58) and noticed we should use `challengeWindowSize`, but it seems not in the official documentation. 

So wonder if it's the correct setting for `handleAction`? If so, could you update your documentation? (If it was already somewhere, maybe make it more obvious)

**Comment by ribeiroguilherme** [comment]
Hi @JustinLiang90 ,

Our docs are now updated showing the `challengeWindowSize` property. Thanks for the feedback!
