### ISSUE TITLE
Unable to raise Apple Pay errors in Apple UI due to missing Error object

### ISSUE THREAD

**Issue by RyanONeill1970** [Adyen/adyen-web#1224]
In response to onShippingContactSelected Apple Pay accepts a response containing an array of Error objects that will populate the payment sheet with helpful errors such as "We are unable to ship to this country.".

We've been trying to implement these but on talking to Adyen support it seems that the Adyen JS does not pass these errors over to Apple.

You can see an example of someone else trying to do this with Adyen at https://developer.apple.com/forums/thread/126654 .

Looking through the source I can't see any filtering or hiding of the errors array. Is this the correct function?

I'm happy to root through this and submit a PR but would really appreciate some guidance. Sorry I don't have the errors at the moment, I can get them if needed but it takes a while to setup for test.

**Comment by marcperez** [comment]
Hi @RyanONeill1970,

Thanks for reaching out. When resolving the `onShippingContactSelected` event promise, any data provided will be passed directly to [`completeShippingContactSelection`](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaysession/1778008-completeshippingcontactselection). The object used to resolve `onShippingContactSelected` should then follow the [`ApplePayShippingContactUpdate`](https://developer.apple.com/documentation/apple_pay_on_the_web/applepayshippingcontactupdate) format. From the component side, no errors should be filtered out. 

Could you provide us some details (and maybe a sample code) on how the `onShippingContactSelected` event is implemented?

**Comment by RyanONeill1970** [comment]
This Typescript is based on the Adyen examples and works except when we attempt to return an error to the UI by filling in the errors array. Am I doing something wrong? Do you have an example where you pass the errors back up to the UI for Apple?

```
private onApplePayShippingContactSelected(resolve, reject, event: IApplePayOnShippingContactSelectedEvent): void {

  let postData = {
      countryCode: event.shippingContact.countryCode,
      postalCode: event.shippingContact.postalCode,
  };

  fetch('/update-apple-shipping-address', {
      method: 'post',
      headers: {
          'content-type': 'application/json'
      },
      body: JSON.stringify(postData)
    })
  .then(function (response) {
        if (!response || !response.ok) {
            return reject();
        }
        return response.json();
  })
  .then((applePayShippingContactUpdate: IApplePayShippingUpdateData) => {
        if (applePayShippingContactUpdate.errors && applePayShippingContactUpdate.errors.length > 0) {
            // This is the call that fails.
            reject(applePayShippingContactUpdate);
        }
        else {
            resolve(applePayShippingContactUpdate);
        }
    })
        .catch(error => {
            log("Server comms error", "onApplePayShippingContactSelected", error);
        });
}
```

The IApplePayShippingUpdateData interface spec that allows us to receive data from the server and is passed to the reject or resolve function is;

```
export interface IApplePayShippingUpdateData {
    errors?: IApplePayError[];
    newLineItems?: IApplePayLineItem[];
    newShippingMethods?: IApplePayShippingMethod[];
    newTotal: IApplePayLineItem;
}

export interface IApplePayError {
    // The error code for this instance.
    code: ApplePayErrorCode,

    // The field name that contains the error on the payment sheet.
    contactField: ApplePayErrorContactField,

    // A localized, user-facing string that describes the error.
    message: string
}
```

If all goes well and we support the shipping address then everything works. If we don't, the errors property is populated and we call reject with the returned data. This results in the following error where instead we'd expect the Apple UI to show a message.

**Unhandled` Promise Rejection: TypeError: Type error**

The Apple Pay component is created as follows;

```
this.applePayComponent = checkout.create("applepay", {
                amount: {
                    currency: "GBP",
                    value: total
                },
                buttonColor: "black",
                buttonType: "plain",
                countryCode: "GB",
                totalPriceLabel: "xxxxxxxxxxx",
                lineItems: lineItems,

                onAuthorized: (resolve, reject, event) => this.onApplePayAuthorised(resolve, reject, event),

                /*
                * @param resolve(ApplePayShippingContactUpdate update) Completes the selection of a shipping contact with an update. This will call https://developer.apple.com/documentation/apple_pay_on_the_web/applepaysession/1778008-completeshippingcontactselection.
                * @param reject(ApplePayShippingContactUpdate update)
                * @param event The event parameter contains the shippingContact attribute.
                */
                onShippingContactSelected: (resolve, reject, event) => this.onApplePayShippingContactSelected(resolve, reject, event),

                /*
                * @param resolve(ApplePayShippingMethodUpdate update) Completes the selection of a shipping method with an update. Will call https://developer.apple.com/documentation/apple_pay_on_the_web/applepaysession/1778024-completeshippingmethodselection
                * @param reject(ApplePayShippingMethodUpdate update)
                * @param event The event parameter contains the shippingMethod attribute.
                */
                onShippingMethodSelected: (resolve, reject, event) => this.onShippingMethodSelected(resolve, reject, event),

                onSubmit: (state, component) => this.onApplePaySubmit(state, component),

                // We'd like to request more fields here, but Apple restricts billing to just address and name.
                requiredBillingContactFields: ["postalAddress"],
                requiredShippingContactFields: ["postalAddress", "name", "phone", "email"],
                // Updated whenever country is changed. Loads from initial data on page load.
                shippingMethods: shippingMethods
            });

            this.applePayComponent
                .isAvailable()
                .then(() => {
                    this.applePayComponent.mount("#applepay-button-container");

                    let tickSelector = document.getElementById("payment-select-applepay");

                    tickSelector.classList.remove("hidden");
                })
                .catch(error => {
                    if (error.message.indexOf("is not available on this device") < 0) {
                        // Logs all other errors except for 'not available'.
                    }
                });
```

**Comment by RyanONeill1970** [comment]
Forgot one thing, this is the shape of the data we receive from the server and pass to reject / resolve;

```
{
  "errors": [
    {
      "code": "addressUnserviceable",
      "message": "We are unable to deliver this order to your country due to delivery restrictions."
    }
  ],
  "newLineItems": [
    {
      "amount": "191.63",
      "label": "Items",
      "type": "final"
    },
    {
      "amount": "28.91",
      "label": "Delivery",
      "type": "final"
    }
  ],
  "newShippingMethods": [
    {
      "amount": "26.91",
      "detail": "£26.91 - Express ",
      "identifier": "Express",
      "label": "Express"
    },
    {
      "amount": "28.91",
      "detail": "£28.91 - Standard ",
      "identifier": "Standard",
      "label": "Standard"
    }
  ],
  "newTotal": {
    "amount": "220.54",
    "label": "Total",
    "type": "final"
  }
}
```

**Comment by marcperez** [comment]
Hi @RyanONeill1970,

Thanks for the detailed response. One follow-up question: does this happen as well if you call `resolve` instead of `reject`? (Both should call `completeShippingContactSelection`)

**Comment by RyanONeill1970** [comment]
If we call resolve instead of reject we get the below error. The error seems wonky as there is still a newTotal property there.

**Unhandled Promise Rejection: TypeError: Member ApplePayShippingContactUpdate.newTotal is required and must be an instance of ApplePayLineItem**

**Comment by RyanONeill1970** [comment]
We've been plugging away at this and have found out how to pass the errors back to Apple. They must be constructed as ApplePayError types and plain JS objects will not work.

So when we take the JSON (above) from the server, we need to rewrite the errors property. We do this using the below function. 

        private mapShippingContactUpdateErrors(data: IApplePayShippingUpdateData): IApplePayShippingUpdateData {
            let mapped = {
                errors: [],
                newLineItems: data.newLineItems,
                newShippingMethods: data.newShippingMethods,
                newTotal: data.newTotal,
            };

            // If we don't return errors then status is assumed to be success (see https://developer.apple.com/documentation/apple_pay_on_the_web/applepayshippingcontactupdate).
            // ApplePayError is a class, not a simple list of properties so must be created in this fashion. See https://developer.apple.com/forums/thread/92912
            for (let i = 0; i < data.errors.length; i++) {
                let err = data.errors[i];
                mapped.errors.push(new ApplePayError(err.code, err.contactField, err.message));
            }

            return mapped;
        }

The Apple UI is still inconsistent when we send back an error, the API insists that we send newTotal, newLineItems and newShippingMethods but does nothing with them. I don't think this is an Adyen issue though.

We did try and use the Apple Pay demos for Adyen to troubleshoot but they are not working at the moment.

I'll close this, if you want more information please let me know.

Thanks

Ryan

**Comment by marcperez** [comment]
Hi @RyanONeill1970, thanks for such a detailed explanation. 
Indeed, this seems to be something to do with the Apple Pay JS API itself. Happy you found a way to show the errors, though!
