### ISSUE TITLE
Invalid card brand doesn't show error status

### ISSUE THREAD

**Issue by fernandoamz** [Adyen/adyen-web#1227]
**Describe the bug**
If the user enters one of the below-listed values in the "Card number" field, no error message is displayed right away under the box:

"0000 0000 0000 0000 0000" / "1111 1111 1111 1111 1111" / "3333 3333 3333 3333 3333" / "6666 6666 6666 6666 6666" / "7777 7777 7777 7777 7777" / "8888 8888 8888 8888 8888" / "9999 9999 9999 9999 9999"

If the user types an invalid card type that is not showing the error on the input, how can I activate the error status if it's an invalid regex?

**To Reproduce**
1. Go to the dropin frame
2. Start fill the data
3. Add "0000 0000 0000 0000 0000" / "1111 1111 1111 1111 1111" / "3333 3333 3333 3333 3333" / "6666 6666 6666 6666 6666" / "7777 7777 7777 7777 7777" / "8888 8888 8888 8888 8888" / "9999 9999 9999 9999 9999" in the "Card number" field
4. Fill in the remaining required boxes
5. Click on the pay button you will notice that we didn't get an error on the input because is an invalid card.

**Expected behavior**
Show the error status if the brand is not detected or if you click the pay button an it doesn't type a valid card.

**Comment by fernandoamz** [comment]
Hi @marcperez, sorry for tag you, qq, Do you have a recommendation or suggestion about how to fix this?

**Comment by sponglord** [comment]
Hi  @fernandoamz - thanks for your question.

_Technically_ this is correct behaviour - these numbers pass the luhn check. So therefore they are "valid" and, although we don't recognise them as belonging to a particular card brand, we don't let this (non-recognition of brand) be a reason to block the payment on the frontend.
(If the shopper tries to pay then it will be caught by the backend - probably with a "Invalid card number" 422 error)

However, I must admit these are not very "plausible" card numbers - so we will look into how to handle them and prevent the payment request from even being made.

Thanks for bringing this to our attention.

**Comment by fernandoamz** [comment]
Thanks for answer @sponglord

**Comment by fernandoamz** [comment]
Hi @sponglord, It is the same case for the ZIP Code? it isn't validating in QA the Zip Codes.
The user can enter any value in the "Zipcode" field, being able to complete the purchase flow.

Expected result:

Only valid values are accepted in the "Zip code" field
An error message which informs the user about the invalid Zip code is displayed (as we have the case on the eComm checkout page)

**Comment by sponglord** [comment]
Hi @fernandoamz - I don't believe that we are performing any country based validation on the zip code on the Checkout frontend.
This _is_ something that I know we do in other products so I'll create a ticket to look into adding this to a future release

**Comment by sponglord** [comment]
@fernandoamz - I can confirm that the next release of AdyenWeb (current version is 5.2.0) will contain a check for these "all the same digit" numbers
