### ISSUE TITLE
Documentation is not clear about how implement custom button.

### ISSUE THREAD

**Issue by fernandoamz** [Adyen/adyen-web#1228]
**Describe the bug**
Just a suggestion, Could you provide an example about how to implement a custom button?

I was researching the documentation about how to implement my own button on the drop-in web because I want to keep it disabled until the user fills all the inputs and these are valid.

I saw that firstly we need to change the property `showPayButton: false`, this hides the button but if I want to implement my custom button I need to call the `dropin.submit()` if I call the reference I get an `undefined`.  I let you the code in order to help me add this feature to my code.

```

import React, { useRef, useEffect, useState } from 'react';
import { connect } from 'react-redux';
import Button from '@material-ui/core/Button';

import { callServer, handleSubmission } from '../../../utils/serverHelpers';

function Dropin() {

  const dropinContainer = useRef();

  useEffect(async () => {
    init()
  }, []);

  const init = async () => {
    const response = await callServer(
      '/getPaymentMethods'
    ).then((result) => result);

    let configuration = {
      paymentMethodsResponse: response.body,
      clientKey: process.env.ADYEN_PAYMENT_CLIENT_KEY,
      locale: "en_US",
      environment: 'test',
      paymentMethodsConfiguration: {
        card: {
          brands: ['amex', 'diners', 'discover', 'mc', 'visa'],
          showPayButton: false,
          hasHolderName: true,
          holderNameRequired: true,
          name: "Credit or debit card",
          billingAddressRequired: true,
          billingAddressAllowedCountries: ['US'],
          data: {
            billingAddress: {
              street: '',
              city: '',
              country: 'US',
              stateOrProvince: ''
            }
          },
        }
      },
    }

    configuration = {
      ...configuration,
      onSubmit: async (state, component) => {
        if (state.isValid) {
        }
      },
    };

    const AdyenCheckout = (await import('@adyen/adyen-web')).default;
    const checkout = new AdyenCheckout(configuration);
    checkout.create('dropin').mount(dropinContainer.current);
  };

  return (
    <div>
      <div ref={dropinContainer} className="dropin" />
      <Button
            variant="contained"
            onClick={() => dropinContainer.submit()}
       >
         PAY
       </Button>
    </div>
  );
}

const mapStateToProps = (state) => ({});

const mapDispatchToProps = dispatch => ({});

export default connect(mapStateToProps, mapDispatchToProps)(Dropin);
```

Reference: https://docs.adyen.com/online-payments/drop-in-web#configuring-drop-in

<img width="800" alt="Screen Shot 2021-07-21 at 4 39 14 PM" src="https://user-images.githubusercontent.com/7818620/126563694-0e41285e-d0da-46f8-9603-d7ae4c2a06cf.png">

Thanks, it would be great if you can help me to share an example.

**Comment by marcperez** [comment]
Hi @fernandoamz,

Thanks for your suggestion! 

I see where the confusion comes from. What the documentation means with `dropin`, is the instance returned when creating it, for example:

```js
    const dropin = checkout.create('dropin').mount(dropinContainer.current);
    // ...
    dropin.submit();
```

Hope this helps resolve the issue. I'll pass on your feedback so we can clarify this part on our documentation, thanks again!

**Comment by fernandoamz** [comment]
Thanks @marcperez, I could implement my custom button, thanks a lot.
