### ISSUE TITLE
Web component: autoFocus on first empty field

### ISSUE THREAD

**Issue by JesusNaturitas** [Adyen/adyen-web#1229]
According to your docs, It seems to be possible on [custom card integration](https://docs.adyen.com/payment-methods/cards/custom-card-integration), but I can't make it work on web components 4.7.1

Thanks!

**Comment by pabloai** [comment]
Hi @JesusNaturitas.

The `autoFocus` property you mention is not meant for focusing the first field automatically. What it does is to jump from one field to the next one when the field was completed with a valid value. For example entering a date like `03/30` in the Expiry date field will make the focus jump to the CVC / CVV field.

That being said, you can make focus in the first field of the custom card component  as soon as it's loaded by adding this:
```js
onConfigSuccess: () => {
  myCard.setFocusOn('encryptedCardNumber');
}
```

I hope this clarifies things, and thanks for reaching out!

**Comment by lauterry** [comment]
Hi there,

I've noticed that currently, when a field is left empty, it automatically gains focus.

However, I'd like to disable this behavior. The reason being, I've integrated Adyen inputs into another form alongside other inputs.

Instead, I'd prefer if the page would scroll to the first empty input before the Adyen input.

How can I disable the autofocus please ?
