### ISSUE TITLE
[BUG] Exports of CoreOptions in the main package 

### ISSUE THREAD

**Issue by emidev98** [Adyen/adyen-web#123]
**Describe the bug**
Dear development team, using the version 3.11.0 of the adyen-web component from npm I see that the package @adyen/adyen-web it's not exporting all the resources needed to instance the Checkout component.

**To Reproduce**
1. Install the @adyen/adyen-web@3.11.0 in a Angular9 project
2. Import the library inside a component with the next notation 
`import AdyenCheckout from '@adyen/adyen-web';`
3. Create an instance of the `AdyenCheckout` with the next notation 
`const checkout = new AdyenCheckout(this.config);`

 You will notice that the object "this.config" cannot be of type `import { CoreOptions } from '@adyen/adyen-web` which is the expected export for an important interface like that. 

Instead of importing the interface from the core package right now the developer should import it from 
`import { CoreOptions } from '@adyen/adyen-web/dist/src/core/types'`.

**Expected behavior**
Be able to import the package from the main package.

**Comment by marcperez** [comment]
Hi @emidev98,

Thanks for your suggestion. In the future we will improve the way we export our types. For the time being I would suggest using the full path.

Cheers!
