### ISSUE TITLE
Ability to override iOS Safari AutoFill in web dropin component

### ISSUE THREAD

**Issue by tmadison-gpsw** [Adyen/adyen-web#1240]
**Describe the bug**
Override iOS Safari Auto fill background color on dropin component.

<img width="373" alt="Screen Shot 2021-08-06 at 2 36 15 PM" src="https://user-images.githubusercontent.com/16724169/128573499-8cc2770b-eb73-4407-b6fd-7560a9c6df27.png">

<img width="637" alt="Screen Shot 2021-08-09 at 10 15 17 AM" src="https://user-images.githubusercontent.com/16724169/128746824-0a0f1181-4f88-4b1c-ac70-fc6e4217095d.png">

**Expected behavior**
Able to override the default styles of the inputs such as:
```
input:-webkit-autofill,
input:-webkit-autofill:hover,
input:-webkit-autofill:focus,
textarea:-webkit-autofill,
textarea:-webkit-autofill:hover,
textarea:-webkit-autofill:focus,
select:-webkit-autofill,
select:-webkit-autofill:hover,
select:-webkit-autofill:focus {
  background-color: #111 !important;
  box-shadow: 0 0 0px 1000px #111 inset !important;
  -webkit-background-fill-color: #111 !important;
  -webkit-box-shadow: 0 0 0px 1000px #111 inset !important;
  -webkit-text-fill-color: white !important;
  background-color: rgb(17, 17, 17) !important;
  background-clip: content-box !important;
}
```
Is this possible?

Thank you!

**Comment by camil-adyen** [comment]
Hi all!

A BETA version of Web v6 is now available on Github. Feel free to take a look and give us feedback! We aim to release the official v6 in the coming weeks. More information can be found [here](https://github.com/Adyen/adyen-web/releases/tag/v6.0.0-beta.0).

**Comment by sponglord** [comment]
The major release, `v6.0.0`, was launched today!
See the documentation here:
- [release notes](https://docs.adyen.com/online-payments/release-notes/#releaseNote=2024-07-24-web-componentsdrop-in-6.0.0)
- [migration guide](https://docs.adyen.com/online-payments/update-your-integration/migrate-to-web-v6/)

For you specific issue you need will need to generally override the input's background colour somewhere in your own stylesheet e.g.
```
:root {
    --adyen-sdk-color-background-primary:yellow;
}
```

And then when you configure the `Card` component, pass in a `styles` object e.g.
```
window.card = new Card(checkout, {
  styles: {
    base: {
      background: 'yellow'
   }
}
```
to ensure the background colour of the iframe is also changed.

**Comment by CoreyFedde** [comment]
For anyone else referencing this, the styles syntax doesn't directly fix this. The iframe and autofill coloring seems to look at the root level color-scheme. So Sponglord's answer + add:
```
:root {
  color-scheme: dark;
}
```
In your stylesheet to lower the contrast used in the highlight
