### ISSUE TITLE
Pressing Enter should trigger form submission

### ISSUE THREAD

**Issue by mogelbrod** [Adyen/adyen-web#1242]
**Describe the bug**
Pressing <kbd>Enter</kbd> while a credit card input is focused doesn't trigger submission, instead requiring the user to manually focus the submit button and press it. Is this intentional?

**To Reproduce**
1. Go to https://www.mystoredemo.io/#/
2. Add any item to the cart
3. Enter the checkout
4. Focus any of the credit card form inputs
5. Press <kbd>Enter</kbd>
6. Nothing happens

**Expected behavior**
<kbd>Enter</kbd> triggers form submission, which in turn highlights any remaining errors.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: Version 92.0.4515.131 (Official Build) (x86_64)

**Additional context**
Related issue: https://github.com/Adyen/adyen-web/issues/610

**Comment by sponglord** [comment]
Hi @mogelbrod - this is intentional.
We do not capture "Enter" key presses on the credit card fields. We expect users to Tab between fields and when they have Tabbed onto the Pay button, pressing Enter will then validate/submit the form

**Comment by gabrielf** [comment]
But why? HTML forms by default submit on enter. Have you experienced that this causes problems and in that case, what problems?

Would it be possible to let integrators configure this behaviour? By default it could be off but with a setting you could capture enter presses and submit the form?
