### ISSUE TITLE
Unable to re-type at start of 'Name on card'

### ISSUE THREAD

**Issue by karajanov-nikola** [Adyen/adyen-web#1243]
**Describe the bug**
Typing in last name then typing first name before last name is not possible.

**To Reproduce**
- Go to https://www.mystoredemo.io/#/
- Add any item to the cart
- Enter the checkout
- Input Last name to 'Name on card' field e.g 'Smith'
- Input First name before last name to 'Name on card' field e.g 'John'

**Actual behavior**
Name 'JSmithohn' was typed into 'Name on card' field

**Expected behavior**
Name 'John Smith' to be into 'Name on card' field

**Desktop :**
 - OS: macOS, Windows
 - Browser: Chrome, Firefox
 - Version: 92.0.4515.131 (Official Build) (x86_64)

**Comment by ribeiroguilherme** [comment]
Hi @karajanov-nikola ,

Thanks for reaching out to us. Can you tell us which version of `adyen-web` are you using? I did a quick test on our MyStoreDemo with Chrome and Firefox and I didn't manage to reproduce the issue.

**Comment by ribeiroguilherme** [comment]
Closing this as we didn't manage to reproduce the bug. Feel free to reopen it if the issue still persists.
