### ISSUE TITLE
"Name on card" erasing letter wrong behavior

### ISSUE THREAD

**Issue by albertoaldanar** [Adyen/adyen-web#1247]
**Describe the bug**
In the Name on Card input, when user erases a letter which is not the last one. The cursor goes back to the end of the last word.

**To Reproduce**
1. Go to "Name on Card" input
2. Type a name. Example "John Smith"
3. Put the cursor in any letter that is not the last one. Example "Joh|n Smith"
4. Erase that letter and see how the cursor goes to the end of the last word. Example "Jon Smith|"

**Expected behavior**
When the user erases a letter the cursos should stay right where letter was erased.

**Desktop (please complete the following information):**
OS: macOS, Windows
Browser: Chrome, Safari
Version: 92.0.4515.131 (Official Build) (x86_64)

**Comment by marcperez** [comment]
I'm closing this issue since the issue seems resolved, feel free to reopen if the problem reappears. Thanks!
