### ISSUE TITLE
[Paypal] Allow to provides Content-Security-Policy nonce to iframe

### ISSUE THREAD

**Issue by Altahrim** [Adyen/adyen-web#1269]
**Problem**
I would like to use `Content-Security-Policy` on my website with [`nonce-*`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#other_values) instead of [`unsafe-inline`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#unsafe_keyword_values).
When I do that, it blocks Paypal inline scripts included in their iframe since they don't have the nonce value.

**Possible solution**
Paypal has a way to provide a nonce, as explained [here](https://developer.paypal.com/docs/checkout/troubleshoot/support/#content-security-policy-rules).
I think it could be a nice security improvement if Adyen component could handle this.
Maybe it's also applicable to other payment providers.

**Comment by marcperez** [comment]
Hi @Altahrim,

Thanks for raising this. We will add this to our backlog and update you once it's ready. Hope this helps!

**Comment by ribeiroguilherme** [comment]
Hi @Altahrim 

We released a new version this week (5.2.0) which the `cspNonce` can be passed to Paypal component. 
I'll close this ticket, but feel free to reach out to us if you find any issue related to this matter.

PR: #1339
