### ISSUE TITLE
Missing field on translation's documentation

### ISSUE THREAD

**Issue by fernandoamz** [Adyen/adyen-web#1284]
**Description**
I have been searching on documentation about how to add internalization, currently, I can translate the iframe following the documentation but I found a missing field that is not clear on documentation.

I let you an image in order to help me the way to translate it. Thanks so much!

I am following up on these instructions: 
https://docs.adyen.com/online-payments/components-web/localization-components#fields

![Screen Shot 2021-09-13 at 10 49 17 AM](https://user-images.githubusercontent.com/7818620/133116437-02fd5b37-357f-4712-a2cc-b255d85e9a5e.png)

**Comment by marcperez** [comment]
Hi @fernandoamz,

Thanks for reaching out. The "Credit Card" value you see there is a payment method name. Payment method names come from the `/paymentMethods` response. You can easily get this values translated by setting the correct [`shopperLocale`](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/paymentMethods__reqParam_shopperLocale) when calling `/paymentMethods`.

Hope this helps!
