### ISSUE TITLE
Save credit card details for future payments not working

### ISSUE THREAD

**Issue by victorbadila** [Adyen/adyen-web#1292]
**Describe the bug**
I implemented the dropin in an angular environment. It works well, except that when a user choses credit card there is also a tick box for saving the credit card info for future payments. In my case it does nothing, users have to add the details every time they make a new payment. Same browser, same url, nothing changes in this regard that could affect how this works.

**To Reproduce**
1. From the adyen dropin chose "credit card"
2. Add credit card information and tick "save details for future payments"
3. Pay and wait for the process to finish
4. Attempt the process again, the credit card inputs are empty

**Expected behavior**
The credit card details are automatically completed for the user

**Desktop (please complete the following information):**
 - OS: Tested on both Windows and MacOS
 - Browser: Chrome / Safari
 - Version: latest

**Comment by marcperez** [comment]
Hi @victorbadila,

Thanks for reaching out. By checking "save details for future payments", the Card component will add `storePaymentMethod` to the `state.data` object you get on the `onSubmit`/`onChange` event handlers. That needs to be sent onto `/payments` when making the payments request. Also make sure you're providing a [`shopperReference`](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/payments__reqParam_shopperReference) on that call.
More details can be found here: https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens
I'll close this ticket, but feel free to reopen if you think this is still an issue related to this library.

Hope this helps!
