### ISSUE TITLE
[Klarna] Change the Swedish translation of Klarna Payment Methods

### ISSUE THREAD

**Issue by toanphan19** [Adyen/adyen-web#1338]
**Is your feature request related to a problem? Please describe.**
- "Klarna Konto" and "Klarna Bankkonto" (see screenshot 1 below) have very similar meaning in Swedish and can be confusing. Furthermore, "Klarna Konto" as the name does not capture the meaning of the payment option, which is pay over time / pay in installments.
- "Klarna Faktura" is ok, but Klarna's term "Få först. Betala sen" is more common and easier to understand for Swedes. 
- There is a dot at the end for the English translation (see screenshot 2), which is not consistent with other payment methods (Card, Trustly, Google Pay, etc...). 

**Describe the solution you'd like**
- The "Klarna Konto" translation should either reuse the term "Dela upp" that Klarna used in (image below), or an equivalent translation of "Pay over time with Klarna" in Swedish. 
- Potentially change "Klarna Faktura" to "Få först. Betala sen".
- Remove the dot at the end for consistency.

**Additional context**
- Adyen's Swedish translation:
![image](https://user-images.githubusercontent.com/8591599/138723875-0a9a8c2f-ce32-4454-850a-20b2f776396b.png)
- Adyen's English translation:
![image](https://user-images.githubusercontent.com/8591599/138724664-07190486-78a3-40d0-ad3f-2b0325e1dbee.png)
- Translation from Klarna (https://www.klarna.com/demo/se/sv-SE/kp/checkout/):
![image](https://user-images.githubusercontent.com/8591599/138845891-23579cde-fdc8-40c8-8127-6f47ee9a49f7.png)

**Comment by ribeiroguilherme** [comment]
Thanks for reaching out @toanphan19 . We are checking this internally with the team and we will get back to you as soon as we get the response.

**Comment by ribeiroguilherme** [comment]
Hi @toanphan19 . We adjusted our translations for the Klarna payment method, therefore I am going to close this issue. Thanks for reaching out!
