### ISSUE TITLE
[Card Component] Security code field does not show error when you type 4 digits CVC and then credit card number which has 3 digits

### ISSUE THREAD

**Issue by pajelonek** [Adyen/adyen-web#1341]
When you type 4 digits to CVC input and then you type first few digits/first digit of credit card number which has a 3 digits CVC (in my case 4 for VISA), your CVC would lose correct checkmark indicator as well as all DOM classes covering security code field would lose classes which indicates that field has been filled (no --filled, --error or --valid classes) where they should have --filled or --error class. State and error elements do not have any information about security code anymore, where in reality input has been filled with 4 digits at the start and there should be somewhere information that there is and error in form and CVC field has been filled with incorrect data. After clicking and unclicking on CVC field there is error checkmark as well as error input below it.

1. Go to https://www.mystoredemo.io/#/
2. Add product to basket
3. Go to card https://www.mystoredemo.io/#/cart
4. Click "Continue to checkout"
5. From dropdown menu select Credit Card
6. Type 7373 in CVC field
7. Type 4 in Card Number field. -->CVC field lose it's checkmark, it's been replaced with default one from the start
8. Click on CVC field and unclick to make it lose it's focus. --> Now the field has correct status that indicates field is invalid, before focusing on it there was no information about it

After typing some numbers of credit card which has 3 digits, CVC field should have error checkmark and in state object there should be information about invalid CVC field. DOM elements should have correct classes before hovering on the field to fix it.

Screenshots
1. CVC field has valid checkmark after typing 7373.
![image](https://user-images.githubusercontent.com/48658611/139075955-0a202d30-822c-4694-9774-b21f159921bc.png)
2. CVC field has no checkmark after typing 4 to verify it's VISA brand.
![image](https://user-images.githubusercontent.com/48658611/139076105-1052deb3-ef48-42cb-9540-137607535d07.png)
3. After clicking on CVC field and unclicking it, there is an error checkmark, it should happened earlier.
![image](https://user-images.githubusercontent.com/48658611/139076331-f94cd359-4250-4e7b-8c7b-1d269399154f.png)

Desktop (please complete the following information):
 - OS: Windows 10.0.19042
 - Browser: Chrome, Edge
 - Adyen Web Component: 4.7.4 - 4.9.0

**Additional context**
In the shop that I work at, credit card form styles need to be consistent with the previous one, which requires iframe to keep track of what happens in the form, this behavior results in blocker before release phase.

**Comment by sponglord** [comment]
Hello @pajelonek. Thanks for contacting us.

We consider what happens in the CVC field after you've entered a 4 digit number and then entered a credit card number for a card that requires a 3 digit cvc to be reasonable behaviour:
- initially the cvc field is marked as valid (green tick, green underline)
- then, when you enter a card number for a brand with a 3 digit cvc, _those valid indicators are removed_
- any attempt to press "pay" will cause the form to be validated, an error will show on the CVC field & the shopper will be unable to proceed with the payment until they've fixed the error

We will however discuss internally if this is something we wish to change

**Comment by ribeiroguilherme** [comment]
Hi @pajelonek ,

We released the version `v5.3.0` which contains the fix for this issue. It is available as a `npm` package. 
Thanks again, and feel free to reach out to us if you find any issue related to the library.
