### ISSUE TITLE
onError callback not called

### ISSUE THREAD

**Issue by chessydk** [Adyen/adyen-web#1344]
**Describe the bug**
onError callback not fired, when all fields of VISA payment left empty, when calling submit.

**To Reproduce**
Leave creditcard info empty, call submit on paymentComponent (returned from `checkout.create`)

**Expected behavior**
Expected the onError callback (setup in the configuration) to fire - like in version 4.7.4. onSubmit callback is also not called (probably OK).

**Screenshots**
![image](https://user-images.githubusercontent.com/1286704/139195642-23903aea-9094-4acd-85ca-22f6708e0c01.png)
![image](https://user-images.githubusercontent.com/1286704/139195692-29124e62-d49a-4f67-ab18-bca86fe2de09.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 -  95.0.4638.54

**Additional context**
Stopped working with version 5.0.0 of adyen npm package (@adyen/adyen-web). Worked fine with v. 4.7.4.

**Comment by ribeiroguilherme** [comment]
Hi @chessydk ,

`onError` now is triggered for different error types (ex: network issue, invalid payment type, payment cancellation). It is not used to validate the payment fields anymore.

Can't you rely on the `isValid` property in order to verify if there are errors in the form?

**Comment by chessydk** [comment]
Hi, it depends on you, I guess. If you are not planning to re-implement the old behaviour, I'll have to... 
It's ennoying though, because I'll then have to put in more logic so I can react on state being invalid only after I have called submit (because onUpdate is called with isValid==false all the time, during initial phase where information has not been filled in completely yet).

But its a breaking change which I strongly believe belongs in the documentation with the work around.

**Comment by ribeiroguilherme** [comment]
I am going to close this ticket as there is no action needed here. Feel feel to reopen it in case you face any issue with the library, and thanks for reaching out!
