### ISSUE TITLE
[Accessibility] - VoiceOver reads payment field names when page loads with web dropin component

### ISSUE THREAD

**Issue by joeboonv** [Adyen/adyen-web#1347]
**Describe the bug**
When using the VoiceOver screenreader on iPhone or Mac, the web drop-in component reads the payment field names when the page first loads. This is confusing when the page has other content before the payment component.

For example, as soon as you navigate to the page containing the dropin component, VoiceOver speaks:
           `   card number field, expiry date field, security code field`
Sometimes it also reads the cvc/cvv field name or the name-on-card field name. 

This impacts all countries I have tried except where there is a choice of banks in the form (e.g. Netherlands).

**To Reproduce**
1. Steps to reproduce the behavior:
2. On an iPhone or a Mac turn on VoiceOver 
3. Go to the Adyen demo site https://www.mystoredemo.io/
4. Pick country United Kingdom from the footer (also happens with other countries)
5. Add any item to the cart
6. View the shopping cart using the header icon
7. Press Continue to Checkout
8. Listen to what VoiceOver reads

**Expected behavior**
Field names are not spoken until the user tabs to that field

**Desktop:**
 - OS: Mac BigSur
 - Browser: safari
 - Version: 14.1

**Smartphone:**
 - Device: iPhone 8
 - OS: iOS 14.8
 - Browser safari
 - Version 14.8

**Comment by ribeiroguilherme** [comment]
@joeboonv we released a fix for this issue on `5.3.0`  #1386  . Feel free to reach out to us again if you find any issue with the library. Thanks!
