### ISSUE TITLE
Hybris content security policy

### ISSUE THREAD

**Issue by Momberg** [Adyen/adyen-web#1352]
I'm trying to use the PIX payment method with the hybris plugin, when it try to get the payment status I'm getting this error on chrome console content security policy.

1. Install hybris plugin
2. Use PIX payment component
3. Create a new QRCode for payment
4. See error on chrome console

**Expected behavior**
Get payment status without content security policy

**Screenshots**
![image](https://user-images.githubusercontent.com/15896033/140065090-086d05d9-98d9-4a24-8ab8-16d55b54a5ef.png)
![image](https://user-images.githubusercontent.com/15896033/140065118-7927a782-2dda-4e78-bbe8-d64ccda284aa.png)

**Comment by acampos1916** [comment]
Hello @saquibsayyad @martinsrenato. Is this something you can help with?

**Comment by ribeiroguilherme** [comment]
Hi @Momberg ,

Seems like this issue isn't related to this project. Please reach out to [adyen-hybris](https://github.com/Adyen/adyen-hybris) if this issue isn't solved yet 👍
