### ISSUE TITLE
Possible to localize payment method name

### ISSUE THREAD

**Issue by lpan42** [Adyen/adyen-web#1355]
It is possible to config the payment method name (in adyen-checkout__payment-method__header) based on the locale configuration.

eg: Instead of "credit card", payment method name shows "carte bancaire" if locale is "fr_FR". 

Thanks!

**Comment by marcperez** [comment]
Hi @lpan42,

Thanks for reaching out. This can be achieved with the `name` property on any component (through the `paymentMethodsConfiguration` object). This doesn't depend on a specific locale, but could be a variable you set dynamically with a condition on your side.

```js
const checkout = await AdyenCheckout({
  paymentMethodsConfiguration: {
    card: {
      name: 'Custom card name'
    }
  }
});
```

Hope this helps!
