### ISSUE TITLE
[Drop In - beforeSubmit event] error on actions.resolve

### ISSUE THREAD

**Issue by jfatonlineville** [Adyen/adyen-web#1356]
**Describe the bug**
I want to add a locale action on beforeSubmit event.
The documentation explains that actions.resolve() submit payment data to Adyen servers.
But I have an error at this call with message "Required field 'paymentMethod' is null" (payment method is present in log of data field).

How to use beforeSubmit or onSubmit event and send payment data to Ayden servers by the browser (not by a call from our server) ?

**Screenshots**
![Screenshot_20211108_145924](https://user-images.githubusercontent.com/40488346/140755081-f36ecf7f-571f-47c7-aa6f-c8bf5165f400.png)

![Screenshot_20211108_150636](https://user-images.githubusercontent.com/40488346/140755985-9a8b7ec9-a5bb-471c-af15-1c26c5bf2899.png)

**Desktop (please complete the following information):**
 - Linux KDE Neon (last)
 - Chrome
 - 95

**Comment by marcperez** [comment]
Hi @jfatonlineville,

Thanks for reaching out. `actions.resolve()` should be called with the data you receive as a first parameter:

```js
beforeSubmit: (data, component, actions) => {
  // ...
  actions.resolve(data);
}
```

I see this is not clear enough in the documentation and we already sent a note to adjust it. Hope this helps!

**Comment by jfatonlineville** [comment]
:+1:

**Comment by thomasbalsloev** [comment]
Dear @marcperez  @acampos1916 and who else it might concern.

After 3 and half years, you STILL haven't updated your docs about this issue!
I encountered the exact same problem and spent a couple of hours reading your docs and changing NPM package version, just for this...

PLEASE make sure your docs are up to date 🙏 

> Thanks for reaching out. `actions.resolve()` should be called with the data you receive as a first parameter:
> 
> beforeSubmit: (data, component, actions) => {
>   // ...
>   actions.resolve(data);
> }
> I see this is not clear enough in the documentation and we already sent a note to adjust it. Hope this helps!
