### ISSUE TITLE
Adyen_dropin: Possible to check a customised state in  onSubmit event

### ISSUE THREAD

**Issue by lpan42** [Adyen/adyen-web#1357]
Hi, I am trying to integrate the drop-in to my react app and I am having trouble with implementing the onSubmit event for the pay button. (Adyen client version 4.9.0)

As For the payment, I have a checkbox for CGV condition. I would like to verify if the checkbox is checked or not, before triggering the final submit and calling my server. (if checked true,  continue the submit process,  or if not, have an alert and stop the submit.)

Is there a solution for this use case?
Looking forwards to your kindly help.
Thanks a lot!

**Comment by ribeiroguilherme** [comment]
Hi @lpan42 ,

You should be able to perform this check inside the `onSubmit` method, before doing the payment API call. If the checkbox is not checked, you can perform some action and not do the payment request.

Something like:

```javascript
const checkout = new AdyenCheckout({
    ...
    onSubmit: (state, dropin) => {
        // check if your checkbox is checked here
       if (!isChecked) {
           // do something
           return;
        }
       
      makePayment(state.data)
          .then(...
    },
    ...
});
```

Whereas `isChecked` is part of your React state or Ref. It is up to you how you implement it.

I hope it helps!
