### ISSUE TITLE
PayPal window keeps loading forever

### ISSUE THREAD

**Issue by baatractive** [Adyen/adyen-web#1359]
**Describe the bug**
When clicked on **PayPal** button, a new window is opened and loader keeps loading forever.
**ON ERROR CALLBACK**: The instance of the PayPal component being used is not the same which started the payment

**To Reproduce**
1. Click PayPal button
2. Wait for the windows to load

**Expected behavior**
It should show a PayPal **Pay** button.

**Screenshots**

![image](https://user-images.githubusercontent.com/88047235/141357748-0db017da-2a61-408e-bf1c-c7fdb3123bd0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Mozilla
 - Version 94.0.1 
 - Backend PHP: V52

**Additional context**
```
const paypalConfiguration: CoreOptions = {
          environment: 'test', // Change this to "live" when you're ready to accept live PayPal payments.
          countryCode: 'NL', // Only needed for test. When live, this is retrieved automatically.
          style: { // Optional configuration for PayPal Smart Payment Buttons.
            layout: 'vertical',
            color: 'blue'
          },
          onShippingChange: function(data, actions) {
            // Listen to shipping changes.
          },
          onInit: (data, actions) => {
          // onInit is called when the button first renders.
          },
          onSubmit: (state, component) => {
            component.handleAction({
              paymentData: 'some encrpyted token',
              paymentMethodType: 'paypal',
              sdkData: {
                token: 'foo token'
              },
              type: 'sdk'
            });
          }
        };
        
        const checkout = await AdyenCheckout(paypalConfiguration);
        checkout.create('paypal')
          .mount('#paypal-button-container');
   ```

**Comment by baatractive** [comment]
#1007

**Comment by baatractive** [comment]
The issue occurred the because the component state was not set to `ready` when I called `handleAction` with static data. However, with timeout the issue was resolved. This error was quite misleading and was not sure what could be wrong. This probably needs to be fixed. Thanks

**Comment by ribeiroguilherme** [comment]
Thanks for reaching out @baatractive .

For more insights in how to integrate with PayPal, you can check [here](https://github.com/Adyen/adyen-web/blob/51863e12484ba7b035c748ce4f7b0eb0ce6e1a96/packages/playground/src/pages/Wallets/Wallets.js#L104).

**Comment by baatractive** [comment]
@ThermScissorpunch Here's what I did in the submit function as far as I remember but I rolledback all the changes becuase Express Checkout HPP was not planned for depreication at that point of time

```
onSubmit: (state, component) => {
            setTimeout(() => {
            component.handleAction({
              paymentData: 'some encrpyted token',
              paymentMethodType: 'paypal',
              sdkData: {
                token: 'foo token'
              },
              type: 'sdk'
            });
          }
   }, 100)
```

**Comment by ThermScissorpunch** [comment]
Thanks! Now the popup does something :)
It closes immediately.
What kind of value must I enter in `sdkData.token`? I don't seem to have this in my data yet.

**Comment by baatractive** [comment]
@ThermScissorpunch I couldn't recall from where I got the token but most probably it would be inside the component/state param or otherwise check the XHR calls but not sure

**Comment by stefanovollono81** [comment]
@ThermScissorpunch did you figure out where to get the sdkData.token from?
