### ISSUE TITLE
Paypal button style config in adyen 4.9

### ISSUE THREAD

**Issue by udgdev** [Adyen/adyen-web#1366]
**Describe the bug**
I would like to use the style attribute to change the appearance of the paypal button

**To Reproduce**
1. add the style attribute to the paypal configuration and run the app
```
const configurationPaypal = {
          paymentMethodsResponse: res,
          environment: this.adyenEnvironment,
          clientKey: this.adyenClientKey,
          countryCode: 'DE', 

          style: { // Optional configuration for PayPal Smart Payment Buttons. See also https://developer.paypal.com/docs/checkout/integration-features/customize-button/
            color: 'blue',
          },
       // ...

const checkoutPayPal = new AdyenCheckout(configurationPaypal);
checkoutPayPal.create('paypal').mount(this.checkoutContainerPaypal.nativeElement);
```

**Expected behavior**
the button is visible, usable and blue.

**Result**
the button can be used, but its color is yellow (=standard).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 95
 - adyen-web 4.9 (used in angular 12.2)

**Additional context**
Is there any documentation for the adyen-web versions prior 5.0.0? I could not find any.

**Comment by ribeiroguilherme** [comment]
Hi @udgdev ,

You are passing the paypal `style` configuration to the main [Configuration object](https://docs.adyen.com/online-payments/web-components/integrated-before-5-0-0?tab=v5_0_0_or_later_1#step-2-add-components). You should pass it to the paypal configuration object.

It can be achieved by doing:
```javascript
checkout.create('paypal', {
    ...
    style: { color: 'blue' },
    ...
});
 ```

or by passing it to the `paymentMethodsConfiguration` object:

```javascript
const configuration = {
    paymentMethodsResponse: res,
    ...
    paymentMethodsConfiguration: {
        paypal: {
            style: { color: 'blue' }
        }
    }
};
 
const checkout = new AdyenCheckout(configuration);

checkout.create('paypal').mount(this.checkoutContainerPaypal.nativeElement);
```

More about paypal configuration can be found [here](https://docs.adyen.com/payment-methods/paypal/web-component#layout)

I hope it helps!
