### ISSUE TITLE
Error in a React-component: Cannot set properties of undefined (setting 'components')

### ISSUE THREAD

**Issue by persyl** [Adyen/adyen-web#1371]
**Describe the bug**
A have a React functional component using adyen-web version 5.2.1 that sets:

`const adyenElementRef = React.createRef()`

and then in a useEffect() I do:

```
React.useEffect(() => {
        if(adyenElementRef && adyenElementRef.current && adyenConfig){
            AdyenCheckout(adyenConfig).then(checkout => {
                checkout.create('dropin').mount(adyenElementRef.current) // Create an instance of Drop-in and mount it to the container you created.
            })
        }
    }, [adyenElementRef, adyenConfig])
```

And my render is doing:

`return <div ref={adyenElementRef}></div>`

**Expected behavior**
My dropin card payment should render

**Error I get in the browser console**
Cannot set properties of undefined (setting 'components')

**Comment by ribeiroguilherme** [comment]
Hi @persyl ,

As you are using `useEffect`, that means that you are writing a Functional Component in React. Therefore you should use `useRef` hook instead of `createRef()` in order to keep the reference of the element.

More about the difference can be found [here](https://stackoverflow.com/questions/54620698/whats-the-difference-between-useref-and-createref). I believe that this might fix your issue. Can you please check?

**Comment by ribeiroguilherme** [comment]
Closing this issue for now. Feel free to reach out if you have problems using the library.

**Comment by heronfilho** [comment]
I have the same issue with Vue 3. 

The thing is, this error seems to be triggered by the `const checkout = await AdyenCheckout(configuration)` line not the `checkout.create()` or `checkout.mount()` which could then be related to the ref. In my case I already validated that the ref is being correctly retrieved/returned, but I still get this error on the AdyenCheckout() line, any thoughts on this @ribeiroguilherme ?

**Comment by ribeiroguilherme** [comment]
@heronfilho I suspect that you might have been missing something in your `configuration` object then

Did you have the chance to take a look into our [adyen-vue example](https://github.com/adyen-examples/adyen-vue-online-payments) ? Maybe it can shed some light of how to create the AdyenCheckout using Vue
