### ISSUE TITLE
Add browserInfo object in ApplePayElement component

### ISSUE THREAD

**Issue by straimis** [Adyen/adyen-web#1377]
**Describe the bug**
For example GooglePay, DropIn components retrieves `browserInfo` object.
ApplePay element does not retrieve this object.

It is expected that ApplePay element also retrieves `browserInfo` object.

Should look something like this:
![image](https://user-images.githubusercontent.com/148342/142885257-342fe371-1a8f-498e-8bc8-b41a2fa6135d.png)

P.S. If I would have rights, I could create a PR for this change.

**Comment by straimis** [comment]
PR created https://github.com/Adyen/adyen-web/pull/1379

**Comment by ribeiroguilherme** [comment]
Hi @straimis .

Thanks for reaching out to us and for creating the PR. Can you share why ApplePay is expected to retrieve the `browserInfo` object? Are you facing any issue related to the lack of this data?

**Comment by straimis** [comment]
Hi @ribeiroguilherme,

our integration relies on `browserInfo` object. DropIn, GooglePay components provide this object, so why not ApplePay? For consistency, it would be great that all parts returns same unified objects.

**Comment by ribeiroguilherme** [comment]
Hey @straimis 

Basically it appears that we don't need this property on ApplePay, since it's only required for 3DS2 payments and ApplePay cannot trigger that. There is no point adding it just for consistency if it isn't used by the payment method. Why do you need it?

**Comment by ribeiroguilherme** [comment]
I am going to close this issue and the PR related to it for now, as ApplePay does not require 3DS2. Thanks for reaching! 🙌
