### ISSUE TITLE
Securefield Styling not applied on Stored Payment Methods

### ISSUE THREAD

**Issue by endbay** [Adyen/adyen-web#1385]
Edit: Thanks to @VasiliyBP, indeed the problem could be fixed with the `storedCard` property. Solved, could be closed!

**Describe the bug**
Stored Payment Methods Securefields CVC field is not able to get styled. While Card Component is correctly styled.

**To Reproduce**
```js
const paymentMethodStyles = {
  base: {
    color: 'white',
    fontFamily: '\'Montserrat\', sans-serif',
    fontSmoothing: 'antialiased',
    webkitFontSmoothing: 'antialiased',
    lineHeight: '1.415',
    fontSize: '14px',
    caretColor: '#ffffff',
    background: 'transparent',
  },
  error: {
    color: 'white',
  },
  placeholder: {
    fontWeight: 400,
    color: '#747778',
  },
  validated: {
    color: '#ffffff',
  },
};

const configuration = {
      paymentMethodsResponse,
      countryCode,
      amount,
      clientKey: Config.adyenClientKey,
      locale: fullLang,
      environment: Config.adyenEnv,
      onSubmit: this.onSubmit,
      onAdditionalDetails: this.onAdditionalDetails,
      paymentMethodsConfiguration: {
        card: {
          enableStoreDetails: true,
          styles: paymentMethodStyles,
        },
      },
};

this.checkout = await AdyenCheckout(configuration);
```

**Expected behavior**
CVC Securefield should be white like in other Card Component.

**Screenshots**

![1](https://user-images.githubusercontent.com/38842789/143455769-0fcf4252-714e-4d9f-856b-388951264343.jpg)
![2](https://user-images.githubusercontent.com/38842789/143455785-03bf6924-cc1c-4ea0-8b11-beb9d38ce558.jpg)

**Version**
v5.2.2

**Comment by VasiliyBP** [comment]
Accidentally i found that for stored cards use another key in paymentMethodsConfiguration. It's `storedCard`. But where this information in docs? Can i see all possible keys for this object?

**Comment by ribeiroguilherme** [comment]
@VasiliyBP thanks for pointing that out. Indeed in the docs we are missing that information. We discussed it internally and we are going to update our documentation soon 👍 

Answering your question, you can use the same keys as you use for normal [Card component](https://docs.adyen.com/payment-methods/cards/custom-card-integration#default-style). I hope it helps!
