### ISSUE TITLE
Next.js 12 + adyen-web not working in IE11

### ISSUE THREAD

**Issue by Knusperchicken** [Adyen/adyen-web#1391]
**Describe the bug**
We are using this library together with Next.js 10/11 and it was working so far in IE11 (which we unfortunately have to support). Now after we upgraded Next.js to version 12, it doesn't work anymore in IE11.

Upon calling the constructor - and it doesn't matter if it's done like this:
```javascript
const checkout = await AdyenCheckout(configuration) // V5
```
... or like this:
```javascript
const checkout = new AdyenCheckout(configuration) // V4
```
I get a crash which looks like this (see screenshots).

Here's a sample project where this problem occurs: [test-adyen-ts.zip](https://github.com/Adyen/adyen-web/files/7617071/test-adyen-ts.zip).

If you need more details feel free to ask.

**Expected behavior**
I would expect this library to work like in any other browser 🙂 

**Screenshots**
![image](https://user-images.githubusercontent.com/46893381/143839450-824dfb05-c45d-43e9-b35a-20ce2e69daea.png)

**Desktop (please complete the following information):**
 - Tested in Windows 10/IE11 (Browserstack)

**Comment by m1aw** [comment]
Hello @Knusperchicken

I believe this might have to do with https://nextjs.org/blog/next-12#es-modules-support-and-url-imports.

ES Modules are not supported by Internet Explorer so you will need to do so yourself.

Hope this helps.

**Comment by Knusperchicken** [comment]
Hey @m1aw,

I'm pretty new to all these things so I'm sorry when asking "dumb" questions 😉  If it's like you're saying, shouldn't the CC form then be visible at all?

**Comment by m1aw** [comment]
No, the full library needs to be loaded before anything is rendered. Could you verify that you are polifylling correctly for IE?

**Comment by Knusperchicken** [comment]
Hm afaik I'm loading the library before anything else is rendered and the IE polyfilling in the example project is the same as it has always been in our main project (which was working before) but I'll check it again. One additional information: It seems to work fine in IE11 with the production build (`yarn build && yarn start`).

**Comment by danielnehrig** [comment]
polyfills are automatically applied by next afaik @m1aw.
also the full lib is loaded before first render.

**Comment by danielnehrig** [comment]
> https://nextjs.org/blog/next-12#es-modules-support-and-url-imports

i agree we'll look into it

**Comment by danielnehrig** [comment]
i remember we are doing dynamic imports because having a es import doesn't work nicely with the serverside transpiling
i changed it to a direct import now we are getting following error
```
erver Error
ReferenceError: Element is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Object.<anonymous>
file:///home/dnehrig/code/work/next-checkout/node_modules/@adyen/adyen-web/dist/cjs/index.js (1:26882)
```

**Comment by danielnehrig** [comment]
good point `Regardless of that, the library still needs to be instantiated in a browser environment. On Next.js you can do that loading with no SSR` we'll do that

**Comment by Knusperchicken** [comment]
I'm going to try it with the new release soon - hopefully this fixes the issue 👍🏻

**Comment by Knusperchicken** [comment]
Yes, the new release solves the issue we were facing - thanks guys 👍🏻
