### ISSUE TITLE
Payment not processing. 422 status code for session.

### ISSUE THREAD

**Issue by pankaj210891** [Adyen/adyen-web#1397]
**Describe the bug**
I have implemented Adyen Apple Pay on ReactJS for web with Drop-in. Also, I am using Adyen's Apple Pay Certificate.

For web it was my issue that I didn't logged with apple account in macOS, after logging it works on first click.

But the new issue that I am facing is that on web it ask for bluetooth connection with apple device with same login. After connecting both iPhone and Mac with bluetooth, it is not processing payment and says "iPhone could not be found, please make sure iPhone is nearby".

On iPhone XR Safari:
When I click on Apple Pay it opens Payment Sheet but in next few seconds it closes it. When checked the network call a session api is getting called but it fails with below response:

URL : https://checkoutshopper-test.adyen.com/checkoutshopper/v1/applePay/sessions
Request Params (Not using the actual values): 
 {
    "displayName": "XXX",
    "domainName": "XXXX.XXXX.XX",
    "initiative": "web",
    "merchantIdentifier": "XXX.XX.XXX.XXX"
} 

Response : 
{
  "status": 422,
  "errorCode": "000",
  "message": "Payment Services Exception merchantId=XXXXX unauthorized to process transactions on behalf of merchantId=XXXXX reason=\"XXXXX never authorized mass enablement transactions to occur via XXXXX"",
  "errorType": "validation"
}

**Desktop:**
 - OS: MacOS
 - Browser Safari
 - Version 13.1.3

**Smartphone:**
 - Device: iPhone XR
 - OS: iOS 15.1
 - Browser Safari
 - Version 15.1

**Comment by ribeiroguilherme** [comment]
Hi @pankaj210891.

Thanks for reaching out to us. Which version of adyen-web are you using?

**Comment by pankaj210891** [comment]
I am using the latest version 5.3.1

**Comment by pankaj210891** [comment]
> Hi @pankaj210891.
> 
> Thanks for reaching out to us. Which version of adyen-web are you using?

I am using the latest version 5.3.1

**Comment by marcperez** [comment]
Hi @pankaj210891,

There seems to be an Apple Pay certificate configuration issue.
Please make sure you followed this required Apple Pay setup steps as described in our documentation: https://docs.adyen.com/payment-methods/apple-pay/web-drop-in#set-up-apple-pay

If the problem persists, please [contact our support team](https://www.adyen.help/hc/en-us) so they can help further.

I'll close this issue in the meantime. Hope this helps!

**Comment by notadilnaqvi** [comment]
@pankaj210891 Hey, I'm facing the same issue. Did you get any resolution with this issue from the support team?

**Comment by notadilnaqvi** [comment]
Adyen's support team resolved this issue for us. This issue seemed to have arisen due to some config issue on Adyen's end. We contacted their support team, mentioned this issue, and they got back to us saying they've resolved it. They never explicitly told us what they fixed but the issue seems to be gone now.

**Comment by aokalla** [comment]
Adyen's support team resolved this issue for us. 
They found that all our domains were not configured at payment method level. 
They added the new domain on the ApplePay payment method, this action fixed the issue.
