### ISSUE TITLE
`useOriginalFlow` not passed correctly when calling `createFromAction`

### ISSUE THREAD

**Issue by tr33m4n** [Adyen/adyen-web#1402]
When creating a fingerprint action instance using the `createFromAction` method and passing `useOriginalFlow` in the config, eg:
```js
checkout
    .createFromAction(threeDSAction, {
        useOriginalFlow: true
    })
    .mount(threeDSRef.current);
```
The `useOriginalFlow` prop never makes it to https://github.com/Adyen/adyen-web/blob/99668f7dfb0670ef34ed0d2ea90247f166a0652b/packages/lib/src/components/ThreeDS2/ThreeDS2DeviceFingerprint.tsx#L47 due to the `get3DS2FlowProps` method stripping it and some of the original props here https://github.com/Adyen/adyen-web/blob/2417c126f28c90ba73db31a3873c4f59fed9175f/packages/lib/src/core/ProcessResponse/PaymentAction/actionTypes.ts#L71 (specifically https://github.com/Adyen/adyen-web/blob/2417c126f28c90ba73db31a3873c4f59fed9175f/packages/lib/src/components/ThreeDS2/components/utils.ts#L198)

**To Reproduce**
1. Create a new `ThreeDS2DeviceFingerprint` instance using the `createFromAction` method and pass the `useOriginalFlow` prop
2. See the `ThreeDS2DeviceFingerprint` class still call `this.callSubmit3DS2Fingerprint` instead of `this.onComplete` due to the missing prop

**Expected behavior**
`this.onComplete` is called within the `ThreeDS2DeviceFingerprint` class, instead of `this.callSubmit3DS2Fingerprint`

**Desktop**
 - OS: macOS Big Sur
 - Browser: Chrome
 - Version: 96

**Comment by sponglord** [comment]
Hi @tr33m4n,
What is it you are trying to achieve here?
The `useOriginalFlow` is an undocumented property used to separate internal processes, related to 3DS2, as we transitioned from `v66` to `v67` of our backend API.
I'm surprised to see anyone trying to do anything with it

**Comment by tr33m4n** [comment]
Hi @sponglord 
We're currently transitioning an older project to the latest versions of the Magento module and the dropin. The frontend uses the `onComplete` method to do some custom processing and noticed that it could be triggered with the undocumented `useOriginalFlow` flag. If this is not an intended use case then no worries, I'm leaning towards trying to get `v67` up and running and therefore use the newer `callSubmit3DS2Fingerprint` method

**Comment by sponglord** [comment]
Hi @tr33m4n 

Hi @tr33m4n 
> I'm leaning towards trying to get `v67` up and running and therefore use the newer `callSubmit3DS2Fingerprint` method
I would definitely recommend this. This approach removes the "friction point" we identified of an implementer needing to make an extra `/details` call after the device fingerprinting since we handle that for them with an internal call to `/submitThreeDS2Fingerprint`
I am going to close this issue. 
Please reach out, with a new issue, if you need to.
