### ISSUE TITLE
Return pspReference and refusalReason in onPaymentCompleted callback

### ISSUE THREAD

**Issue by ahimik** [Adyen/adyen-web#1422]
**Is your feature request related to a problem? Please describe.**
My payment workflow implementation relies on `pspReference` field returned by `/payments` request when payment completes. Since `adyen-web`  starting from v `5.0.0` has simplified workflow which performs `/payments` request under the hood, I cannot obtain `pspReference` any more.
The same for `refusalReason` field when `resultCode` is `Refused`.

**Describe the solution you'd like**
`onPaymentCompleted` callback should return `pspReference` along with the `resultCode` field as it was in previous versions.
It should return `refusalReason` as well when `resultCode` is `Refused`.

**Comment by ribeiroguilherme** [comment]
Hi @ahimik ,

Thanks for reaching out to us.  Can you share more why your workflow relies on `pspReference` and `refusalReason` ? What are you doing with these properties? I'd like to understand better your use case so I can give you an advice regarding this.

**Comment by ahimik** [comment]
Hi @ribeiroguilherme ,

`pspReference` is very useful for us in the following use-cases:
1. When payment successfully completes we wait for the webhook payment notification(according to suggestion from docs) to present the result to a shopper(we use instant payment methods only). Therefor we use `pspReference` on a client side to find the corresponding notification. I know that `merchantReference` might be used but it's not applicable in our case.
*Actually for this use-case I've already found a workaround - I use `sessionId` field instead which is unfortunately not well documented yet*.
2. When something goes wrong we present `pspReference` to our shoppers for them to be able to contact to our support. `pspReference` helps our support team to find the payment quickly.

We also present `refusalReason` to our shoppers when payment is rejected. This helps them to quickly identify what went wrong.

In a previous payment workflow implementation both `pspReference` and `refusalReason` fields were available instantly.
Now we have to wait for the notification in order to determine the refusal reason which might take some time in a case of 3D Secured payment. And we don't know which order reference to present to a customer when notification is not received in order to contact our support.

**Comment by ribeiroguilherme** [comment]
Thanks for the explanation @ahimik.

The `pspReference` and `refusalReason` are values which should be best kept private. I understand that your implementation relies on them directly, but we do not recommend to expose them on the frontend. That is why they are not available from v5 onwards.

For the points you brought up:
1. Ideally you should use merchantReference or metadata for this
2. Ideally you should display the merchantReference or metadata to the shopper (order reference or so), not the adyen `pspReference`
3. Same as 2

I hope this set your expectations about these properties!

**Comment by ahimik** [comment]
@ribeiroguilherme thanks for the explanation.
However, our `merchantReference` is used for another purposes because of `metadata` limitations.
We needed some properties, such as `userId` in our system to be included into each webhook notification response, but unfortunately `metadata` as well as `shopperReference` for the gods unknown reason cannot be included into some notifications types such as REFUND or CANCEL.
I contacted support regarding this use-case and they confirmed that the only way to include this data into all notifications is to use `merchantReference` field therefor our `merchantReference` field contains a small json with some custom properties we use in notifications. Looks a bit weird? I agree, but this is strange limitation.
That was actually the reason we used `pspReference` to identify shoppers' transactions.

Regarding `refusalReason`: why is it not recommended to present the refusal reason such as `cvc declined` to a shopper? Should we show some generic message that something went wrong only? I think it will be an extra load on our support team.

**P.S.** we are not in production yet, so I appreciate your suggestions. It's just in time. 
That would be nice if you can suggest how we can get `userId` in REFUND webhook notification instead of including it into `merchantReference` field.

**Comment by ahimik** [comment]
I've checked it again and it seems that `metadata` problem is fixed now:
```
Checkout API (all versions)
Fixed
We fixed an issue where the 3D Secure 2 flow could break when receiving an unsupported screen.colorDepth value on Google Chrome v83 or v84.
We fixed an issue where metadata was not being sent back in the notification webhook.
```

**Comment by ribeiroguilherme** [comment]
You are welcome @ahimik 👍
