### ISSUE TITLE
Content-Security-Policy causes adyen.js to block

### ISSUE THREAD

**Issue by ahimik** [Adyen/adyen-web#1426]
**Describe the bug**
Setting `Content-Security-Policy` header causes `adyen.js` v.5.0.0+ to block with the following message:
```
adyen.js:1487 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src https://checkoutshopper-test.adyen.com ...".
    at Function (<anonymous>)
    at adyen.js:1487
    at adyen.js:1489
    at adyen.js:2
```

**To Reproduce**
1. Install `adyen-web` v 5.0.0 or higher using `npm`
2. Set up `Content-Security-Policy` header. Do not allow 'unsafe-eval' execution.
3. Load the page importing `adyen-web` functionality.

**Expected behavior**
`adyen.js` should be loaded correctly.

**Actual behavior**
`adyen.js` execution is blocked by the browser.

**Note**
The problem doesn't appear in versions less than 5.0.0.
The problem might be related to webpack compiler options.
Webpack should be set up to avoid generating unsafe javascript evaluations.

**Screenshots**
![image](https://user-images.githubusercontent.com/30721033/146653392-c2cd110e-af73-49cb-8d9c-fdb01d9f58f2.png)

**Comment by ribeiroguilherme** [comment]
Hi @ahimik ,

Thanks for reaching out. Indeed there is an issue with excluding `'unsafe-eval'` from the CSP. I am going to create a ticket in our backlog for the fix, and I will update this ticket once it is solved. Thanks for reporting it!

**Comment by ribeiroguilherme** [comment]
Hi @ahimik . We released v.5.11.0 which contains the fix for this problem, therefore I am closing this thread. Thanks for reporting it.
