### ISSUE TITLE
Allow custom redirection handling with Amazon Pay

### ISSUE THREAD

**Issue by ahimik** [Adyen/adyen-web#1435]
**Is your feature request related to a problem? Please describe.**

Our site specificity is we don't redirect users from our site during payment process.
Therefor we integrated with drop-in in a such way that we always manually handle redirect actions in a child popup or an iframe by hooking into `beforeRedirect` callback. In a case of PayPal the drop-in automatically opens it in a popup window.
Unfortunately, when clicking on Amazon Pay button user gets immediately redirected to external site without `beforeRedirect` callback being called. The only hook I've found is `onClick` callback of `amazonpay` configuration object: 
```
amazonpay: {
   onClick: (resolve, reject) => ...
}
```
which is not documented and it doesn't provide any data to proceed with.

**Describe the solution you'd like**
It would be nice to have something like `beforeRedirect` hook for Amazon Pay which provides `CheckoutSessionConfig` data and allows to build custom redirect flow(for example in a popup window instead of redirecting user from current site)
**or** similar to PayPal behavior with Amazon Pay button by default if possible.

**Describe alternatives you've considered**
As an alternative solution I consider opening initial drop in component in a popup window so the redirect will happen in the popup as well, but this is less desirable solution since it looks worse and has some other disadvantages.

I also wonder if there are any plans to provide simplified flow for Amazon Pay?
I just migrated to the latest web `drop-in` version, removed `/paymentMethods` and `/payment` end points implementation and after that I realized that I have to revert everything back just because of Amazon Pay.

**Comment by m1aw** [comment]
Hey @ahimik 

Let me take a look at this, and get back to you about it.

**Comment by ahimik** [comment]
@m1aw , any updates on this?

**Comment by m1aw** [comment]
Hey Alex,

Let me see if I understand the first point correctly. What you are suggesting is to redirect into a new window like Paypal? 
The consequence I see with this is that when performing the next steps in the checkout process (merchant side, ie: get shipping details, order confirm), it would be done also inside this window, since that is the return behavior from Amazon Pay. Would this be what you expect?
