### ISSUE TITLE
User unable to enter text into 'Name on card' field, using Chrome on Android 12.

### ISSUE THREAD

**Issue by ficklephil** [Adyen/adyen-web#1440]
**Describe the bug**

We're unable to enter into the 'Name on card' field (Credit/Debit Card) when using version 5.4.0 of @adyen/adyen-web package.

What we experience is that the User has to enter a number into this field first, before they can enter any other character.

We are experiencing the issue on Chrome (96.0.4646.104), coupled with Android 12 or Android 8.1.0.

We've tested on various devices running Chrome with Android 12.

Please note that when we degraded the version of @adyen/adyen-web package to v5.3.1 it works correctly.

**To Reproduce**

1. Go to the Adyen Drop-in component web interface.
2. Click Credit / Debit Card.
2. Try to fill in the 'Name on card' text field.
4. Using Chrome, on a device running Android 12 or Android 8.1.0, does not allow the User to enter their name on card.

**Expected behavior**

The User is able to enter their name on card.

**Smartphone:**
 - Device: Any device running Android 12 or Android 8.1.0.
 - Browser: Chrome
 - Version: 96.0.4646.104

**Comment by cskills-ganeshholkar** [comment]
Same issue as mentioned above

**Comment by matt-downs** [comment]
We also seem to be experiencing this issue on `5.5.0` - downgrading to `5.3.1` as described seems to resolve the problem

**Comment by ficklephil** [comment]
> Thanks for reaching out folks. This issue got fixed on `5.6.0` 👍

Thanks!
