### ISSUE TITLE
Session expired error handling

### ISSUE THREAD

**Issue by ahimik** [Adyen/adyen-web#1444]
**Is your feature request related to a problem? Please describe.**
As a customer I want to see the appropriate message when my payment session is expired.

**Describe the solution you'd like**
Adyen web drop-in should return appropriate error name and message when session is expired.

**Additional context**
Currently when session expired error occurs:
![image](https://user-images.githubusercontent.com/30721033/148891917-3abf191f-1035-4fe4-b4dc-b6a090700cff.png)

the drop-in returns incorrect error object:
![image](https://user-images.githubusercontent.com/30721033/148892093-87d9e0a6-45ce-4c5f-b8c5-5787a5119fb9.png)

**Comment by ribeiroguilherme** [comment]
Hi @ahimik ,

We released the version 5.6.2 which contains improvements for the error messages. Hope it helps!
