### ISSUE TITLE
3ds2 submit password no callback

### ISSUE THREAD

**Issue by wangxingxing123654** [Adyen/adyen-web#1451]
![image](https://user-images.githubusercontent.com/28847126/149928258-3393e561-e06b-477b-8151-44701a401158.png)

we use  "@adyen/adyen-web": "3.19.0",
(3ds2 test account  )  4035501428146300
03/30 737
![image](https://user-images.githubusercontent.com/28847126/149928530-9777a06f-9159-4966-bef8-c1e32ada6757.png)

here is the test website
https://harbor2-cdn.alpha.stylewe.com/checkout/payment-method/61e6a37ab1413132610687ec
![image](https://user-images.githubusercontent.com/28847126/149928712-9a25d6ae-e422-4581-949e-c664c94058cc.png)

**Comment by wangxingxing123654** [comment]
window.checkout = new this.AdyenCheckout({
      environment: googleEnvironment,
      originKey: additionData.originKey,
      paymentMethodsResponse,
      onAdditionalDetails: this.handleOnAdditionalDetails,
      onError: this.handleBlikError,
    });

it should fired the onAdditionalDetails callback.

**Comment by ribeiroguilherme** [comment]
Hi @wangxingxing123654 ,

Thanks for reaching out. I tested the `onAdditionalDetails` callback on 3.19.0 and it is working fine, so the issue might be related to your configuration.

Sometimes a wrong `origin` on the `/payments` request can break this, since the iframe cannot communicate back to the merchant context. Can you double check if the `origin` is correct?

**Comment by sponglord** [comment]
Hello @wangxingxing123654
There is no callback possible from the "Continue" button that you  highlight - since what you are looking at here is an iframe whose content is entirely the responsibility of the relevant ACS/Issuer and as such is out-of-scope for Adyen-Web.
The only callback you can expect to be called is `onAdditionalDetails` once the 3DS2 challenge process has completed and we are ready for you to submit the result to our `/payments/details` endpoint.
I hope this answers your question.

**Comment by sponglord** [comment]
Hello @MohsinActive8 
> what are the callbacks that we can use other then `onAdditionalDetails`

You can see a list of the available callbacks here (for the Dropin): https://docs.adyen.com/online-payments/web-drop-in/optional-configuration#events
And here (for the Card component): https://docs.adyen.com/payment-methods/cards/web-component#optional-configuration

**Comment by taimaiduc** [comment]
I have the same issue, on a react app, and dev mode
onAdditionalDetails is trigger

![image](https://user-images.githubusercontent.com/10907980/222613084-55429047-6324-4bd2-842c-5d63732637a9.png)

**Comment by dimitriBouteille** [comment]
Hello,

Same issue again ... on `react app` (next) and dev mode.  Also, when I add the `onAdditionalDetails` option to `AdyenCheckout` the component validation no longer works. 

```js
// Create AdyenCheckout
const adyenCheckout = useAdyenCheckout({
	onAdditionalDetails: (state) => {
		console.log('ADYEN::onAdditionalDetails', state);
	},
  });

...

// Mounted composant adyenCheckout.create('card', {...})
const secureFieldsRef = useRef<SecuredFieldsElement>(null);

...
const onPlaceOrder = useCallback(
    async (method: AvailablePaymentMethod) => {
      if (!secureFieldsRef.current) {
        return console.error('Checkout not initialized.');
      }

      secureFieldsRef.current.showValidation();
      if (secureFieldsRef.current.isValid === false) {
        return console.error('Invalid payment method options.');
      }

      ...
    }
  }
, [])
```	

When I trigger onPlaceOrder, secureFieldsRef.current.isValid return false :(

![Capture d’écran du 2023-05-12 19-21-59](https://github.com/Adyen/adyen-web/assets/34821762/876b1f3e-47eb-48ef-bf8a-90b6c208402b)

@sponglord Can you re-open this issue and try to fix this bug?

**Comment by taimaiduc** [comment]
After checking this issue can be fixed by setting the origin URL on the server side.
I am using Adyen PHP Magento2
![image](https://github.com/Adyen/adyen-web/assets/10907980/01000d02-72b5-4297-a44f-4a180e350eaf)

**Comment by dimitriBouteille** [comment]
Hi @taimaiduc 

Thank you very much, the 3D2S works perfectly now!

To complete your message, the configuration is in `Payment Methods | Adyen | Advanced settings | Headless Integration | Payment Origin URL`. If you use a single domain for all stores, the easiest way is to set this value to `Default Store`.

![Capture d’écran du 2023-05-16 10-28-26](https://github.com/Adyen/adyen-web/assets/34821762/b5412960-8d45-463b-b6d5-a40447c30264)

**Comment by sudha5555** [comment]
> Hi @wangxingxing123654 ,
> 
> Thanks for reaching out. I tested the `onAdditionalDetails` callback on 3.19.0 and it is working fine, so the issue might be related to your configuration.
> 
> Sometimes a wrong `origin` on the `/payments` request can break this, since the iframe cannot communicate back to the merchant context. Can you double check if the `origin` is correct?

We were facing the same issue in angular js. Origin was the issue, we gave the wrong value here
