### ISSUE TITLE
Ability to add custom text above the pay button in the drop in component

### ISSUE THREAD

**Issue by jcpof** [Adyen/adyen-web#1472]
It would be nice if a user was able to add some custom text (ie: legal text) above the pay button in the drop in component. 

A solution could be to add an optional prop to the drop in configuration that would accept text or a node.

**Comment by ribeiroguilherme** [comment]
Hi @jcpof ,

There are no plans to add such customization for the Drop-in component. 

As a solution for this, an approach is to position the text somewhere else, or to use our Components with a custom button. You can also try Drop-in and experiment configuring it with the property `showPayButton: false`, then create your own Pay button with the text. I hope it helps!

**Comment by michalkrynski** [comment]
> Hi @jcpof ,
> 
> There are no plans to add such customization for the Drop-in component.
> 
> A solution for this is to position the text somewhere else, or to use our Components with a custom button. You can also try Drop-in and experiment configuring it with the property `showPayButton: false`, then create your own Pay button with the text. I hope it helps!

Is it possible to create custom Pay button and display it inside payment method in the same place as default pay button? How to achieve that?

**Comment by ribeiroguilherme** [comment]
Hi @michalkrynski 
I don't advise to create the button inside the payment method, as the re-renders triggered internally will end up removing it.
