### ISSUE TITLE
(Un)successful iDeal payment doesn't trigger callback

### ISSUE THREAD

**Issue by Zwartpet** [Adyen/adyen-web#1478]
**Describe the bug**
After finishing the iDeal payment you get redirected back to the app with a redirectResult. Neither the `onError` or `onPaymentCompleted` callback is being called.

**To Reproduce**
1. Finish an iDeal payment

**Expected behavior**
I expected the callbacks to be called so I can tell the user if the payment was successful

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: latest

**Comment by ribeiroguilherme** [comment]
Hi @Zwartpet,

Thanks for reaching out. Which version are you using?

**Comment by Zwartpet** [comment]
Hi @ribeiroguilherme I'm using version 5.6.2

**Comment by Zwartpet** [comment]
With some trial and error and going through the adyen source code I've fixed it.
Maybe the docs could be more clear on how to handle the redirect result:

```
const config = {
                environment: 'test',
                session: {
                    id: sessionId
                },
                clientKey: 'test_************',
                onPaymentCompleted: (result, component) => {
                    console.info(result, component);
                },
                onError: (error, component) => {
                    console.error(error.name, error.message, error.stack, component);
                },
            };

            const checkout = await AdyenCheckout(config);
```

It wasn't working due to a config error

**Comment by ribeiroguilherme** [comment]
I'm glad you managed to fix your issue @Zwartpet.  Can you point out what went wrong in your case and what could be improved on our docs? So I can discuss internally with the team and improve the documentation. Thanks!

**Comment by Zwartpet** [comment]
Sorry for the late response, I missed the mail with your response.

In the documentation about handling [redirects](https://docs.adyen.com/online-payments/web-components#handle-redirects) there's an example:
`const checkout = await AdyenCheckout(configuration);`

I misconfigured the configuration as I assumed the `sessionId` and the `redirectResult` would be enough. There's no hint that it also needs the same required configuration from [the documentation above it](https://docs.adyen.com/online-payments/web-components?tab=codeBlocksessions_tNhEg_bash_1#configure) (which is pretty obvious in hindsight)

**Comment by ribeiroguilherme** [comment]
Thanks @Zwartpet , I will discuss this internally with the team and improve our docs. Cheers!

**Comment by haronka1999** [comment]
Hello @Zwartpet, I'm facing with same issue for using the TWINT payment. Can you share more of your solution and what caused the problem? Thank you
