### ISSUE TITLE
PayPal support in stored payment methods

### ISSUE THREAD

**Issue by andriichuk** [Adyen/adyen-web#1480]
Hi there! It looks like PayPal is not supported for stored payment methods - https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/core/ProcessResponse/PaymentMethodsResponse/filters.ts#L13, but according to the Adyen documentation, PayPal supports recurring payments https://docs.adyen.com/payment-methods/paypal/web-component#recurring-paypal-payments. Also, I see the PayPal method in the list of stored payment methods (`paymentMethods.storedPaymentMethods`) from the `paymentMethods` response https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/paymentMethods.

![image](https://user-images.githubusercontent.com/38154251/152845026-4487ce40-89ef-4e8f-a66e-35947d40f909.png)

Could you please clarify this behavior or maybe I should use a different component configuration?

**To Reproduce**
1. Enable PayPal recurring payments
2. Mount PayPal component on payment form
3. Pay order with `storePaymentMethod: true` option (https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/payments__reqParam_storePaymentMethod)
4. Open the payment form once again and check the response from the https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/paymentMethods endpoint
5. `paymentMethods.storedPaymentMethods` response array contains PayPal method with credentials from the first payment
6. Assign server-side response to Adyen component (`const checkout = new AdyenCheckout(config)`)
7. Request stored method from component (`checkout.paymentMethodsResponse.storedPaymentMethods`)
8. PayPal is missing

**Desktop:**
 - OS: Ubuntu 18.04.6 LTS
 - Chromium
 - Version 98.0.4758.80 (Official Build)

**Comment by lebara-moaead** [comment]
It seems like a limitation in the drop in.
we have the same issue, we had to fork the repo and do the changes to support it

<img width="763" alt="image" src="https://user-images.githubusercontent.com/84312526/155281210-54bebae8-15af-45eb-8e26-e757180aa288.png">

**Comment by Popone55** [comment]
Any update on this one?

**Comment by ribeiroguilherme** [comment]
We do not supported PayPal as stored payment method. We do offer recurring payments with PayPal, but only via subscriptions, which means that there is no need to display the PayPal button as stored payment method in the Drop-in. 

I hope that is clear!
