### ISSUE TITLE
Unhandled promise rejection TypeError: null is not a function at Y (adyen.js:1:2181)

### ISSUE THREAD

**Issue by ajpulluvelil** [Adyen/adyen-web#1482]
An error is logging in the browser console.
Unhandled promise rejection TypeError: null is not a function at Y (adyen.js:1:2181)

I am using Adyen version 4.5.0 in an Angular project. The modules are using lazy loading, when we go to the module where the Adyen is used, from that scenario the error logs are coming. 
I think importing AdyenCheckout from '@adyen/adyen-web' causes the issue due to some null values.

Due to this error browser is staying in an idle state. For e.g. if we have added a loader, that loader will remain in UI until we fire an event like mouse move or click.

![Screenshot (173)](https://user-images.githubusercontent.com/45339469/152954341-86cb0dcb-8f8f-4fef-9176-2ae4a8649884.png)

 - OS: Seems like all OS has the issue, I've tested in Windows 10.
 - Browser: Same like in the case of OS, I got the error in chrome and Mozilla Firefox

**Comment by ribeiroguilherme** [comment]
Hi @ajpulluvelil ,

Can you share more how you are importing the library in your file and how you are instantiating it? Are you doing SSR? 

We have the [Angular example](https://github.com/adyen-examples/adyen-angular-online-payments) repository where you can have a look. It might shed some light on your problem. Btw, it is using same version as you are using on your project (4.5.0).

**Comment by ribeiroguilherme** [comment]
And at what moment is the exception throw in your case? (When you create the `checkout`? When you attach it to the DOM? etc)

**Comment by ajpulluvelil** [comment]
In my case the exception is throwing when the module is loaded into the DOM. Checkout creation and other instantiations are exactly like in the example provided earlier.

**Comment by ajpulluvelil** [comment]
Will any other npm packages will cause this error? Because I'm using some other packages also.

**Comment by Ajithonline** [comment]
`const checkout = await AdyenCheckout(configuration);`

**Comment by ribeiroguilherme** [comment]
Hi @ajpulluvelil . Are you still facing issues regarding this? If yes, can you create a repo reproducing the problem so I can take a look?

**Comment by ajpulluvelil** [comment]
Hi @ribeiroguilherme, we have upgraded the version to "5.5.0" and it solved our issue. Thanks for the responses for the issue.
