### ISSUE TITLE
Billing address stateOrProvince input dropdown list is not reset after unfocusing on search 

### ISSUE THREAD

**Issue by ctnswb** [Adyen/adyen-web#1497]
**Describe the bug**
For the billing address state dropdown input, the search input doesn't get reset if the user clicks outside of the input/dropdown to close the dropdown.  The dropdown list will have the old search results the next time the user clicks on the input even though the search input looks empty.

**To Reproduce**
1. Create a dropin component that has a card payment method with billing address required.
2. Click on the State input
3. Type in a search word
4. See the dropdown list with the filtered results
5. Click outside of the input/dropdown, without selecting an option.
6. Click on the input again
7. See that the search input is empty (no longer has the search word previously typed), but the dropdown list results still shows the same filtered results from the prior search instead of the initial list containing all the options.

**Expected behavior**
When the user clicks on the state dropdown input, if the search field is empty, the dropdown list should display all the options.

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - Browser chrome
 - Version 5.6.1

**Additional context**
Testing this in the US

**Comment by ribeiroguilherme** [comment]
Hi @ctnswb ,

Thanks for reaching out, and good catch! I created one ticket in our backlog to fix this problem, and I will update this issue once the fix is done.

**Comment by ribeiroguilherme** [comment]
Hi @ctnswb,

We released the version 5.13.1 which contains the fix for this issue. Thanks for reaching out!
