### ISSUE TITLE
Boleto Bancario component uses a different structure of data to pre-fill the shopper details than in documentation

### ISSUE THREAD

**Issue by FastAlien** [Adyen/adyen-web#1503]
**Describe the bug**
I've found inconsistency between documentation and implementation of the Boleto Bancario component. Documentation says that data used to pre-fill shopper details should have following structure:
```
{
  shopperName: {
    firstName: string;
    lastName: string;
  };
  billingAddress: {
    city: string;
    street: string;
    country: string;
    postalCode: string;
    stateOrProvince: string;
    houseNumberOrName: string;
  };
  socialSecurityNumber: string;
  shopperEmail: string;
}
```
Source: https://docs.adyen.com/payment-methods/boleto-bancario/web-drop-in#optional-configuration

But component expects following structure:
```
{
  firstName: string;
  lastName: string;
  billingAddress: {
    city: string;
    street: string;
    country: string;
    postalCode: string;
    stateOrProvince: string;
    houseNumberOrName: string;
  };
  socialSecurityNumber: string;
  shopperEmail: string;
}
```
Source: https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/components/Boleto/Boleto.tsx#L28

**Steps to reproduce**
1. Configure Boleto Bancario with data in format suggested by documentation:
```
boletobancario: {
  data: {
    shopperName: {
      lastName: 'Smith',
      firstName: 'John',
    },
    billingAddress: {
      city: 'Example City',
      street: 'Example Street',
      country: 'BR',
      postalCode: '04642000',
      stateOrProvince: 'SP',
      houseNumberOrName: '34',
    },
    socialSecurityNumber: '12345678890',
  },
}
```
2. First name and last name fields are not pre-filled.

**Expected behavior**
First name and last name fields should be pre-filled. Boleto Bancario component should use the same structure of data as described in documentation.

**Comment by ribeiroguilherme** [comment]
Hi @FastAlien ,

Thanks for reporting this problem. Indeed the pre-fill for first/last name of boleto is not working as described on our docs.
I created a ticket on our backlog, and I will update this thread once the fix is released.
