### ISSUE TITLE
A way to specify payment method when mounting Dropin

### ISSUE THREAD

**Issue by geext-dk** [Adyen/adyen-web#1510]
**Is your feature request related to a problem? Please describe.**
We have a case when our payment amount may change after initializing the Dropin. The documentation [advices ](https://docs.adyen.com/online-payments/web-drop-in/integrated-before-5-0-0#methods) to remount (unmount and mount) the widget in case it changes. But payment methods configuration (some of which also require `amount`) is specified in the global configuration only, so it also should be updated. That's why I use `AdyenCheckout.update` method to update the configuration and remount dropin automatically. Yet it introduces another problem - after remounting, the dropin doesn't open the payment method that was opened before unmounting.

Without updating the amount, Google Pay and Apple Pay show outdated amount in their widgets.

To workaround that, I get the current payment method type (`this.dropin.activePaymentMethod?.type`) and I find the needed payment method in the DOM via this selector `.adyen-checkout__payment-method--${type}` and call `.click()` to simulate choice. And all of that should be done in the `onReady` dropin hook, because when `AdyenCheckout.update` resolves dropin is not yet fully mounted. I think that's not how it should be done.

Of course it's possible I'm doing it the totally wrong way.

**Describe the solution you'd like**
Add a public method for selecting a payment method by its type

**Describe alternatives you've considered**
* Preserve selected payment option when remounting Dropin
* Add a public method or other way to update amount without remounting Dropin
* A configuration value that specifies which payment method to open upon mounting the Dropin

**Additional context**
Our dropin is integrated the old way (before 5.0.0).
Package version we use (`@adyen/adyen-web`): 5.3.1.

**Comment by ankarhem** [comment]
Hey,

I have a similar problem. I think the approach klarna has for solving this problem is quite good. They allow you to lock the UI with a suspend function when performing external actions that affect the session. And then a resume function that unlocks the UI, that also refetches the internal amount in klarnas' session.

You could provide a way to patch the session via api and then mimick this behaviour in the mount / remount function. That provides a good DX which abstracts much of the logic.

**Comment by camil-adyen** [comment]
Hi all!

A BETA version of Web v6 is now available on Github. Feel free to take a look and give us feedback! We aim to release the official v6 in the coming weeks. More information can be found [here](https://github.com/Adyen/adyen-web/releases/tag/v6.0.0-beta.0).

**Comment by ribeiroguilherme** [comment]
Hi all,

We release v6.0.0 this week which exposes the functionality to pre-select payment method when mounting Drop-in.

Ex:

```js
const dropin = new Dropin(checkout, {
  openPaymentMethod: { 
    type: 'ideal',
  }
});
```

Try it out and let us know in case you guys face any issues with that. Cheers!

**Comment by daniel-qima** [comment]
Hi @ribeiroguilherme , thanks for the update, I'm trying to set `openPaymentMethod` as following to show Cards as the default one, but it not working, I've checked [this](https://docs.adyen.com/payment-methods/payment-method-types/) page, seems currently `scheme` is not supported?
```
const dropin = new Dropin(checkout, {
  openPaymentMethod: { 
    type: 'scheme',
  }
});

```

**Comment by ribeiroguilherme** [comment]
Hi @daniel-qima - setting the type as `scheme` should work. I just tested on my local env using the latest version and works as expected.

Did you also try other payment methods by any chance? Is it only happening to the 'scheme'? Which version are you using?

**Comment by daniel-qima** [comment]
Hi @ribeiroguilherme, thanks for the quick update, yes today I tried again and the `scheme` worked, it must be something wrong with my local env, sorry for the stupid question.
