### ISSUE TITLE
Examples don't work without basic auth

### ISSUE THREAD

**Issue by code-acrobat** [Adyen/adyen-web#152]
**Describe the bug**
Node.js server doesn't work without adding basic auth credentials.

**To Reproduce**
1. configure api key, setup origin in ws account
2. run npm devserver
3. access card component
```
> node ./server/node/index.js

Listening on localhost:3000
Request to /originKeys ended with status 401 - 401
Request to /payments ended with status 401 - 401
```
**Expected behavior**
Expect to have the example running with setting the described params in .env file

**Additional context**
I managed to get the example running by adding the basic auth "Authorization: Basic ...." header in 
server/node/utils/getPostParameters.js

**Comment by marcperez** [comment]
Hi @code-acrobat,

We are not able to replicate this issue. Could provide the commands you are using to start the server?

Also, could you double check that you are providing the `CHECKOUT_API_KEY` and `MERCHANT_ACCOUNT` fields on the `.env` file?

Thanks!

**Comment by code-acrobat** [comment]
I have CHECKOUT_APIKEY as per template not CHECKOUT_API_KEY. But yeah otherwise I have them.

**Comment by code-acrobat** [comment]
npm run devserver 
is used to start the server

**Comment by marcperez** [comment]
Hi @code-acrobat 

> I have CHECKOUT_APIKEY as per template not CHECKOUT_API_KEY. But yeah otherwise I have them.

The correct name is `CHECKOUT_API_KEY` as shown in the `env.default` file in the root of this project. Could you try that?

> npm run devserver
> is used to start the server

We don't have any script called `devserver`. Could you try running the project following [this instructions](https://github.com/Adyen/adyen-web#development-environment)? 

```sh
yarn start
```

Hope this helps,
Cheers!

**Comment by code-acrobat** [comment]
my bad, I've been working on https://github.com/Adyen/adyen-components-js-sample-code.git

**Comment by code-acrobat** [comment]
In this project i have the same issue.
setup the .env file from the env.default with merchant_account, api key, etc from customer area. 

run yarn start:
access an example page (http://localhost:3000/securedfields) I kept port 3000.

then the log shows:
ℹ ｢wdm｣: Compiled successfully.
Request to /originKeys ended with status 401 - 401

and I see a forever spinning wheel in the browser.

**Comment by marcperez** [comment]
Hi @code-acrobat,

Could you try changing the port back to `3020`?

Please note that this environment is intended for the development of this library. If you would like to try out different components I would advise you to use our [sample code repository](https://github.com/Adyen/adyen-components-js-sample-code).

Hope this helps!

**Comment by code-acrobat** [comment]
As written above the bug I wanted to raise is intended for the sample code repository.
Also changing back the port to 3020 doesn't help. 
I always get a "Request to /originKeys ended with status 401 - 401". 
Most likely because the requests require basic auth, which is nowhere to be confiured either here or in the sample code repository.

Is it possible/required to run the ws@Company account without basic auth? AFAIR my local curl examples wouldn't work then.

**Comment by marcperez** [comment]
Hi @code-acrobat,

In this case, the correct `.env` variables can be found [here](https://github.com/Adyen/adyen-components-js-sample-code#requirements). 
Please note that the `CHECKOUT_APIKEY` should contain the API Key and not the `originKey` (more information on this [here](https://docs.adyen.com/user-management/how-to-get-the-api-key)).

Another thing you could try is [running the PHP server provided in that repository](https://github.com/Adyen/adyen-components-js-sample-code#running-the-php-server).

Also, you could try [calling the API](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v53/overview) through cURL, in order to discard any issues with your account configuration.

Hope this helps!

**Comment by code-acrobat** [comment]
Ok, I've generated a new API key and it solved the issue. Looks like basic-auth and api-key is either or.
The new key wasn't immediately effective and there must have been a typo so my inital curl examples. 
So I included a basic auth in everything which magically made it work but then failed in example applications.

**Comment by marcperez** [comment]
Happy it's solved now!
