### ISSUE TITLE
onSelect event for sessions workflow

### ISSUE THREAD

**Issue by carter-roller** [Adyen/adyen-web#1524]
Currently using card events to get access to payment brand and last four card digits.  However, if the user switches from card to another payment method, I'm unsure what event to use to clear the card detail on my side.  This can be solved using onSelect, but this doesn't appear to be wired up for sessions.

Ideally onPaymentCompleted would provide some extra detail (payment brand, last 4 card digits) so this doesn't need to be handled manually.  I'm aware we can get this from the payment notification too, but if drop-in has access to this data already it would be nice to get it with the payment result.

**Comment by carter-roller** [comment]
The payment method Zip requires billing and delivery address.  Ideally drop-in would handle this, but if onSelect was working I could identify the payment method as Zip then use beforeSubmit to add an address to the data being resolved.  Can't see any other way with the session workflow to conditionally supply the billing/delivery address.

**Comment by carter-roller** [comment]
Looks like beforeSubmit data includes paymentMethod so I can use that to conditionally add add billing/delivery address.

**Comment by ribeiroguilherme** [comment]
Hi @carter-roller .

`onSelect` works for sessions. I tested on v5.11.0 and works as expected. Following code works:

```js
const dropin = checkout.create('dropin', {
    onSelect: component => {
        console.log(component.data);
    }
}).mount('#dropin-container');
```

You can get payment method data accessing `component.data` . The payment result that comes  from the API does not contain any data related to the payment method.

> Looks like beforeSubmit data includes paymentMethod so I can use that to conditionally add add billing/delivery address.


According to the docs, you should use `beforeSubmit` to add such data. Check this out here: https://docs.adyen.com/online-payments/web-components/optional-configuration#events

I hope this helps!

**Comment by carter-roller** [comment]
Thanks @ribeiroguilherme .  I confused the configuration - I was putting all the events in the checkout configuration but realised after I saw your example there's separate options/configuration that seem to be specific to the initialisation of drop-in.

Confirmed working 👍
