### ISSUE TITLE
openFirstPaymentMethod not working with v5 sessions

### ISSUE THREAD

**Issue by carter-roller** [Adyen/adyen-web#1531]
The property openFirstPaymentMethod is not working with v5 sessions.  This is working for us on the older version, non-session workflow.

Windows, Chrome.

**Comment by ribeiroguilherme** [comment]
Hi @carter-roller ,

I didn't manage to reproduce this on my side. I tried with v5.11.0 and it seems to be working as expected. How are you setting the property?

For instance, I tried the following:

```js
const dropin = checkout.create('dropin', {
    openFirstPaymentMethod: false,
    openFirstStoredPaymentMethod: false
}).mount('#dropin-container');
```

**Comment by carter-roller** [comment]
Thanks @ribeiroguilherme .  I did not realise there was separate options as per your example, I was putting all the configuration in `await AdyenCheckout(configuration)`.

Confirmed working 👍

**Comment by carter-roller** [comment]
Thanks @ribeiroguilherme .  I did not realise there was separate options as per your example, I was putting all the configuration in `await AdyenCheckout(configuration)`.

Confirmed working 👍
