### ISSUE TITLE
Build issues from 5.6.2 onwards

### ISSUE THREAD

**Issue by foscjos2** [Adyen/adyen-web#1553]
**Describe the bug**
After installing the latest version using (5.12.0 at time of writing) via 'npm i @adyen/adyen-web' I am getting build errors when running npm run build. The build errors stem from the typescript files included in the adyen-web npm packages. 

Build errors I am seeing are as follows. I am seeing these on every version from 5.6.2 onward: 
`ERROR in C:/.../node_modules/@adyen/adyen-web/dist/types/components/UIElement.d.ts
ERROR in C:/.../node_modules/@adyen/adyen-web/dist/types/components/UIElement.d.ts(6,13):
TS1005: '=' expected.

ERROR in C:/.../node_modules/@adyen/adyen-web/dist/types/components/UIElement.d.ts
ERROR in C:/.../node_modules/@adyen/adyen-web/dist/types/components/UIElement.d.ts(6,38):
TS1005: ';' expected.`

**To Reproduce**
1. Run 'npm i @adyen/adyen-web' to get the latest version. I was getting 5.12.0 at time of writing. 
2. Run 'npm run build'
3. You should see the above build errors. 

**Expected behavior**
These typescript build errors should not be present. 

**Screenshots**
Not applicable. Can provide if requested. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser NA

 **Environment:**
- Typescript version: 3.7.1-rc

**Comment by foscjos2** [comment]
Currently I'm running 5.6.1 to resolve this issue but I'd love to be able to stay on the latest release.

**Comment by ribeiroguilherme** [comment]
Hey @foscjos2 ,

Thanks for reaching out. Is there a chance for you to upgrade the Typescript to 3.8.0? I can't test locally but I suppose that it is because the `UIElement.d.ts` is using `import type` , which is available on 3.8.0 onwards.

**Comment by foscjos2** [comment]
@ribeiroguilherme  that does seem to be the issue. I will look into upgrading our typescript to allow us to get on more recent versions of this project. Thank you.
