### ISSUE TITLE
Amazon Pay should not be shown for unsupported currencies

### ISSUE THREAD

**Issue by ahimik** [Adyen/adyen-web#1563]
**Describe the bug**
`Amazon Pay` payment method is shown for a non-supported currency.

**To Reproduce**
1. Configure and integrate with Amazon Pay payment method.
2. Configure Drop-in object and pass an amount object with a non-supported currency:
```
amount: {
    currency: 'PLN'
    value: 3800,
}
```
3. Create and mount Drop-In instance.
4. Observe Amazon Pay payment method is shown in the list of available payment methods.
5. Observe an unexpected error occurs when clicking on Amazon Pay payment button.

**Expected behavior**
Amazon Pay payment method should not be shown by Drop-in since `PLN` is not supported currency by Amazon Pay. Here is the list of supported currencies: https://amazonpaylegacyintegrationguide.s3.amazonaws.com/docs/eu/amazon-pay-onetime/supported-currencies.html

**Screenshots**
![1](https://user-images.githubusercontent.com/30721033/161903454-9400351f-253d-42be-89ac-a55db1c2c4ee.JPG)
![2](https://user-images.githubusercontent.com/30721033/161903469-e7f3317d-d6ff-4d1b-b6b0-6e470f43ca1a.JPG)

**Comment by m1aw** [comment]
Hey Alex,

Let me check this internally, is not something that is directly related to adyen-web, but I will check and give you an update on this.

**Comment by m1aw** [comment]
This configuration should be part of the payment method configuration attached to your merchant account please [contact our support team](https://www.adyen.help/) to solve this issue.

I'll close this issue since the library is working as expected. Thanks again!
