### ISSUE TITLE
Add `onAuthorizedBeforeSubmit` for ApplePay

### ISSUE THREAD

**Issue by aralroca** [Adyen/adyen-web#1579]
**Is your feature request related to a problem? Please describe.**
Having access to the apple pay event before submitting is important. Adding an event that is`onAuthorizedBeforeSubmit` would help solve this so you don't have to implement it with apple pay without Adyen.

**Describe the solution you'd like**
Add `onAuthorizedBeforeSubmit` event and execute here:

```diff
onPaymentAuthorized: (resolve, reject, event) => {
    if (!!event.payment.token && !!event.payment.token.paymentData) {
        this.setState({ applePayToken: btoa(JSON.stringify(event.payment.token.paymentData)) });
    }

+   if(onAuthorizedBeforeSubmit) {
+      await new Promise((resolve) => onAuthorizedBeforeSubmit(resolve, reject, event));
+  }
    super.submit();
    onPaymentAuthorized(resolve, reject, event);
}

**Describe alternatives you've considered**
Adding the apple pay `event` to the `beforeSubmit` event.

**Comment by m1aw** [comment]
Hey Aral, what is the use case?

**Comment by aralroca** [comment]
we would like to create an express flow with Apple Pay that just pressing the "Pay with Apple Pay" button will work even if users are not logged in or not registered. **We would like to create the order in our system before the payment is authoritzed in Adyen and to be able to create the order, we need the shipping address**. We do not want an authorized payment that is not yet associated with any order / user in our system.

**Comment by ribeiroguilherme** [comment]
Hi @aralroca . Thanks for reaching out and proposing the current solution 🙌 

We are already discussing internally how to improve ApplePay and other payment methods in order to make them work better for your scenario. There is already a task in our backlog to improve the ApplePay and return the shipping address - we haven't started it yet though.

As a quick workaround for now, I suggest you to use the `onAuthorized` callback to do the submit part: you can get the details from the `event` object, create the order on your end, and then do what you would do within the `onSubmit` block.  

In this way, you would not use the `onSubmit` callback. It will be triggered, but you can ignore it and do the whole flow within the `onAuthorized`. Let me know if that works.

**Comment by aralroca** [comment]
Hi @ribeiroguilherme. Thanks for your proposal as a temporal workaround meanwhile this process is not managed in a better way. 

Unfortunately, I get "Payment not completed" in the Apple popup, this error is hard to catch:

- `onError` is not executed
- `onPaymentCompleted` is not executed
- Any error in the console or network

```js
const appleConfig = {
  ...restOfConfig,
  // void onSubmit
  onSubmit: () => {},
  // onAuthorized calling own submit endpoint
  onAuthorized: async (resolve, reject, event) => {
    // ... here the rest of code to save the user, etc
    const { status, data } = await submit({
      token: cart.token,
      paymentId,
      applePayToken: JSON.stringify(event.payment.token.paymentData),
     // Other fields are fulfilled by our endpoint
    })
    console.log(status) // => 200
    console.log(data) // => { "result": "Authorised" }
    if (status === 200 && data.result === 'Authorised') resolve()
    else resolve()
  },
}
```

Do you have any idea about what causes this issue and how to solve it? Looks that after the `resolve` is not detecting that the `submit` was done... Or is it something I miss doing? 

Thank you

**Comment by ribeiroguilherme** [comment]
Hi @aralroca ,

By checking the code, it seems to me that it should work as expected when you call the `resolve()` method.  Resolving the promise should trigger the [completePayment](https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/components/ApplePay/ApplePayService.ts#L70) and then you would get the successful message.

Do you have any other findings on your side? Did you manage to get any error on the console or network tab?

**Comment by ribeiroguilherme** [comment]
Glad to hear it worked. Cheers! 👌
