### ISSUE TITLE
Typescript error occurs on compile in v.3.11.1

### ISSUE THREAD

**Issue by arnibarnason** [Adyen/adyen-web#158]
**Describe the bug**
I'm getting a typescript error from the latest version of the library (3.11.1). When running tsc I get the following error
```
$ tsc --noEmit
node_modules/@adyen/adyen-web/dist/src/components/helpers/IssuerListContainer.d.ts:25:53 - error TS2559: Type 'IssuerListProps' has no properties in common with type 'UIElementProps'.

25 declare class IssuerListContainer extends UIElement<IssuerListProps> {
                                                       ~~~~~~~~~~~~~~~
```

**To Reproduce**
1. Install the package
2. Compile your code with the typescript compiler (tsc)

**Additional context**
The typescript build was fixed in [3.11.0](#121) but this issue seems to have been introduced in [3.11.1](#154)

**Comment by pabloai** [comment]
Hi @arnibarnason,

This was fixed and release in v3.11.2
Thanks again for reaching!
