### ISSUE TITLE
Ability to use updateStyles on individual Field using checkout.create('securedfields, ...)

### ISSUE THREAD

**Issue by Seif-apprentus** [Adyen/adyen-web#1594]
Hello,
Is there any possibility to use updateStyles with just one field instead of all input fields in the same time?

**Comment by ribeiroguilherme** [comment]
Hi @Seif-apprentus ,

It is not possible to apply for only one field. `updateStyles` apply for all fields. What is your use case?

**Comment by ribeiroguilherme** [comment]
Closing this issue due to its inactivity.
