### ISSUE TITLE
Klarna visible for amount lower than allowed (AUD36)

### ISSUE THREAD

**Issue by milindsingh** [Adyen/adyen-web#1600]
**Describe the bug**
The Klarna client library officially hides when amount in lower than allowed  but adyen components doenst have same behaviour.

**To Reproduce**
1. Render with amount lower than allowed. (AUD 36)

**Expected behavior**
Pay with Klarna should not be visible.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version latest

**Smartphone (please complete the following information):**
 Same

**Additional context**
Component Version: 4.9

**Comment by ribeiroguilherme** [comment]
Hi @milindsingh .  Does this issue still relevant? Are you using 4.9 still?

**Comment by ribeiroguilherme** [comment]
Closing it as it is stale. Feel free to reach out if the issue persists.
