### ISSUE TITLE
Add dev containers configuration to the project

### ISSUE THREAD

**Issue by axmz** [Adyen/adyen-web#1605]
To be able to use the project you need to have yarn and node > v12
It is possible to use nvm locally to use a different node version or install yarn separately, but as an alternative one could use [dev containers](https://code.visualstudio.com/docs/remote/containers).
Dev container would allow a dev to run the project in an isolated environment without the need to install specific node version or yarn.
Although this option would be available for vscode users (i don't know how to run the container outside the vscode)

**Comment by ribeiroguilherme** [comment]
Hi @axmz , thanks for reaching out!

There is no interest from our side to move forward with this as enhancement for now. We have other items on our backlog which are higher priority, and we won't have time any time soon to investigate/work on this. But regardless of that, thanks for sharing your idea.

Cheers!
