### ISSUE TITLE
Timeout in 3dSecure for dropin.handleAction(response.action);

### ISSUE THREAD

**Issue by loclahost** [Adyen/adyen-web#1607]
**Describe the bug**
The web drop in gets a timeout waiting for 3dsecure in test. It also seems to not care about the timeout if the error is unhandled. I am running 5.15.0 dropin  on a pre 5.0.0 integration.

This is the observed path:
2022-05-24T06:37:30.231Z :: Fetching payment methods 
2022-05-24T06:37:33.760Z :: Initializing the dropin
2022-05-24T06:37:54.988Z :: onSubmit: Submitting credit card data
2022-05-24T06:37:59.508Z :: onSubmit: Submitting credit card data - 3Dsecure action required 
2022-05-24T06:38:09.538Z :: onError:  { errorCode: "timeout", message: "ThreeDS2 timed out" }

If dropin.setStatus('error') is used here this onError is the final state, but if you do not set the status but waits instead you get presented with a 3dsecure input which can be submitted. If you wait another ten minutes the flow continues:

2022-05-24T06:48:09.799Z :: onAdditionalDetails: Submitting additional details
2022-05-24T06:48:12.708Z :: onAdditionalDetails: Submitting additional details - Status received is final
2022-05-24T06:48:13.108Z :: onAdditionalDetails: Submitting additional details - Status is success, fetching redirect url

**Expected behavior**
1. 3dsecure should not timeout
2. It is a bit strange that the flow continues even after the onError handler has been called
3. Why does it take ten minutes to verify the 3dsecure input?

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 102

**Additional context**
Initialization script
````
		debugLog("Fetching payment methods");
		getPaymentMethods()
			.then(paymentMethods => {
				debugLog(paymentMethods);
				const adyenDropInConfig = {
					locale: 'sv-SE',
					environment: 'test',
					clientKey: 'MY_KEY',
					paymentMethodsResponse: paymentMethods,
					amount: { value: javascriptContext.currentOrderValueInSEK, currency: 'SEK' },
					onSubmit: (state, dropin) => {
						debugLog("onSubmit: Submitting credit card data");
						makePayment(state.data)
							.then(response => {
								if (response.action) {
									debugLog("onSubmit: Submitting credit card data - 3Dsecure action required: %o", response);
									dropin.handleAction(response.action);
								} else {
									showFinalResult(response);
								}
							})
							.catch(error => {
								debugLog("An error occurred while creating a payment or while the dropin was setting up 3ds: %o", error);
								throw Error(error);
							});
					},
					onAdditionalDetails: (state, dropin) => {
						debugLog("onAdditionalDetails: Submitting additional details");
						submitDetails(state.data)
							.then(response => {
								if (response.action) {
									debugLog("onAdditionalDetails: Submitting additional details - Action required on the additional details: %o", response);
									dropin.handleAction(response.action);
								} else {
									showFinalResult(response);
								}
							})
							.catch(error => {
								debugLog("An error occurred while submitting additional details or while the dropin was handling extra actions: %o", error);
								throw Error(error);
							});
					},
					onError:(error) => {
						debugLog("onError: An error occurred somewhere in the dropin: %o", error);

						dropIn.setStatus('error', {message: error.message});
					},
					paymentMethodsConfiguration: {
						card: {
							hasHolderName: true,
							holderNameRequired: true,
							enableStoreDetails: false,
							hideCVC: false,
							name: 'Credit or debit card'
						}
					}
				};
				debugLog("Initializing the dropin");
				let dropIn;
				AdyenCheckout(adyenDropInConfig)
					.then(checkout => {
						dropIn = checkout.create('dropin').mount('#dropin')
					})
					.catch(error => debugLog("Initialization: Error while setting up the dropin: %o", error));
			})
			.catch(error => {;
				$('#dropin').append("<h1>" + error.message + "</h1>");
				debugLog("Error while fetching payment methods: %o", error);
			});
````

**Comment by loclahost** [comment]
The problem was a bad configuration on my side. Port number (I run a nonstandard port i test) was included in the Origin in the handleAction calls but not in my initial call to /payments. After making sure they match the problem has gone.

**Comment by fahu** [comment]
Thanks for pointing out @loclahost! We faced the same issue, very helpful that you provided the info on how to resolve it :)
