### ISSUE TITLE
Incorrect credit card number validation when copy/paste

### ISSUE THREAD

**Issue by jkubiszewski** [Adyen/adyen-web#1612]
**Describe the bug**
Incorrect credit card number validation when copy/paste

**To Reproduce**
1. Go to [MyStore](https://www.mystoredemo.io/)
2. Select 'Credit Card' as payment method
3. Paste the number of the unsupported card in the 'Card number' field, e.g. `4013 2500 0000 0000 006`
4. Click on Pay
5. Paste the number of valid card in the 'Card number' field, e.g. `5212 3456 7890 1234`
7. The field validation does not refresh, even though the brand itself was correctly recognized

**Expected behavior**
In the above case, the validation should be refreshed and allow the payment to continue.

**Screenshots**
<img width="404" alt="image" src="https://user-images.githubusercontent.com/5447242/171189813-7e06295d-4a90-4912-8a4e-31810d7eaa75.png">
<img width="407" alt="image" src="https://user-images.githubusercontent.com/5447242/171189846-724df13c-b5bb-43d2-a6e5-9e82dab26109.png">

**Additional context**
It seems that calling the `showValidation()` function causes some kind of state problem, because without calling it everything works fine

**Comment by sponglord** [comment]
Hi @jkubiszewski 
It does indeed seem that it's the pressing of the Pay button between the 2 paste actions that causes the problem.
This is a good find, thanks for pointing this out. We'll look into it

**Comment by sponglord** [comment]
This issue has been addressed and the fix will be available in the next release
