### ISSUE TITLE
CVC field doesn't honour Payment Methods (When AMEX isn't an option)

### ISSUE THREAD

**Issue by tsun-work** [Adyen/adyen-web#1634]
**Describe the bug**
When you only pass through VISA and MC as the payment method options (AdyenCheckout) to Adyen to create the checkout form card, you can still enter a 4 digit CVC code even though the placeholder mentions '3 digits' 

**To Reproduce**
1. Create a form from the web Web Drop-in integration guide
2. For `paymentMethodsConfiguration` pass in VISA and MC as the two payment options
3. Once form initialises, scroll to the CVC field and the place holder should say `3 digits`
4. If you try typing in `1234` into the CVC field it allows 4 characters (Currently if you inspect the maxchars attribute, it has 4 too)
5. If you type in `4111` into the card number field, it will register as a VISA and then update the CVC to have 3 max chars
6. If you type in `3700` into the card number field, it will show invalid card number but then allow 4 numbers in the CVC field number again

**Expected behavior**
1. CVC should not allow 4 digits when AMEX is not a supported option (Assuming VISA and MC only allow 3 CVC digits)
2. The placeholder should correctly reflect the maxchars

**Screenshots**
![image](https://user-images.githubusercontent.com/107836757/174547233-49509ced-1a2c-4669-82b7-5839bf0f69ae.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version 5.16.2 Adyen

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All

**Additional context**

**Comment by sponglord** [comment]
Hi @tsun-work, thanks for making us aware of this issue. 
It's been fixed and will be available in an upcoming release (watch the release notes!)
