### ISSUE TITLE
include LICENSE file in published package

### ISSUE THREAD

**Issue by lutzk** [Adyen/adyen-web#1636]
**Is your feature request related to a problem? Please describe.**
when building a webapp we are required to provide a list of software license used in the application
normally packages include their license so it can be displayed for legal disclaimer

**Describe the solution you'd like**
please include the `LICENSE` file in the published npm package

**Comment by marcperez** [comment]
Hi @lutzk,

Thanks for your feedback! This has been fixed in #1657 and released on `v5.19.0`.

**Comment by lutzk** [comment]
great!
thanks!
