### ISSUE TITLE
Improve Documentation (Especially for "Important" Features/Aspects)

### ISSUE THREAD

**Issue by chrisidakwo** [Adyen/adyen-web#1637]
**Is your feature request related to a problem? Please describe.**
This is not a feature request. But more of a suggestion or say, enhancement in respect to your documentation. Not sure if that's open-sourced too. At the moment, there are quite a number of things not clearly stated or "exampled" in your documentation hence Devs spend a lot of time figuring out how certain things work. For example, event hooks. I'd consider that to be an important part of this project yet no real/clear/substantive examples of how they work and can be used. For further example, we've tried a number of combinations and scenarios to see when the  `onError` hook is triggered, but still can't get it to work. No examples of it on your documentation. This is just one of many "trial and error before we figure out" situations on where and how certain things are supposed to be and work. Shouldn't be that difficult if properly documented.

**Describe the solution you'd like**
Improve the documentation, I guess. Wouldn't mind contributing towards this if it's open source. I think all "important" features/aspects should be broadly covered in the documentation. Saves a lot of dev time, reduces integration time. One less unhappy Dev is always a good thing.

**Comment by ribeiroguilherme** [comment]
Hi @chrisidakwo ,

The documentation project isn't open source, but it is very important for us to hear feedback about it - thanks for sharing your thoughts! I forwarded your suggestion internally and we will take a look into that. 🙌 

I will close this issue as it isn't related to the SDK itself, but feel free to reach out to us if you face any issue or have other thoughts. Cheers!
