### ISSUE TITLE
Dankort, Diners, UATP and Visa Electron should not be allowed when VISA and MC as the only payment methods

### ISSUE THREAD

**Issue by mrfoofu** [Adyen/adyen-web#1654]
**Is your feature request related to a problem? Please describe.**
When using https://docs.adyen.com/online-payments/web-drop-in/customization and you specific only VISA and MC in the payment Methods in the configs, only Visa and Mastercard should be accepted, but these card brands are being accepted too:

Dankort
Diners
UATP
Visa Electron 

This is expected behaviour but would expect the above credit cards to not be part of the accepted cards. Unsure if this is related https://github.com/Adyen/adyen-web/issues/1018 but as a user of the payment app, this shouldn't be allowed if payment methods are restricted to only VISA or MC unless otherwise stated.

**Describe the solution you'd like**
If VISA and MC are the only available payment options, Dankort, Diners, UATP, Visa Electron should not be accepted or at least allowed to be entered into the Account Number field. i.e. a validation error should appear.

**Describe alternatives you've considered**
Client side validation to override but this may break future upgrades and any modifications to the codebase will be avoided.

**Additional context**
N/A - Have had a quick chat to Jason and have been advised to raise here to see if this is a feature request which can be considered. Please reach out if you need any more information but we are currently using this in a large payment application.

Thanks!
Tony :)

**Comment by sponglord** [comment]
Hi @mrfoofu 

Thanks for raising this issue.

We are looking into the issues with the `allowedPaymentMethods` prop for the `/paymentMethods` request.
As you know such brands exist in hierarchies (e.g. Visa Electron is a child of Visa) and currently the `allowedPaymentMethods` seems to deliver the entire hierarchy.

However using this property is _not_ the best way to limit the brands that a card component will accept.

You should be setting the `brands` property (https://docs.adyen.com/payment-methods/cards/web-drop-in#optional-configuration).
For the Dropin this is done via the `paymentMethodConfiguration` object set in the top level AdyenCheckout configuration: https://docs.adyen.com/payment-methods/cards/web-drop-in#include-optional-configuration

So it would look something like this:
```
const configuration = {
  environment: 'test', 
  clientKey: 'test_870be2...'
  ...
  paymentMethodsConfiguration: {
    card: {
      brands: ['mc', 'visa']
    }
  }
}
...
const checkout = await AdyenCheckout(configuration);
```

I hope this is useful to you

**Comment by ribeiroguilherme** [comment]
Hi @mrfoofu ,

As mentioned above, you can explicitly configure the supported brands in the `paymentMethodsConfiguration` and that should do the trick. Feel free to reach out if there are any other issues. Cheers!
