### ISSUE TITLE
Adyen bundle size is so big

### ISSUE THREAD

**Issue by aralroca** [Adyen/adyen-web#1655]
E-commerce has to go fast, Adyen slows us down, it is currently the largest piece of JavaScript in our project, would it be possible to dedicate to reduce this size? Thank you.

![image](https://user-images.githubusercontent.com/13313058/178467007-4992c2a3-8cdd-4273-bb18-8f50a23036b1.png)

**Comment by m1aw** [comment]
There is already an issue open for questions and reports related to bundle size. #337
