### ISSUE TITLE
Error in onSubmit keeps PayPal window open indefinitely

### ISSUE THREAD

**Issue by mwalercz** [Adyen/adyen-web#1662]
**Describe the bug**
We are using Adyen Web Drop-in (@adyen/adyen-web v3.21.1) with PayPal payment method. 
When user clicks PayPal button inside Adyen Web Drop-in, our code throws an error in `dropin.onSubmit` (eg. due to failed API call to the backend). `dropin.onError` handler is not invoked and PayPal window is kept open indefinitely. PayPal button does not react to clicks.
For other payment methods, like cards, `dropin.onError` is invoked and calling `dropin.setStatus('ready')` allows buyer to click buy button again.

How can we restart PayPal experience without reloading the whole page?

**Dropin configuration**
```
  configuration = {
    ...
    onSubmit: async function(state, dropin) {
      dropin.setStatus('loading');
      await new Promise(r => setTimeout(r, 2000));
      throw new Error('request error');
    },
    onError: function() {
      console.log('dropin.onError');
      dropin.setStatus('ready');
    },
  };
  const checkout = new AdyenCheckout(configuration);
  const dropin = checkout.create('dropin');
  dropin.mount(el);
```

**Screenshots**
![image](https://user-images.githubusercontent.com/15079480/180820862-0b27ac9b-da2b-4cdd-bd65-e533df8e5388.png)

**Comment by ribeiroguilherme** [comment]
Hey @mwalercz ,

Thanks for reaching out. In this version that you are using, it doesn't have a method which can close the pop-up for you directly.

I suggest you upgrading the SDK to the newest version, which makes it possible to close the pop-up by interacting with the component returned in the 'onSubmit' callback: `component.handleReject('my error message')`. 

In this way, the pop-up is closed, and the `onError` is triggered.

I hope it helps!

**Comment by mwalercz** [comment]
Yes, thank you.
