### ISSUE TITLE
[AdobeCommerce][CC] Fields cleared on submit payment

### ISSUE THREAD

**Issue by marc-arnoult** [Adyen/adyen-web#1673]
**Describe the bug**
On the checkout of the Adyen integration for AdobeCommerce.

When a user try to submit a CC payment on the first try, all the fields are cleared and it display an error on each one.

On the second try, everything seem to work properly.

**To Reproduce**
- Go to the checkout payment step, fill one or multiple the credit card fields.
- Submit.

**Expected behavior**
I should be able to pay at the first try.

**Screenshots**
First step : 
![Capture d’écran 2022-08-03 à 17 00 49](https://user-images.githubusercontent.com/16859411/182641545-041aff56-0cf3-45a3-bf67-976ee1e03ba7.png)
Second step: 
![Capture d’écran 2022-08-03 à 17 00 52](https://user-images.githubusercontent.com/16859411/182641579-46ab46c3-9adf-4330-b4c8-39110ed53197.png)

**Desktop (please complete the following information):**
 - OS: OS X Catalina
 - Browser: Chrome
 - Version: 103

**Additional context**
The strange thing is, i can see 2 Iframes for each fields.
![Capture d’écran 2022-08-03 à 17 14 26](https://user-images.githubusercontent.com/16859411/182644462-ede03c34-ad21-4fc3-918f-5e13454c1c4e.png)
The first one is correct, the second one is not.

**AdobeCommerce Adyen module version :  8.2.2**

**Comment by jonathanribas** [comment]
We have this issue on a big international store in PRODUCTION.

**Comment by marc-arnoult** [comment]
![Capture d’écran 2022-08-03 à 17 56 56](https://user-images.githubusercontent.com/16859411/182654879-3ad9164d-54e3-470d-a78f-9ccb8e3d880c.png)
FI, the first Iframe is good `js-iframe` that we can find here https://github.com/Adyen/adyen-web/blob/23ac5283e15b7421610a9e6af6efe4386bca220f/packages/lib/src/components/internal/SecuredFields/lib/securedField/utils/createIframe.ts#L9
I don't know where the second one is coming from `js_frame_ccnumber`
