### ISSUE TITLE
Please add back the refusalReason to onPaymentCompleted so that we can optimize UX 

### ISSUE THREAD

**Issue by danyj** [Adyen/adyen-web#1677]
We are working on the drop-in implementation and are in need to display specific messages based on the refusalReasons in order to optimize the UX and have the user understand the refusal. 

These 3 in particular 

- Expired Card 
- Invalid Card Number 
- Restricted Card

Currently we cannot optimize the messages because the resultCode's are Refused, Error, or Cancelled.
At this moment users are left guessing as to why the payment is refused where a simple message could help them continue the payment flow ( grab a different card ). This issue will result in unnecessary customer service requests that can be solved by simple messaging. 

Is there any other hook that we can use to optimize the refusal messages?

**Comment by marcperez** [comment]
Hi @danyj,

Thanks for reaching out and for your feedback.

Unfortunately this is not something we can freely share with the client side libraries for security reasons. We also do not recommend disclosing this level of detail after a failed payment attempt, and usually opt for a more generic error message (e.g. asking the shopper to try a different form of payment).

These links can provide a bit more context:

- https://docs.adyen.com/online-payments/payment-result-codes
- https://docs.adyen.com/development-resources/refusal-reasons

An alternative, and if absolutely necessary, could be to use the [Advanced flow](https://docs.adyen.com/online-payments/web-drop-in/advanced-use-cases/update-payment-amount), where you will receive this information on your server.

Please reach out to our support team if you have any further questions on this. Hope this helps!
