### ISSUE TITLE
3DS2 Simulator buttons barely visible under iOS mobile devices

### ISSUE THREAD

**Issue by kdimitrovosf** [Adyen/adyen-web#1694]
**Describe the bug**
We noticed that the buttons in 3DS2 Simulator page under iOS mobile devices are not visible. There is a scroll usually which we are not able to see under iOS mobile devices.

**To Reproduce**
1. Go to an Adyen test environment payment page
2. Select 'Credit Card' with 3DS (for example **3714 4963 5398 431**, Expiry Date: **03/30**, CVC: **7373**)
3. Fill in all the details fields with valid information
4. Click on the 'Continue' CTA

**Expected behavior**
Both buttons should be fully visible or able to scroll to.

**Screenshots**
Safari:
<img width="200" alt="3ds-simulator-mobile" src="https://user-images.githubusercontent.com/76946766/185075260-1124c99e-bf79-49f7-9c83-c4ea17c422fa.png">

Chrome:
<img width="200" alt="3ds-simulator-mobile" src="https://user-images.githubusercontent.com/76946766/185082287-acefd5b8-f98d-482a-821a-8e34d0768e04.jpg" />

**Desktop:**
Not reproducible

**Smartphone:**
 - Device: iPhone 13 Pro
 - OS: 15.6
 - Browser: Safari and Chrome
 - Version: v15.6 and v104.0.5112.99

**Comment by ribeiroguilherme** [comment]
Hi @kdimitrovosf ,

Thanks for reaching out. What version of the SDK are you on?

**Comment by ribeiroguilherme** [comment]
Hi guys. 
Please raise this issue on the [sales force project](https://github.com/Adyen/adyen-salesforce-commerce-cloud/) if it still relevant. Cheers
