### ISSUE TITLE
[5.22.0] Invalid import in index.d.ts 

### ISSUE THREAD

**Issue by mvannes** [Adyen/adyen-web#1697]
**Describe the bug**
Introduced in https://github.com/Adyen/adyen-web/commit/c5ecf2d10c4f282d071c0df2849abd8d2e624cd3 it seems like the import is wrong here. 
It says to import from `src/` , but looking at the index.d.ts location, `src` is not an actual location once build.
Instead, it should probably import like the Checkout does, so `./core/types/` .

This is making some typescript builds with the latest version of this package invalid.

**To Reproduce**
Update to 5.22.0 version of `@adyen/adyen-web`  and try to build with the AdyenCheckout imported into a project.

**Expected behavior**
It shouldn't error on resolving the adyen-web's internal imports.

**Comment by ribeiroguilherme** [comment]
Hi @mvannes ,

Good catch! Thanks for the heads up and for the PR. We merged it into master and the fix is going to be available on our next release that should take place earlier next week. 👌  I will close this issue once we release it.

**Comment by mvannes** [comment]
Thanks! Looking forward to it!

**Comment by ribeiroguilherme** [comment]
Good news @mvannes - the version 5.23.0 is available with the fix 😄  Thanks for the reaching out and for the fix. Cheers!
