### ISSUE TITLE
[5.20+] securedFields.html - TypeError: o.subtle is undefined prevents web drop-in display

### ISSUE THREAD

**Issue by enwin** [Adyen/adyen-web#1710]
**Describe the bug**
Since v5.20.0, running the web drop-in component on a non http localhost domains throw an error and prevent the component to be displayed

**To Reproduce**
1. Create a http local domain like http://test.adyen.local
2. Add the domain to the allowed origins for the test client key in adyen admin
3. Instantiate the component in a page a load it on the local domain
4. See the error in the console and the spinner keep spinning

**Expected behavior**
The web drop-in component should be displayed on non-localhost http domain like said in the [documentation](https://docs.adyen.com/development-resources/client-side-authentication#allowed-origins)

**Screenshots**
Firefox:
![image](https://user-images.githubusercontent.com/1038339/186120698-b7f66376-5d81-4946-8c29-d84fbd185881.png)
Chrome:
![image](https://user-images.githubusercontent.com/1038339/186120831-3ed486e0-ada7-4e34-a80d-969b0c57662b.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Browser Firefox, Chrome
 - Version 103, 104

**Additional context**
- Running the same domain with https after adding the https version in the allowed origins works but its not possible for us unfortunately
- Running the same code on http://localhost works
- Reverting the web drop-in component to v5.19 fixes the issue

**Comment by sponglord** [comment]
Hi @enwin 

This is happening because, in `v5.20.0` we changed the way we encrypt our fields. We have starting using JSON Web Encryption (JWE).

This relies, internally, on `window.crypto`; and more relevant in this case `window.crypto.subtle` (https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle)

As you can see from the above link, this feature is marked as "Secure context required".

From MDN's docs on [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts):
> Locally-delivered resources such as those with http://127.0.0.1 URLs, http://localhost and http://*.localhost URLs (e.g. http://dev.whatever.localhost/), and file:// URLs are also considered to have been delivered securely.

In essence, without the `localhost` an http domain is not considered secure and therefore `window.crypto.subtle` fails.

I wonder, what is your use case for using a custom http domain in your development rather than `http://localhost`?

**Comment by enwin** [comment]
Hi @sponglord 

Thank you for your feedback. I was thinking it was something like insecure context but I couldn't find the culprit.

In our specific case the website we're working on is handling multiple languages based on the domain (.fr, .de, .se and more) instead of using a prefix in the path. We have a fallback locale when no matching domain is found so we can use localhost a bit but when it comes to work with other locales then we'll have to change the code to specifically load the desired locale.

I'll check if we can use a trick like having `http://website.fr.localhost`.

**Comment by alepore** [comment]
@sponglord i also had this problem and it was very hard to debug. 
If the SDK could show an useful message it would be extremely useful I think...

**Comment by sponglord** [comment]
@alepore - we aim to add a console.warning to a future version for when we detect a custom http domain is in use

**Comment by timma-haro** [comment]
Ran into the same issue with code working correctly in `localhost` but erroring in our preview environment even though the preview env url was added to allowed origins.

If `http` is supported in test environment only for `localhost` would be best if it would mentioned in [client-side authentication docs](https://docs.adyen.com/development-resources/client-side-authentication/#allowed-origins). Right now it states that `http` is always supported in test env.
