### ISSUE TITLE
Delay/force focus on card number when using adyen web drop-in 

### ISSUE THREAD

**Issue by ehsantl** [Adyen/adyen-web#1718]
**Describe the bug**
When user tries to copy/paste a card number and proceed to complete the next fields (exp date / cvc) the iframe force the focus back to the card number, causing confusing UX. 

**To Reproduce**
1. Go to https://mystoredemo.io/ and add a sample product to your cart
2. Click on Cart icon 
3. Click on Continue to checkout
4. Have test card copy in clipboard: 4111 1111 4555 1142
5. Select Credit card as pay with option
6. Paste the card number in card Number field
7. Press Tab to continue to next field
8. Enter a valid date / cvc
9. See the focus get lost and it goes back to Card number which is already filled 

**Expected behavior**
Expected behavior is to NOT auto focus the user to Card Number if it is already filled 

**Screenshots**
Recording of the issue in action:

https://user-images.githubusercontent.com/1445573/188035456-d610a38b-8818-46f8-853f-5679c2514176.mov

**Desktop (please complete the following information):**
 - OS: All
 - Browser: Chrome
 - Version: 104

**Comment by sponglord** [comment]
Hi @ehsantl - I cannot recreate.
what action are you performing after you type the "3" into the CVC field? Clicking somewhere? Pressing Tab?

**Comment by ehsantl** [comment]
> Hi @ehsantl - I cannot recreate.
> what action are you performing after you type the "3" into the CVC field? Clicking somewhere? Pressing Tab?

Nothing. Trying to type the next digit but the focus gets changed to card number by the iframe unexpectedly.

**Comment by ehsantl** [comment]
To clarify @sponglord 's comment:

Steps to replicate the issue

1. Go to https://www.mystoredemo.io/#/ and add a sample product to your cart
2. Click on Cart icon
3. Click on Continue to checkout
4. Have test card copy in clipboard: 4111 1111 4555 1142
5. Select Credit card as pay with option
6. Paste the card number in card Number field
7. Press Tab to continue to next field
8. Enter a valid date
9. Enter a CVC 
10. ISSUE: Focus get lost and it goes back to Card number which is already filled - (in the video attached, after entering 3)

**Comment by sponglord** [comment]
Hi @ehsantl - we have been able to reproduce this.
It depends on 3 conditions:
- pasting a card number
- a slow internet connection
- the BIN of the  pasted card _not_ being in our databases (which can only happen on our Test servers)

In this scenario the shopper has moved focus to another input, _before_ our `/binLookup` endpoint has been able to respond. Then, when the `/binLookup` response reports that we don't recognise the BIN, we "reset" the card number UI (which places focus back onto the card number input)

The last condition (BIN of the  pasted card not being in our databases) is not a _real world_ one, our Live BIN databases are fully populated - so this issue will not arise in a Live/Production
