### ISSUE TITLE
Missing translation for QR Component

### ISSUE THREAD

**Issue by markusahlstrand** [Adyen/adyen-web#1769]
**Describe the bug**
The QR Component uses the i18n key `or` which is missing at least from the Swedish locale file.

**Expected behavior**
When using a swedish browser the to `or` should be translated to `eller`

**Screenshots**
<img width="441" alt="Skärmavbild 2022-09-27 kl  17 14 34" src="https://user-images.githubusercontent.com/89469/192770485-f9d57e00-486c-4ce8-b9cb-685351bd2d02.png">

**Additional context**
This is where the i18n tag is used:
https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/components/internal/QRLoader/QRLoader.tsx#L228

This is the locale file for swedish:
https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/language/locales/sv-SE.json

**Comment by ribeiroguilherme** [comment]
Thanks for reaching out @markusahlstrand . I created an PR fixing this issue, and we expect it to be released early next week. I will close this github issue once the fix is live. Cheers.

**Comment by ribeiroguilherme** [comment]
The fix is live, therefore closing this issue. Thanks for reaching out!
