### ISSUE TITLE
KlarnaContainer enforces displayName onto payment button

### ISSUE THREAD

**Issue by Kasea** [Adyen/adyen-web#1773]
**Describe the bug**
The Klarna implementation enforces the usage of the display name in the payment button. See https://github.com/Adyen/adyen-web/blob/dcb9643cbf905917c946fc33c50012a1172912ca/packages/lib/src/components/Klarna/components/KlarnaContainer/KlarnaContainer.tsx#L35

**Expected behavior**
Would expect same behavior as other implementations, which means using `payButton`'s entire string as the naming. Alternatively would expect it use `continue` as to not enforce the name.

**Additional context**
Running the latest version, not sure what the procedure is when changing something like this. I would imagine at the very least it would be a minor update. If this would potentially cause issues for other customers, would it be possible to add an additional prop to remove the enforced name?

**Comment by ribeiroguilherme** [comment]
Thanks for reaching out @Kasea .

> Would expect same behavior as other implementations, which means using payButton's entire string as the naming. Alternatively would expect it use continue as to not enforce the name.

I am not sure that I fully understood the issue - what are the 'other implementations' that you mentioned above? 
We always display the label `Continue to` concatenated with the respective payment method name in the Pay button, for all payment methods.

**Comment by Kasea** [comment]
I was referring to `Card` (Visa / MC) in that statement, as it uses `payButton` text as opposed to the `Continue to`.

Should've been specific, thanks for the quick reply though @ribeiroguilherme !

**Comment by ribeiroguilherme** [comment]
No worries @Kasea . It is more clear now :) 

So, depending of the type of payment method, we use different labels for the pay button. 

Payment methods that have redirects for example we use the `Continue to ${displayname}` . The 'Card' for example we show the `Pay ${currency-symbol} ${amount}`label as likely there is no redirect and the payment will take place after clicking on Pay. 

The only way for now to customize the pay button labels is by [changing the translations](https://docs.adyen.com/online-payments/web-components/localization-components).  

There are no plans to introduce a new property to change the display label of the Pay button as you proposed -that isn't an easy task as the display name can be affected by different things like the amount, or by certain configurations passed to the payment method configuration. This would add a lot of complexity and would need to be adjusted on every payment method.

I hope it is clear!

**Comment by Kasea** [comment]
Yeah that makes sense, thanks for clearing it up. Ideally would like a way in the payment configuration to override which translation it uses for generating the text, but that sounds like it would be a different issue than what is opened here. But I will make due with what is available at this moment.

Thanks!
