### ISSUE TITLE
Drop-in not supported on older browsers

### ISSUE THREAD

**Issue by paralichko** [Adyen/adyen-web#1775]
Drop-in is not supported on browsers of older models of Samsung TV's ( like Tizen 2.3, 2.4 ) LG < WebOS 3.0, Playstation 4.

Also on Chrome ver 40, 45. On Chrome - the console error is:

RsaHashedImportParams: hash: Algorithm: Not an object.

Please resolve the issue ASAP

Regards

**Comment by sponglord** [comment]
Hi @paralichko - can you please tell us what version of Dropin you are using?

**Comment by paralichko** [comment]
Hello,

i have tried with 5.23 and now i am using 5.25.0 - with 5.23.0 it is not loading at all, with 5.25.0 the forms loads very slowly, but in all the fields - there is label - The iframe is not configured - see warnings in console. I am attaching screenshot.
![image](https://user-images.githubusercontent.com/10962896/193572306-809d5064-6868-4569-a2f0-560b94a4ac9d.png)

**Comment by paralichko** [comment]
Hello,

with 5.19.0 is almost OK. The payment passes - only the user is not redirected to the thanks page because of some errors:

![image](https://user-images.githubusercontent.com/10962896/193858811-cdd24e05-c445-4055-ae9d-76e512880f15.png)

**Comment by sponglord** [comment]
Hi, 
The issue there looks connected to something going on in your own `app.js` file. 
The `onPaymentCompleted` callback has been called so now it's your own code for this handler that is running.

I've just tested Dropin v5.26.0 on a Playstation 4 and it worked fine.

I can see that there is an issue with Chrome <= v53 (although I don't get the same error as you report) - this is something we _will_ be able to address, I've had it working down to version 45.

Likewise I've also been able to recreate the issue on a Samsung Smart TV and get it working with the same fix that works for Chrome versions 45 through to 53

**Comment by sponglord** [comment]
🤔 - my PS is on software vn 10.x, I wonder if that's the difference?

**Comment by m1aw** [comment]
I believe this issue has been fixed from versions [v5.28.0 onwards](https://github.com/Adyen/adyen-web/releases), could you test?

**Comment by sponglord** [comment]
`v5.28.0` allows you to specify `forceCompat: true` in the card component configuration.
This corrects the issue for out test Samsung Smart TV and Chrome < v53 & >= v45. 
It should also fix the issue for Playstation4 with system software vn <10; and for iOS 10.x

A future release will include a fix that resolves the issue for Samsung Smart TV and Chrome < v53 & >= v45 without the need to use the `forceCompat` option

**Comment by paralichko** [comment]
> I believe this issue has been fixed from versions [v5.28.0 onwards](https://github.com/Adyen/adyen-web/releases), could you test?

Hello,

i will. I am waiting "Embed script and stylesheet" version of 5.28 to be available here - https://docs.adyen.com/online-payments/release-notes?integration_type=web&tab=embed-script-and-stylesheet_2022-10-11-ulyg_2

Regards
Gabriel

**Comment by ribeiroguilherme** [comment]
Hi @paralichko . Did you have the chance to test 5.28? Did it fix your issue?

**Comment by paralichko** [comment]
Yes, it is solving the issue. Thanks.

**Comment by paralichko** [comment]
Hello,

something has been changed, because we have complains that the payment can not be done on Tizen 2.3 and Tizen 2.4. Also on LG WebOS < 3.0. When You try to pay, and fill the card data, and press PAY, messages under all fields appears - saying that the fields are empty.
