### ISSUE TITLE
Provide a way to interact with the PayPal component once loaded (e.g. onReady callback)

### ISSUE THREAD

**Issue by nsarno** [Adyen/adyen-web#178]
**Is your feature request related to a problem? Please describe.**

We want the user to be redirected to PayPal automatically to fit our user flow.

Example user flow:
- Click a native button in our app
- Load a webview and instantly see the PayPal form

A possible solution would be to hide the entire container and automatically click on the PayPal button when it is ready. This isn't currently possible due to the button being inside an iframe.

**Describe the solution you'd like**

Provide a callback `onReady` (similar to `onSubmit`) as well as a function on the component to trigger the button.

e.g.

```js
onReady: (state, component) => {
  component.click();
}
```

**Describe alternatives you've considered**

I've considered triggering the button via javascript. As state above, this isn't possible because of the iframe.

**Comment by pabloai** [comment]
Hi @nsarno!

Thanks for reaching.
Unfortunately the PayPal SDK doesn't provide a way to trigger the flow programatically.
This has been requested several times but it doesn't seem to be in the roadmap.
See paypal/paypal-checkout-components#1264

Would hiding your button and showing PayPal's not work for your use case?
Keep in mind there's an `onInit` function and an `onClick` function you can pass to the PayPal component which could help in your flow. Here's an example from the PayPal docs:
https://developer.paypal.com/docs/checkout/integration-features/validation/#synchronous-validation

Let me know if that helps!

**Comment by nsarno** [comment]
Bummer. Thanks for the quick response. We'll adapt for now.

**Comment by zhentan** [comment]
@pabloai The Adyen iOS SDK can open a webview and it will load a blank page that auto redirect's user to the Paypal auth screen without the user clicking on any Paypal component. We are trying to recreate/figure out how that is done.
