### ISSUE TITLE
Autofill don't validate Component on Chromium browsers

### ISSUE THREAD

**Issue by UlrichHP** [Adyen/adyen-web#1793]
**Describe the bug**
On Chrome/Edge (and maybe Safari), when using Autofill to fill the component inputs, adyenCheckout `state.isValid` remains at `false` and in `state.valid`, these fields are missing:
- encryptedCardNumber
- encryptedExpiryMonth
- encryptedExpiryYear
- encryptedSecurityCode

This bug doesn't occur on Firefox.

**To Reproduce**
1. Load adyen form in Chrome
2. Autofill fields with a saved card

**Expected behavior**
Inputs are filled and `state.isValid` should be true

**Screenshots**
![Screenshot_20221011_110627](https://user-images.githubusercontent.com/27560999/195047897-2befb175-b55f-435e-ad92-cabd469e235e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version 106.0.5249.103

**Comment by UlrichHP** [comment]
The latest version, 5.28

**Comment by JoachimL** [comment]
We use the latest version, whatever that is, and also experienced this on 4.x. This is really hurting our business, so please fix asap.

**Comment by m1aw** [comment]
Hello all,

We are trying to gather more information on this issue. In our testing environment this feature seems to be working. For example in https://www.mystoredemo.io/ .

Could you all please share a few more details on this?

- Which version of `adyen-web` are you using? 
- Are you using components or dropin?
- What framework is your website built on? (React, Vue, Next, ....)
- What configuration object are you passing to the card component?

**Comment by pellebjerkestrand** [comment]
Autofill on https://www.mystoredemo.io/ works for me with Safari 16 and Chrome 106 on macOS 12.6.

**Comment by UlrichHP** [comment]
Hello,

Autofill is working on the demo [https://www.mystoredemo.io/](https://www.mystoredemo.io/) but still not on our website. And i use Chrome 106.

- We use 5.28.0
- Components
- We use sylius and vanilla js
- The configuration object of AdyenCheckout is listening state.isValid in the onChange event

Like i said in the first post, in the `onChange` event, `valid` doesn't add encryptedCardNumber, encryptedExpiryMonth, encryptedExpiryYear and encryptedSecurityCode when using autofill on Chrome. But it is working correctly on Firefox.

**Comment by UlrichHP** [comment]
This bug seems to be fixed by updating adyen-web to `5.28.1`

So preact seems to be responsible for this bug on Chrome.
