### ISSUE TITLE
Preact 10.11.1 is incompatible with Adyen

### ISSUE THREAD

**Issue by AndreasJilvero** [Adyen/adyen-web#1794]
We're using @adyen/adyen-web@5.16.0 which depends on Preact. If you do a fresh install, you will get Preact@10.11.1 which is not compatible with Adyen - maybe following https://github.com/preactjs/preact/pull/3720.

The effect is that Adyen dropdown select **items** can't be clicked. This is due to select items (the `li` element) getting a `data-disabled="false"` attribute which later on prevents the click event due to a if condition `if(!t.getAttribute("data-disabled")) { ... }`.

![image](https://user-images.githubusercontent.com/7750212/195067755-d97045d7-6f2a-495d-b3d4-b530fc78cff0.png)

To clarify, nothing happens if I click on POP Pankki due to the reason I mentioned above.

Edit: You can probably work around this by importing the [pre-compiled Adyen file](https://cdn.jsdelivr.net/npm/@adyen/adyen-web@5.16.0/dist/adyen.min.js) but it's not preferred.

I understand that the issue is not in Adyen code but if possible, Adyen should restrict Preact usage to **not** 10.11.1.

**Comment by AndreasJilvero** [comment]
@m1aw The solution you suggest seem to rely on either using Yarn or npm-force-resolutions. In our case, we used [npm overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) to force the version to 10.10.6.

**Comment by ribeiroguilherme** [comment]
Hey @AndreasJilvero . Can you upgrade to 5.28.1 and verify if it fixes the issue?

**Comment by ribeiroguilherme** [comment]
Upgrading the library to > 5.28.1 should fix the issue, therefore I am closing this ticket.
