### ISSUE TITLE
web-dropin 5.24.0 error reporting issue

### ISSUE THREAD

**Issue by pine3ree** [Adyen/adyen-web#1798]
Hello, when using the Test 3D Secure 2 authentication card (amex 3714 4963 5398 431), sometimes the component's onError is called, but instead of an error object (with name/message props) I get a string (see the console.log('error =' , error) screenshot)

This happened in a couple of tests (out of 50~60) just after sending the card information and waiting for the security code form to be displayed.

kind regards

![adyen-network-error](https://user-images.githubusercontent.com/3229979/195597132-0aa37760-29be-44d4-b2c5-619dda3426fc.png)

**Comment by m1aw** [comment]
Hey @pine3ree 

If I understand correctly the error that you got was seems to be a network error cause by your own server correct?

So the issue is regarding why this doesn't go through the library `onError` instead of throwing an exception?

**Comment by pine3ree** [comment]
Hello @m1aw ,
in this case the issue is not the network error per se, but the fact that i do not get an error object. I get a string instead. It does go through the onError(error, component) handler, but error is a string (the first line in the screenshot is my call console.log('error =', error) inside onError()). I expect and error object with a `name` property and a `message` property, also according to adyen-web js api.

**Comment by pine3ree** [comment]
@m1aw I would expect:
error.name = 'NETWORK_ERROR'
error.message === 'Call to https://.,,ect'

**Comment by pine3ree** [comment]
Inside my handler:
```js
    function handleError(error, dropin) {
        IS_DEBUG && console.log('error =', error);
        setTimeout(function() {
            window.location.href = HREF_ADYEN_OUTCOME + '&rc=' + encodeURIComponent(error.name) + '&mref=' + MREF;
        }, REDIRECT_TIMEOUT);
    }
```
since `error.name` is undefined `'rc=' + encodeURIComponent(error.name)` resolves to `'rc=undefined'`, while it should resolve to `'rc=NETWORK_ERROR'`.

As a temporary patch I added a type check inside my handler (just before the setTimeout call), hoping that if `error` is a string there is a first part before a colon char that represents one of adyen error/result codes 
```js
        if (typeof error === 'string') {
            var regexp = /^[A-Z]+(?:\_[A-Z]+)*\:/i;
            if (regexp.test(error)) {
                var parts = error.split(':', 2);
                error = { name: parts[0].trim() };
            }
        }
```

**Comment by m1aw** [comment]
Hello @pine3ree 

I was taking another look at this issue, could you let us know which request is generating this error?

Additionally could you let us know which version of browser are you using and which version of `@adyen/adyen-web` are you using?

Thank you,

**Comment by pine3ree** [comment]
Hello @m1aw , 
I was testing the native 3DS2 Drop-in integration. The (uncaught?) network error occurred just after sending the credit card info in order to receive the additional 3ds2 secure code form. I test mostly in FF (linux, latest version at the time of this issue so probably 103~105). But i remember I had the same issue even with chromium-linux (v.90). I updated my customer frontend libs up to version 5.29.x (and the php server library too), but since with my workaround the issue was circumvented I cannot tell if the issue itself is still there. Another strange fact that i remember is that the issue would not happen in a week during tests and the maybe twice within a few minutes. Kind regards.
