### ISSUE TITLE
Dropin payment has issues with intent parameter

### ISSUE THREAD

**Issue by natiagelashvili3** [Adyen/adyen-web#1802]
Hello, We are using 
- Adyen Checkout Api version: v67 
- JS SDK version: 4.5.0

We try to add Paypal payment method in dropin payment

First request that we send is /paymentMethods and from here I get intent: authorize in paypal configuration

![Screenshot from 2022-10-20 15-42-37](https://user-images.githubusercontent.com/44501214/196944119-85fda509-ea47-43e4-8cc5-4a0973152735.png)

But when I pass this to Adyen Dropin configuration I always get error: **“Expected intent from order api call to be authorize, got capture. Please ensure you are passing intent=capture to the sdk ur**l”

![Screenshot from 2022-10-20 15-52-26](https://user-images.githubusercontent.com/44501214/196944337-0d02f28d-62d8-4024-926c-be26f9a8067d.png)

If I pass intent as “capture” in Adyen transaction I have an error:

![Screenshot from 2022-10-20 15-54-09](https://user-images.githubusercontent.com/44501214/196944512-642f1d4c-fdf0-456c-aa07-5e01aecf1f2c.png)

can you please describe correct flow of paypal payment? which one should i use capture or intent?

what im doing is very simple:
1. im sending /paymentMethods request and get all available payment methods including paypal
2. if i have intent: “capture” in configuration i send /payments, 
which includes `"paymentMethod" : { "type" : "paypal", "subtype" : "sdk" }` in the request, it returns me 
{
   "resultCode" : "Pending",
       "action" : {
          "paymentData" : "******",
          "paymentMethodType" : "paypal",
          "sdkData" : {
             "token" : "********************"
          },
          "type" : "sdk"
   }
} this responce
3. last step is to call `onAdditionalDetails` method and call /payments/details endpoint where it returns error

![Screenshot from 2022-10-20 16-14-38](https://user-images.githubusercontent.com/44501214/196945755-555f81a9-87cb-4813-82dd-38aef208b176.png)

and i dont get what is the problem, seems like im doing everything but still have an error

**Comment by ribeiroguilherme** [comment]
Hey @natiagelashvili3 .

It seems to me that can be something related to how you configured PayPal in your account. Did you reach out to the tech support to verify your settings?

The flow you described seems right to me. `/paymentMethods` call will return the available payment methods (including PayPal) with the intent value already in place - you don't have to set that manually. Then you do the `/payments` call, the pop-up will show up, and after completing the payment there, you do the `/payment/details` call . The request body seems right to me. 

Could you by any chance test the flow using our latest version of the SDK? Although it requires some adjustments in the code as described [here](https://docs-admin.is.adyen.com/online-payments/release-notes?integration_type=web&version=5.0.0&tab=v5-0-0-or-later_2021-10-04-stzc_1#releaseNote=2021-10-06-web-componentsdrop-in-5.0.0)

**Comment by natiagelashvili3** [comment]
hi @ribeiroguilherme, thanks for your answer, we will reach support team to double check Paypal configuration, and meanwhile will test in new SDK version.

**Comment by ribeiroguilherme** [comment]
Hi @natiagelashvili3 . Did you manage to solve your issue?

**Comment by ribeiroguilherme** [comment]
Closing this as the issue is stale. Feel free to reach out if the problem persists.
