### ISSUE TITLE
Filter supported payment methods

### ISSUE THREAD

**Issue by dpinheiro** [Adyen/adyen-web#1813]
**Is your feature request related to a problem? Please describe.**
In one of our projects we are integrating Adyen using the web components, and making an API call to the REST endpoint /paymentMethods in order to obtain the available payment methods and display a selection to the end user. The problem is that this call is returning payment methods that may not be available on the user browser like Apple Pay. I know when mounting the component we can use the method `isAvailable()` but I would say that's already too late since we already let the user to select an option that is not supported

**Describe the solution you'd like**
Either to have some way to pass some browser context to the REST endpoint /paymentMethods, so the response would already only contain the supported payment methods for that specific user OR have some sort of utility class on this package that allow us to verify if some payment method is supported by the user browser `isAvailable(paymentMethod: string)` so we could filter the list received from the API.

**Describe alternatives you've considered**
Or to use the existing method `isAvailable()` at the component level but that would be a bad UX for the user, or alternatively dig into the code https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/components/ApplePay/ApplePay.tsx#L123 and try to extract those conditions to some helper

**Additional context**
n.a.

**Comment by ribeiroguilherme** [comment]
Hey @dpinheiro ,

That is the trade off of using web components: in one hand you have more flexibility of what to render on the screen, but on the other hand you need to treat such scenarios like excluding certain payment methods.

>  I know when mounting the component we can use the method isAvailable() but I would say that's already too late since we already let the user to select an option that is not supported

In this case, you shouldn't let the user neither see or select any option until you know which payment methods are available. You should first use the `isAvailable()` then render the Component as described [here](https://docs.adyen.com/payment-methods/apple-pay/web-component#step-3-mount-the-component).

I am afraid we can't help much here as there is no plan to enhance the REST endpoint passing the shopper browser whatsoever, neither expose any other utility function as the Component already exposes that. Regardless of that, I will sync with the team about this idea. Thanks for sharing it.
