### ISSUE TITLE
Cursor in Expiry date field works incorrectly

### ISSUE THREAD

**Issue by pof-wojciechszubryt** [Adyen/adyen-web#1823]
**Describe the bug**
Cursor in credit card expiry date input field works incorrectly.

**To Reproduce**
1. Click credit card expiry date input field in DropIn
2. Enter "1222"
3. Place the cursor between "12" and "/22" either by keyboard or mouse
4. Hit backspace or delete key on the keyboard
5. Cursor remains at the same position although the digit was deleted properly, so when you now enter "1" for example you'll get the date "12/12" instead of "11/22"

**Expected behavior**
Digit will be deleted and cursor moves one position to the left / right. So when you now enter "1" for example you'll get the date "11/22".

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 107.0.5304.88

**Comment by sponglord** [comment]
Hi @pof-wojciechszubryt - thanks for raising this.
This is a known issue - an annoying "quirk" of the card component (basically when reduced to 3 digits the expiryDate tries to create the basis for a new date from what is left in the field)
At the moment, however, this is low on our priority list for fixing

**Comment by sponglord** [comment]
The major release, `v6.0.0`, was launched today!
See the documentation here:
- [release notes](https://docs.adyen.com/online-payments/release-notes/#releaseNote=2024-07-24-web-componentsdrop-in-6.0.0)
- [migration guide](https://docs.adyen.com/online-payments/update-your-integration/migrate-to-web-v6/)

After this upgrade you will see that the `expiryDate` behaves in a much less quirky way when being edited
