### ISSUE TITLE
Throw two errors and Caller can catch

### ISSUE THREAD

**Issue by Kerita** [Adyen/adyen-web#1833]
**Is your feature request related to a problem? Please describe.**
There are two case that I get error but cannot catch it when init 3DS 2.0 flow via call createFormAction(data, config).

Case 1:
The error occurs when I pass wrong `data` pass to  createFormAction. 
 I change token filed in data which getting from Adyen and API https://checkoutshopper-test.adyen.com/checkoutshopper/v1/submitThreeDS2Fingerprint gets 500 error.
![image](https://user-images.githubusercontent.com/10560806/200468648-27d9b782-51a4-4ac5-8730-e8617eca52c0.png)

Case 2:
I using Charles to change the param paymentData pass, and https://checkoutshopper-test.adyen.com/checkoutshopper/v1/submitThreeDS2Fingerprint get 422 error.
![image](https://user-images.githubusercontent.com/10560806/200468889-9e36d334-3204-4d4c-b471-46adcfe2fc1e.png)

**Describe the solution you'd like**
I add onError in configuration and pass configuration to new AdyenCheckout(configuration), but cannot catch these two errors. 
Could you throw these two errors to onError event?

**Comment by ribeiroguilherme** [comment]
Hey @Kerita .

What version of the SDK are you using? Could you also test this scenarios with the latest library version?

**Comment by ribeiroguilherme** [comment]
Closing this as the issue is stale. Please reach out if the problem persists.
