### ISSUE TITLE
PayPal and `showPayButton:false`

### ISSUE THREAD

**Issue by dariusz-wozniak** [Adyen/adyen-web#1835]
**Describe the bug**
While integrating Adyen with PayPal, PayPal payment works fine with the flag `showPayButton` set to true. However, our requirement is to have a custom button outside the drop-in and disable that flag.

However, this results with:
- `paypal.onSubmit` is not being called (is being called when the `showPayButton` == true)
- error on AdyenCheckout submit: `IMPLEMENTATION_ERROR Calling submit() is not supported for this payment method`

How can we proceed in such scenario? What's your recommendation?

**To Reproduce**
1. Set `showPayButton: false`
2. Try to invoke payment via PayPal by custom button

**Additional context**
The SDK version is 5.28.2.

**Comment by ribeiroguilherme** [comment]
Closing this issue for now. Feel free to reach out if the issue persists.
