### ISSUE TITLE
How to be able to know to redirect to 3ds validation window close event

### ISSUE THREAD

**Issue by lynn1286** [Adyen/adyen-web#1838]
**Is your feature request related to a problem? Please describe.**

The business requirement is that when the user redirects to a third-party page (such as 3ds), the user closes the verification window or exits the payment, how can we know?

**Describe the solution you'd like**
You need to know that the user exits the payment after the redirection is to the third party page

**Describe alternatives you've considered**
How to implement nesting of third-party pages in the form of iframes, currently calling handleAction will reopen the window and jump

**Additional context**
<img width="964" alt="image" src="https://user-images.githubusercontent.com/40122311/201459294-1441c007-c264-45e6-8220-b1af52e220a8.png">

**Comment by sponglord** [comment]
@lynn1286 - does this answer your question at all? (Relates specifically to 3DS2)
> Clicking on the Cancel button, however, does lead to a measurable result - cancelling is a legitimate user action in the 3DS2 flow and will lead to a call to any onAdditionalDetails handler that you have defined.
If this handler then makes the expected call to the /payments/details end point you will get a response with a resultCode: "Refused" and a refusalReason: "3D Not Authenticated"

(from #1839)

**Comment by lynn1286** [comment]
> 

This is not my problem. I hope that when the component can redirect the third-party page, I can display this page in the form of iframe without jumping to the page. I looked at the official example of 5.0, which uses iframe to display third-party pages.

**Comment by ribeiroguilherme** [comment]
Hi @lynn1286 

- What is the version if the adyen-web SDK that you are using?
- Our component already shows the iframe embedded in the page as part of the 3DS2 flow. What is the flow you are experiencing to trigger redirect to another page? Can you explain that and maybe share a video / test cards / whatever other information to help us understand your problem.

**Comment by ribeiroguilherme** [comment]
Closing this issue for now. Feel free to reach out if you have more information to help us investigate this issue. Cheers
