### ISSUE TITLE
Not able to style Chrome autofilled secure fields

### ISSUE THREAD

**Issue by pof-wojciechszubryt** [Adyen/adyen-web#1840]
**Describe the bug**
There is no way now to style Chrome autofilled secure field like credit card number and expiry date. The default background for autofilled input is white which could look incorrect for black styled inputs.

**To Reproduce**
1. Use autofill feature in Chrome for payment details
2. Look at secure fields background color

**Expected behavior**
Should be a way to style autofilled input

**Screenshots**
![image](https://user-images.githubusercontent.com/104028473/201738479-1944657f-85a1-421d-90cc-64643b7e3947.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 107.0.5304.107 (Official Build) (64-bit)

**Comment by ribeiroguilherme** [comment]
Hey @pof-wojciechszubryt ,

Thanks for reaching out. Unfortunately we don't support this feature yet, but it is in our backlog. 
I will make sure to keep this thread updated and will let you know once this feature is released.

Related: #1240

**Comment by sponglord** [comment]
The major release, `v6.0.0`, was launched today!
See the documentation here:
- [release notes](https://docs.adyen.com/online-payments/release-notes/#releaseNote=2024-07-24-web-componentsdrop-in-6.0.0)
- [migration guide](https://docs.adyen.com/online-payments/update-your-integration/migrate-to-web-v6/)

For you specific issue you need will need to generally override the input's background colour somewhere in your own stylesheet e.g.
```
:root {
    --adyen-sdk-color-background-primary:yellow;
}
```

And then when you configure the `Card` component, pass in a `styles` object e.g.
```
window.card = new Card(checkout, {
  styles: {
    base: {
      background: 'yellow'
   }
}
```
to ensure the background colour of the iframe is also changed.
