### ISSUE TITLE
Queryparam MD in return URL too large

### ISSUE THREAD

**Issue by nachogarcia** [Adyen/adyen-web#185]
**Describe the bug**
The return URL to go to the confirmation page contains a queryparam `MD`. In some cases, this queryparam is extremely large which causes a 431 HTTP error on our page since it exceeds the maximum sice.

**To Reproduce**
Make a payment with LaCaixa and 3dSecure

**Expected behavior**
A valid HTTP URL

**Screenshots**
![image](https://user-images.githubusercontent.com/9975630/89785683-1455f900-db1b-11ea-9895-aab38d418de9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest

**Comment by pabloai** [comment]
Hi @nachogarcia,

Thanks for reaching us.
This seems to be related with the API, not with with the adyen-web library.
I'd suggest you to get in touch with [Adyen Support](https://www.adyen.help/) and provide them a PSP reference as well as the details you shared here.

Have a nice day!

**Comment by rdelonSinfin** [comment]
We had the same problem.

We fix it ( thanks to Théo from technical support ) by editing our NGINX config with : 

`http2_max_field_size 8k;`

Update the http2_max_field_size config in the SSL offloader from the default 4k to 8k which makes longer URL's serviceable by the backend.
