### ISSUE TITLE
Security code Input field, the placeholder is displayed as "3 digits"

### ISSUE THREAD

**Issue by manoj7594** [Adyen/adyen-web#1853]
**Describe the bug**
In Security code Input field, the placeholder is displayed as "3 digits". But before it is "CVC / CVV". 

**To Reproduce**
1. In Enter your card detail section in payment details.
2. Look at the security code.

**Expected behavior**
I want "CVC /CVV" as placeholder.

**Screenshots**
<img width="275" alt="image" src="https://user-images.githubusercontent.com/18344251/203058926-89f95eee-244d-4ea5-9aa9-185599af6070.png">

**Desktop (please complete the following information):**
 - Chrome Browser 
 - Version 22

**Smartphone (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 22

**Comment by SarKurd** [comment]
You can provide your translation

here the configuration: https://docs.adyen.com/online-payments/web-drop-in/customization#customizable-text

These three are relevant to your case:

```json
"creditCard.cvcField.placeholder": "123",
"creditCard.cvcField.placeholder.4digits": "4 digits",
"creditCard.cvcField.placeholder.3digits": "3 digits",
```

**Comment by sponglord** [comment]
@manoj7594 - @SarKurd is correct, you can localise which placeholders are used with a translations object placed in the configuration object used when you initialise Checkout: https://docs.adyen.com/online-payments/web-drop-in/customization#customizing-a-localization
For the credit card it is the 
```
"creditCard.cvcField.placeholder.4digits": "4 digits",
"creditCard.cvcField.placeholder.3digits": "3 digits"
```
you will need to set.

(Thanks, @SarKurd, for answering! )
