### ISSUE TITLE
Submit the form by pressing the Enter key with the custom card integration 

### ISSUE THREAD

**Issue by pguilbert** [Adyen/adyen-web#1881]
**Is your feature request related to a problem? Please describe.**
I'm doing a [custom card integration](https://docs.adyen.com/payment-methods/cards/custom-card-integration). As a user, I would like to be able to submit the form by pressing the Enter key (default browser behavior for native forms).

**Describe the solution you'd like**
Add an `onSubmit` callback (next to `onFieldValid` / `onChange`, etc...) that is called when the user presses enter in the iframe fields.

**Describe alternatives you've considered**
AFAIK, there is no other way to do this (?)

**Comment by ribeiroguilherme** [comment]
Hi @pguilbert ,

Does this answer your question? 

> We do not capture "Enter" key presses on the credit card fields. We expect users to Tab between fields and when they have Tabbed onto the Pay button, pressing Enter will then validate/submit the form

from #1242

**Comment by pguilbert** [comment]
Hi,

Not really. I would like to offer the user the same experience as in an html form. 
For that, the only thing that is missing is the ability to submit the form with the "Enter".

**Comment by ribeiroguilherme** [comment]
Hi @pguilbert ,

The `onSubmit` callback already exists and it is used to perform the `/payments` call . It would make more sense to provide something like `onEnterPress` for example.

Regardless of that, I discussed internally with the team and we created a ticket to check this out. We have other priorities at the moment, but we will make sure to keep this ticket updated with the progress. Cheers

**Comment by obouchari** [comment]
I have a custom button using components, when calling submit() the form doesn't seem to show any validation errors! Am I missing something?

**Comment by ondrakub** [comment]
hi, any progress on this issue? we would also like to submit the form using enter. This is a common behavior that users are used to and would improve the experience.

**Comment by sponglord** [comment]
The major release, `v6.0.0`, was launched today!
See the documentation here:
- [release notes](https://docs.adyen.com/online-payments/release-notes/#releaseNote=2024-07-24-web-componentsdrop-in-6.0.0)
- [migration guide](https://docs.adyen.com/online-payments/update-your-integration/migrate-to-web-v6/)

See the "New" section of the Release notes...
> Shoppers can now confirm the payment by pressing the Enter key...

For a `CustomCard` you will need to implement your own `onEnterKeyPressed: (activeEl, component) => {}` function and use it to validate/submit your form e.g. by triggering `click()` on your Pay button
