### ISSUE TITLE
Debit Card showing installments option

### ISSUE THREAD

**Issue by jonathanribas** [Adyen/adyen-web#1882]
**Describe the bug**
A Debit Card shouldn't show installments, only Credit Cards.

**To Reproduce**
1. Go to checkout
2. Digit a Debit Card number
3. Installments are still showing up

**Expected behavior**
A Debit Card shouldn't show installments, only Credit Cards.

If then you choose to use a Credit Card, installments should appear.

**Desktop (please complete the following information):**
All browsers.

**Smartphone (please complete the following information):**
All devices and browsers.

**Comment by ribeiroguilherme** [comment]
Hey @jonathanribas ,

What version of the adyen-web checkout SDK are you using? Could you also share the card component configuration?

**Comment by jonathanribas** [comment]
Hi @ribeiroguilherme, 
- We are using `5.24.0`.
- Card component configuration:
`card: {
              onBrand: (data) => (brand.value = data.brand),
              installmentOptions: {
    amex: {
      values: [1, 2, 3]
    },
    visa: {
      values: [1, 2, 3]
    },
    mc: {
      values: [1, 2, 3],
    },
    showInstallmentAmounts: true,
  }
            }`

**Comment by ribeiroguilherme** [comment]
Are you using Drop-in or Components? Are you by any chance also using the [splitCardFundingSources](https://docs.adyen.com/api-explorer/Checkout/latest/post/sessions#request-splitCardFundingSources) to split Debit and Credit payment methods?

**Comment by jonathanribas** [comment]
Hi @ribeiroguilherme, thanks for your reply.

We are using drop-in, any chance to have this `splitCard` on drop-in too?

**Comment by ribeiroguilherme** [comment]
@jonathanribas Unfortunately on Drop-in , the card configuration is used in both Credit and Debit types. Meaning that, if you configure `installmentOptions` for the `card` configuration, it will be applied to both. 

We have one ticket in our backlog to remove the installments when the Card `fundingSource` is `debit`, but it hasn't being picked up yet by our team.

If using Components is an option for you, you could create two separated Components in this case, and for the 'Credit' card component you can pass the `installmentOptions` property, and in the 'Debit' one can you omit it. In this way, you will be able to achieve what you want.

I will keep this issue open and will update it once we fix the installments for Debit in Drop-in.

**Comment by jonathanribas** [comment]
Hi @ribeiroguilherme, thanks for your reply.
This one is really important for Brazilian market. 
Any chance to have an ETA?

**Comment by ribeiroguilherme** [comment]
Hey @jonathanribas ,

We release 5.35.0 which contains the fix for this issue. Thanks for reaching out to us. Cheers!

**Comment by jonathanribas** [comment]
Hi @ribeiroguilherme,
Thanks for the fix, we will test it anytime soon!
Cheers!
