### ISSUE TITLE
Error when starting the server

### ISSUE THREAD

**Issue by naattmoo** [Adyen/adyen-web#1883]
A merchant is incurring in an error when running their integration. It seems that some characters are missing in some parts of the code.
This happen to them with the version 5.30.0 and the previous one.

**ERROR**

ERROR in node_modules/@adyen/adyen-web/dist/types/components/AmazonPay/config.d.ts(10,54): error TS1005: ']' expected. node_modules/@adyen/adyen-web/dist/types/components/AmazonPay/config.d.ts(10,56): error TS1134: Variable declaration expected. node_modules/@adyen/adyen-web/dist/types/components/AmazonPay/config.d.ts(10,90): error TS1005: ';' expected. node_modules/@adyen/adyen-web/dist/types/components/PayPal/config.d.ts(6,51): error TS1005: ']' expected. node_modules/@adyen/adyen-web/dist/types/components/PayPal/config.d.ts(6,53): error TS1134: Variable declaration expected. node_modules/@adyen/adyen-web/dist/types/components/PayPal/config.d.ts(6,258): error TS1005: ';' expected. node_modules/@adyen/adyen-web/dist/types/components/internal/Address/constants.d.ts(3,56): error TS1005: ']' expected. node_modules/@adyen/adyen-web/dist/types/components/internal/Address/constants.d.ts(3,58): error TS1134: Variable declaration expected. node_modules/@adyen/adyen-web/dist/types/components/internal/Address/constants.d.ts(3,129): error TS1005: ';' expected.

Please let me now when this is solved.

**Comment by ribeiroguilherme** [comment]
Hi @naattmoo 
Which version of adyen-web this error doesn't happen?

**Comment by naattmoo** [comment]
Typescript version: 3.1.6. They haven't changed it since they start integrating. They believe they haven't tried a version were this wasn't happening.

**Comment by ribeiroguilherme** [comment]
@naattmoo I suppose you are using an old version of Typescript, which doesn't support certain types exposed by the library. Is there a chance for you to upgrade the Typescript to > 3.8.0 and try it out?

**Comment by m1aw** [comment]
Hey @naattmoo 

I hope the last answer was sufficient to fix the issue. If that is not the case please fell free to open the issue again.

Cheers,
