### ISSUE TITLE
Adyen Web component - upgrading to 5.20.0 or later triggers onError during local development

### ISSUE THREAD

**Issue by ssolders** [Adyen/adyen-web#1886]
**Describe the bug**
During local development we specify an alias in the host file for our localhost:80

```
127.0.0.1 mysite.local 
```

We have whitelisted `http://mysite.local` in the list of domain allowlist in the Adyen portal, and everything works as expected when we run `5.19.0` or a previous versions locally

After we upgraded to 5.20.0 or any of the later versions, we end up with the Adyen component being loaded, but `onError` is triggered and the secure fields all display an error message + logs an error in the developer console.

```
securedFields.html?type=card&d=aHR0cDovL2hhbGxvbi5sb2NhbA==:136 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'importKey')
    at securedFields.html?type=card&d=aHR0cDovL2hhbGxvbi5sb2NhbA==:136:69095
    at s (securedFields.html?type=card&d=aHR0cDovL2hhbGxvbi5sb2NhbA==:136:137085)
    at Generator._invoke (securedFields.html?type=card&d=aHR0cDovL2hhbGxvbi5sb2NhbA==:136:136838)
    at Generator.next (securedFields.html?type=card&d=aHR0cDovL2hhbGxvbi5sb2NhbA==:136:137448)
    at ze (securedFields.html?type=card&d=aHR0cDovL2hhbGxvbi5sb2NhbA==:136:66163)
    at a (securedFields.html?type=card&d=aHR0cDovL2hhbGxvbi5sb2NhbA==:136:69278)
    at securedFields.html?type=card&d=aHR0cDovL2hhbGxvbi5sb2NhbA==:136:69339
    at new Promise (<anonymous>)
    at securedFields.html?type=card&d=aHR0cDovL2hhbGxvbi5sb2NhbA==:136:69218
    at securedFields.html?type=card&d=aHR0cDovL2hhbGxvbi5sb2NhbA==:136:69382
```

The issue occurs both when the Adyen session is created from a deployed backend running on https or one running locally on http. Once we run the client deployed on https it works as expected with the 5.19.0 or later.

The hostfile alias setup is just my guess as the root-culprit, hence including that in the bug-description.

**To Reproduce**
1. Run a local web client, configure it to run against a hostfile alias
2. Client requests a backend to create a adyen session
3. Setup the adyen web component with the sessionId
4. The web component loads but errors are logged in the browser console and the fields display an error.

**Expected behavior**
The web component should load the fields without any errors

**Screenshots**

![Screenshot 2022-12-15 at 10 24 03](https://user-images.githubusercontent.com/7665542/207822235-b1ccc6c8-85b8-4dbe-9d40-04d4970f9ec9.png)

**Desktop (please complete the following information):**
 - OS: MacOS 13.0.1 and Windows 11
 - Browser: All browsers

**Comment by ribeiroguilherme** [comment]
Hi @ssolders ,

I believe the comment below is related to the problem you are facing:

> This is happening because, in v5.20.0 we changed the way we encrypt our fields. We have starting using JSON Web Encryption (JWE).
> 
> This relies, internally, on window.crypto, and, more relevant in this case window.crypto.subtle (https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle)
> 
> As you can see from the above link (> Browser compatibility table), this feature is marked as "Secure context required".
> 
> From MDN's docs on [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts):
> 
> Locally-delivered resources such as those with http://127.0.0.1 URLs, http://localhost and http://*.localhost URLs (e.g. http://dev.whatever.localhost/), and file:// URLs are also considered to have been delivered securely.
> 
> In essence, without the localhost an http domain is not considered secure and therefore window.crypto.subtle fails.
> 

(from #1710)

Can you try using alias with `localhost` ?  or serve your web app through `https`?

**Comment by ssolders** [comment]
Hi @ribeiroguilherme, thanks for the quick response, we can look into that yea!

**Comment by ribeiroguilherme** [comment]
Closing this issue for now. Feel free to reach out if the problem persists.
