### ISSUE TITLE
[dropIn] onChange event not triggered when switching payment method type 

### ISSUE THREAD

**Issue by michielmetcake** [Adyen/adyen-web#1887]
**Describe the bug**
We're using the `onChange` event to validate/invalidate our payment flow. When selecting a payment method type + issuer and switch from payment method type and back. The `onChange` event is not being triggered when switching from payment method type. It's only being triggered when actually updating the values within the payment method forms.

**To Reproduce**
1. Go to https://github.com/adyen-examples/adyen-node-online-payments#run-this-integration-in-seconds-using-gitpod and setup an example 
2. Click on `Drop-in`
3. Click on `Continue to checkout`
4. Select a issuer in the `iDeal` payment method
5. A `onChange` event is triggered 
6. Click on `Credit or debit card`
7. A `onChange` event is triggered 
8. Click on `iDeal`
9. NO onChange event is triggered 

**Expected behavior**
An `onChange` event should be triggered every time the form changes state. So the actual returned value could represent the current form state.

**Desktop & smartphone (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Additional context**
Tested with sdk `5.30.1`

**Comment by ribeiroguilherme** [comment]
Hey @michielmetcake 

The `onChange` event is triggered when the input fields are *rendered by the first time* or when the *user interacts* with it by changing its value. 

What is happening in this case is: When you open iDeal, the input field is created, then you switch to the Card and its fields are created, then you come back to iDeal but the field is already created, and it was just hidden. That leads to `onChange` not be triggered. This can be something that we can take a look internally, seems like this could be improved.

Which kind of validation are you trying to achieve here? You can also use the [onSelect](https://docs.adyen.com/online-payments/web-drop-in/optional-configuration#optional-drop-in-configuration) to detect when the shopper changes the payment method in the dropin , and you can also get the payment method data from this callback.

**Comment by michielmetcake** [comment]
@ribeiroguilherme thank you for your quick reply.

You're 100% correct. But I can't get the values that I'm looking for from the arguments of the `onSelect` callback.

The values from the `onChange` callback are:

```
{
    "data": {
        "paymentMethod": {
            "type": "ideal",
            "issuer": "0511"
        },
        "clientStateDataIndicator": true
    },
    "errors": {
        "issuer": null
    },
    "valid": {
        "issuer": true
    },
    "isValid": true
}
````

And if I look into the component argument from the `onSelect` then I see a `state` and `props` value which might be kind of the same, but not 100%. 

```
{
    "data": {
        "issuer": "0511"
    },
    "valid": {
        "issuer": true
    },
    "errors": {
        "issuer": null
    },
    "isValid": true
}
```

Especially for the creditcard it's lacking a lot of information that's not available in the `onSelect`  arguments. Do you see any possibility to get the same values?

**Comment by ribeiroguilherme** [comment]
Can you shed some light of which arguments are you looking for, and what is the use-case?
