### ISSUE TITLE
3DS 2.0 problem with drop-in implementation never receiving a challenge

### ISSUE THREAD

**Issue by guillaumepigeon** [Adyen/adyen-web#1888]
**Describe the bug**
Hi,
we recently implemented adyen magento 2 headless integration using the drop-in component. We are now trying to setup 3DS 2.0. We followed the documentation and we got to the step of handling the challenge. Our problem is that we place the order and call dropin.handleAction(action) but never receive any feedback or error message after that. We looked at the data and the challenge never shows even with the resultCode being "IdentifyShopper". We are using api version 69 and adyen-web 5.19.0.

![image](https://user-images.githubusercontent.com/120659429/207893806-a59626f9-5148-4531-9790-38c6cb786173.png)

**Expected behavior**
When we place our order using the test cards, we should receive a challenge pop up window asking us to confirm our identity.

**Comment by ribeiroguilherme** [comment]
Hey @guillaumepigeon ,

At a first glance, seems like the 'action' property is stringified in this case whereas it actually should be an object. Is it true?

Perhaps you can try to reach out to [adyen-magento2](https://github.com/Adyen/adyen-magento2) team to verify what is the problem, as they are the one working with this plugin integration.

**Comment by nikhild64** [comment]
Hi , 
I am also facing similar issue with version 5.29, adyen web 
below is the action action
paymentData: "Ab02b4c0!BQABAgA*******6IkBAQxBf72DEjzY
paymentMethodType: "visa"
subtype: "fingerprint"
token:"eyJ0aHJlZURTTWVzc2FnZVZlc********yNzQ2Lm=="
type: "threeDS2"

onAdditionalDetails  callback is never called on close or success

**Comment by ribeiroguilherme** [comment]
Are you implementing any of our plugins, or are you integrating directly with adyeb-web library? What is the test card you tried?

**Comment by nikhild64** [comment]
Hi @ribeiroguilherme , using web sdk with script tag approach, just found the issue, it was with backend as it was sending incorrect origin to adyen payment page
@guillaumepigeon check if this was the same issue with you
