### ISSUE TITLE
"Modern" library future, documentation, roadmap

### ISSUE THREAD

**Issue by sainthardaway** [Adyen/adyen-web#1931]
**Is your feature request related to a problem? Please describe.**
As described [here](https://github.com/Adyen/adyen-web/pull/1343/files) or [here](https://github.com/Adyen/adyen-web/issues/1655) there is a "modern" version of bundle for adyen-web that weights way less (more then twice less) and it can be used just by using `import AdyenCheckout from '@adyen/adyen-web/modern/';`. But there are no mentions about this in documentation, also no roadmap or something that will shed light on on the future of this nice ability. Since we plan to move one to the usage of the modern version of the bundle, can the someone from the dev team give a bit more information then is given in the PR or in the github issues 

**Describe the solution you'd like**
Documentation/roadmap or any details on support/progress of "modern" verios of the adyen-web library.

**Describe alternatives you've considered**
Answer in the issue below

**Additional context**

**Comment by ribeiroguilherme** [comment]
Hey @sainthardaway ,

Thanks for reaching out. We released the 'modern' bundle a while ago indeed and it was being tested by merchants - that is why we didn't create any specific documentation for it back then, but it seems that now we can start mentioning it in our Github page. I will discuss internally with the team about this.

This 'modern' version is officially supported by us, and we have plans to improve it in the next major release. However, there are other internal priorities right now which we will dig into this later this year 🤞 

There is something to consider before using this bundle:
- Polyfills might be needed depending of which kind of browsers you are targeting (Example: IE11, Safari)

Please let us know if that is clear. Cheers!

**Comment by robin-thomas** [comment]
@ribeiroguilherme I can confirm `modern` version does work (`import AdyenCheckout from '@adyen/adyen-web/modern'`), but I'm getting a TypeScript error in my IDE (VS code)
```
Cannot find module '@adyen/adyen-web/modern' or its corresponding type declarations.
```

Any idea how to solve this (without suppressing the error)?
