### ISSUE TITLE
Accessibility issue with WCAG guidelines

### ISSUE THREAD

**Issue by mateo76910** [Adyen/adyen-web#1933]
I am adapting website to WCAG accessibility guidelines and I have this bug with Ayden checkout form.

Apparently the problem by WCAG is that **label's for attribute contains an ID that does not exist in the document**.

So I'm wondering is there any way to fix that with Ayden library for react?
Because I don't have access to Ayden inputs - I am only mounting the whole form.

Thank you!

**Comment by m1aw** [comment]
Hey @mateo76910 

This is something we are currently working on. We are planning a bit accessibility overhaul in the upcoming months. The problem with the labels and ID across documents is something is the the list and will be tackled.

This is something we need to fix in our end. I will keep the ticket open and updated it later, but keep an eye out for our release notes.

**Comment by sponglord** [comment]
Hi @mateo76910  FYI - from v5.38.0 labels no longer have a _for_ attribute that points to an element that does not exist in the DOM
