### ISSUE TITLE
Publish a TypeScript definition file that can be consumed from a project without a module loader

### ISSUE THREAD

**Issue by RyanONeill1970** [Adyen/adyen-web#1935]
**Is your feature request related to a problem? Please describe.**
We use Adyen via a script src tag and have code written in TypeScript. We do not use a module loader or webpack. The Adyen npm package .d.ts files are not parsed by TypeScript, I think because they use export / import statements. Adding an 'import' statement in our TypeScript code means it will compile, but that import statement causes the browser to expect a module loader on the client which fails. It may be my lack of understanding but I am unable to make the definitions work with a codebase that does not use a module loader.

**Describe the solution you'd like**
I'd like the Adyen npm package Type Definitions to be able to be consumed by TypeScript that is not module based (outputs plain JavaScript). 

**Describe alternatives you've considered**
I've tried adjusting the official Adyen examples to use type definitions but these fail to compile. See below.

**Additional context**
You can see the examples I've forked and where I've tried to get it to pick up the type definitions and output to vanilla javascript in my repo. This line particularly (https://github.com/RyanONeill1970/adyen-dotnet-online-payments/blob/main/checkout-example/scripts/adyenImplementation.ts#L37) will fail as AdyenCheckout is not defined. 

I've also [opened an issue on that example repo](https://github.com/adyen-examples/adyen-dotnet-online-payments/issues/56) but I think they'll refer me back to the source (here).

**Comment by RyanONeill1970** [comment]
I've solved this but it requires a bit of config with TypeScript. If you'd like to use what I have done, please see [this repo](https://github.com/RyanONeill1970/adyen-dotnet-online-payments) . I can help you create docs for this scenario if you like or if you don't feel this is of any value, please just close this issue.

**Comment by ribeiroguilherme** [comment]
Hi @RyanONeill1970 ,

I'm glad you managed to find a solution for this issue. We will follow up internally with the team that supports the project you forked to see if that is a viable solution for your use case. In the meantime, we don't see any changes needed from our side in the adyen-web library. Cheers!
