### ISSUE TITLE
Add more details UnionPay testing card

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-web#1961]
It's possible to add `SMS Code` information [on this page](https://docs.adyen.com/development-resources/testing/test-card-numbers#china-unionpay) ? 

For mobile, the SMS Code is `123456`, for desktop is `111111`.

![Capture d’écran du 2023-01-24 10-30-47](https://user-images.githubusercontent.com/34821762/214256524-a0e3038a-5c2a-461d-bd5e-cd3ec85f2b0c.png)

**Comment by ribeiroguilherme** [comment]
Hi @dimitriBouteille ,

Thanks for the feedback. We forwarded it to the docs team, and they will take a look into this and update the documentation if required. Cheers!
