### ISSUE TITLE
TypeError with Card 3D Secure payment and Next JS build

### ISSUE THREAD

**Issue by FranNetti** [Adyen/adyen-web#1988]
**Describe the bug**
Using Next JS (library version below), 3d secure payment doesn't work correctly with Cards after building. 
In development mode by running the code with command `next dev` everything works as intended. When I build the code with `next build` and later start it on a webpack dev server with `next start` I get the following error  

> "TypeError Invalid attempt to destructure non-iterable instance.
> In order to be iterable, non-array objects must have a [Symbol.iterator]() method."

I'm using the cards listed [here](https://docs.adyen.com/development-resources/testing/test-card-numbers#test-3d-secure-2-authentication) (American Express, Maestro, Visa and Discover)

I'm following the component based approach: after creating the AdyenCheckout class I'm rendering each payment method received from the API call.

 ```
 const configuration: CoreOptions = {
  environment: payments.adyen.environment,
  clientKey: payments.adyen.clientKey,
  session: {
    id: result.sessionId,
    sessionData: result.sessionData,
  },
  showPayButton: true,
  locale,
  onPaymentCompleted: async (result: CheckoutSessionPaymentResponse) => {
    switch (result.resultCode.toLowerCase()) {
      case "authorised":
        router.replace(nextPageUrl");
        break;
      case "refused":
        showPaymentOutcome(PaymentOutcome.Refused);
        break;
      case "cancelled":
        router.back();
        void showNotification({ message: formatMessage("checkout.canceledError"), type: NotificationType.Error });
        break;
      default:
        showPaymentOutcome(PaymentOutcome.Failure);
    }
  },
  onError: (error: Error) => {
    console.error("----- ERROR -----");
    console.error(error.name);
    console.error(error.message);
    console.error(error.stack);

    showPaymentOutcome(PaymentOutcome.Failure);
  },
};

const checkout = await AdyenCheckout(configuration);
setCore(checkout);
```
-----------------
```
return (
    <div className={styles["adyen-page"]}>
      <div className={styles["adyen-container"]}>
        {core?.paymentMethodsResponse?.paymentMethods?.map((elem, index) => {
          const isSelected = selectedTab === index;
          return (
            <Box key={elem.type} className={`${styles["adyen-payment-method-container"]} ${isSelected ? styles["selected"] : ""} ${paymentOutcome != null ? styles["hide"] : ""}`}>
              <Accordion expanded={isSelected}>
                <AccordionSummary onClick={() => setSelectedTab(isSelected ? null : index)} expandIcon={<Radio size="small" checked={isSelected} />}>
                  {elem.name}
                </AccordionSummary>
                <AccordionDetails>
                  <div className="adyen-checkout__payment-method__details" ref={registerRef} />
                </AccordionDetails>
              </Accordion>
            </Box>
          );
        })}
      </div>
    </div>
);
```
-----------------

**Expected behavior**
3d secure should work both in development and build mode

**Screenshots**
Insert data
![insert data](https://user-images.githubusercontent.com/39243260/217560861-9a157f93-f73d-4336-9e00-227afe0843bf.png)

Development mode result
![development - 3ds ok](https://user-images.githubusercontent.com/39243260/217560971-a7d2cf65-47f2-420d-845b-b7ed740adf09.png)

Build mode result
![build - 3ds error](https://user-images.githubusercontent.com/39243260/217565307-d706ee18-4141-4257-a0e7-cd6688b20e35.png)

**Desktop:**
 - OS: macOS Ventura 13.0.1
 - Browser Chrome 109.0.5414.119

**Libraries:**
 - Next JS 12.3.1
 - React 18.2.0
 - Adyen Web: 5.30.1 - 5.31.0 - 5.32.0

**Steps to reproduce the behavior:**
1. Build code with `next build`
3. Start a webpack dev server with `next start`
4. Start a new Adyen payment transaction
5. Choose card payment
6. fill fields with values from [Test cards](https://docs.adyen.com/development-resources/testing/test-card-numbers#test-3d-secure-2-authentication)
7. click on "Pay" button

**Comment by tleyris** [comment]
Hello @FranNetti,
We had exactly the same issue.
We found a solution. In our Next config, we used swcMinify set to true.
When we removed this line "swcMinify: true", the 3DS2 payment has been fixed.

Hope this helps you.

**Comment by alepore** [comment]
I also have some 3DS problems and I see some TypeError, but I'm not on next.js

**Comment by sponglord** [comment]
@FranNetti - can you confirm whether the solution proposed by @tleyris works for you? Thanks

**Comment by FranNetti** [comment]
Hi all, thanks a lot @tleyris I did what you suggested me and now it works! 

I don't know if this is something to report to NextJS, because there is a bug in their swc minification, or if it's a bug of adyen library that happens only with swc. I think it's the latter, but I'm not sure about this: what do you think?

**Comment by m1aw** [comment]
Hello @FranNetti 

We have tested SWC in our React implementation playground and it still works in production mode. So it might be something with either Next+SWC or the default configurations Next uses with SWC.

For now I will close this issue. If you find any more relevant information for testing we can reopen the ticket.
