### ISSUE TITLE
DropIn component not working reliably with React 18 in StrictMode

### ISSUE THREAD

**Issue by martijnbru** [Adyen/adyen-web#1996]
**Describe the bug**
We're currently implementing the DropIn component in a new React 18 project. We've noticed during development that iDEAL and PaySafeCard (and most likely other payment methods that require redirects) do not perform their redirect action. This is ONLY happens when `<React.StrictMode>` is enabled and React 18's new render syntax using `createRoot()` is used.

The most likely reason for this issue is a bug related to the double render that occurs with React 18's StrictMode in development.

**To Reproduce**
1. Setup a React 18 project using the DropIn Component or use Adyen's react example project ([adyen-react-online-payments](https://github.com/adyen-examples/adyen-react-online-payments))
2. Run the project in a local development environment (for example using npm start from Adyen's React example project)
3. Make sure that in your index you're using `React.createRoot()` and `<React.StrictMode>` (Adyen's example project currently still uses the legacy React 17 `ReactDOM.render()` syntax and does not have StrictMode enabled)
4. Start a checkout using the DropIn component
5. Select iDEAL or PaySafeCard during checkout
6. You'll notice that the 'Pay' button does not redirect the user

Sidenote for step 6: very rarely the user is redirected to the page. It seems that this occurs when the http call from the browser to the payments API is slow getting a response, but it's been very difficult to consistently test this.

**Expected behavior**
On step 4 we'd expect the user to be redirected to the redirect URL specified in the action of the response from the payments API call.

**Desktop:**
 - OS: [e.g. iOS] MacOS Ventura 13.2
 - Browser [e.g. chrome, safari] Chrome 109

**Example screenshot with broken and wroking code side by side:**
![Screenshot 2023-02-17 at 16 41 33](https://user-images.githubusercontent.com/95087495/219699141-36b9aa13-e7f4-454a-8da3-091379e7c43f.png)

**Additional context**
Please note this bug also occurs in your [adyen-react-online-payments](https://github.com/adyen-examples/adyen-react-online-payments) project when changing the render in index.js from `ReactDOM.render()` to `React.createRoot()` and add `<React.StrictMode>` tags.

**Comment by ribeiroguilherme** [comment]
Hi @martijnbru ,

Thanks for reaching out. It seems like you are right - StrictMode will attempt to mount the Component two times, and that can lead to issues.

Could you try to call the mount step only once and see if the error goes away?  You can for ex. create a variable: 

```js
const isMounted = useRef(false);
```

And then update its value to `true` after the first mount happens. Then you can add a check to skip the 'mount' phase if the Component is already mounted.  Ex:

```js
if (isMounted.current === true) return;

checkout.create('dropin').mount(paymentContainer.current);
isMounted.current = true;
```

**Comment by martijnbru** [comment]
Hi Guilherme,

Thanks for quick your response!

The issue is indeed related to the mount/unmount/mount principle in React 18's StrictMode, thus using your solution does solve the issue in development.

Additionally, the method specified in React's beta docs ([https://beta.reactjs.org/learn/synchronizing-with-effects#fetching-data](https://beta.reactjs.org/learn/synchronizing-with-effects#fetching-data)) works as well.

However, since the exact tasks performed by `checkout.create()` are not fully specified in Adyen's documentation (at least as far as I can tell), I was hesitant to implement this solution.

I can imagine two potential solutions for this case:
1. Update the react-example project to make this methodology the 'standard' way of implementing adyen-web in React. This means that the example project can also start benefiting from StrictMode as well as React 18's render function. This would be an excellent update for that particular project, since React 18 is already specified as the used major version in the package.json. If this solution is chosen, I think the solution with the cleanup return function as suggested in the Beta docs is probably the most logical.
2. An update to adyen-web project so that the mount/unmount/mount methodology no longer causes issues? Perhaps by using a solution that caches request responses as suggested in the React beta docs linked above?

**Comment by ribeiroguilherme** [comment]
Hi @martijnbru ,

Thanks for your input. We updated our react-example by adding React Strict Mode there. Cheers!
