### ISSUE TITLE
Payment can not be done on Samsung and LG smart TV's

### ISSUE THREAD

**Issue by paralichko** [Adyen/adyen-web#1998]
Hello,

I want to refer to issue #1775 - but i can not re-open it.

Something has been changed, because we have complains that the payment can not be done on Tizen 2.3 and Tizen 2.4. Also on LG WebOS < 3.0. When You try to pay, and fill the card data, and press PAY, messages under all fields appears - saying that the fields are empty. This is testes versions 5.28 and 5.33.

Before, when the "force compat" parameter have been implemented - the payment was working OK.

Regards

**Comment by paralichko** [comment]
Hello,

any news on this ?

**Comment by ribeiroguilherme** [comment]
Hi @paralichko ,

Not sure what could have changed in this case.  I am afraid we can't test the issue as we don't have the Tizen OS/LG WebOS that you mentioned above... Is there any way which we can reproduce the issue in a normal laptop?

By your description, seems like the shopper can normally interact with the Card fields, and then when pressing Pay, we display some validation errors which were not supposed to be displayed. Do you have a recording/screenshots of this by any chance?

**Comment by sponglord** [comment]
@paralichko - just to confirm, nothing has changed in `v5.28.0`. We haven't patched it or altered it in any way.
What happens if you downgrade to the version that doesn't require the `forceCompat` config prop (this would be `v5.19.0`)

**Comment by paralichko** [comment]
Hello,

even with 5.19 is not working. Have You made something in the backend ?

Regards

**Comment by sponglord** [comment]
What version of the api are you using? (https://docs.adyen.com/online-payments/release-notes?integration_type=api)

**Comment by paralichko** [comment]
Hello,

we are using [adyen-php-api-library] so we are not declaring API version anywhere.
Those are the calls from the browser to the adyen backend.
![image](https://user-images.githubusercontent.com/10962896/222418095-772a0504-d16b-4397-a67f-1dad87fb3d88.png)

Attached is video - showing the problem

https://user-images.githubusercontent.com/10962896/222418382-3a3ec341-f6e4-4658-bb81-c0bbd6aa96c4.mp4

**Comment by paralichko** [comment]
Any news on this ?

**Comment by sponglord** [comment]
Without any way to recreate this problem it's very hard to debug.
You say this problem still happens if you use v5.33.0? 
The only time we have seen the problem you describe is when the npm version of adyen-web was being used alongside Preact 10.11.1.
But since adyen web v5.28.3 we hardcoded the Preact version to 10.11.2 to avoid this issue [#1809]

**Comment by paralichko** [comment]
I can upload video, if it can help...

https://user-images.githubusercontent.com/10962896/229815532-04770e1f-184d-44c6-b0a2-5e145726fe91.mp4

**Comment by sponglord** [comment]
Can you re-confirm:
- what version of adyen-web you are using
- are you building using npm?
-  and, if so, what version of Preact are you using

**Comment by paralichko** [comment]
We are using those 2 scripts:

<script src="https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/5.33.0/adyen.js"
     integrity="sha384-mPMlkgVUT7jVJZT0sTSfe+M4uN1ArRf1Itg76PcI6Y+zPLDvjCnjmAyyjtak3269"
     crossorigin="anonymous"></script>

<link rel="stylesheet"
     href="https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/5.33.0/adyen.css"
     integrity="sha384-86hqIixzFjIoRoaNYg9pd4mtpn3HtgJmrpYiyTv+3DaGPF70VnRUbtK7MKLTLRd9"
     crossorigin="anonymous">

We are using prebuild version.

With a LG smart TV ( WebOS < 3.0 ) ot Samsung ( Tizen < 3.0 )

Regards

**Comment by sponglord** [comment]
And what version of the adyen-php-api-library are you using?

**Comment by paralichko** [comment]
adyen/php-api-library 10.1.0 A PHP client library for accessing Adyen APIs

**Comment by sponglord** [comment]
In the video, which I've removed because it contains a credit card number, how have the card details been entered?
Manually? Or does the browser have some kind of stored card/autofill?

**Comment by paralichko** [comment]
We have entered it manually, We have tried cookies clear, TV factory defaults, different TV's. It seems that the JS it trying to encode somehow the fields and did not succeed.

**Comment by paralichko** [comment]
We have tried also with php lib 14.0.1 - without success.

Regards

**Comment by paralichko** [comment]
Hello,

if this info can help..

If You put wrong card number into the field - and go to another field - warning that the card number is not valid appears, if the card number is valid - the warning does not appear. So that means that the JS is able to reed the fields...

**Comment by paralichko** [comment]
Hello,

did You have a chance to test this issue ?

regards

**Comment by sponglord** [comment]
Hi, without a Samsung TV running Tizen 2.4, we have no way to test/debug this issue.
If `v5.19.0` doesn't work - at the moment, I don't know what else to suggest

**Comment by sponglord** [comment]
I have asked our Infrastructure team if we: 
- a) have any Samsung TVs...
- b) ...on which I could install/downgrade the OS to Tizen 2.4

If the answer is "no" then I see no way to proceed with this issue

**Comment by sponglord** [comment]
@paralichko - can you tell me how I can use Tizen Studio to recreate this issue?

I would like to be able to Right-Click on my project, select `Run as > Tizen Web Simulator Application (Samsung TV)`
(_or_ `Run as > Tizen Web Simulator Application` ***and know for sure*** that I am simulating Tizen 2.4

Please keep the instruction simple - this is not my usual working environment :-)

**Comment by paralichko** [comment]
Hello,

i am quite sure that you can not simulate it with Tizen Studio. I already tried to make something with LG, in order to see the console - but it doesn't work. The very strange thing, that i found yesterday is, that if i delete some digits, and re-type them, sometimes it accepts the fields. I can not find the pattern... You can help, if You can think of - what is the check if the fields are empty. May be You can make us a version that is not checking if the field are empty and we can try with that. And somehow the backend is involved, because i am sure that it was working with 5.19 and 5.28.2 and stopped by itself. Also You can think if there are any callbacks - where the https certificate was changed.

**Comment by sponglord** [comment]
@paralichko - can you go to this url: https://sponglord--checkout-playground.netlify.app/?allowedpms=[scheme] and tell me if the issue still persists?
(If it does - I have something else I want to try afterwards)

**Comment by paralichko** [comment]
> @paralichko - can you go to this url: [https://sponglord--checkout-playground.netlify.app/?allowedpms=[scheme]](https://sponglord--checkout-playground.netlify.app/?allowedpms=%5Bscheme%5D) and tell me if the issue still persists? (If it does - I have something else I want to try afterwards)

Hello,

here the problem is, that the TV does not recognize the https certificate or the SSL options, but It can not even open https://playground.netlify.app/

Could You give me the .js or the whole project in order to upload it to my webserver ?

Regards

**Comment by sponglord** [comment]
Hi - https://playground.netlify.app/ is not the url I asked you to try.
Can you access https://sponglord--checkout-playground.netlify.app/?allowedpms=[scheme] ?

**Comment by paralichko** [comment]
Yes, i have tried https://sponglord--checkout-playground.netlify.app/?allowedpms=%5Bscheme%5D and the screen remained white.  I noticed the red cross over the padlock in the URL bar - that warns that SSL connection can not be made. After this i tried https://playground.netlify.app/ and was the same - white screen with red cross over the padlock. So i realised that the TV can not make SSL connection to this web server. 
I have had problems with old TV sets and https in the past, so i have spent time to tune the apache SSL algorithms.

So i propose - give me the content of the directory, i will with our web server.

**Comment by sponglord** [comment]
I'm afraid I can't give you a custom build. 
Soon this change will be added to a new release. I'll let you know when that happens and you can test in the normal way

**Comment by sponglord** [comment]
There is a new version, 5.49.4, which uses an updated version of Preact in the code for the securedField iframes. 
Another issue  we were investigating had shown that the previous version of Preact, in some circumstances, wasn't always correctly propagating state; which is what appears to be happening in your case.

Can you please try it?

**Comment by paralichko** [comment]
Hello again,

with this version i can not even select the fields in order to type in them. I [tried](url) with different versions, and seems that with 44 and above, the form is loading very slowly on the TV, and afterwards the fields are unselectable.

https://github.com/Adyen/adyen-web/assets/10962896/20508c1d-3733-42b3-83dd-e7b195442fb2

**Comment by sponglord** [comment]
To me that looks like the fields aren't loading at all...
Does v5.43.1 work ok?
