### ISSUE TITLE
Incorrect typing of BaseElement.data

### ISSUE THREAD

**Issue by onlyann** [Adyen/adyen-web#2012]
**Describe the bug**
The [return type  of BaseElement.data](https://github.com/Adyen/adyen-web/blob/8fad8fc274620d970e427a9a2febd7f555130e1f/packages/lib/src/components/BaseElement.ts#L53) is incorrect. 

**To Reproduce**

N/A

**Expected behavior**

The type should either remain loose or should correctly represent what is being returned.
For instance `RiskData` is not a possible return type given the implementation of that function.

**Additional context**

This typing issue was introduced in #1858 .
While the previous type of `any` was too loose, it wasn't incorrect.

**Comment by ribeiroguilherme** [comment]
Closing this thread as it isn't an issue, as mentioned above.
