### ISSUE TITLE
Card component fails to load in Chrome Incognito while inside an iframe

### ISSUE THREAD

**Issue by joaniehollberg** [Adyen/adyen-web#2020]
**Describe the bug**
- When the Adyen card component is inside an iframe in Chrome incognito, the component fails to load due to an exception trying to access local storage:
<img width="612" alt="Screen Shot 2023-03-06 at 1 09 57 PM" src="https://user-images.githubusercontent.com/52332307/223231469-3baffaf5-14ea-4a09-a7d5-414b1d6218bc.png">

Note that this only occurs in Chrome, whereas private windows in Firefox/Safari don't have this same issue.

**To Reproduce**
Here is a video recording reproducing the bug using the Gitpod version of this repo: https://drive.google.com/file/d/1xswNV1kONdV7x2DGQwHVZaRJKtU7ThNd/view?usp=sharing

1. Run this repo in gitpod
2. Use create react app (or anything else) to locally run an iframe whose source is the gitpod url from step 1
3. In Chrome incognito, run the app with the iframe and try to open the card component.
4. Card component doesn't load and the error is visible in the console.

**Expected behavior**
The Adyen component 

**Screenshots**
See video here: https://drive.google.com/file/d/1xswNV1kONdV7x2DGQwHVZaRJKtU7ThNd/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser - Chrome, incognito window

**Additional context**
We brought up this issue to our onboarding contact from Adyen and were told that embedding the component within an iframe is not a recommended approach. However, our company is an alternative payment method that is used within larger e-commerce ecosystems (like Shopify for example), and in certain flows it is required that our entire app is embedded within an iframe. In general with alternative payment methods it is extremely normal for them to be in embedded iframes, and this is across different ecommerce platforms. We imagine you have other customers that are alternative payment methods that are actually doing this but haven't found this bug because it is a case that they might not be testing (e.g. Chrome incognito specifically). So the thought is that there is a valid argument to support this working for the Adyen component (even if it is discouraged), as there is a definite use case for a subset of your customers.

**Comment by sponglord** [comment]
@joaniehollberg - we will fix this in an upcoming release

**Comment by joaniehollberg** [comment]
@sponglord thank you so so much & really appreciate the quick turn around time on this!

**Comment by sponglord** [comment]
A fix for this, #2028, will be in the next release (`v5.36.0`)
