### ISSUE TITLE
3DS input window not added

### ISSUE THREAD

**Issue by olrandir** [Adyen/adyen-web#2023]
**Describe the bug**
So after an upgrade on our project to nextJS 12, we realised 3DS basically stopped working. It's triggered by the code but the window where the 3DS input should appear is never added to the DOM.

There's an error logged from inside the Adyen library: 

> TypeError Invalid attempt to destructure non-iterable instance.
> In order to be iterable, non-array objects must have a [Symbol.iterator]() method. 

This appears to be happening in code belonging to the Adyen library, not on our side, and it's therefore quite hard for us to debug the cause of it.

**To Reproduce**

1. This is [reproducible on one of our test environments](https://frontend-uk-nextjs-git-investigate3ds-manualco.vercel.app/) with a 3DS test card
2. Go to [/hair-loss/power-shampoo](https://frontend-uk-nextjs-git-investigate3ds-manualco.vercel.app/hair-loss/power-shampoo), click "choose your plan", select any of the power-shampoo options (you can ignore other products on the page) and click "start assessment" on it (to be clear, the problem appears for all products, but the other ones require a questionnaire to be answered, so it's simpler to test with the shampoo product)
3. Open cart in top right, click "start assessment"
4. In checkout, you'll need to register and add an address before you can get to payment step (you can use this UK postcode if it helps: SE1 4GT)
5. In payment, use one of the 3DS test cards, eg 4917 6100 0000 0000, exp 03/2030, cvc 737
6. A pop-up modal appears, where the 3DS challenge is supposed to show, yet the modal is never updated with the 3DS iframe, and the `<div#my-container-adyen>` that's supposed to contain it is left empty.

**Expected behavior**
A pop-up modal should open with the 3DS challenge, the user should be able to complete that and send their order.

**Screenshots**
![Screenshot from 2023-03-07 17-15-24](https://user-images.githubusercontent.com/584213/223465587-983f492f-2fd3-454b-b0da-b46dfad0879b.png)
![Screenshot from 2023-03-07 17-15-53](https://user-images.githubusercontent.com/584213/223465607-66211817-b5db-4eb7-9055-d33f53065eff.png)
![Screenshot from 2023-03-07 17-19-53](https://user-images.githubusercontent.com/584213/223465936-ead6f375-48e1-4c98-97cd-c4822710f10a.png)

**Desktop (please complete the following information):**
 - happens cross-browser and OS

**Smartphone (please complete the following information):**
 - happens cross-browser and OS

**Additional context**
To be clear, this was all working as expected before the nextJS upgrade, and is working after we reverted the change.

**Comment by olrandir** [comment]
Did some quick testing with that fix and it appears to work! Will report back when QA have done their part but this looks promising, thanks

**Comment by olrandir** [comment]
Update: we've done quite thorough QA on this and are confident it works now. Thanks for pointing us to the fix!

For reference: the fix was to remove `swcMinify: true` from the nextjs.config.js file, it appears the new minifier is messing up the library somehow.

**Comment by sponglord** [comment]
@olrandir Thanks for the update and glad it's fixed!
