### ISSUE TITLE
Paypal Popup when beforeSubmit action is rejected

### ISSUE THREAD

**Issue by antonkarsten** [Adyen/adyen-web#2025]
**Describe the bug**

Im using version 5.35.0 of the SDK and am using the Drop In integration

I have the following in my AdyenCheckout Configuration

```
beforeSubmit: (data, component, actions) => {
     actions.reject();
}
```

But when I click the Paypal button, the Pop up window still comes up. When I put a breakpoint inside the `beforeSubmit` and wait a little moment before resuming this doesnt happen.

On all the other payment methods so far I have not had problems.

**Expected behavior**
I expect nothing to happen. As if I hadnt clicked the button. That would be my understanding of `actions.reject();`

**Screenshots**
![paypal button](https://user-images.githubusercontent.com/4773313/223711789-6af156e2-1e09-46ca-bee7-66ad30bfd1a2.png)

Im clicking the yellow button

Is there something that I am missing

**Comment by ribeiroguilherme** [comment]
Hey @antonkarsten ,

You are right - `beforeSubmit` does not work well with the PayPal flow.  What happens is that when PayPal button is clicked, we trigger the [createOrder](https://developer.paypal.com/sdk/js/reference/#link-createorder) which opens the pop-up, and we can't actually close it.

Perhaps we could rethink this flow at some point, but that would require a rework in the PayPal component and likely it will be a breaking change. 

If you want to close the pop-up before doing the 'submit', you can rely on the PayPal `onClick` event. That will close the pop-up and it won't trigger the 'submit' flow.

Ex:
```js
onClick(data, actions): {
   return actions.reject();
}
```

I hope it helps! Thanks!
