### ISSUE TITLE
Allow non-English numbers to be used in the credit card fields

### ISSUE THREAD

**Issue by Baha-mumzwolrd** [Adyen/adyen-web#2035]
I'm using the drop-in component for the credit card payment method, the form renders fine, but the input doesn't allow non-English numbers (Arabic, for example) to be entered in the card number field or other card details fields. The question is if there is any config or props that should be passed or if, by any chance, we can customize the input behavior. Or if we can convert Arabic numbers to English when the user starts typing Arabic numbers

**Screenshots**

https://user-images.githubusercontent.com/118981469/224986378-34021ea6-e4d4-4ee1-b683-25dfa5b80d57.mov

**Comment by sponglord** [comment]
Hi @Baha-mumzwolrd - thanks for raising this issue.

Back when we worked on RTL (right-to-left) text in our components - the consensus was that all cards around the world used "English" numbers.
We also talked to some colleagues from Arabic countries and they all agreed that the expectation was to write card info just as we do in Europe, and also in the LTR direction.

For this reason there is no config or inbuilt conversion mechanism that would allow the user to enter Arabic numbers.

However, I have asked posed this question again to our Card Payment Methods team - and will let you know if there has been any change in our policy.

**Comment by Baha-mumzwolrd** [comment]
@sponglord Thanks for your response. It makes sense to use English numbers in the form, but if the user is using an Arabic keyboard, in this case, if we can convert the entered numbers from Arabic to English instead of not rendering anything in the input field, that would be great.

**Comment by sponglord** [comment]
Hi @Baha-mumzwolrd - at this point in time we don't want to spend time building an Arabic to English number converter.
If you wanted to build such a thing yourself and then create a PR we would happily consider it for inclusion in our repo.
