### ISSUE TITLE
Hardcoded `showImage: false` for Online banking Czech Republic `onlineBanking_CZ`

### ISSUE THREAD

**Issue by theazgra** [Adyen/adyen-web#2052]
**Describe the bug**
There is a hardcoded option In the [OnlineBankingCZElement](packages/lib/src/components/OnlineBankingCZ/index.ts) component to not show bank logos.

**To Reproduce**
1. Use onlineBanking_CZ Web Component
2. Set `showImage` to `true`
3. Open select box
4. There are no bank logos

**Expected behavior**
Bank logos are visible on the left side of the list item.

**Screenshots**
![image](https://user-images.githubusercontent.com/18343952/226331595-48681d0a-8649-4dd8-b763-88da4aa5aa71.png)

**Desktop (please complete the following information):**
- All versions

**Comment by m1aw** [comment]
Hello @theazgra 

This is deliberate as images are not available to us. I have forwarded your request to the product team.

Thanks

**Comment by theazgra** [comment]
@m1aw Hi,

thanks for contacting the product team. :)

**Comment by ribeiroguilherme** [comment]
As mentioned, we already reached out to the product team to request this feature, but that might take some time still. Anyway, keep an eye on the release notes. Once the logos are available, we will release a new version mentioning that. Cheers!
