### ISSUE TITLE
ApplePay Required field 'merchantIdentifier' is null

### ISSUE THREAD

**Issue by tarach** [Adyen/adyen-web#2073]
I've setup the playground on a server with letsencrypt ssl certificate and I'm trying to make a payment via Apple Pay.

Unfortunately on a request via `POST` to `https://checkoutshopper-test.adyen.com/checkoutshopper/v1/applePay/sessions?clientKey=test_CEPL7TOKNNDJXP2X6WPWONFQTEE76ZHF`
I'm getting 500 status code with following response payload.
```
{
    "status": 500,
    "errorCode": "702",
    "message": "Required field 'merchantIdentifier' is null",
    "errorType": "validation"
}
```

**Comment by ribeiroguilherme** [comment]
Hey @tarach .

Did you reach out to the Adyen support team? It seems to me that something can be misconfigured with your Merchant account. They might be able to help you out.

**Comment by tarach** [comment]
Hey @ribeiroguilherme,
Yes I did reach out to support team. It is definitely likely something is misconfigured but:

Drop-in form does work ie. it does make a successful `POST /applePay/sessions` request 
But the Component implementation via Wallets section does not.

Feel free to check it yourself:
https://adyendemo.tarach.net/
Basic Auth:
    - user: adyen
    - pass: 123456
