### ISSUE TITLE
Issue with displaying stored payment information for cards

### ISSUE THREAD

**Issue by Loktor** [Adyen/adyen-web#208]
**Describe the bug**
It is no longer possible with the newest api to display stored card informations correctly.

The issue is the following one, the call to https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v53/post/paymentMethods returns the following result (reducted to relevant part):

```
{
  ....
  "storedPaymentMethods": [
    {
      ....
      "id": "8315980248.....",
      ....
      "type": "scheme"
    }
  ]
}
```

The adyen web components are expecting the following format to work tho:

```
{
  ....
  "storedPaymentMethods": [
    {
      ....
      "storedPaymentMethodId": "8315980248.....",
      ....
      "type": "scheme"
    }
  ]
}
```

So by using the newest api with the adyen components it is no longer possible without replacing the raw id with the storedPaymentMethodId to get the stored payment method properly displayed. Passing the information in the raw format is actually defined in the documentation here: https://docs.adyen.com/payment-methods/cards/web-component#show-a-stored-card-in-your-payment-form

**To Reproduce**
1. Inititialize a checkout via the following code and use the exact response you get for the request from with a shopperId https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v53/post/paymentMethods
```
if (paymentMethodsResponse != null && paymentMethodsResponse.storedPaymentMethods.length > 0) {
        const storedPaymentMethod = paymentMethodsResponse.storedPaymentMethods[0];
        const oneClick = checkout.create('card', storedPaymentMethod).mount('#component-container-one-click');
}
```
2. The user has to enter the credit card data again

**Expected behavior**
1. Initialize request as mentioned above
2. User only has to enter the cvc from the stored payment method again

**Screenshots**

Expected result:

![image](https://user-images.githubusercontent.com/490061/90916140-db523a00-e3e0-11ea-89ec-a9de0d61103e.png)

Actual result:

![image](https://user-images.githubusercontent.com/490061/90916195-ee650a00-e3e0-11ea-9d77-1500ab97d7f4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

Hope i have written down the issue clear enough. :)

best regards,
David

**Comment by marcperez** [comment]
Hi @Loktor,

In the case of stored payment methods, we process that response data when initializing a new checkout instance.
Here you can find the detailed steps: https://docs.adyen.com/payment-methods/cards/web-component#show-a-stored-card-in-your-payment-form

These are the key points:

> When creating an instance of the AdyenCheckout, pass the full /paymentMethods response to the paymentMethodsResponse object
 ```
const storedPaymentMethod = checkout.paymentMethodsResponse.storedPaymentMethods[0]; // This comes from the main instance, not the raw response itself
const card = checkout.create("card", storedPaymentMethod).mount("#stored-card");
```

Hope this helps!

**Comment by Loktor** [comment]
Thx for clarifying that i must have overlooked that part 👍

**Comment by denic** [comment]
Hey guys,

I am suffering from the same behavior. I do what is described in the documentation and what was said here it renders the regular form but adds the card holder name.

When I replace the `id` property name with the `storedPaymentMethodId` name the form behaves as expected.

I am using version 3.18.1 of the Adyen Web SDK (`https://checkoutshopper-test.adyen.com/checkoutshopper/sdk/3.18.1/adyen.js`)

**Comment by marcperez** [comment]
Hi @denic, 

Could you double check that you are using the processed paymentMethodsResponse in the `AdyenCheckout` instance to create the component? 

```
const storedPaymentMethod = checkout.paymentMethodsResponse.storedPaymentMethods[0]; // This comes from the main instance, not the raw response itself
const card = checkout.create("card", storedPaymentMethod).mount("#stored-card");
```

It seems to work on our end. If the problem persists I'd advise you to [contact our support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) so they can better help you with your integration.

Hope this helps!

**Comment by denic** [comment]
Oh boi, you are right! I missed the part about getting the data from the AdyenCheckout instance.

Sorry for the confusion and have a nice weekend.

**Comment by marcperez** [comment]
Hi @denic, happy it's all working for you now!
