### ISSUE TITLE
Failed Apple Pay payment via Drop-in

### ISSUE THREAD

**Issue by tarach** [Adyen/adyen-web#2082]
I cannot make a test payment via Apple Pay Drop-in method. 
And via Wallets Component ( after resolving issue: https://github.com/Adyen/adyen-web/issues/2073 )

In both cases I'm trying to use normal VISA and I've seen in tests that actually a Mastercard payment went through https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=NGDTJJN49DQ2WN82&txType=Payment

The error message says: "Apple Pay Is Not Available For This Website" and disappears very fast. ( Had to record the screen to be able to see it ) 

App: Adyen Demo App https://github.com/Adyen/adyen-web
Account: Miinto242ECOM
Website: https://adyendemo.tarach.net/
Access:
   - user: adyen
   - pass: 123456

P.S. Issue was also reported to support and assigned ticked id [3761445](https://www.adyen.help/hc/en-us/requests/3761445)

Thanks

![image (1)](https://user-images.githubusercontent.com/351514/229148587-2b23adea-2ff4-4ee0-9d2d-8c150f5eff19.png)

**Comment by ribeiroguilherme** [comment]
@tarach I just tried again and the payment worked fine for me. I used an iOS test device that I have here, which has configured an Apple account with test cards. I opened your app in Safari browser, and then performed the payment.

**Comment by ribeiroguilherme** [comment]
Hi @tarach, can you please reach out to support to check this? It seems like your testing account isn't configured properly or some configuration is missing on your side. The payment is working fine for me and on the provided test environment. Cheers
