### ISSUE TITLE
Paypal component not refreshing changed currency and fails on submit

### ISSUE THREAD

**Issue by almirakrdzic1991** [Adyen/adyen-web#210]
I have form with country selector and paypal smart button.
Change of the country will cause change of the currency and price.

I have written to the support and they said to umount and mount the component again to refresh the currency, so I did that.
Here is my code for it:
```
    onPlanChanged() {
      this.mountedPaypal.unmount();
      this.$nextTick(() => {
        this.mountPaypal();
      });
    },
    mountPaypal() {
      this.mountedPaypal = this.checkout
        .create("paypal", {
          environment: "test",
          countryCode: this.plan.country,
          amount: {
            currency: this.plan.currency,
            value: this.plan.price,
          },
          merchantId: "***",
          onSubmit: (data, component) => {
            data.handleAction = (action) => {
              component.handleAction(action);
            };
            this.$emit("submit", data);
          },
        })
        .mount(".pm-paypal-action");
    },
```

If currency is changed and button clicked, UI tries to open the paypal secure browser and then fails with error:
`Expected currency from order api call to be EUR, got USD. Please ensure you are passing currency=USD to the sdk url.`

Do I maybe need to wait for some amount of time between unmount and remount of the component or it is some other issue.

Note: when button is submitted we are sending the data to our api where latest plan with latest currency is used and they return us the action needed.

**To Reproduce**
1. Mount paypal component with some currency variable have "EUR" value
2. Change currency variable from "EUR" to "USD"
3. Unmount existing paypal component
4. Create and mount new paypal component with "USD" currency
5. Submit button and do api call to get the action
6. Provide action to mounted paypal component
7. You will get error `Expected currency from order api call to be EUR, got USD. Please ensure you are passing currency=USD to the sdk url.`

**Expected behavior**
Paypal component should open the secure browser with the USD currency plan

**Screenshots**
 - OS: MacOS (Catalina)
 - Browser: Chrome 83

<img width="502" alt="Screenshot 2020-08-24 at 11 06 08" src="https://user-images.githubusercontent.com/52447893/91025754-17acb280-e5fa-11ea-9518-6c3c5b0a7488.png">

**Additional context**
Version: checkoutshopper/sdk/3.11.0

**Comment by pabloai** [comment]
Hi @almirakrdzic1991,

Thanks for such a complete report.
We were able to fix the issue and it will be included in our next release.

Cheers.

**Comment by pabloai** [comment]
Closing issue, let us know if we can help with anything else. Cheers!
