### ISSUE TITLE
Typescript definition for create always returns InstanceType<PaymentMethods['redirect']>

### ISSUE THREAD

**Issue by brendanoffer** [Adyen/adyen-web#2100]
**Describe the bug**

Typescript definition for `Core`'s create methods are incorrect. https://github.com/Adyen/adyen-web/pull/1566 introduced a fallback however this typescript interface will be used for all calls using a string paymentMethod paramter.

**To Reproduce**
1. Use typescript
2. Follow https://docs.adyen.com/payment-methods/apple-pay/web-component documentation for adding a Apple Pay web component
3. When `const applePayComponent = checkout.create('applepay', applePayConfiguration);` is called it returns a type `InstanceType<PaymentMethods['redirect']>`
4. See error `Type error: Property 'isAvailable' does not exist on type 'RedirectElement'.` 

**Expected behavior**

Apple Pay Component or `InstanceType<PaymentMethods[T]>` type is returned from `.create`

**Comment by obouchari** [comment]
I have had the same issue but it turned out if somehow the configuration you pass in doesn't match what "applepay" expect it will return a Redirect type.

**Comment by dprcoles** [comment]
Hey @brendanoffer, I recently ran into the same issue. It looks like `totalPriceLabel` is a required property on the [`ApplePayElementProps`](https://github.com/Adyen/adyen-web/blob/cc7aa40e89d46ce9b121c63576190a4b62faae4b/packages/lib/src/components/ApplePay/types.ts#L51) type, which is the type that needs to be passed in to the `options` parameter of the `checkout.create()` method for it to return the expected `ApplePayElement` type.

If you change your call to `const applePayComponent = checkout.create<'applepay'>('applepay', applePayConfiguration);` you should see a typescript error flagging this.

**Comment by ribeiroguilherme** [comment]
Hi @brendanoffer ,

@dprcoles made a fix for this issue, and it should be available on 5.43.0 onwards. Thanks for reporting it. Cheers!
