### ISSUE TITLE
Security issues in automated testing scenario

### ISSUE THREAD

**Issue by rapidfixer** [Adyen/adyen-web#2112]
I'm trying to do end-to-end testing regarding adyen payments using Cypress. However, due to cross-origin iframe rules, i am not able to enter test payment data to Dropin, cause access to iframe with actual input from parent document is not permitted by browser. 

If i disable security checks in Chrome (_--disable-web-security_ flag), then iframes are indeed available, but Dropin reports incorrect configuration, as in the case when CLIENT_KEY is not correct.

What is supposed way to deal with it? 
Is it possible to somehow disable security for testing environment?

**Comment by ribeiroguilherme** [comment]
Hi @rapidfixer ,

I am not familiar with Cypress, but we do use Testcafe and Playwright for our tests, and we have many tests testing the Card fields. We didn't have to disable any security flags as far as I know.

You can take a look in our repository in the folders `packages/e2e` and `packages/e2e-playwright` . It might shed some light into your use case.

Cheers!
