### ISSUE TITLE
PayPal Error - No Token Was Provided

### ISSUE THREAD

**Issue by bsulliva** [Adyen/adyen-web#2113]
Hello, I'm adding PayPal to our site using web components v3.7, using the documentation listed here: https://docs.adyen.com/payment-methods/paypal/web-component

When I click on the Smart PayPal button, my request to /payments is sent.

My request body:
`{"channel":"Web","shopperInteraction":"Ecommerce","additionalData":{"RequestedTestAcquirerResponseCode":null},"amount":{"currency":"USD","value":969},"applicationInfo":{"adyenLibrary":{"name":"adyen-dotnet-api-library","version":"5.2.0"}},"billingAddress":{"city":"Fort Worth","country":"US","houseNumberOrName":"NA","postalCode":"76102","stateOrProvince":"TX","street":"1000 N Main"},"browserInfo":{"acceptHeader":"application/json, text/javascript, */*; q=0.01","colorDepth":24,"javaEnabled":false,"language":"en-US","screenHeight":720,"screenWidth":1280,"timeZoneOffset":300,"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.39","javaScriptEnabled":true},"countryCode":"US","deliveryAddress":{"city":"Mansfield","country":"US","houseNumberOrName":"NA","postalCode":"76063","stateOrProvince":"TX","street":"1000 N Main"},"merchantAccount":"MouserEmea","paymentMethod":{"type":"paypal"},"reference":"A638170112439857584","returnUrl":"https://www.mouserdev.com:44333/myaccount/verifyadyenredirectresponse","shopperEmail":"barry.sullivan@mouser.com","shopperIP":"127.0.0.1","shopperReference":"884680","telephoneNumber":"817-804-3587"}`

My response body:
`{"resultCode":"RedirectShopper","details":[{"key":"payload","type":"text"}],"paymentData":"Ab02b4c0!BQABAgBw+MSYEK3S8F9H0yt8v4QKz8PhhIqdv9528eySuN/Q5KWPSg7BxoOIuOTVEnZbOSRrC1De82AVHcXOPm1+RLVWiRdZDp60TpxRbJhBdBskQGd4xnc8hTZ9Tcx4ZiNBWa4SrgrAso8L6NY6+cYdWgMxSBIGyee7DKxS/U3i5WH3x+IgadhMZxLiTfJfJZINwcjkcnpxsdSUF7isxoSL02SNd67tN0qgR/iVCF3Y7F6k0slz5a7sJLzFUE3J3uENe4UolwvLZs+K+9BOE1qERG/o8v8XUPgAG1GzRq0zCIV78WfgarKXy5xxzBKaGakaMdmL+rc1IMQMSE4CN3tx1/euzN190xNyS8X2HCTFycrimIgz9wkev7olV5WZzYfs2h6jsmbLhQ6F5Jx+UPW9udCrBfxVl2SRqKC/UQJG7yWqAHqhQ29aS2fUEdPIHv76zbZ+uxWwLvy8dk1U7ZLkBrX0hcsxOUWCoKnt6nM3NCuBZUWw/viFPiE6vaWe96s51wnEkbH7021eOckvYTuxBBONxxsbeSm3iqdyx1r/KWXT3OZWX6vRXvzzAlcovs/5n0TzbvvUBOIgj6nZ5o6Yp3yp6LMP0KkG57O8RqHLa2Zy8YhFhI5la7JwZANsnYqAfJO3F2HxHgikzYRLMMrQwYdyuwJPTK21U8SK+qZ/6DrgRwwR0o5VquWoWGHIMAQASnsia2V5IjoiQUYwQUFBMTAzQ0E1MzdFQUVEODdDMjRERDUzOTA5QjgwQTc4QTkyM0UzODIzRDY4REFDQzk0QjlGRjgzMDVEQyJ9OF5R99O//ZZ2gyvKF4T+FnGe0UoTEvGjQ1fila4F7BSbx7MZ6mktgfpse0DDUj2vUpwj9l6EBO1NjRRk3v66Kt/IOU+0n4z169288CM5r7Nkhyqa8g/w02WdMflRJvjMCBB3+pFkm4wPuR0rMDZnRHA34TFlF3jNTB39c7MHaRi25IJ4lHTciSBOWSlgDvnNjPOJXZagi1qlEmWkHkCYCGSANkMsbWHF2r7RP5CkNrtB77VX3H8zRvdUBdizwxWRg5hNYYnRNIii9QJNsdJRO6ZXARHdXjlEORXuci3NaRuW+K86f1ZLCGQ+mU2xXFsWn6B8pLFZXnbOD8xvUC1m8Oom1yoy2OqlBZXKmEj56D0wUOvb+YQTKVRnxetzefmS9e/qH9KNjUv9hDY5vBYW8cYzuQtl782eAEvOkk76OxWIa/o3g+MFjj5suc4uhW+ZYcFCQNTj8XOTKhVEXSMTyMb6dVUYjrgendFYZbWr0Z1Ww5HPa1z688bpSItjRNlkwoFoOPTYrlFIiXfLB4wDDyThoO3C/Sg+/cchpo5GRLpwaOispnvAHNJolm70hXa8rndVJCDGbVu014lo2caJAOFcDJj17JoSCm15GSwBPRFfjDqS29lnjIOv9zIVU7gT3LYhs7M8y6Ywfo02mvo+0xPZ8Ha1t4VYLWfBnmXzOi7tp8jhVuaascZoJt9KMjFQqJNCDeTsCyt/+/re1Q/nFJKM43r4RAIet9JlUKhKUyxEWA78gqWRvQEU4CRK/RvTFPulBgF8FnTqh/VDdLKNmZ7HqpLdtFI+3wgR2wC7jU0E3CIanxYdAiqBvLP+qdqrVIkEs/griVgRWpWVw1zv39BBR6lfu9gfuLpEYg8qiHb6bcC0YOHf3zaYOOi7zbOOiMdcrJAfl7a51Nn8Xkpx74FvwH4U2Y0zJBgu39vqs9QJm1DGZAm5IPuKaNJuLnRVnKrvKZJXqaKQqtVsGc/gnU9wfxI7fGmrdTc+7ircDf9GOEHPy7pRir0ASBmsA12sLCimucHQHKRVyEi2e3PulVVvjCb5l6DOqlylXsDCtxoCU0Buxudu50ymDhEjXyps4XUKpv6JrqmngH9Xy7/7xhk1vukc9wRUN7c7XKxCzXDA3DYnMEexzN4kFr0vDgWl7iSSLsImTlGIyQ1mYOZP4DasfWXlPpxIcVb4S1kfwFMcSTxY/lhCIortrn7zk8NCcCWlsPM3kjw5LRpvLSAebUJhWnUqCldNUbUk0ggmblwh4HGGo0DSXBoGuXiDtOCf9npWklUue+rIanigaouLxLt5rBcPy/z9oXhBwOUYA9cz8JORVAfO6KyKtrjpLhUtjofz4ggKV7+/NUC3szpXfLI3vCjJZdRLtM+/Q0KleB+dGb+7IXhLes5y2KbJyzv6Q1gk6TxN72OlZcgjY/yew00CMsBBMLWYz+XmiCNTEICa87dhPvwMl+bfsa72oadgYjxlHcUk9O6pyy+ScVvy7WtvTmmz35K2F1tuCMUUpz5nh0G1sOutKCAnXpedTAwVdbR+T46aObJCdp93mMlYvxUrsCsb+OpxA2SADrH9L205c4EPAWw9ETJS+8G/gJNDamlW90Nj2UsvWLU6mXJY+awHJVLAL+0e3Wjn0OCJ7Y36v6LqfZloZ2iDu1TYD44MEw+1nizRyxZ9IcaKDx/wGN4rCHUrK4t1mB/s4qR4saDOM4r8xInXpOWVeQg5aVQBYKYlmA6bz6u/+EbrSWwIaEyEEOramxFnH4UXARTyuWXxiwTVLDGz9fqC5ZkNSogtHpczJ2mny2MibyKbpiZo9BDQ/u1dclcVh9WrtgywapNmBlUaKYs0rjA25vzoG+QjEfBvAuk0g2bgGA16R0B7C0huK2QEgV/4fUmuERkGLvBwJbWYVUrR+A==","redirect":{"method":"GET","url":"https://test.adyen.com/hpp/checkout.shtml?u=redirectPayPal&p=eJxtVF1zojAU-TX60oHhW3zIgyt*rfVjrNrOvnQiXDUtJDQELPvr94LYbtUZJgP3nMRzzz2RpmnMQqqY4BO*F3rMdpLKck4TIDQqgWuRUByURlOmNWCb3t*0BZlhibi6pRvtHYtjxg*9KJKQZXrIVEmGQqqHZ1yON7DIuZIl2TxdI0eRZzDPkx3Ihax1zXvXnFRkisZ9EQHpeKZhXeOIKljIpRQF4yGQ9cstQwIoYhqG8TB-mFHGrxjrMgWCB0vKo-qHUlqmNG43wusSig9zKYGHl**gHUHMCpDlDx9mlGd7BnF0C3-7cA3dNeKa9MMJw7NvCHesuKXceHFFacxIQIZHylUvrGWTWaVQDhKgX9CEKzjIOiq6qnb1x4P*dLFZv44G88Fq0r-LLC5JMr-gFeyhchZIz7N9s2OYpuXYXd-tuL7zH0vlkgdUUbLc9oPRaOY-PgfW89z-VvvEDgSMebCz3mTLGnZC4f1mHbX4*PwYjkbrYOmYUajK-nSY26seMsaHlh20cd4JYK9J3WrX67YlVNPGiPQFzoyGiqwG-c1qNZmPEEuBKk1wTbEERK7InsYZYD3brB7JUak0a9nV6fiERwjfkZMdRZqC1BRkSq9vH*YhuSVgBX0uWAgZvi7PwiYcuShmBRFDZQqRwsQlFiGNG84M1FFELXt4NTns73t2LcuTtY0oFIGzVMutxLqVXFxOp5Oe1BsiKM4aEXcc27ZrPClpc3D1hdNk*7LuRzbi0IZUcPQjwzThpLc0ZlF1MyzDsjXD0Ux7bRlokO3gYjh-2k3ruoIY0qPgzU0gGAXNxw2263cupEFCWUx2VMpSz3K8xQXlLcc4K67kXohV5qrBVVkbYL2yBS7gd*J83-F841Jvwp*9M37*I8h3emHpvmG6tuu5XbdjWV3L0MV682luu9H09S8Ey5FHx28vYjweF8-TT22idq*D7SFeTH4Fyekf-V74iA"},"action":{"type":"redirect","method":"GET","paymentData":"Ab02b4c0!BQABAgBw+MSYEK3S8F9H0yt8v4QKz8PhhIqdv9528eySuN/Q5KWPSg7BxoOIuOTVEnZbOSRrC1De82AVHcXOPm1+RLVWiRdZDp60TpxRbJhBdBskQGd4xnc8hTZ9Tcx4ZiNBWa4SrgrAso8L6NY6+cYdWgMxSBIGyee7DKxS/U3i5WH3x+IgadhMZxLiTfJfJZINwcjkcnpxsdSUF7isxoSL02SNd67tN0qgR/iVCF3Y7F6k0slz5a7sJLzFUE3J3uENe4UolwvLZs+K+9BOE1qERG/o8v8XUPgAG1GzRq0zCIV78WfgarKXy5xxzBKaGakaMdmL+rc1IMQMSE4CN3tx1/euzN190xNyS8X2HCTFycrimIgz9wkev7olV5WZzYfs2h6jsmbLhQ6F5Jx+UPW9udCrBfxVl2SRqKC/UQJG7yWqAHqhQ29aS2fUEdPIHv76zbZ+uxWwLvy8dk1U7ZLkBrX0hcsxOUWCoKnt6nM3NCuBZUWw/viFPiE6vaWe96s51wnEkbH7021eOckvYTuxBBONxxsbeSm3iqdyx1r/KWXT3OZWX6vRXvzzAlcovs/5n0TzbvvUBOIgj6nZ5o6Yp3yp6LMP0KkG57O8RqHLa2Zy8YhFhI5la7JwZANsnYqAfJO3F2HxHgikzYRLMMrQwYdyuwJPTK21U8SK+qZ/6DrgRwwR0o5VquWoWGHIMAQASnsia2V5IjoiQUYwQUFBMTAzQ0E1MzdFQUVEODdDMjRERDUzOTA5QjgwQTc4QTkyM0UzODIzRDY4REFDQzk0QjlGRjgzMDVEQyJ9OF5R99O//ZZ2gyvKF4T+FnGe0UoTEvGjQ1fila4F7BSbx7MZ6mktgfpse0DDUj2vUpwj9l6EBO1NjRRk3v66Kt/IOU+0n4z169288CM5r7Nkhyqa8g/w02WdMflRJvjMCBB3+pFkm4wPuR0rMDZnRHA34TFlF3jNTB39c7MHaRi25IJ4lHTciSBOWSlgDvnNjPOJXZagi1qlEmWkHkCYCGSANkMsbWHF2r7RP5CkNrtB77VX3H8zRvdUBdizwxWRg5hNYYnRNIii9QJNsdJRO6ZXARHdXjlEORXuci3NaRuW+K86f1ZLCGQ+mU2xXFsWn6B8pLFZXnbOD8xvUC1m8Oom1yoy2OqlBZXKmEj56D0wUOvb+YQTKVRnxetzefmS9e/qH9KNjUv9hDY5vBYW8cYzuQtl782eAEvOkk76OxWIa/o3g+MFjj5suc4uhW+ZYcFCQNTj8XOTKhVEXSMTyMb6dVUYjrgendFYZbWr0Z1Ww5HPa1z688bpSItjRNlkwoFoOPTYrlFIiXfLB4wDDyThoO3C/Sg+/cchpo5GRLpwaOispnvAHNJolm70hXa8rndVJCDGbVu014lo2caJAOFcDJj17JoSCm15GSwBPRFfjDqS29lnjIOv9zIVU7gT3LYhs7M8y6Ywfo02mvo+0xPZ8Ha1t4VYLWfBnmXzOi7tp8jhVuaascZoJt9KMjFQqJNCDeTsCyt/+/re1Q/nFJKM43r4RAIet9JlUKhKUyxEWA78gqWRvQEU4CRK/RvTFPulBgF8FnTqh/VDdLKNmZ7HqpLdtFI+3wgR2wC7jU0E3CIanxYdAiqBvLP+qdqrVIkEs/griVgRWpWVw1zv39BBR6lfu9gfuLpEYg8qiHb6bcC0YOHf3zaYOOi7zbOOiMdcrJAfl7a51Nn8Xkpx74FvwH4U2Y0zJBgu39vqs9QJm1DGZAm5IPuKaNJuLnRVnKrvKZJXqaKQqtVsGc/gnU9wfxI7fGmrdTc+7ircDf9GOEHPy7pRir0ASBmsA12sLCimucHQHKRVyEi2e3PulVVvjCb5l6DOqlylXsDCtxoCU0Buxudu50ymDhEjXyps4XUKpv6JrqmngH9Xy7/7xhk1vukc9wRUN7c7XKxCzXDA3DYnMEexzN4kFr0vDgWl7iSSLsImTlGIyQ1mYOZP4DasfWXlPpxIcVb4S1kfwFMcSTxY/lhCIortrn7zk8NCcCWlsPM3kjw5LRpvLSAebUJhWnUqCldNUbUk0ggmblwh4HGGo0DSXBoGuXiDtOCf9npWklUue+rIanigaouLxLt5rBcPy/z9oXhBwOUYA9cz8JORVAfO6KyKtrjpLhUtjofz4ggKV7+/NUC3szpXfLI3vCjJZdRLtM+/Q0KleB+dGb+7IXhLes5y2KbJyzv6Q1gk6TxN72OlZcgjY/yew00CMsBBMLWYz+XmiCNTEICa87dhPvwMl+bfsa72oadgYjxlHcUk9O6pyy+ScVvy7WtvTmmz35K2F1tuCMUUpz5nh0G1sOutKCAnXpedTAwVdbR+T46aObJCdp93mMlYvxUrsCsb+OpxA2SADrH9L205c4EPAWw9ETJS+8G/gJNDamlW90Nj2UsvWLU6mXJY+awHJVLAL+0e3Wjn0OCJ7Y36v6LqfZloZ2iDu1TYD44MEw+1nizRyxZ9IcaKDx/wGN4rCHUrK4t1mB/s4qR4saDOM4r8xInXpOWVeQg5aVQBYKYlmA6bz6u/+EbrSWwIaEyEEOramxFnH4UXARTyuWXxiwTVLDGz9fqC5ZkNSogtHpczJ2mny2MibyKbpiZo9BDQ/u1dclcVh9WrtgywapNmBlUaKYs0rjA25vzoG+QjEfBvAuk0g2bgGA16R0B7C0huK2QEgV/4fUmuERkGLvBwJbWYVUrR+A==","paymentMethodType":"paypal","url":"https://test.adyen.com/hpp/checkout.shtml?u=redirectPayPal&p=eJxtVF1zojAU-TX60oHhW3zIgyt*rfVjrNrOvnQiXDUtJDQELPvr94LYbtUZJgP3nMRzzz2RpmnMQqqY4BO*F3rMdpLKck4TIDQqgWuRUByURlOmNWCb3t*0BZlhibi6pRvtHYtjxg*9KJKQZXrIVEmGQqqHZ1yON7DIuZIl2TxdI0eRZzDPkx3Ihax1zXvXnFRkisZ9EQHpeKZhXeOIKljIpRQF4yGQ9cstQwIoYhqG8TB-mFHGrxjrMgWCB0vKo-qHUlqmNG43wusSig9zKYGHl**gHUHMCpDlDx9mlGd7BnF0C3-7cA3dNeKa9MMJw7NvCHesuKXceHFFacxIQIZHylUvrGWTWaVQDhKgX9CEKzjIOiq6qnb1x4P*dLFZv44G88Fq0r-LLC5JMr-gFeyhchZIz7N9s2OYpuXYXd-tuL7zH0vlkgdUUbLc9oPRaOY-PgfW89z-VvvEDgSMebCz3mTLGnZC4f1mHbX4*PwYjkbrYOmYUajK-nSY26seMsaHlh20cd4JYK9J3WrX67YlVNPGiPQFzoyGiqwG-c1qNZmPEEuBKk1wTbEERK7InsYZYD3brB7JUak0a9nV6fiERwjfkZMdRZqC1BRkSq9vH*YhuSVgBX0uWAgZvi7PwiYcuShmBRFDZQqRwsQlFiGNG84M1FFELXt4NTns73t2LcuTtY0oFIGzVMutxLqVXFxOp5Oe1BsiKM4aEXcc27ZrPClpc3D1hdNk*7LuRzbi0IZUcPQjwzThpLc0ZlF1MyzDsjXD0Ux7bRlokO3gYjh-2k3ruoIY0qPgzU0gGAXNxw2263cupEFCWUx2VMpSz3K8xQXlLcc4K67kXohV5qrBVVkbYL2yBS7gd*J83-F841Jvwp*9M37*I8h3emHpvmG6tuu5XbdjWV3L0MV682luu9H09S8Ey5FHx28vYjweF8-TT22idq*D7SFeTH4Fyekf-V74iA"}}`

My Code is:
` var configuration = {
            locale: Adyen.LocalSetting,
            originKey: Adyen.OriginKey,
            environment: Adyen.EnviroSetting,
            countryCode: "US", // Only needed for test. When live, this is retrieved automatically.
            amount: {
                currency: "USD",
                value: 1000
            },
            onSubmit: (state, component) => {
                // Your function calling your server to make the /payments request.
                Adyen.MakePayment(state, component);
            }`

`var checkout = new AdyenCheckout(configuration);
var paypalConfiguration = {
                            configuration: {
                                merchantId: "{placeholder}",
                                intent: "authorize"
                            },
                            onInit: (data, actions) => {
                                // onInit is called when the button first renders.
                                // Call actions.enable() to enable the button.
                                actions.enable();
                                // Or actions.disable() to disable it.
                            },
                            blockPayPalCreditButton: true,
                            blockPayPalPayLaterButton: true
                        };`

`var t = checkout.create('paypal', paypalConfiguration).mount("#paypal-div");`

`MakePayment(state, component) {
        Adyen.SetPaymentData(state.data);`

        $.ajax({
            url: "/checkout/payment/postpaypaladyenpayment",
            cache: false,
            type: "POST",
            contentType: "application/json",
            dataType: "json",
            data: JSON.stringify({ "request": JSON.stringify(Adyen.GetPaymentData()) }),
            timeout: 30000, // 30 seconds
            success(response) {
                if (response !== null) {
                    if (response.action) {
                        // The Component handles the action object from the /payments response.
                        component.handleAction(response.action);
                    } else {
                        // Your function to show the final result to the shopper.
                        Adyen.ShowFinalResult(response);
                    }
                } else { // Error occurred
                    alert("error");
                }
            },
            error(jqXHR, textStatus, errorThrown) {
            }
        });
    }
`

**Screenshots**
![image](https://user-images.githubusercontent.com/6124598/231874104-58eeacf9-a20f-483f-8f31-5d0376aa8d42.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version 112.0.1722.39

**Comment by bsulliva** [comment]
Also, I was just curious why I would receive a redirect response from /payments to redirect me to PayPal. Shouldn't I complete the payment in the window that pops up?

![image](https://user-images.githubusercontent.com/6124598/231877891-d597aacb-2392-4280-8f71-98da127f2f77.png)

**Comment by ribeiroguilherme** [comment]
@bsulliva Is it possible to upgrade the library to the latest version? 

I'd recommend to upgrade so we can give you better support with this issue. v3.7 is more than 3 years old, and there are many improvements/fixes for PayPal that was done since v3.7 release.

**Comment by bsulliva** [comment]
Ok thanks
