### ISSUE TITLE
Adyen Highly Recommended 3DS2 fields and Risk Product fields

### ISSUE THREAD

**Issue by Philip-Hel** [Adyen/adyen-web#2116]
**Is your feature request related to a problem? Please describe.**
Adyen recommends sending the shopperEmail when performing 3DS2 but mention in the documentation that it should be captured beforehand.  Business channels integrating are complaining why the Drop-in component would support Billing Address but not other fields for this purpose.

**Describe the solution you'd like**
Adyen Drop-in to allow capturing of recommended fields like shopperEmail so they are not captured seperately outside the Drop-in

Similarly the Risk product has a set of required fields which includes shoppername and telephone and delivery address.  

For the Drop-in widget to be an all-in one widget solution should it not allow capturing of all highly recommended fields for 3DS2 and support the fields required for the standard Revenue Protect product?

**Describe alternatives you've considered**
Having business units implement themselves but experiencing understandable resistance to this.

**Additional context**
For Email Adyen documentation even states it should be collected beforehand as it is required by schemes. This is a good case to include in the Drop-In
![image](https://user-images.githubusercontent.com/28574833/232532283-aa43a492-cc0c-4a3a-9f52-5bfa371e124d.png)

**Comment by sponglord** [comment]
Hi @Philip-Hel - to be clear, is this related specifically to the Credit Card component?

**Comment by Philip-Hel** [comment]
Hi @sponglord 
Thanks for the response, I have taken that into consideration for the general request around the fields.

Specifically Considering the credit card component and shopperEmail.    Why is billingAddress different from shopperEmail.  Both are required for 3DS2 per the API Explorer info?
See in both images API Explorer clearly state they are required for 3DS2.
![image](https://user-images.githubusercontent.com/28574833/233151257-20fbce1f-ae94-483b-bbd0-850d0cd22a50.png)

![image](https://user-images.githubusercontent.com/28574833/233151495-7367c649-8a71-4091-a572-d11a83d8e2f6.png)

**Comment by sponglord** [comment]
Hi @Philip-Hel - We explicitly have the option to ask for billingAddress in the card component because we need that for AVS checks.

Regarding 3DS2  - according to EMVCo, `billingAddress` is required unless local regulations restrict sending it. However, _merchants can choose not to send it_ even if there's no restriction from local regulations, but schemes suggest sending it for lower challenge rate and higher conversion rate.

And the same applies to `shopperEmail`
