### ISSUE TITLE
AdyenCheckout is blocking in Safari V14

### ISSUE THREAD

**Issue by sonegs** [Adyen/adyen-web#2125]
**Describe the bug**
The AdyenCheckout function is blocking the web. This behavior is happening only in Safari V14, but looks fine in Chrome, Firefox or Safari V16 and the payments can be done correctly.

This behavior appears in local and in the production webapp.

**To Reproduce**
Go to webapp where this function is applied.

**Expected behavior**
The AdyenCheckout component is working correctly

**Screenshots**
![Captura de pantalla 2023-04-26 a las 16 09 16](https://user-images.githubusercontent.com/47485321/234602064-3a1009ab-5bef-4ba9-b7cd-b9b2512a5593.png)

**Smartphone (please complete the following information):**
- OS: iPhone 12 mini
 - Browser Safari
 - Version 14.3

**Comment by ribeiroguilherme** [comment]
I can't reproduce this issue @sonegs . I tested with iPhone 12 mini and iPhone 12 Pro Max, Safari 14.3 . It works as expected.
I opened the https://www.mystoredemo.io/#/ and performed the checkout without any issue.

Did you check the errors in the browser in the dev tools? Please check and share, so we can investigate further

**Comment by ribeiroguilherme** [comment]
I tested in other devices too, and I couldn't manage to reproduce the issue. 
I am using Browserstack for that, which simulates using real devices

- iPhone 11 v13.3
- iPhone 11 Pro Max v14
- iPhone 14 v14.7

I am not sure how to reproduce this!

**Comment by sonegs** [comment]
Looks like a problem related with the sandbox paypal environment. I have check it in the PROD environment with a physical device and the problem is not appeared. @longyulongyu @ribeiroguilherme
