### ISSUE TITLE
Field error icon always displayed

### ISSUE THREAD

**Issue by Plaskowitz** [Adyen/adyen-web#2174]
**Describe the bug**
Since version 5.38.0 there is a bug for me, where the red error icon always gets displayed, no matter if there is an error in the associated input field or not. The error message on the other hand shows up and gets removed as expected. 

**To Reproduce**
1. Checkout version 5.38.0 or later
2. Create a card with some input fields.

**Expected behavior**
The info icon should only be displayed if there is an error inside the associated field.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version 1.50.121, Chromium: 112.0.5615.138]

**Additional context**
This issue could be created by the change in the file field.tsx (line: 128) of the PR: https://github.com/Adyen/adyen-web/pull/2059/files#

**Comment by Plaskowitz** [comment]
Hello ribeiroguilherme,

No the bug does not appear for me on the site you linked. Is it using the [web-components](https://docs.adyen.com/payment-methods/cards/web-component) to rendering the cards? As we are using the web-components for our creditcard integration, where the bug appears for me.

**Comment by ribeiroguilherme** [comment]
It is using the Drop-in in that case. But Drop-in uses the web components under the hood, so I expect that the bug isn't happening anymore.

Could you double check testing our latest version with your integration then?

**Comment by Plaskowitz** [comment]
Okay, on further testing I could not reproduce the problem either. Sorry for the inconvenience!
