### ISSUE TITLE
Adyen card container accepting unsupported card numbers without error - How to fix?

### ISSUE THREAD

**Issue by harneetar** [Adyen/adyen-web#2191]
Entered an unsupported card number: 9162 9912 8719 8161 476, in Adyen card container, but didn't get any error saying card number is invalid. Container takes it in successfully and doesn't validate the digits on input.

Here's the relevant image showing card digits entered and Adyen not returning any error message.

https://i.stack.imgur.com/XBZRj.png

**Comment by sponglord** [comment]
Hi @harneetar - What is happening here, I am guessing, is that your are testing agains our _Test_ backend.

The card number you are entering is valid, in that it passes the [luhn check](https://en.wikipedia.org/wiki/Luhn_algorithm)

However the card BIN is not in our Test databases - so we can't detect the card brand. 
In this scenario we fall back to allowing the card payment and leaving it up to the backend to decide whether to allow it or not.

When it comes to the Live production environment, the databases are fully populated, and we would therefore expect to detect the card brand and, whether you as a merchant, are configured to accept it. In the scenario that you do not allow this card brand, an "unsupported card" error would be generated in the UI and it would not be possible for the shopper to proceed with the payment.

**Comment by harneetar** [comment]
Thank you so much for the clarification!
