### ISSUE TITLE
What is the key to enable the display of the shopper's name in Adyen's dropin for stored cards with ReactJs?

### ISSUE THREAD

**Issue by harneetar** [Adyen/adyen-web#2192]
Used 'dropin' for showing stored cards. The UI rendered from Adyen dropin component doesn't show the shopper's name. Is there any key which enables showing the shopper/holder's name in stored cards' container?

Web dropin used with ReactJs.

**Comment by ribeiroguilherme** [comment]
Replied here: 
https://stackoverflow.com/questions/76357421/what-is-the-key-to-enable-the-display-of-the-shoppers-name-in-adyens-dropin-fo
