### ISSUE TITLE
Mbway error with sr-panel-holder

### ISSUE THREAD

**Issue by simonmarcoux-valtech** [Adyen/adyen-web#2195]
**Describe the bug**
Using adyen-web version 5.43.1 for cards and MBWay, there is an issue with the dropin generating an infinite loop of sr-panel-holder elements in the DOM when filling the mbway phone field and clicking outside of the field.

**To Reproduce**
1. Select MBWay payment method in the adyen web dropin
2. Enter a valid phone number.
3. Click outside of the phone number field to remove focus.
4. See error. (page is unresponsive and dom elements are inserted infinitely)

**Expected behavior**
Using the MBway form, we should be able to place order.

**Screenshots**
![image (54)](https://github.com/Adyen/adyen-web/assets/131485901/337be777-2472-43e6-a10a-c1fb825ec92a)
![image](https://github.com/Adyen/adyen-web/assets/131485901/cfa44096-509e-4a53-a350-fcdf2f4d6749)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome (using mobile breakpoints Iphone SE)
 - Version 112

**Additional context**
- MBway is configured in the adyenCheckout dropin following this documentation https://docs.adyen.com/payment-methods/mb-way/web-drop-in.
- We disabled srConfig in the adyenCheckout core config using this code, but this is not part of the documentation: 
```
srConfig: {
   enabled: false,
},
```

**Comment by sponglord** [comment]
@simonmarcoux-valtech Thanks for bringing this to our attention. We're currently trying to reproduce the issue.
In the meantime, is disabling the srPanel with... 
```
srConfig: {
   enabled: false,
}
```
...solving the issue for you? (This is the correct way to disable the module, btw :-))

**Comment by simonmarcoux-valtech** [comment]
Disabling the module does fix the issue for us. 
We recently updated from 5.30.1 to 5.43.0, but we've identified the issue is there since at least 5.39.1 during debugging because this is where we originally found it.

**Comment by sponglord** [comment]
Hi @simonmarcoux-valtech - do you experience the same issue if you go here: https://www.mystoredemo.io/
(Set the country to Portugal, and "buy" something...)

At the moment we are having trouble recreating your issue

**Comment by simonmarcoux-valtech** [comment]
Hi @sponglord, I am unable to reproduce the issue on the demo store. 

In our case, we can see multiple sr-panel-holder elements as soon as the dropin is loaded, and more appear on payment method selection and on phone field validation. Something in our setup could be causing this issue?

Here's a video demo:
https://github.com/Adyen/adyen-web/assets/131485901/11e936c9-0d3f-4324-b61e-9976ba1488ba

Here's our adyencheckout and dropin configs:
![image](https://github.com/Adyen/adyen-web/assets/131485901/92178864-14cb-4e56-9fe0-788ca08d2cc4)
![image](https://github.com/Adyen/adyen-web/assets/131485901/3c7227b7-5d13-48f2-9208-6c2b5fdccfea)

**Comment by sponglord** [comment]
Hi @simonmarcoux-valtech - are you re-rendering the page that initilaises `AdyenCheckout`?

**Comment by sponglord** [comment]
@simonmarcoux-valtech - is this still an issue or can I close it?

**Comment by simonmarcoux-valtech** [comment]
@sponglord You can close it, we've disabled the config and can't investigate further. Thank you
