### ISSUE TITLE
Flutter webView

### ISSUE THREAD

**Issue by teneon** [Adyen/adyen-web#2196]
**Is your feature request related to a problem? Please describe.**
We are creating Apps in Flutter, latest is a platform where our partners can signup as business partners. They would then be able to accept payments via our app. Based on what i see, there is no official Flutter package available.

**Describe the solution you'd like**
In ideal world, I would like to see official Flutter package available :-) Is it planned? And if it is planned, any ETA?

**Describe alternatives you've considered**
One alternative might be, to use a webView in the payment process, so that the web API could be used. I've read on Stackoverflow that some people tried to implement Adyen into their Flutter project by using webView. Not sure if they succeed at the end or not. Is there some official documentation how this could work? 

best regards,
Jim

**Comment by camil-adyen** [comment]
Hi Jim,

Over the past year, we received multiple requests to develop a Flutter SDK. Up until now our development resources have been focused on releasing the [Adyen React Native SDK](https://github.com/Adyen/adyen-react-native). We hope to release this SDK in the coming weeks. 

I can confirm that, from Q3 on, we will be allocating our resources to the development of an Adyen Flutter SDK. However, it would take at least until the end of Q1 '24 before we expect to start piloting. There are several options that other merchants used to implement our Checkout into their Flutter project: 

1) Use a redirect to a web page
2) With the help of a webview
3) Take the React Native SDK as an example and use it to develop your own Checkout integration for Flutter

Unfortunately, we don't have any documentation on how this would work as this is not an official way of integrating. 

I hope you can find a way to make this work for your apps!

Best,
Camil
