### ISSUE TITLE
Adyen container doesn't pick up updates to the redux slice values

### ISSUE THREAD

**Issue by harneetar** [Adyen/adyen-web#2199]
In our implementation, Adyen container (dropin & web component) are expecting some values from redux (slices) for having the values of some payment Instruments according to our checkout flow.
Once Adyen container is loaded, the particular component wherein we are creating the AdyenCheckout instance is always somehow having the initial value of the redux slices.
Even if we are updating those slices and their states and also having those as states as dependency in the useEffect in the Adyen component file, Adyen checkout instance still doesn't accept the changed values. 
Whatever values of slices were present before loading of Adyen component are getting persisted.
According to our checkout flow, those latest redux values are expected inside onSubmit() hook, but the latest/updated values are not getting reflected.
The component though has those latest values in their respective useEffects with dependency. But within onSubmit() it's not reflecting.

**Comment by harneetar** [comment]
Hi @sponglord, yes that's right.
handleSubmit (onSubmit hook) expects redux values from various slices.

**Comment by ribeiroguilherme** [comment]
@harneetar can you be more specific what kinda of values/data are you trying to update within `onSubmit` event, and why do you need to do that?

The callbacks aren't reactive, meaning that they don't get updated if you change values in your Redux store or whatever state management library you use. The callback _ideally_ should not rely on external properties/values as well. 
You must be able to perform the payment with the data that is passed by the callback itself.

**Comment by ribeiroguilherme** [comment]
Closing this as it isn't an issue with the library. If you have any problems implementing it, please reach out to support. Cheers
