### ISSUE TITLE
Delete stored card from dropin

### ISSUE THREAD

**Issue by harneetar** [Adyen/adyen-web#2208]
Used dropin for showing stored cards. Need to integrate **remove card** functionality. 
Is there any key in the Adyen UI which enables this? Need to get something in the UI(cancel/delete button) to invoke the delete stored card API.

**Comment by ribeiroguilherme** [comment]
Hi @harneetar ,

You can configure the [property showRemovePaymentMethodButton and event onDisableStoredPaymentMethod](https://docs.adyen.com/online-payments/build-your-integration?platform=Web&integration=Drop-in&version=5.43.0#drop-in-configuration) for Drop-in.

When configuring both properties, Drop-in will display an element in the UI of your Stored Payment Method to remove it. When clicking on the button to remove the card, the event `onDisableStoredPaymentMethod` will be fired, so you can add your code there to delete the respective stored payment method. 

Cheers
