### ISSUE TITLE
loadingContext is missing in CoreOptions

### ISSUE THREAD

**Issue by david-eventfrog** [Adyen/adyen-web#2209]
Error: node_modules/@adyen/adyen-web/dist/types/core/Analytics/Analytics.d.ts:2:48 - error TS2344: Type '"amoun" | "loadingContext" | "locale" | "clientKey" | "analytics"' does not satisfy the constraint 'keyof CoreOptions.
  Type '"loadingContext"' is not assignable to type 'keyof CoreOptions'.

2 export type AnalyticsProps = Pick<CoreOptions, 'loadingContext' | 'locale' | 'clientKey' | 'analytics' | 'amont'>;

As you can see on the error, there is a problem with the 'loadingContext' in the CoreOptions.
In your CoreOptions (../types/core/types.ts) 'loadingContext' is missing. Please add the attribute and fix your package.

**Comment by ribeiroguilherme** [comment]
Hi @david-eventfrog ,

Which version are you testing? It seems like we have the [loadingContext](https://github.com/Adyen/adyen-web/blob/main/packages/lib/src/core/types.ts#L156) defined in the CoreOptions object

**Comment by david-eventfrog** [comment]
Hi @ribeiroguilherme 

I am using version 5.44.0.

And yes, I see you have `loadingContext` defined in your `CoreOptions`.

BUT: You have declared it as `@internal`, see [here](https://github.com/Adyen/adyen-web/blob/main/packages/lib/src/core/types.ts#L154) and set `stripInternal` to true in [tsconfig.json](https://github.com/Adyen/adyen-web/blob/main/packages/lib/tsconfig.json#L18). So the variable is not exposed and not available in your package.

You can find more information about this topic [here](https://www.typescriptlang.org/tsconfig#stripInternal).
