### ISSUE TITLE
Error loading translations

### ISSUE THREAD

**Issue by david-eventfrog** [Adyen/adyen-web#2216]
As soon as I change the value for 'locale' from 'en-US' no more translations are loaded. This is not only true for 'de-DE' but also for others (I have not tested all of them).

![image](https://github.com/Adyen/adyen-web/assets/135618669/f7b6b3cf-c376-4980-833a-c58274b41400)

![image](https://github.com/Adyen/adyen-web/assets/135618669/6a7ed939-1a30-4b96-95bc-b3846ec3124c)

I am using version 5.44.0.

**Comment by sponglord** [comment]
@david-eventfrog - can you try setting `shopperLocale: 'de-DE' instead of `locale`?

**Comment by david-eventfrog** [comment]
Hi @sponglord 

Thanks for the hint. Unfortunately I get the same error when I set the `shopperLocale` in the session and remove `locale` for it.
It seems to me that the compilation of the URL for the translation file is incorrect (see error message in the first post).

**Comment by ribeiroguilherme** [comment]
@david-eventfrog can you try to create the minimal setup here reproducing the problem? https://stackblitz.com/  
It will help us debugging. Thanks
