### ISSUE TITLE
Billing address dropdowns do not close

### ISSUE THREAD

**Issue by moaead** [Adyen/adyen-web#2221]
**Steps to reproduce**
- Create a dropin component that has a card payment method with billing address required.
- Pass onAddressLookup

**Screenshots**

<img width="597" alt="image" src="https://github.com/Adyen/adyen-web/assets/6399593/b5a27b66-39ac-49fa-bd55-101dd5a2755e">

<img width="573" alt="image" src="https://github.com/Adyen/adyen-web/assets/6399593/ca04ad76-cb65-49cd-9490-629728744a54">

**Expected behavior**

- Clicking outside of dropdown should close it.
- Clicking on the up arrow should close it and keep old value.

**Desktop**

OS: macOS Ventura  13.3.1
Browse: Chrome
Version:  5.45.0

**Comment by m1aw** [comment]
Hey @moaead, any updates on this issue?
