### ISSUE TITLE
composer require adyen/php-api-library pulling a different version of code than the specified version in the doc

### ISSUE THREAD

**Issue by kkhs2** [Adyen/adyen-web#2223]
I'm trying to implement a manual capture and the Adyen support team recommended me to use the following PHP class in order to facilitate this: 

https://github.com/Adyen/adyen-php-api-library/blob/41a1bf2da795e0a447b7e703a6e2d75a2b22be5b/src/Adyen/Service/Checkout/ModificationsApi.php

According to the Github page the ModificationsApi.php file is located in adyen-php-api-library/src/Adyen/Service/Checkout, but from doing a  composer require adyen/php-api-library as suggested in the README.md, I do not see such file or such directory.

The adyen PHP library version in my codebase is 14.0.1 after running composer require adyen/php-api-library, it looks as though that this is possibly pulling another version of the library which is a different version to the one specified in https://github.com/Adyen/adyen-php-api-library/

**To Reproduce**

**Expected behavior**
 When doing a composer require adyen/php-api-library, the expected behaviour is pulling the same directories and files as per the library here: https://github.com/Adyen/adyen-php-api-library

**Comment by m1aw** [comment]
Hey @kkhs2 

Can you open the issue with the [adyen php project github](https://github.com/Adyen/adyen-php-api-library/issues)?
I think they might be able to help you there.
