### ISSUE TITLE
AdyenCheckout-Bundle only for special paymentMethods

### ISSUE THREAD

**Issue by holgerh** [Adyen/adyen-web#2226]
**Is your feature request related to a problem? Please describe.**
The bundle-size of the bundle is extraordinary big. To make the checkout faster – especially on mobile – we want to reduce the bundle-size.

**Describe the solution you'd like**
We are only using a subset of the payment-methods. We want to build a bundle only for the used payment-methods by us.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by m1aw** [comment]
We are tracking this issue in #337. So I will close this one as duplicate.
There's some suggestion there that might help, and we are working on bringing the size down in upcoming versions.
