### ISSUE TITLE
ResultCode type in components/types does not contain "Refused" as a possible value

### ISSUE THREAD

**Issue by martijnbru** [Adyen/adyen-web#2235]
**Describe the bug**

- When writing an `onPaymentCompleted` function in the AdyenCheckout configuration object, the response is of type `OnPaymentCompletedData`.
- This object contains a property `resultCode` of type `ResultCode`
- The current type definition of ResultCode is:
`export type ResultCode = 'Authorised' | 'Cancelled' | 'ChallengeShopper' | 'Error' | 'IdentifyShopper' | 'Pending';`
- However, according to our tests, as well as Adyen's react example (https://github.com/adyen-examples/adyen-react-online-payments/blob/main/src/util/redirect.js), `Refused` should also be a valid value on this type.
- Thus, adding a redirect case for `Refused` will lead to a type error

**To Reproduce**
1. Pull Adyen's react example project
2. Edit the onPaymentCompleted in the `features/redirect/Redirect.js` file to log the response output and stop redirect
3. Run a test payment with, for example, an iDEAL test issuer that provides a `Refused` response
4. Confirm that `Refused` is a valid response for the resultCode property
5. Write a typescript version of `getRedirectUrl()` that expects resultCode to be of type `ResultCode`
6. Typescript will provide an error on the case 'Refused'

**Solution**
Add `Refused` as a valid value to the type definition of `ResultCode`

**Screenshots**
![Screenshot 2023-06-23 at 14 53 04](https://github.com/Adyen/adyen-web/assets/95087495/c7f90581-706c-481c-9880-bbe21468d855)

**Additional context**

**Comment by m1aw** [comment]
Hello @martijnbru 

Thanks for the detailed report. Indeed this is a problem, it must have slipped when typing that interface. 
We will make the changes to fix this.

**Comment by m1aw** [comment]
A fix for this has been included in version v5.49.3 and later.
