### ISSUE TITLE
No returnUrl in onSubmit state.data

### ISSUE THREAD

**Issue by joaooliveiramanteigas** [Adyen/adyen-web#2244]
**Describe the bug**

When updating our current web implementation from Session Flow to Advanced Flow following the provided [documentation](https://docs.adyen.com/online-payments/build-your-integration/additional-use-cases/advanced-flow-integration?tab=v67-actions_2&platform=Web&integration=Drop-in&version=5.32.0#handle-the-redirect-result-1), we encountered an issue. During payments that require redirect behavior, our NET server returned the following error response:
`{"status":422,"errorCode":"14_030","message":"Required field 'returnUrl' is not provided.","errorType":"validation","pspReference":"LMZRSK5J36PFWR82"}`. 

We have previously implemented the Advanced Flow in our React-Native application, where we were able to configure the returnUrl on the AdyenCheckout configuration object as seen here [example code](https://github.com/Adyen/adyen-react-native/blob/develop/example/src/Views/Checkout/CheckoutView.js). This implementation works seamlessly both on our applications and server.

However, in the adyen-web package, we noticed that no returnUrl is passed on the `onSubmit` prop `state.data`. This discrepancy is causing the server-side validation to fail, as it expects the `returnUrl` to be provided.

Expected behavior
We expect the behavior of the adyen-web package to be similar to our current React-Native implementation. In other words, we would like to have a way to pass the returnUrl to the server as the adyen-react-native package allows. Alternatively, if there is a different approach to specifying the returnUrl directly through the request body, please provide guidance on how to achieve this.

Please let us know if there is a solution or workaround available for this issue. Thank you.

**Comment by longyulongyu** [comment]
@joaooliveiramanteigas 

In the session flow, you would need to pass the `returnUrl` in the `/sessions` call before creating the `AdyenCheckout`. When updating to an advanced flow, `AdyenCheckout` doesn't know the `returnUrl` beforehand, hence you need to pass it while making `/payments` call.

Assuming you are making a `/payments` call in the `onSubmit` callback, you can pass `returnUrl` in the request payload. More information can be found on the section [make a payment](https://docs.adyen.com/online-payments/build-your-integration/additional-use-cases/advanced-flow-integration?tab=v67-actions_2&platform=Web&integration=Drop-in&version=5.39.1#make-a-payment).

**Comment by joaooliveiramanteigas** [comment]
But then why would there be a difference when implementing Advanced Flow in adyen-react-native package and adyen-web, one suggests adding the returnUrl in the AdyenCheckout configuration object, and is passed on the onSubmit data, while on the web we need to send this to the server separately?

[Here](https://github.com/Adyen/adyen-react-native/blob/develop/example/src/Views/Checkout/CheckoutView.js) is the example of Advanced Flow implementation with adyen-react-native, where we pass the returnUrl on the configuration object.

**Comment by ribeiroguilherme** [comment]
Hey @joaooliveiramanteigas ,

For React Native, the `returnUrl` is modified by the SDK's internally, whereas for web we simply use it as it is.

Regardless of that, I added your feedback to our improvements list which we are working on. We will take a look into it and see if that makes sense to be added to the web SDK in the next major version. 

For now, you will have to pass it to the `onSubmit` callback.

Cheers!
