### ISSUE TITLE
blockPayPalPayLaterButton: true doesn't work

### ISSUE THREAD

**Issue by alokltd** [Adyen/adyen-web#2248]
**Describe the bug**
I'm trying to implement a PayPal button on my website. I've created a `/session` and initialized the button. Below is my initialization code.

`try {
    const configuration = {
      environment: environment,
      clientKey: clientKey,
      analytics: {
        enabled: true
      },
      intent: "capture",
      session: {
        id:id,
        sessionData: sessionData
      },
      onError: (error, component) => {
          console.error(error.name, error.message, error.stack, component);
      },
      blockPayPalCreditButton: true,
      blockPayPalPayLaterButton: true,
    };
    AdyenCheckout(configuration).then((checkout) => {
      const paypalComponent = checkout.create('paypal').mount('#paypal-container');
      
    });
    } catch (error) {
      console.error(error);
    }` 

Every variable in the above `configuration` object is coming correctly. Even after using `blockPayPalCreditButton: true` and `blockPayPalPayLaterButton: true` nothing seems to work. It still shows the Pay Later button.

I'm using `https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/5.46.0/adyen.js` as SDK.

**To Reproduce**

**Expected behavior**
I do not want the **Pay Later** button showing.

**Screenshots**
![pay-later](https://github.com/Adyen/adyen-web/assets/109710758/434c5f3c-e02c-4ca6-a443-4ef926e688a4)

**Desktop (please complete the following information):**
 - Cloud9
 - Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ribeiroguilherme** [comment]
Hi @alokltd ,

You should pass the PayPal configuration to the PayPal configuration object, and not to the AdyenCheckout object.

Example:
```js
const paypalComponent = checkout.create('paypal', {
    blockPayPalCreditButton: true,
    blockPayPalPayLaterButton: true,
}).mount('#paypal-container');
```

I hope it helps. cheers

**Comment by alokltd** [comment]
Hi @ribeiroguilherme 

Thank you for your response.

That worked perfectly thanks. Now I can see just the PayPal button. But the payment is not being captured.

Below is my AdyenCheckout configuration

```
{
      environment: 'test',
      clientKey: '*****',
      session: {
        id: id,
        sessionData: sessionData
      },
      onPaymentCompleted: (result, component) => {
      }
}
```

I'm receiving the below response after payment is completed on PayPal.

```
{
    resultCode: 'Received',
    sessionData: 'Ab02b4c0!*******yr0ojs6noSg', 
    sessionResult: 'X3XtfGC***************IH8='
}
```

Do I need to call a `/payments` endpoint to capture the payment?

I can see the transactions being logged in the **Transactions -> Offers** with a **Status** = **Open**. Why are they not showing in the **Payments** tab?

I look forward to your response.

Best regards,
