### ISSUE TITLE
Safari 13 bug: SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.

### ISSUE THREAD

**Issue by DannyvanHolten** [Adyen/adyen-web#2249]
**Describe the bug**
Safari 13.1.2 throws an error :

```SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.```

**To Reproduce**
1. Use Safari 13.1.2
2. Try to complete a payment

**Expected behavior**
For there to be no error in Safari 13

**Screenshots**

Screenshot of Sentry issue:
![Screenshot 2023-07-06 at 13 34 01](https://github.com/Adyen/adyen-web/assets/6751652/189fe192-5eca-4b56-9d88-bf6d580dccd7)

The result is a non-loading page because it's a "fatal" error

**Smartphone (please complete the following information):**
 - Device: iPhone
 - Browser: Safari 13

**Additional context**
Looking on StackOverflow this seems to be the related error:
https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet

**Comment by m1aw** [comment]
Hello @DannyvanHolten 

What version of adyen-web are you using?
Also what time of integration, does it come from the embedded script or through npm? If the later what module are you importing?

**Comment by ribeiroguilherme** [comment]
To add on top of the @m1aw questions - which payment method did you try? can you tell us in which step it crashes?

**Comment by DannyvanHolten** [comment]
We are using 4.9.0 from npm. I cannot actually see from with payment method this is coming. As I don't have Safari 13 myself.

It seems to be a payment method with a QR code.

We are using BCMC Mobile & WeChat as payment methods that have a QR code. So it might be one of those 2
