### ISSUE TITLE
Log a warning when initializing without paymentMethodsResponse

### ISSUE THREAD

**Issue by MagicLegend** [Adyen/adyen-web#2267]
**Is your feature request related to a problem? Please describe.**
I made the mistake of spreading the `paymentMethodsResponse` in the config object, instead of just passing it in. This causes the drop-in to initialize with only this div:

```html
<div class="adyen-checkout__dropin adyen-checkout__dropin--ready"></div>
```

This confused the hell out of me, since it does not log any warnings that you initialized without any payment methods. I spent more time than I want to admit searching in other directions, since I was convinced I was passing in the `paymentMethodsResponse` correctly.

**Describe the solution you'd like**

The module should log a warning / error that it was initialized without any payment methods, and that the developer should verify the `paymentMethodsResponse` is passed in. I believe the intention of rendering the drop-in would always be to render payment methods as well, so a warning would be justified.

Doing a quick search in the codebase, I'd imagine this would be the right spot for such a warning:

https://github.com/Adyen/adyen-web/blob/56db1adbaf11add1a4a3cb145ea3f59f4362dc95/packages/lib/src/components/Dropin/components/DropinComponent.tsx#L132-L157

**Additional context**

I'm using the Magento extension with GraphQL to get the `paymentMethodsResponse` in my React PWA frontend.

**Comment by ribeiroguilherme** [comment]
Hi @MagicLegend ,

Thanks for reaching out. We could indeed log a warning when rendering the Drop-In component without any payment methods. That will be helpful for debugging for sure! I created a ticket on our backlog to improve this, but also feel free to contribute by yourself if you feel like. Cheers!
