### ISSUE TITLE
Cleanup instance of AdyenCheckout in React useEffect cleanup function

### ISSUE THREAD

**Issue by woudsma** [Adyen/adyen-web#2271]
**Is your feature request related to a problem? Please describe.**
To use the web drop-in in React, you have to create an instance of `AdyenCheckout` in a `useEffect`.
Since props can change during rendering (in our case parts of the configuration might load later), you can use the `useEffect` cleanup function to destroy any objects or clear event listeners. It's good practice and can help to prevent memory leaks, etc.
The `@adyen/adyen-web` package does not seem to follow this pattern.

**Describe the solution you'd like**
Being able to clean up / destroy a previously created instance of `AdyenCheckout` in the `useEffect` cleanup function, so that a new (updated) instance can be initialized.

I would expect something like this, where the checkout is re-initialized when the `configuration` changes for example:
```js
useEffect(() => {
  const initialiseAdyenCheckout = async () => {
    const checkout = await AdyenCheckout({
      ...configuration,
      removePaymentMethods: [PaymentGroupCodes.AFTERPAY_TOUCH],
    });

    const integration = checkout
      .create('dropin', {
        onSelect: component => selectHandler(component, integration),
      })
      .mount(dropinContainer.current);

    // Store the checkout to interact with it when payment methods change.
    setActiveCheckout(checkout);

    // Store the web drop in a global context to interact with it elsewhere.
    setActiveWebDropIn(integration);

    return checkout
  };

  const adyenCheckout = initialiseAdyenCheckout();

  return () => {
    adyenCheckout.then(checkout => checkout.destroy())
  }
}, [configuration]);
```

**Describe alternatives you've considered**
Waiting until all configuration is loaded in the frontend before initializing the `AdyenCheckout` object.

**Additional context**
Maybe I'm missing something from [the docs](https://docs.adyen.com/online-payments/build-your-integration?platform=Web&tab=codeBlocksessions_web_prMP7_JS_6#methods), should `integration.unmount()` be used in the cleanup function for example?
Any thoughts/tips on updating the configuration after the web drop-in has mounted would be appreciated!
Related issue: https://github.com/Adyen/adyen-web/issues/1996

**Comment by ribeiroguilherme** [comment]
Hi @woudsma ,

You can use `checkout.update` for some situations. Can you share more your use-cases? Which kind of configuration are you updating/planning to update? 

As you mentioned, you can also call `unmount` method to remove the element from the UI. It will just remove it from the screen though. The `checkout` object will still contain all the configuration passed to it.
