### ISSUE TITLE
Type error: Property 'handleFinalResult' is protected and only accessible within class 'UIElement<P>' 

### ISSUE THREAD

**Issue by chrisneven** [Adyen/adyen-web#2272]
Sorry, if this is not the correct way to report this issue. 

**Describe the bug**
We've been using the adyen web component for some time now and recently upgraded from `5.43.0` to `5.48.0`. Since then we've been running into some type conflicts with regards to the `onSubmit` callback which is called with the state and the component:
```ts
    // from CoreOptions
    onSubmit?(state: any, element: UIElement): void;
```

We use the component (of type `UIElement`) to handle the payment result. The way we've done this, is by utilizing the `handleAction` and `handleFinalResult` methods. However, since the typings for the `onSubmit` changed, we've been getting the following typescript error:
```
Property 'handleFinalResult' is protected and only accessible within class 'UIElement<P>' and its subclasses.ts(2445)
```

What's the reason for this method to be protected? What's the (better) alternative solution?

From the docs it's a little bit hard to tell.

**To Reproduce**
1. Use the web component
2. Create an onSubmit callback
3. Try to access `handleFinalResult`
4. A type error will show

**Expected behavior**
To be able to access the `handleFinalResult` method on the component (`UIElement`)

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by ribeiroguilherme** [comment]
Hi @chrisneven ,

The `handleFinalResult` method is used internally by our library. (It is not even documented on our docs) 

You don't need to rely on it - you should handle the logic in your `onSubmit` callback: if there is an action, you should call `component.handleAction(action)`. If there is no action, you should check the `resultCode` and react accordingly (redirect shopper to another page; or display a message in the current page).

I hope it helps!

Cheers
