### ISSUE TITLE
3dSecure iframe content doesn't fit the iframe

### ISSUE THREAD

**Issue by karol-gro** [Adyen/adyen-web#2302]
**Describe the bug**
Swedish Nordea 3dsecure iframe content doesn't fit the default 390x400 iframe so it requires scrolling. It's a big issue for a user as scroll bars are hidden.

From my understanding, we should be able to display 3dsecure iframe in any of supported 5 sizes and it's bank's responsibility to comply. If so, it could be an issue with their 3dsecure or the Adyen package somehow incorrectly communicate with this iframe content

**To Reproduce**
1. Open a webpage with Adyen drop-in with 3d secure configured to iframe
2. Provide card details for Nordea card
3. Observe 3D secure iframe

**Expected behavior**
The whole iframe content is visible, including the buttons in the bottom

**Screenshots**
![image](https://github.com/Adyen/adyen-web/assets/865361/7fbbccf3-54aa-4a6f-8a6f-384c31d4c374)
![image](https://github.com/Adyen/adyen-web/assets/865361/f0a0b85e-f7d6-4798-9bfe-127211b76457)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 
 - Version: 116

**Additional details**
Size info (from test 3dsecure):
![image](https://github.com/Adyen/adyen-web/assets/865361/81752a3f-0e5d-4019-852b-6aa0440f932e)

**Comment by sponglord** [comment]
@karol-gro - It is possible to set the size of the iframe that the 3DS2 challenge window displays in, as described here: https://docs.adyen.com/online-payments/3d-secure/native-3ds2/web-drop-in/#configure-drop-in

**Comment by karol-gro** [comment]
@sponglord OK, but according to this link 390x400 is the default size, so I'd expect it to be the size selected when we don't provide any. However, in this case we can see the frame size is indeed 390x400 while the content is higher, which is not the behavior I'd expect. Is it expected though?

**Comment by sponglord** [comment]
It is expected. There is no dynamic sizing. The default size is 390x400. This is a size we have found to work best for the _many_ different challenge windows that the issuers present to us.
However it is possible for you to configure this to another value
