### ISSUE TITLE
Default value for `storePaymentMethod` on stored payment method is `true` instead to be `false`

### ISSUE THREAD

**Issue by kdivan** [Adyen/adyen-web#2304]
**Describe the bug**
Default value for `storePaymentMethod` on card component checkbox  is `true` instead to be `false` . 

**To Reproduce**
1. Use DropIn integration and pass `enableStoreDetails` to the component card configuration
2. Check `storePaymentMethod` value in `stateData` 
3. On init, the value is `true` instead to be `false`

**Expected behavior**
Init value for `storePaymentMethod` must be false

**Additional context**
The default has been modified since the last tag here : 
https://github.com/Adyen/adyen-web/compare/v5.49.3...v5.49.4#diff-00b4d57f4874a48caf94045ffc0d271e24a38a177dd8a7face6ea40b7328ae4dR9

**Comment by ribeiroguilherme** [comment]
Hi @kdivan ,

Thanks for reaching out. We released a new version which contains the fix for this problem (5.49.6) , therefore I am closing this issue. Feel free to reach out if the problem persists. Cheers
