### ISSUE TITLE
It is not possible to select bank option from the list

### ISSUE THREAD

**Issue by tatsiak** [Adyen/adyen-web#2309]
**Describe the bug**

**To Reproduce**
1. Go to dropin with EPS enabled
2. Click on EPS payment method
3. Click on bank select
4. Click on any option
5. Observe that click is not affecting select in any way

**Expected behavior**
The option is selected

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 116.0.5845.96

**Additional context**
The issue appears with dropin version 4.9

**Comment by tatsiak** [comment]
the issue is caused by the fact that `data-disabled` equals "false"
which is later in code interpreted as boolean `true`

![image](https://github.com/Adyen/adyen-web/assets/17749946/2f7bcf30-1ec3-4a2d-802f-b9d073540e2a)

**Comment by tatsiak** [comment]
Here is the line that causes the issue for 4.9 version
https://github.com/Adyen/adyen-web/blob/613457b7982bdec2b21973003a187e01aa002f0f/packages/lib/src/components/internal/FormFields/Select/Select.tsx#L56

**Comment by ribeiroguilherme** [comment]
Hi @tatsiak .

Thanks for reaching out. We fixed couple of bugs since 4.9, which few of them are related to the bank list. I recommend you to update the library to the most recent version and try it out. Feel free to reach out if the issue persists on the most recent version.

Cheers
