### ISSUE TITLE
3D Secure redirection fails when the application is loaded in an iframe

### ISSUE THREAD

**Issue by anooparveti** [Adyen/adyen-web#2316]
**Describe the bug**
Our application is loaded inside an `iframe`. After adding the Credit Card details (India), we perform `checkout.createFromAction().mount()` which is supposed to redirect user on to URL `https://checkoutshopper-live-in.adyen.com/checkoutshopper/threeDS/checkoutRedirect/xxx`.  We have the error in console (Refer attached screenshots).

The issue occurs when Adyen component tries to redirect the user to URL using `window.location.assign()`.

P.S: Doing this redirection on the top most window would solve our issue. i.e. `window.top.location.assign()`

We dont reproduce the issue when we load the application outside of an iframe.

**Expected behavior**
Redirection to the requested URL must happen without any error even if our application is loaded inside iframe

OR

Provide callback from Adyen component so that we can redirect user to the required URL outside of our `iframe`

**Screenshots**

<img width="1791" alt="ConsoleError" src="https://github.com/Adyen/adyen-web/assets/22835814/813bf6ea-f91b-4906-9ca6-bef98d36ac4d">

**Comment by sponglord** [comment]
@anooparveti  - I'm not currently able to recreate this exact issue.

I've tried running Dropin in an iframe to test 2 other "redirect" scenarios, and in both cases: 
- a 3DS2, MDflow, redirect
- _and_ a regular credit card redirect
everything works as expected.

Because the Dropin is in an iframe - the call to `window.location.assign()` that you mention, works within the context of the Dropin/iframe, and the content of the iframe is correctly replaced with the content from the redirect url.

I've asked our Authentication team if it's possible to recreate the original, 3DS2 redirect flow (that is now only available, afaik, in countries like India & Sri Lanka) - but since this also uses the same `Redirect` component as the other 2 test cases - I would expect it to also work.

**Comment by sponglord** [comment]
@anooparveti the url in the screenshot: https://ca.ovh.com is this your url?

**Comment by anooparveti** [comment]
> @anooparveti - I'm not currently able to recreate this exact issue.
> 
> I've tried running Dropin in an iframe to test 2 other "redirect" scenarios, and in both cases:
> 
> * a 3DS2, MDflow, redirect
> * _and_ a regular credit card redirect
> 
> everything works as expected.
> 
> Because the Dropin is in an iframe - the call to `window.location.assign()` that you mention, works within the context of the Dropin/iframe, and the content of the iframe is correctly replaced with the content from the redirect url.
> 
> I've asked our Authentication team if it's possible to recreate the original, 3DS2 redirect flow (that is now only available, afaik, in countries like India & Sri Lanka) - but since this also uses the same `Redirect` component as the other 2 test cases - I would expect it to also work.

Thanks for the quick response @sponglord :)

We are testing the "Add Credit Card" in India. So I am referring to "3DS2 redirect flow". We dont notice any issue with registering credit cards in other countries.

Let me give you a brief overview about our application.

Our application is composed of
1. Container (hosts the sidebar + topbar + iframe to display the content)
2. Content (We have multiple micro-apps and we display any one app based on user selection in topbar)

We display payments page in one of our micro-app and when we are trying the "Add Credit Card" feature for India, Adyen component tries to redirect to `https://checkoutshopper-live-in.adyen.com/checkoutshopper/threeDS/checkoutRedirect/xxx`. `window.location.assign()` only tries to replace our Content section. So basically, `ca.ovh.com` is trying to load `checkoutshopper-live-in.adyen.com` in its iframe and this is causing the CORS error. 
But when Adyen components redirects on the top most window, `ca.ovh.com` will be replaced with `checkoutshopper-live-in.adyen.com` and we will not have any issue.

Let me know if you need any more info.

**Comment by sponglord** [comment]
@anooparveti - Hi. Just to be clear... when you say 
> "Add Credit Card" feature"

I presume this is seeing the shopper go through the whole credit card payment process (which culminates in the 3DS redirect)?

**Comment by anooparveti** [comment]
> @anooparveti - Hi. Just to be clear... when you say
> 
> > when we are trying the "Add Credit Card" feature
> 
> I presume this is a process that sees the shopper go through the whole credit card payment process (and which culminates in the 3DS redirect)?

Yes @sponglord

**Comment by sponglord** [comment]
@anooparveti - can you tell me more about this Content iframe?
Is it within your domain, or, more specifically, can you communicate from it _up_ to the `parent.window`?

**Comment by anooparveti** [comment]
@sponglord,

Here are my answers, 

> can you tell me more about this Content iframe?
Is it within your domain, or, more specifically, can you communicate from it up to the parent.window?

Yes, the content of `iframe` is within our domain and we can communicate with the parent window.

>And, I presume, that somewhere within the content running in this iframe you are instantiating a new instance of AdyenCheckout: const checkout = AdyenCheckout()
and then creating a (custom) card component: checkout.create('securedfields')
and then, at some point, making & handling a call to out /payments endpoint?
All within the iframe?

Yes, we are doing exactly the same within the `iframe`.

>Basically, I'm wondering if you can't make the /payments call and then handle the response differently?
Instead of instantly calling checkout.createFromAction(...).mount(...) - you could pass the response.action object and checkout reference up to your top level window.
Then use them to call checkout.createFromAction(action).mount({MY_ELEMENT}) - mounting them into a top level window element of your choice.

Our parent window constitutes to handling more generic purpose of the application like authentication, navigation bar, locale management and so on.
So we feel that moving `checkout.createFromAction(action).mount({MY_ELEMENT})` will tightly couple one of our applications (displayed inside iframe) with the parent window and will not work independently without the parent window which is against the idea of micro-front end application.

**Comment by anooparveti** [comment]
@sponglord, do you face any difficulties in implementing `window.top.location.assign()` on a conditional manner based on the config?

**Comment by anooparveti** [comment]
@sponglord any updates on this??

**Comment by sponglord** [comment]
@anooparveti - I believe our Implementation Manager, Gurpreet Singh, has been talking to you about this?

**Comment by anooparveti** [comment]
> @anooparveti - I believe our Implementation Manager, Gurpreet Singh, has been talking to you about this?

@sponglord, Yes indeed. I didn't notice yesterday's reply from Gurpreet. So I added a reminder.

**Comment by sponglord** [comment]
There is a new npm release: `v5.51.0`.
You will need to add a `redirectFromTopWhenInIframe: true` to your config for AdyenCheckout
