### ISSUE TITLE
Error with dual branded card: "Cannot read properties of undefined (reading 'brand')"

### ISSUE THREAD

**Issue by ncordin** [Adyen/adyen-web#2319]
**Describe the bug**

We recently added the card brand choice on our website. Since then we detect many of those errors on Sentry: 

<img width="707" alt="image" src="https://github.com/Adyen/adyen-web/assets/1555211/eaffe252-0190-466d-835a-2d1c09eb3d02">

We are using the `onBinLookup` params of "securedfields" to get card brands to display.

**To Reproduce**
We are not able to reproduce this bug with the available test cards. But it seems some of our customers are stuck after this error and can't finalise their payment.  

**Expected behavior**
To be able to choose the brand without errors.

**Desktop (please complete the following information):**
 - Adyen web version: ^5.29.0

**Additional context**

We inspected the stack trace, and it seems the error is related the those instructions, in the `packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/handleBrandFromBinLookup.ts` file:
```
    const binBrandObj: BrandObject = binLookupResponse.supportedBrands[0];

    const passedBrand: string = binBrandObj.brand;
 ```

**Comment by ncordin** [comment]
> @ncordin - I presume you are using the "custom" card component i.e you `checkout.create('securedfields')` rather that the regular card component `checkout.create('card')`?

Yes, we are using `checkout.create('securedfields')` because with need customisation to integrate to our payment form.

**Comment by sponglord** [comment]
hi @ncordin 
If you are using the custom card with `onBinLookup` then at some point, when the shopper chooses one of the dual brands, you must be making a call like this: `securedFields.dualBrandingChangeHandler(e)`?

Can you log the value of `e` - the parameter that is passed to the function?

My initial thought is that `e` doesn't contain anything from which we can extract a value that corresponds to one of the dual  card brands e.g. "visa" or "cartebancaire"

**Comment by sponglord** [comment]
@ncordin As an addition... 
there is definitely some discrepancy between what is getting passed back, by you, to the `securedFields.dualBrandingChangeHandler` (e.g. `'visa'`) and the object we have stored from the `/binLookup` response (before we pass it to you as the `supportedBrandsRaw in the `onBinLookup` callback).

But without the ability to see exactly what your `onBinLookup` callback is receiving and what value is subsequently being sent to `securedFields.dualBrandingChangeHandler` it is very hard to debug.

As my colleague has said, the new version `5.50.1` will, at least, prevent this discrepancy from becoming a fatal error
