### ISSUE TITLE
Apple Pay not visible on Ipad Mini 4

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-web#2324]
**Describe the bug**

I added the Apple Pay payment method to my site, but I have a customer who does not see the method displayed on the checkout.

I followed the following documentation https://docs.adyen.com/payment-methods/apple-pay/web-component/ to add the method, I am using the `isAvailable()` function and this function displays the following message in the console:

> Apple Pay is not available

The customer uses an Ipad Mini 4, normally Apple Pay support this device: [documentation](https://support.apple.com/en-ca/HT208531).

![Capture d’écran du 2023-09-05 18-21-03](https://github.com/Adyen/adyen-web/assets/34821762/0c8d2509-d42a-441a-b658-10330d7a2e53)

Possible to have information on the functioning of the `isAvailable()` method? This function should not return an error with this device.

**Expected behavior:**

Apple Pay must be displayed.

**Desktop information:**

 - OS: Mini 4 IOS 15.7.8
 - Browser: Safari web browser
 - @adyen/adyen-web version: 5.49.1
 - Device: Ipad Mini 4

**Comment by ribeiroguilherme** [comment]
Hi @dimitriBouteille ,

Can you check if you can see the ApplePay button on[ this page](https://applepaydemo.apple.com/), using the Ipad Mini 4 device?

**Comment by dimitriBouteille** [comment]
Hi @ribeiroguilherme 

The bug is fixed:)
