### ISSUE TITLE
Proposal: Add `onPayButtonClick()` hook to dropin

### ISSUE THREAD

**Issue by KirillKotliar** [Adyen/adyen-web#2333]
Hi! I am using the dropin Adyen checkout form with adding a custom form with an `email` input field. I have problems with synchronizing the validation of my custom form and the Adyen form on pay buttom click. Right now I am triggering custom validation on the `beforeSubmit` hook.

```
beforeSubmit(data, _component, actions) {
  const isValid =  customFormValidation();
  if (!isValid) {
    actions.reject();
    return;
  }
// ...
  actions.resolve(data);
},
```
However `beforeSubmit` hook is invoked only when the adyen form is valid. This creates an undesirable feel of 2 step validation when adyen form is checked on each click and custom form only if all adyen data is valid. 

![image](https://github.com/Adyen/adyen-web/assets/136968233/2a4d35d9-dd26-4a0e-b4a8-47b5a8fa0e64)

I want to perform custom validation on each Pay button click like it does Adyen form. 

**Proposal feature:**
Add a new `.onPayButtonClick()` hook that invokes after each pay button click even when the adyen from data is invalid. 

There are also other naming alternatives: `onFormValidation` or `onSubmitClick`.

**Comment by ribeiroguilherme** [comment]
Hi @KirillKotliar ,

For this use case, you should opt in for implementing your own Pay button. It will give you more control over the actions that need to be done once the user click on it. 

You should use the configuration property `showPayButton: false` when creating `AdyenCheckout` , so the button will hide.  You can check more about this config [here](https://docs.adyen.com/online-payments/build-your-integration/?platform=Web&integration=Components&version=5.51.0#props)

When creating your UI component, you will have  public methods available which you can use to verify if the Component data is valid or not ( `isValid`, `showValidation()`) , so you can use these in combination with your custom form validations to proceed with the payment.

I hope it helps.

Cheers!
