### ISSUE TITLE
Error thrown: "secured field iframes have failed to load" in 1 out of 3 page loads

### ISSUE THREAD

**Issue by andretauffer** [Adyen/adyen-web#2335]
**Describe the bug**
Once every three or four page loads we get an error throw by the onError callback with the message: 
`secured field iframes have failed to load`. After investigating the adyen-web codebase a bit it seems to me there is a timeout that logs this error.
timeout: 
https://github.com/Adyen/adyen-web/blob/7d67e7b27a3bee476ff7d58e84c884aa1a9f8fe8/packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProvider.ts#L196C7-L196C7

My suspicion is that since we're re rendering the parent and re initiating the library, it might be unmounting without properly clearing out the timeout. Strangely it only happens like 30% of the attempts, and I can't tell where the race condition is. 

**To Reproduce**
1. Render the default export component with saved card option
2. Select the saved card option
3. wait for up to two minutes
4. See error by logging from the onError callback

**Expected behavior**
I expected the secured field iframes to load properly every time, or that the timeout is cleared on a componentUnmount kind of event

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version 117.0.5938.88 (Official Build) (arm64)
 PS.: but it was also reproduced in linux machines

**Comment by sponglord** [comment]
Hi @andretauffer - this issue should be fixed by the PR #2334 
This will be included in our next release (date TBD - but either next week (week of October 2nd) or the week after (week of October 9th))

**Comment by andretauffer** [comment]
Hi @sponglord. This is great news! We'll be waiting to get that update then. Thanks for the quick response!

**Comment by sponglord** [comment]
@andretauffer fyi - This has been fixed in `v5.52.0`
Depending on how you integrate with us this version is available now (npm) or on Monday 16/10/23 (embedded, adyen.js)

**Comment by andretauffer** [comment]
Hi @sponglord , thank you for letting me know. Will update to that version when possible then
