### ISSUE TITLE
Iframe is incompatible with CSP headers that contains a NONCE value

### ISSUE THREAD

**Issue by wezz** [Adyen/adyen-web#2336]
**Describe the bug**
createIframe.ts sets a style attribute to the iframe. 
This cause CSP errors if a website CSP headers contain a NONCE key. 

**To Reproduce**
1. Implement the drop-in on a page
2. Serve the page with a security header that includes this: 
style-src https://use.typekit.net https://p.typekit.net https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css https://checkoutshopper-test.adyen.com https://checkoutshopper.adyen.com https://checkoutshopper-live.adyen.com 'nonce-73b286c7-d81b-4b7e-84f6-8067f3240676' 'self';
4. The error you get will be:
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src https://use.typekit.net https://p.typekit.net https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css https://checkoutshopper-test.adyen.com https://checkoutshopper.adyen.com https://checkoutshopper-live.adyen.com 'nonce-73b286c7-d81b-4b7e-84f6-8067f3240676' 'self' ". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

**Expected behavior**
I expected the page to load without CSP errors since security should take precedence over inline styles. 

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome
 - Version 116

**Additional context**
Using inline-styles is usually very troublesome when running a website with proper CSP headers. 

I would suggest moving the styling to a css file that can be imported and loaded with the NONCE attribute.

**Comment by longyulongyu** [comment]
@wezz Thank you for reporting it.
Are you integrating via npm or the embeded?

**Comment by sponglord** [comment]
@wezz fyi - This has been fixed in `v5.52.0`
