### ISSUE TITLE
After packing, the volume is too large

### ISSUE THREAD

**Issue by longhonour** [Adyen/adyen-web#2339]
![image](https://github.com/Adyen/adyen-web/assets/13929056/89bc3f05-5381-4643-acc0-f40da337ec19)

**Comment by longyulongyu** [comment]
Hi @longhonour 
We are aware of the issue. 
We are currently working on a major version change which we will support tree shaking, the bundle size will be presumably reduced depending on modules you are importing.
If you are using umd format, we will not include all translations (except for English), we will dynamic load translations you specified.

**Comment by ribeiroguilherme** [comment]
Hey @longhonour . Can you share what is your current tech stack? Which frameworks are you using to integrate and build your application?

**Comment by longhonour** [comment]
@ribeiroguilherme Hey，The application I am currently using is built with React and Webpack.

**Comment by ribeiroguilherme** [comment]
@longhonour which webpack version?
