### ISSUE TITLE
Swish payment method use on mobile browser via Open the app button

### ISSUE THREAD

**Issue by KiprasJ** [Adyen/adyen-web#2342]
I am using Swish payment method on our website and I'm trying to figure out how can I access this event via Dropin when the button is clicked. We need to do some additional changes on this button click. This case is from Android device by using chrome browser.

Referring to this redirect https://docs.adyen.com/payment-methods/swish/api-only/#redirect

![image](https://github.com/Adyen/adyen-web/assets/7200930/d24d3204-38de-4d34-973c-8984b677ad9a)

**Comment by ribeiroguilherme** [comment]
Hey @KiprasJ ,

There is no event/callback attached to this button currently. Could you elaborate a bit more your use-case? What do you want to achieve?

**Comment by KiprasJ** [comment]
Hey @ribeiroguilherme,

Alright thanks for the information. Lets say I would like to save some data in localstorage before the actual button does the redirect. Maybe there is another way to achieve this?

**Comment by ribeiroguilherme** [comment]
@KiprasJ you currently have two options:
- if you are using sessions: save the details using  the`beforeSubmit` callback 
- if you are using advanced flow: save the details when the `onSubmit` callback

We currently don't have any event attached to that button, and we aren't planning to add as we haven't heard any feature requests from merchants up to now. I hope the solution above works for you. Cheers
