### ISSUE TITLE
Postal code validation error messages don't match with regex

### ISSUE THREAD

**Issue by ignas-seskauskas2** [Adyen/adyen-web#2362]
Postal code validation error message doesn't show correct information. It says that 99999 format should be correct, but it's not correct, error message is still shown.

![image](https://github.com/Adyen/adyen-web/assets/103568359/6aa69544-7657-4544-9ed0-88aef163edc9)

In https://github.com/Adyen/adyen-web/blob/main/packages/lib/src/components/internal/Address/validate.ts:
language LT pattern is "/^(LT-\d{5})$/"
But in https://github.com/Adyen/adyen-web/blob/main/packages/lib/src/components/internal/Address/validate.formats.ts error message for language LT is: '9999 or 99999 or LT-99999'

There may be a similiar issue for other languages too

**Comment by m1aw** [comment]
Hello @ignas-seskauskas2 

This issue has been fixed on the latest version `5.68.1` and `6.1.1`.
