### ISSUE TITLE
Ability to retry failed payments

### ISSUE THREAD

**Issue by jesperjohansson** [Adyen/adyen-web#2373]
**Is your feature request related to a problem? Please describe.**
If the payment fails there is no way to retry or switch payment method.

**Describe the solution you'd like**
Add a retry button to the error status component. It could be configurable. Clicking this button could take you back to the payment method selection.

**Describe alternatives you've considered**
Showing a button outside the drop-in, but that looks ugly. 

**Additional context**
v5.50.0
Using the drop-in implementation.
Example, when canceling a Swish payment from the Swish app (a retry button could be under the "payment failed" text):
![Screenshot 2023-10-18 at 15 41 55](https://github.com/Adyen/adyen-web/assets/21033162/2de9dcdf-3d01-44fe-8415-d7c8378ca75f)

**Comment by ribeiroguilherme** [comment]
Hi @jesperjohansson ,

In this case, you can opt in to set the status by yourself. You must set the `setStatusAutomatically` on `AdyenCheckout` to `false`. Then,  when detecting that the payment got Refused/Cancelled, you can set the status to `ready` by doing `dropin.setStatus('ready')` . This should allow for subsequent payments with the same instance and session.

The session will not be able to process a payment after ~5 refusals though, so a new session would be required then.

I hope it helps. Cheers!
