### ISSUE TITLE
Get list of payouts

### ISSUE THREAD

**Issue by rondanen** [Adyen/adyen-web#2384]
**Is your feature request related to a problem? Please describe.**
I am trying to get the list of payouts and the list of payments they refer to. The only way that seems to exist is to get the report via webhook, but that report has to be created via the console, which is not API-friendly to get a seamless integration.

**Describe the solution you'd like**
- GET enpoint to have the list of payouts
- GET endpoint to pass a payout ID and get the list of payments it includes

**Describe alternatives you've considered**
Use the reports, but there is no way to programmatically generate a report.

**Additional context**
n/a

**Comment by ribeiroguilherme** [comment]
Hi @rondanen ,

This topic is not related to the adyen-web library. Please reach out to Adyen Support for that.

Cheers
