### ISSUE TITLE
Web Component - update locale

### ISSUE THREAD

**Issue by strublos** [Adyen/adyen-web#2407]
**Describe the bug**
Unpossible to change locale on Web Components (Card, Click To Pay)

**To Reproduce**
```
const instanceGooglePay = checkout.create('paywithgoogle', configuration);
instanceGooglePay.update({buttonType: 'subscribe', buttonLocale: 'cs'});//change locale

const instanceClickToPay = checkout.create('clicktopay', configuration);
instanceClickToPay.update({locale: 'cs'});//nothing happens

const instanceCard = checkout.create('scheme', configuration);
instanceCard.update({locale: 'cs'});//there is no property locale in type CardElementProps
```

Is there some way to change locale on card and click2pay instances?

**Expected behavior**
Change locale without reinitializing component

adyen-web: 5.49.4

**Comment by ribeiroguilherme** [comment]
Hi @strublos ,

`locale` must be passed to `AdyenCheckout` when initializing the library.  It is currently not possible to update it through the `update` function. Can you reinitialize `AdyenCheckout` with the locale and see if it works for you?

**Comment by strublos** [comment]
Hi,
`checkout.update(newConfiguration);` is without effect,
reinitialize checkout works, but it send new OTP password for clickToPay component

**Comment by ribeiroguilherme** [comment]
As I mentioned: using the `update` is not possible. You must reinitialize checkout with the new locale, and that eventually will re-trigger the OTP. 

If your shopper wants to change the language, ideally he will change it before landing in the Checkout page. If the shopper decides to change the language in the Checkout page, you must reinitialize the Checkout.
