### ISSUE TITLE
card payments(web component): The input box of the card payment method cannot be focused in the PC webview, and the cursor is not visible.

### ISSUE THREAD

**Issue by Fog3211** [Adyen/adyen-web#2420]
**Describe the bug**
### Card payments(web component): 
The input of the card payment method cannot be focused in the PC webview, and the cursor is not visible. I need to switch windows once to make input normal

**To Reproduce**
1. select adyen card payment
2. Click pay button
3. open modal

**Expected behavior**
The input can be focused normally and the cursor can be displayed

**Screenshots**

https://github.com/Adyen/adyen-web/assets/23151576/11ab8234-51ec-415e-b6b6-634e94c23dcb

**Desktop (please complete the following information):**
 - Device: PC
 - OS: window11
 - Browser  chrome in unity webview
 - Version 118

**Additional context**

This problem only occurs with input inside iframes （like Card number、Security code、Expiry date）
Although the cursor effect is not visible，But typing can take effect, this may be a style bug ?

![image](https://github.com/Adyen/adyen-web/assets/23151576/a0bceb83-7b39-4d6d-8c13-a09c777a6cc6)
![image](https://github.com/Adyen/adyen-web/assets/23151576/019ecbc8-803f-4ab5-abbd-f156c2000acd)

https://github.com/Adyen/adyen-web/assets/23151576/9831b709-b197-4239-9196-489a21cf1fd7

**Comment by m1aw** [comment]
Hello @Fog3211 

Is there any way to have access to a demo of this? Or code samples?

Or can they share how they are hiding/showing the card component? 

Are they using a specific framework?

**Comment by Fog3211** [comment]
my framework is Nextjs13 + antd-mobile , but I can reproduce it in pure html + vanillaJs

this is my html code
[adyen.html.zip](https://github.com/Adyen/adyen-web/files/13295938/adyen.html.zip)

**Comment by Fog3211** [comment]
I will apply to my superiors. If the test package is allowed to be made public, I will supplement our client's minimum reproduction demo.

**Comment by m1aw** [comment]
I took a look at the sample code provided, it's only the page that is shown inside of the modal correct?
Is the modal part of Unity and has a webview inside (with the sample code provided)?

**Comment by Fog3211** [comment]
> I took a look at the sample code provided, it's only the page that is shown inside of the modal correct? Is the modal part of Unity and has a webview inside (with the sample code provided)?

yes, Unity demo directly opens a webview containing the above html

The unity demo package depends on my colleagues and may not be provided until later.

**Comment by m1aw** [comment]
Hello @Fog3211 I have test on Chrome on Windows, and wasn't able to reproduce.
Because of that I'm assuming it's something with Unity's Chrome webview. 

I see you can connect the debugger to the webview, is there any difference in the style rule of the iframe inputs when they show the carrot and when they do not?

**Comment by m1aw** [comment]
Hello @Fog3211 did you manage to fix the issue?
