### ISSUE TITLE
Google Pay: `component.isValid` is false when using custom pay button

### ISSUE THREAD

**Issue by davidohlin** [Adyen/adyen-web#2421]
I use a custom payment button. Before submitting any component, I check that all input it's valid:

```js
if (!component.isValid) {
  component.showValidation();
  return;
}

component.submit();
```

For Google Pay, the `isValid` property is always `false`. Is this intended?

**Comment by ribeiroguilherme** [comment]
Hi @davidohlin ,

The `component.submit()` has built-in logic to check if the component is valid, and then show validation or perform the payment. You can skip your custom check and you can rely in our internal validation in this case. If you face any issue, please let us know.

Cheers

**Comment by davidohlin** [comment]
@ribeiroguilherme But there is no callback to know that the submit was invalid, right? I omitted my side effects for brevity, but imagine this use case:

```
if (!component.isValid) {
  component.showValidation();
  setLoading(false)
  return;
}

component.submit();
```

How would I achieve that? The `submit` method doesnt return anything or omit any events AFAICT from the docs.

**Comment by lauterry** [comment]
Hello 

Could you assist me with finding documentation or information regarding the availability of the `component.showValidation()` function? 

I'm interested in programmatically triggering form validation, especially for an Adyen component form. 

I have a custom button and would like to synchronize the validation of the Adyen component form with other fields on the form. 

Any guidance on this matter would be greatly appreciated. 

Best regards.
