### ISSUE TITLE
Blik svg not available after upgrade to 5.55.0. (404)

### ISSUE THREAD

**Issue by Oskii2311** [Adyen/adyen-web#2489]
**Describe the bug**
When paying with blik, an svg fetch error is returned and a broken image is displayed.
`GET https://cdf6519016.cdn.adyen.com/checkoutshopper/images/logos/await.svg 404 (Not Found)`.
on the previous version everything was fine(5.29.0).

**To Reproduce**
Pay by blik

**Expected behavior**
The application is able to fetch the image or dorpin should not display the broken image(as in the previous version). 

**Screenshots**
<img width="963" alt="Screenshot 2023-12-12 at 14 20 20" src="https://github.com/Adyen/adyen-web/assets/22234674/75ab584e-4a9f-4b65-9912-83294f8506b9">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome 
 - Version: 120.0.6099.62 
 - dropin 5.55.0

**Comment by longyulongyu** [comment]
@Oskii2311 Could you confirm the version you are using? Is it v5.55.0 or 5.50.0?

**Comment by Oskii2311** [comment]
@longyulongyu 
Sorry, my bad. 
it is: 
5.55.0

**Comment by ribeiroguilherme** [comment]
@Oskii2311 could you please try the newest version and let us know if the problem is solved? Thanks

**Comment by Oskii2311** [comment]
I updated dropin to version 5.55.1 and everything looks good.

Thank you!
