### ISSUE TITLE
IMPLEMENTATION_ERROR : Could not submit payment

### ISSUE THREAD

**Issue by AhmedSaeed10p** [Adyen/adyen-web#2494]
**Describe the bug**
I have used an Adyen Component widget. I provided config to authorized the card and user as below

const configuration = {
    environment: "",
    clientKey: "",
    showPayButton: true,
    analytics: {
      enabled: true,
    },
    paymentMethodsConfiguration: {
      card: {
        brands: ["mc", "visa", "amex"],
        hasHolderName: true,
        holderNameRequired: true,
        billingAddressRequired: true,
        amount: {
          currency: "USD",
          value: 0,
        },
      },
    },
    recurringProcessingModel: "CardOnFile",
    shopperInteraction: "Ecommerce",
    storePaymentMethod: false,
    onPaymentCompleted: (result, component) => {    },
    onChange: (result, component) => {    },
    onError: (error, component) => {  	},
  };

**To Reproduce**
Make Adyen Card Component. And provided the above config.

**Expected behavior**
It should return the Authorized/Reject state. In the case of Authorized, it should store the user card

**Screenshots**
<img width="597" alt="Screenshot 2023-12-15 at 8 10 12 PM" src="https://github.com/Adyen/adyen-web/assets/68601556/d791d8e2-4ad6-431c-9756-8e4442bf19c6">

**Additional context**
I am implementing it for the first time. I might have missed something. Any help would be appreciated.

**Comment by ribeiroguilherme** [comment]
Hi @AhmedSaeed10p ,

You forgot to implement the `onSubmit` callback which takes care of the payment part.

Cheers
