### ISSUE TITLE
Sometimes the status check QR code doesn't wait for the previous request to complete or times out.

### ISSUE THREAD

**Issue by drawtsae** [Adyen/adyen-web#2499]
**Describe the bug**
Occasionally we encounter a case of drop-in trigger **onAdditionalDetails** 2 times in a row just a few milliseconds apart when the user scans the QR code. My system cannot handle this duplicate request, I was workaround by implement queue for this. We were able to replicate this case when the network was unstable.

**To Reproduce**
1. Check out with payment have QR code. in this case I use Paynow, on normal network condition, even offline, it work fine.
![image](https://github.com/Adyen/adyen-web/assets/48081470/5b07c9b4-ed1d-4727-bd43-d4ea2d80326d)

2.  But when I change Network throttling to very slow (up: 8kbit/s,down: 8kbit/s), many API check status will be call
![image](https://github.com/Adyen/adyen-web/assets/48081470/73a4ffad-ebc4-46a0-84e7-5215d586fe76)
3. At this time, if use try to scan QR code, many API check status will return sucess and trigger **onAdditionalDetails**

**Expected behavior**
Can we make sure it retry until getting a complete response from the server or it times out.

**Comment by longyulongyu** [comment]
@drawtsae 

Thanks for reporting.
Which sdk version are you integrating with? There isn't an `onSubmitAdditionalDetail` callback. Do you mean `onAdditionalDetails` callback?

**Comment by drawtsae** [comment]
@adyen/adyen-web: 5.53.2

I use version 5.53.2.
 Sorry for the mistake, and yes it does trigger `onAdditionalDetails` more than 1 time.

**Comment by drawtsae** [comment]
Hi @longyulongyu, I see the issue has been fixed in the latest release version, I checked and it worked as expected. Thanks for your help.
