### ISSUE TITLE
Duplicate brand image

### ISSUE THREAD

**Issue by sinchang** [Adyen/adyen-web#2501]
**Describe the bug**
There are two brand images displayed when I type the cart number `5166 1269 0383 3343`

**Expected behavior**
Only display one brand image

**Screenshots**
![image](https://github.com/Adyen/adyen-web/assets/3297859/fafa3698-e880-4005-ae3f-47d338d96b78)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [120.0.6099.129]
 - SDK version: 4.2.2 (Embed script and stylesheet)

**Additional context**

Here is the API `https://checkoutshopper-live.adyen.com/checkoutshopper/v2/bin/binLookup` response

```
{
    "brands": [
        {
            "brand": "mc",
            "cvcPolicy": "required",
            "enableLuhnCheck": true,
            "expiryDatePolicy": "required",
            "localeBrand": "MasterCard",
            "paymentMethodVariant": "mcstandarddebit",
            "showExpiryDate": true,
            "showSocialSecurityNumber": false,
            "supported": true
        },
        {
            "brand": "pulse",
            "cvcPolicy": "required",
            "enableLuhnCheck": true,
            "expiryDatePolicy": "required",
            "localeBrand": "Pulse Pay",
            "panLength": 16,
            "paymentMethodVariant": "pulse_pinless",
            "showExpiryDate": true,
            "showSocialSecurityNumber": false,
            "supported": false
        },
        {
            "brand": "maestro",
            "cvcPolicy": "optional",
            "enableLuhnCheck": true,
            "expiryDatePolicy": "required",
            "localeBrand": "Maestro",
            "paymentMethodVariant": "maestro",
            "showExpiryDate": true,
            "showSocialSecurityNumber": false,
            "supported": true
        }
    ],
    "issuingCountryCode": "US",
    "requestId": "3faba386-c0e9-4abf-81f9-90f73da8d027"
}
```

**Comment by longyulongyu** [comment]
@sinchang 

From the binLookup response, I could see 3 brands are returned, out of 2 are `supported` - "maestro" and "mc", which are 2 different brands. That's why we are showing 2 logos. So technically, we are showing the brand logos correctly.

If you only want to support only one brand, you could disable the other one in the CA.

**Comment by sinchang** [comment]
noted. thanks @longyulongyu
