### ISSUE TITLE
Swish onComplete or OnPaymentComplete never gets fired

### ISSUE THREAD

**Issue by KiprasJ** [Adyen/adyen-web#2515]
**Describe the bug**
We have dropin saved as a state and triggering different payment methods from another component. With Cards we have no issues with success and failures. Now when we started implementing Swish we can see that whenever we make a successful payment the `onPaymentCompleted` or `onComplete` never gets fired.

**To Reproduce**
1. Save dropin to state (lets say activeDropInElement)
2. Handle the action received by using the state and passing the action `activeDropInElement.handleAction(action)`.
3. Scan the QR with Swish app and complete payment.
4. `onPaymentCompleted` does not fire when the payment is done neither `onComplete`.

Other steps that work:
1. At the dropin level `onAdditionalDetails` event gets triggered with paymentData, which does not specify if the payment is done or canceled.
2. At Swish level `onError` is getting triggered whenever the payment is cancelled through the app.

Any clue what is going there?

**Comment by m1aw** [comment]
Hello @KiprasJ,

What version of adyen-web are you using?
Also which callbacks are you implementing?

It's not clear from your description if you are using `sessions/` integration route, or `paymentMethods/` integration route,
[sessions docs](https://docs.adyen.com/online-payments/build-your-integration/?platform=Web&integration=Components&version=5.55.1#create-payment-session) and [advanced flow docs](https://docs.adyen.com/online-payments/build-your-integration/additional-use-cases/advanced-flow-integration/?platform=Web&integration=Drop-in).

**Comment by KiprasJ** [comment]
I'm using 5.53.2 version with `paymentMethods/` integration route

**Comment by KiprasJ** [comment]
Even on the latest version it's the same behaviour

**Comment by m1aw** [comment]
Hey @KiprasJ

There might have been a misunderstanding. `onPaymentComplete` is a `/sessions` flow callback. When using the advanced flow you must handle the result via the `onAdditionalDetails` callback. The information returned here is going to be managed by your backend integration.

**Comment by KiprasJ** [comment]
Alright, thanks for the information.

**Comment by m1aw** [comment]
Also forgot to mention, in the next major version (V6) this might change. We will keep everyone update on this topic in due time.
