### ISSUE TITLE
Drop-in integration - Fields are disabled

### ISSUE THREAD

**Issue by nenadepam** [Adyen/adyen-web#2529]
Hi, we have issue that is happening randomly for some customer, where fields become disabled.

**To Reproduce**
1. Go to (https://www.intersport.dk/)
2. Try to make order
3. In the end there will be payment page
4. Confirm the behavior(again this is happening randomly for some customer)

**Expected behavior**
Fields are not disabled

**Screenshots**
Here is is the example video from one customer https://www.youtube.com/watch?v=B70BcackH50

We use react with 
_**"@adyen/adyen-web": "5.53.2"**_
 and
_**"@adyen/api-library": "10.1.0"**_

**Comment by sponglord** [comment]
@nenadepam - I am unable to reproduce this issue. The card fields all remain visible for me.
Do you have any details about the browser or device/OS that this is happening in?

**Comment by nsinfoPRO** [comment]
Hi @sponglord, customer (from the video) is running version 120.0.6099.225 of Chrome and Windows 11

**Comment by nenadepam** [comment]
Hi @sponglord, customer (from the video) is running version 120.0.6099.225 of Chrome and Windows 11

**Comment by sponglord** [comment]
@nenadepam - I've tried Chrome 120 in Windows 11 (via Browserstack) and again cannot recreate the issue.

I was wondering if it was related to autofill. In the video the shopper has some saved cards which Chrome shows in a autocomplete tooltip - and it at this point that the credit card fields disappear...

However, I have tried this scenario as well (saving a card in Chrome in Browserstack) and could not recreate.

At this point, without some sure fire way to recreate this issue, I don't know how to proceed

**Comment by sponglord** [comment]
@nenadepam - ok. If you can, can you also find out if any cookie manager or adblocker is coming into play

**Comment by nenadepam** [comment]
@sponglord the extension [Uniqkey - Password Manager]([https://chromewebstore.google.com/detail/uniqkey-adgangskode-manag/ficgojolbnidcdnadicfoldjhaecfmke?pli=1](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fchromewebstore.google.com%2Fdetail%2Funiqkey-adgangskode-manag%2Fficgojolbnidcdnadicfoldjhaecfmke%3Fpli%3D1&data=05%7C02%7Ckst%40intersport.dk%7C0cac6f5243234564a0d908dc231dcc65%7Cf74507fb7f634be7b2b541fff8c3d514%7C0%7C0%7C638423858346772958%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=AhljuZ14JXCJx5XsonQ%2BF0yrpwfWLJIq6yf91UIBZVw%3D&reserved=0)) is the issue. We checked customer browser extensions, and once this one was installed we were able to reproduce the issue.

**Comment by nenadepam** [comment]
Here is the link to that extension https://chromewebstore.google.com/detail/uniqkey-password-manager/ficgojolbnidcdnadicfoldjhaecfmke
