### ISSUE TITLE
Must declare the property "paymentTiming" in the ApplePayLineItem interface since is needed for recurring payments

### ISSUE THREAD

**Issue by gerardcastell** [Adyen/adyen-web#2530]
**Describe the bug**
The ApplePayLineItem in your @types/applepayjs/index.d.ts must declare the property  "**paymentTiming**" since Apple requires it to be set as "recurring" to declare a recurring payment with Apple Pay. Without this property, the Apple integration posts a bad payment request so the result is 422 with a message of "'regularBilling' must be a 'recurring' line item".

In addition, it would be suitable to add all the properties Apple can accept, which you may find on [its website](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaylineitem).

**To Reproduce**
1. Create an Apple Pay component with the Web component integration using your package. Such creation must include the following config:
```javascript
    {
      countryCode: 'US',
      recurringPaymentRequest: {
        paymentDescription: 'Test subscription',
        regularBilling: {
          label: 'Test label',
          amount: '0.02',
          type: 'final',
          paymentTiming: 'recurring',
          recurringPaymentIntervalUnit: 'minute',
        },
        managementURL: 'https://example.com',
      } ,
    }
```

You will see how the linter complains about the paymentTiming properties and recurringPaymentIntervalUnit.
**Expected behavior**
Note that in the case of recurring payments with Apple pay the property **paymentTiming** set as "recurring" is MANDATORY. So we need to start there.

**Comment by ribeiroguilherme** [comment]
Hi @gerardcastell ,

We updated the applepay types on 5.60.0 . It should be fixed now. Cheers
