### ISSUE TITLE
[Web Drop-in] Allow hiding amount  

### ISSUE THREAD

**Issue by hbystrom91** [Adyen/adyen-web#2548]
**Is your feature request related to a problem? Please describe.**
In my team we are working a lot with recurring payments. The button that is rendered by the drop-in contains the preauthorization amount that we are charging. We'd like the to be able to hide that amount and be fully in control of the copy inside of the button. Currently it seems to work if the amount equals zero (thanks to this [PR](https://github.com/Adyen/adyen-web/pull/2514)), but since we are usually charging (only to immediately refund that amount) 0,01€ that always shows up in the button. We have tried to override it manually by passing `amount: { value: 0, currency: '...' }` to the config object, but that doesn't work. We have also tried to implement our own button component, but we ran into issues since PayPal doesn't support calling `submit` programatically. We exist on many different markets with varying payment methods, so we need a solution that works in all cases.

Currently we are exploring hacks to be able to handle the copy ourselves. We feel we shouldn't have to resort to this in order to get the UI right. 

We saw a [similar request](https://github.com/Adyen/adyen-web/issues/2229) has been closed before. The recommended solution doesn't work in our case due to the limited compatibility of a custom button implementation. 

**Describe the solution you'd like**
Enable passing a boolean for hiding the amount from the button. `hideAmount: boolean` would work just fine. For our purposes it would be fine just allowing it for preauthorization payments since we do wanna show the amount for actual purchases.

**Describe alternatives you've considered**
- Passing `{ amount: 0 }` to the the config manually.
- Using a hacky `MutationObserver` API solution to alter the drop-in after it is ready.
- Custom button implementation.

**Comment by sponglord** [comment]
Hi @hbystrom91 - can you please elaborate on why using your own, custom, pay button doesn't work for you?
This would still be our recommended solution. It shouldn't conflict with PayPal since that renders it's own pay button

**Comment by hbystrom91** [comment]
> Hi @hbystrom91 - can you please elaborate on why using your own, custom, pay button doesn't work for you? This would still be our recommended solution. It shouldn't conflict with PayPal since that renders it's own pay button

Absolutely! To use our own button we need to say `showPayButton: false` to avoid displaying two buttons. This removes the button for all payment methods, including PayPal and Apple Pay. I guess a potential solution would be to keep track of the selected payment method and add display: 'hidden' to the default button depending on that. However, that's outside of your API and it also feels like a hack in a sense. Hope that's enough.

**Comment by sponglord** [comment]
@hbystrom91 - I see your problem! 
However you can overcome this by setting the general, `showPayButton: false`, when instantiating Checkout but specifying in the `paymentMethodsConfiguration` object that the button should be shown for PayPal/ApplePay:
```
const checkout = await AdyenCheckout(
{
  showPayButton: false,
  paymentMethodsConfiguration: {
    paypal: {
      showPayButton: true
    },
    applepay: {
      showPayButton: true
    }
  }
})
```

**Comment by hbystrom91** [comment]
> @hbystrom91 - I see your problem! However you can overcome this by setting the general, `showPayButton: false`, when instantiating Checkout but specifying in the `paymentMethodsConfiguration` object that the button should be shown for PayPal/ApplePay:
> 
> ```
> const checkout = await AdyenCheckout(
> {
>   showPayButton: false,
>   paymentMethodsConfiguration: {
>     paypal: {
>       showPayButton: true
>     },
>     applepay: {
>       showPayButton: true
>     }
>   }
> })
> ```

Interesting. I don't know how I missed that. With that information in mind we should have all we need. Thanks for helping us out.
