### ISSUE TITLE
`showPayButton` not working for stored ACH

### ISSUE THREAD

**Issue by jaredtbates** [Adyen/adyen-web#2554]
**Describe the bug**
Hi there! We are using the Adyen drop-in and have an external button to trigger payment. However, the `showPayButton` property is not working when showing stored ACH payment methods. It seems to be showing the "Continue to ..." button no matter what we pass in.

**To Reproduce**

Here's a rudimentary code example:

```typescript
AdyenCheckout({
  paymentMethodsResponse: {
    paymentMethods: [
      {
        brand: null,
        brands: null,
        configuration: null,
        fundingSource: null,
        group: null,
        inputDetails: null,
        issuers: null,
        name: 'ACH Direct Debit',
        type: 'ach',
      },
    ],
    storedPaymentMethods: [
      {
        bankAccountNumber: '011000138',
        bankLocationId: '011000138',
        brand: null,
        expiryMonth: null,
        expiryYear: null,
        holderName: null,
        iban: null,
        id: 'ASDFASDFASDFASDF',
        label: null,
        lastFour: null,
        name: 'ACH Direct Debit',
        networkTxReference: null,
        ownerName: 'Jared Bates',
        shopperEmail: null,
        supportedRecurringProcessingModels: [
          'CardOnFile',
          'Subscription',
          'UnscheduledCardOnFile',
        ],
        supportedShopperInteractions: ['Ecommerce', 'ContAuth'],
        type: 'ach',
      },
    ],
  } as any,
  showPayButton: false,
}).then((checkout) => checkout.create('dropin').mount('#dropin-container'));
```

**Expected behavior**
I expect the `showPayButton` property to hide the "Continue to ..." button in the drop-in.

**Screenshots**
<img width="359" alt="image" src="https://github.com/Adyen/adyen-web/assets/2905521/db3dac41-1e32-4f1d-8bc2-c0b5d494e15f">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge (Chromium)
 - Version: 121.0.2277.112

**Comment by m1aw** [comment]
@jaredtbates this indeed seems to be an issue. Since it regards a few more payment methods we are going to issue a proper fix.

**Comment by jaredtbates** [comment]
Hi @m1aw! Just curious, is there a plan to fix this in the next few weeks possibly? Thanks!

**Comment by m1aw** [comment]
I have created a fix for this. Probably shipping this next week.

**Comment by ribeiroguilherme** [comment]
Hi @jaredtbates - we made a release 5.66.0 which should fix this issue. Could you please verify that?

**Comment by jaredtbates** [comment]
Thanks @ribeiroguilherme, sorry for the delay. This works great for us!
