### ISSUE TITLE
Slash not allowed in Street and House number fields in Drop-in

### ISSUE THREAD

**Issue by mihn** [Adyen/adyen-web#2563]
**Describe the bug**
When trying to input data  with slashes into **Street** and **House number** fields, I'm not allowed to do so. Slashes are valid data Polish addresses and this confuses our users.

**To Reproduce**
1. Start a Credit card payment using drop-in 
2. Try to input slash into **Street** and **House number** fields

**Expected behavior**
Slashes should be allowed as input in  **Street** and **House number**number fields

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version  122.0.1

We have adyen-web 5.54.0 but I've checked release notes and there is nothing referencing this issue.

**Comment by mihn** [comment]
Also checked 5.58.0 - same behavior.

**Comment by sponglord** [comment]
@mihn - thanks for bringing this to our attention. We will fix this in the near future.

**Comment by sponglord** [comment]
@mihn - this will be included in the next release

**Comment by ribeiroguilherme** [comment]
Hi @mihn  . It is fixed on 5.61.0. Cheers
