### ISSUE TITLE
Ideal issuer list not showing in webcomponent

### ISSUE THREAD

**Issue by RobKega** [Adyen/adyen-web#2585]
**Describe the bug**
While implementing iDeal payments in a headless environment using the 5.59.0 version of the web components, the issuer dropdown is not being shown, only the 'pay with ideal' button is shown.

**To Reproduce**
1. add container  with id 'ideal_test'
2. create checkout and mount component 
        checkout = await AdyenCheckout(config);
        checkout.create('ideal').mount('#ideal_test');

**Expected behavior**
The issuer dropdown is shown, together with the pay now button

**Desktop (please complete the following information):**
any

**Smartphone (please complete the following information):**
any

**Comment by ribeiroguilherme** [comment]
Hi @RobKega ,

Are you using sessions or advanced flow?

If you are using advanced flow - are you passing the /paymentMethods response to the `AdyenCheckout` ? Does it contain the payment type `ideal` along with the issuer list?

**Comment by RobKega** [comment]
@ribeiroguilherme I already found the issue and that was the issuer list not being fetched via de graphQL query, so it was not passed to the component.

**Comment by RobKega** [comment]
closing
