### ISSUE TITLE
[Web Drop-in] Trouble generating a boleto in test account.

### ISSUE THREAD

**Issue by lenodeoliveira** [Adyen/adyen-web#2588]
### Description

Hello! 
I'm reaching out because we're encountering an error when attempting to generate boletos with test accounts. 
When we send the information to generate the boleto through the drop-in, we receive this error: 

```
{
"message": Acquirer account 'BoletoBancarioSantander_AdyenTest' is no longer supported [This error message is only provided on TEST, this error will be a 500 Internal Error on LIVE.],
"pspReference": "QL4WW46DL6ZW8N82"
"status": 500
}
```

I would like to know how we can fix and continue generating boletos to carry out our tests.

This error can be reproduced in the demo you provided. Just click on the payment method as boleto, enter the data, and try to send the information; it should appear.

Obs: It is necessary to change the country to Brazil.

[Demo](https://www.mystoredemo.io/#/)

**Comment by camil-adyen** [comment]
Hi @lenodeoliveira, please reach out to support@adyen.com. They will be able to help you with this issue.
