### ISSUE TITLE
Bancontact test card numbers are invalid for version 3.11.0 and up

### ISSUE THREAD

**Issue by rouwe111** [Adyen/adyen-web#260]
**Describe the bug**
I am unable to use the test card numbers from your documentation in the Bancontact (bcmc) checkout form starting at version 3.11.0. The number is working fine on version 3.10.1 and below.

**To Reproduce**
1. Add version 3.11.0 or higher
2. Create the bcmc checkout form
3. Fill in a Bancontact test card number
4. Test card numbers are invalid

**Expected behavior**
The test card numbers are working and I will be able to pay with them.

**Screenshots**
![image](https://user-images.githubusercontent.com/3167988/92694113-d977f880-f346-11ea-94c3-1afcd7ea105f.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox Developer Edition
 - Version: 80.0b7 (64-bit)

**Additional context**
When I check the binLookup request, the detected brand is **mc** instead of bcmc.

**Comment by sponglord** [comment]
Hi rouwe111,
This is a known issue relating to the use of a `clientKey` in components `version >= 3.11.0` with _test cards_ on our _Test`_ servers.
Using the clientKey, as opposed to the originKey, allows the `/binLookup` functionality to activate.
However the databases on Test aren't as complete as the ones on Live so some test cards are not recognised. 
_But merchants shouldn't experience issues with real cards in production._
We are currently looking into the configuration of our Test databases to see if these test cards can be added to prevent this issue in the future

**Comment by sponglord** [comment]
Yes. That would be the best solution for now.

**Comment by sponglord** [comment]
The issue with Bancontact numbers has been resolved
