### ISSUE TITLE
Return some method to understand the Checkout version before initialization

### ISSUE THREAD

**Issue by oleksii-loian** [Adyen/adyen-web#2600]
**Is your feature request related to a problem? Please describe.**
Want to know version of the SDK before initialising it.

**Describe the solution you'd like**
Add Some static variable to the export.

**Comment by ribeiroguilherme** [comment]
Hey @oleksii-loian .

What is the use-case for this? You know the version since you are integrating directly with it, no?

**Comment by oleksii-loian** [comment]
Use case is to send to Product Back-end version. Then product back-end will decide what version of Adyen will be using.

**Comment by sponglord** [comment]
@oleksii-loian - can you elaborate on what exactly it is that you want?
