### ISSUE TITLE
Unmounting and remounting secured fields destroys card brand image element.

### ISSUE THREAD

**Issue by RyanONeill1970** [Adyen/adyen-web#2608]
**Describe the bug**
When trying to clear / reset the UI fields for card details the image element with a class of pm-image and id of pmImage is destroyed which causes the onBrand callback to fail when a new card is entered. The onBrand callback can be made to work if this element is missing but then the card image (Visa, MasterCard etc) does not show and the UI is out of alignment as an element is now missing but not accounted for in the CSS.

**To Reproduce**
1. Use a custom card integration such as the one at https://github.com/Adyen/adyen-secured-fields-sample-code/blob/main/index.php that has a pm-image element.
2. Enter 4444 into the card number field, you'll see a Visa image next to the card.
3. Using the console or a test button, call cardComponent.unmount followed by cardComponent.mount to clear the card number.
4. Enter 4444 into the card number field.
5. The javascript will error due to the missing image element and the card brand will not be shown.

**Expected behavior**
That the card brand image element is not destroyed and survives an unmount and remount.

**Comment by sponglord** [comment]
Hi @RyanONeill1970 - you are looking at a very old version of the custom card integration. 

May I suggest you look at https://github.com/Adyen/adyen-components-js-sample-code and try again with the Custom Card component there.
This uses a much more recent version: `5.51.0` (and in fact we are now at `5.60.0`).

Working with this codebase and following the steps you outline I couldn't reproduce your issue.

As a side question: is this a real world use case? Are you trying to create a means for a shopper to clear all the fields?

**Comment by RyanONeill1970** [comment]
Hi @sponglord ,

I've looked at that demo site and although it uses secured fields, it does not seem to clear them out. Perhaps I am missing something.

The version this occurred on was quite recent (5.57.0). I've since updated it to 5.61.0 and it is still occurring.

I have a workaround of recreating the brand field image now (below) but I think the root issue is still there.

        private resetCardComponentUi() {
            this.cardComponent.unmount();
            this.cardComponent = this.configureCreditCards(this.checkout);

            let cardNumberField = document.querySelector(".card-number");

            let img = document.createElement("img");
            img.setAttribute("class", "pm-image");
            img.setAttribute("id", "pmImage");
            img.setAttribute("width", "40");
            img.setAttribute("src", "https://checkoutshopper-live.adyen.com/checkoutshopper/images/logos/nocard.svg");

            cardNumberField.insertBefore(img, cardNumberField.firstChild);

            // Reset any validation CSS around the secured fields as they are now empty.
            this.onFieldValid({ rootNode: this.securedFieldsDiv, fieldType: "encryptedCardNumber" });
            this.onFieldValid({ rootNode: this.securedFieldsDiv, fieldType: "encryptedExpiryDate" });
            this.onFieldValid({ rootNode: this.securedFieldsDiv, fieldType: "encryptedSecurityCode" });
        }

**Comment by sponglord** [comment]
Hi @RyanONeill1970 - I'm still trying to understand your use case? Are you trying to create a means for a shopper to clear all the fields?

What I experience:
- I run the `CustomCard` at code at https://github.com/Adyen/adyen-components-js-sample-code
- type '4444'
_the Visa brand image appears_
- In the console type: `window.securedFields.unmount();`
_ the inputs disappear_
- then type `window.securedFields.mount('#card-container');`
_the fields appear again_
_the Visa brand image (& errors) remain (this is expected behaviour, for the custom-card you would be expected to clear these yourself)_
- If I then start typing 4444 (for Visa) or 5500 (for MasterCard)
_the brand image shows and the `onBrand` callback is called with the correct brand information

What's happening differently for you?

**Comment by RyanONeill1970** [comment]
Just checking that code now against the version I have.

**Comment by RyanONeill1970** [comment]
Yes, I am trying to clear the UI fields because in this case the customer card was declined and they switched to another payment method outside of Adyen. When switching back, leaving the old data there causes other issues.

I think I've found the reason. In summary, it's because our implementation of the card number field contains the brand image within it, but the demo version has it outside. When the card field is unmounted, the additional elements for brand image are destroyed (or destroyed on re-mounting).

Not sure where our version came from? A screenshot of how it renders is below.

![image](https://github.com/Adyen/adyen-web/assets/1757324/fdadbd7d-1041-4a0d-a09c-7b74d8043a2f)

**Is what we have done not supported or have we implemented it badly?**

Our markup looks like;
```
<label class="pm-form-label cardnumber-field">
    <span class="pm-form-label__text">Card number*</span>
    <span class="pm-input-field card-number" data-cse="encryptedCardNumber">
        <img class="pm-image" id="pmImage" width="40" src="https://checkoutshopper-live.adyen.com/checkoutshopper/images/logos/nocard.svg" alt="">
    </span>
    <span class="pm-form-label__error-text">Please enter a valid credit card number</span>
</label>
```

The demo markup looks like;
```
<span class="pm-image">
    <img
        class="pm-image-1"
        width="40"
        src="https://checkoutshopper-test.adyen.com/checkoutshopper/images/logos/nocard.svg"
        alt=""
    />
</span>
<span class="pm-image-dual">
    <img
        class="pm-image-dual-1"
        width="40"
        alt=""
    />
    <img
        class="pm-image-dual-2"
        width="40"
        alt=""
    />
</span>
<label class="pm-form-label pm-form-label-pan">
    <span class="pm-form-label__text">Card number:</span>
    <span class="pm-input-field" data-cse="encryptedCardNumber" data-uid="adyen-checkout-encryptedCardNumber-1"></span>
    <span class="pm-form-label__error-text">Please enter a valid credit card number</span>
</label>
```

**Comment by RyanONeill1970** [comment]
Yep, sorry to waste your time.

**Comment by sponglord** [comment]
np :-)
