### ISSUE TITLE
Updating the translation for 'installments' doesn't add a label above the installments drop-down

### ISSUE THREAD

**Issue by woudsma** [Adyen/adyen-web#2609]
**Describe the bug**
We would like to add a localizable title above the installments drop-down. Updating the translation for `installments` doesn't add a label above the installments drop-down. Searching the code for `i18n.get('installments')` shows only 1 result so it seems like it's unused. Should there be a label or is this intended behavior and is the translation used for something else?

**To Reproduce**
1. Enable installments
2. Initialize `AdyenCheckout` with translations:
```js
translations: {
  'en-JP': {
    installments: 'Installments',
    installmentOptionMonths: '%{times} installment(s)',
  },
}
```
3. Select a card in the web drop-in
4. Observe the installments drop-down (see screenshot)

**Expected behavior**
A label/title is shown.

**Actual behavior**
No label/title is shown.

**Screenshots**
![Screenshot 2024-03-21 at 12 50 20](https://github.com/Adyen/adyen-web/assets/6162978/292716e7-4afb-48bd-896e-9f244562bfe6)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.2.1 (23C71)
 - Chrome
 - 121.0.6167.184 (Official Build) (arm64)

**Additional context**
It seems no label is rendered because of this prop: `useLabelElement={false}`. Used [here](https://github.com/Adyen/adyen-web/blob/3ce12ef069ba39c4ae9c5f794261f5bbffb87e9a/packages/lib/src/components/Card/components/CardInput/components/Installments/Installments.tsx#L125).

**Comment by ArjenLa** [comment]
Hi @woudsma 

The designer team here, it should indeed have a label!

Thanks for flagging this

**Comment by sponglord** [comment]
@woudsma - sorry about the delay!
This issue will be fixed in our next release
