### ISSUE TITLE
Runtime error caused by `@babel/runtime-corejs3` & `core-js-pure`

### ISSUE THREAD

**Issue by amirakbulut** [Adyen/adyen-web#2620]
**Describe the bug**
Issue related to the package `@babel/runtime-corejs3` importing `core-js-pure` while running my Vue application.

My browser console throws the following error:

`Uncaught SyntaxError: The requested module '/@fs/Users/xxx/Documents/projects/xxx/node_modules/core-js-pure/features/promise/index.js?v=570da9ba' does not provide an export named 'default' (at asyncToGenerator.js:1:8)`

This is caused by the following line of code in `node_modules/@babel/runtime-corejs3/helpers/esm/asyncToGenerator.js`:

`import _Promise from "/@fs/Users/a.akbulut/Documents/projects/embeddables/node_modules/core-js-pure/features/promise/index.js?v=76e5cea3";`

The issue is that there is no default export for `_Promise`, as the file contains the following:
`'use strict';
module.exports = require('../../full/promise');`

I confirmed `@adyen/adyen-web` is the only package in my application that uses `@babel/runtime-corejs3` & `core-js-pure`.

**To Reproduce**
- Use Node version 21.7.1
- Use NPM version 10.5.0
- Install `"@adyen/adyen-web": "^5.53.3"`
- Run your application (Vue `v3.3.4` in my case)

**Expected behavior**
There should be no runtime errors.

**Desktop:**
 - OS: Macbook M2
 - Browser Edge

**Additional context**
The issue only seems to occur very recently, I noticed there has been a new tag release 3 days ago: [5.61.0](https://www.npmjs.com/package/@adyen/adyen-web/v/5.61.0).

However I tried to install  `"@adyen/adyen-web": "5.60.0"` but it did not solve the issue.

Help is appreciated.

**Comment by Isnao** [comment]
Vue 3 is ES module oriented....
Either use the module version through @adyen/adyen-web/module or @adyen/adyen-web/modern
But both use commonJS modules....

In the Vue config, you have [transpileDependencies](https://cli.vuejs.org/config/#transpiledependencies) that could help you (in Nuxt, there is build.transpile)
But be careful with SSR or server rendering of your component using Adyen. It can easily send errors and make your page inaccessible

Personnaly, I have been able to use it in Nuxt@3.9.0 but once I use the method closeActivePaymentMethod, I'm unable to come back to the dropin :/

**Comment by m1aw** [comment]
@amirakbulut indeed, you can go the route of using `esm` or `modern` bundles that are also shipped via npm. Let me know if that solves the problem.

@Isnao can you open another issue for the `closeActivePaymentMethods` issue?

**Comment by m1aw** [comment]
@amirakbulut is this still an existing issue?
