### ISSUE TITLE
Translations revert to US after switching

### ISSUE THREAD

**Issue by RobKega** [Adyen/adyen-web#2624]
**Describe the bug**
When using localisation we noticed that after switching payment methods and re-mounting the a component, the translations are gone and are reverted to english.

**To Reproduce**
1. Go to checkout page
2. Click on first available payment method
3. Click on second payment method and then the first again
4. Translations are not there anymore

**Expected behavior**
Strings are still in the language/locale of the configuration

**Additional context**
We are using version 5.22 of the adyen-web module in a React frontend.

**Comment by sponglord** [comment]
Hi @RobKega - can you give us some more details of your implementation? 
Are you using the `Dropin` to display a list of payment methods or are you generating your own list and then mounting individual components when the shopper makes a selection?

**Comment by RobKega** [comment]
@sponglord We are using individual components, the switch happens after the second time a component is mounted, configuration is built every time using the correct locale. 

Another issue we are having is that the showPayButton config directive does not work all the time, if we set it globally to false, enabling them per payment method does not work (for paypal and applypay for instance). But if we globally enable them (or don't set them specifically) , disabling them for certain payment methods doesn't work.  I feel somehow these things are connected since it both involves the component not adhering to configuration

**Comment by sponglord** [comment]
> We are using individual components, the switch happens after the second time a component is mounted, configuration is built every time using the correct locale.

Are you rebuilding `AdyenCheckout` every time you unmount a component?

**Comment by RobKega** [comment]
@sponglord Yes, with the exact same configuration.

**Comment by sponglord** [comment]
@RobKega - why do you need to re-create `AdyenCheckout` every time?
The expected way to do what you want to do would be to keep the same instance of `AdyenCheckout`.

And when you are mounting a component for a second time - are you keeping a reference to that component and calling it's `mount` function? Or are you making a new instance using `AdyenCheckout.create`?

**Comment by RobKega** [comment]
@sponglord The reasoning behind the recreation is that that part of the checkout is a single component that sort of works like an accordion where the customer can choose his/her desired payment method and fill in the data of that specific payment method. Lots of actions trigger re-renders and that is why the checkout is rebuilt every time
