### ISSUE TITLE
challengeWindowSize not respected on 3ds component via createFromAction

### ISSUE THREAD

**Issue by dan-drews** [Adyen/adyen-web#2638]
**Describe the bug**
Challenge Window Size being ignored on 3D Secure 2 Component. We are specifying challengeWindowSize: "02" on the threeDSConfiguration object, but upon redirect, it's using the fullscreen version

**To Reproduce**
I have followed the instructions at [this link](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/web-component/?tab=create-new-component_2) to perform a 3ds challenge separate from where the payment is collected.

```js
        const iframeDefaults = await getIframeDefaults(token);
        const configuration = {
            ...iframeDefaults,
        };
        const checkout = await new AdyenCheckout(configuration);
        var threeDSConfiguration = {
            challengeWindowSize: "02"
        };
        const tokenData = await get3dsTokenData(token); // This pulls back the result from the original API call.

        checkout.createFromAction(tokenData, threeDSConfiguration).mount("#my-container");
```

**Expected behavior**
The size argument passed in challengeWindowSize should be respected and not ignored

**Screenshots**
Here is a screenshot of it in our demo page we've built for testing this
![image](https://github.com/Adyen/adyen-web/assets/2341007/e9ac84c0-068a-49d6-9ac0-52377c1072bb)

Here is a screenshot of it in the embedded browser on our mobile app
![image](https://github.com/Adyen/adyen-web/assets/2341007/b15a2393-98c2-4d95-a759-8028f3d1255c)

This is happening on both web on desktop and in our mobile app using the embedded browser

**Additional Details**
We handle this in an iframe, but I have tried pulling this out of an iframe and we experience the same issue. I have also tried making a sub-object of the `threeDSConfiguration` object called `threeDS` to match how it works on the drop-in components, and that didn't work (I didn't expect it to, but just wanted to provide debugging details)

**Comment by dan-drews** [comment]
I assume you mean adyen-web and not checkoutWeb? If so, we are on 5.1.0

but I upgraded to 5.62.0 just to see if that would resolve the problem and it did not

**Comment by sponglord** [comment]
Yeah, sorry "checkoutWeb" is just our internal name.

Can you share the contents of the `tokenData` object that you pass when you call `checkout.createFromAction`?

When you talk about "redirect" - is the 3DS2 process _literally_ redirecting to another page (as opposed to staying "in-app" and opening a 3DS2 component in the mounted container)?

**Comment by dan-drews** [comment]
Yup, tokenData is just the `action` parameter of the API response

```JSON
{
    "paymentMethodType": "scheme",
    "url": "https://checkoutshopper-test.adyen.com/checkoutshopper/threeDS/checkoutRedirect/H4sIAAAAAAAA_2WKSw6CMBQATwM7iULqZ8ECxRI1-EUT2Zhan7QB2to-Qry9Lk1MZjUzUiFUlqHUKmZG3liHwpfOdWDPtokFonFelHgh_cIF8Fp36IQ2BuwAwWHAHm9QAdft__A1KCxAegoDJ7BtvIgaZ47wBAuKgxelRTlZbLMLCQs6C_dj4v_2-K86WcVCbUuK037UsSEkK8IPa0ZrRfN7_SIkz6Lrct7DbLepkw8h_Frg3gAAAA",
    "method": "POST",
    "type": "redirect",
    "data": {
        "MD": "M2RzMi5mMzYyMDk4ZGFkMzYxNDc0M2ViOTFhNjE3YTc2NjExY2ZkYjAzNjkxNDc2MmJjOTYyY2FmZWI3MGJhNzg5MTgzLjIuH4sIAAAAAAAA_x2QyW6DMBBAfwX50FMhNmaXogqyNT2lLFKRIiGDTaGl4BpDlEb595rMZQ5vljdzAwgEIJrajjIhBetpEZGO9BUrsqRId0kKngGyVE0jJR-D8-q8olSwy1hKnfPR6D_F8G20wwIwHY1G_nQvXAxzqwauCb2y_qmla9_BsKwZ0jFlULdKaumeiahuujapTZfgyvHUJlMt4lNpzKbhQeRgG7sQmRghiAwh_3IRn_zM9_KPN8e6HId5Gur3Imc89_oUz014GOPN7-txcYaL9OHk73d7J3Q2rhVGEIfuA2GFtssRWspGqYWLpRazL1Y9sA0CuGRlcwPVJNRbqqtqyZKt4jPpJgYCG6m43_8BG1ih9kEBAAA",
        "PaReq": "BQABAgBJDDlscHAeAFoqdFID4WMiZcfrNak1Ljap6g_NtgfABULlNJYEefmAU4eLIgaCqvx2iQ_lKA-OP9996QVnbnHXecHU6XaDLvgLIN2bEaFyldMTJPFkddgilQ7bTAYBUVCsASxp60WKklyz9OAZ1BDmu10B8FKm10mOvQAhAHJ4zJJJqOHlFzKsFe_kJgr1jtQMl2wqppmr0xlO0kQz_h4EH_kZOh-nm2rsL5pjRDPt_ATErr53xTnKoiye0Jr0SaBz02i7jO8_sGj-NWWbFx6qq25YyhbUh64i_8t7Vz0YvUqaJiOhJW6AmG8GiLJ8SNe3piN136ZTgu9U-a0pYR69-3pVc_V760qarAtp2_bwdbnc1qIcmwTtsIWbn_iifdVgDDAB_sr6QSKNjByJ6H6jBZhiWDGB-7lET7FIztiTsoQt0jU35nu3i7HdtomWwxuKtriT9DKD_2WJoXYSBMC0azqSaNjx2oT7h4LBKJGmg7vXipkysB0BPJx8rjsSv5Wmr2krWvSDUgpaaJG0xXZO9UmmwS6FJEKtZpZG_ERCxEWuJP1jnqT_szE2ZCvmAr-iMlJsxGCCjSC73VvDpqDwD9Wmnc4j9wpHa-mWCVAa_VNeyas9UNk5KYRQE3f72feI3kmhJI6sou6xQW-ijFW2wLe83ha4uK6OzAMNqAyWRgwR7bp7oxx0zGPsjxoASnsia2V5IjoiQUYwQUFBMTAzQ0E1MzdFQUVEODdDMjRERDUzOTA5QjgwQTc4QTkyM0UzODIzRDY4REFDQzk0QjlGRjgzMDVEQyJ9wkLqgHPbYCf_TfGohrvLGPCuVOBPh86-5hnBb-uX47ZDwmr3VfN3x35Qc2I3DQ8670v6-0bJBWqmKM3pOJr3QhsPw35aYqrMbR4EG_mO5U1saPvu9gOsjrGmrsWVsbdfb0HMaaYwtRV_3vCJINRdlV8wO2JCKa5xz-cjBvL39wCmq2wwnrn_-iHF_MvFl39BIJiUnBxH0prGnld8Mz4uY60xFvbTP03vfwA-9HKDnwnodvwadpGdpOkZNDrs-p-u_zF7te2DopxGazsSFdbRy_mOP7vNQAycYRrdUKctfOZkJ1GRtKnaLZLI9ethN44tInI2Ma_YzbpgGlnE-lMVc_0XG5cF-sCJVCDPiDjYUgkYXkltJpB6sW0ZoJzqL6qAkv03u7cyG6EITBcISoUFUBCDnv4rukkVLT9V-ZPhHfOOu-2LQWzaCIiS-dLtJ5a8J-SJQoLqwDI88Zpxr1mEawkrcrw1urcZTy-0QTzHO6Yn22O_TvpQkg8_wfd-yt2Rafb0z-NOvToBTYWQpt91aago0yqfyiBrzGvE3TBDa32OGFNevCV_beqdLjIuBQABAQAUa-HMP4oscRj2RNfcqZqeyua_bNTkDCgaMW07JxbUfz5qsbm60fO0kt7wV_EQQ8vwfdcwmgQin6UIxJ68ydyGg1YASDhdRQu7B4u3ZMV50JFyM2UdGITl55szkcM2euZtolnBBQUaBksgd2O2gBu-FSYVOKc6MErebOlybPEGlBl7cpmAajR0j25tyIhBFKmHTBINBXdeRkwsvhtGE0C4AsZKb2sVM9LhhpG7l-jK2BgEjRJNaT8n16yw0RXXECLKlbdXYCL2a6-FEdC6nqzlO5DxDs9sDJBUyrXK539YtA_1WWMxFJFGdbHKLmxQWcjn_jKA95gIRw1loDJH2ugEDOt4uGXpCEwJSB0ClwAAkqLgbaoUd2nHBNlzhRvAqFPgRyEpM-HtppkUNbLcGhIVxJ_LVqA1oM1I2YA4YVFyXQ210-GSlWXJP4trakEZvlytouLSre2eth_5cu88RJFWPmcN_5tzWIxVDROJjpBQPIrtB17s_s72RFmVcU0TOULHlveBfJfGL6qgYI9przd6KIZzgzOi96owdwyV64ROcCtzS_I_NHT55I_IxgSnvYb_vwTCvl4O1SAwNkCkaemgpxHxssIMmrJ8--fA5V7m0aNc6WS7iJL6Al0vE_DQb7QXrLQeTtlMC0Z_020TjUHf5rJhjxUUzQZfUnU8UjP13cXejzR-itZk2rZLG-vsYhrYT9DyFySv3pVGXfpQp2RWyCD7dr1FIVVk5k2l0Zy-N7x1kt7t8tgJ87leJXfF6b5gjG_55Ny01mj0iJFBEeISMu6qQjAjtSqUzidhBrwuFnoNZ7R8NH5qmapKtOuBq3pTrs4lUNkIl3YhuvpQMTIwSP1mcfB2BL3TpzRjdkF0548a3WZCcUIhMQ24ocqQ7deoO_qEvY2e4_a0QrV4tQscWH2A2KXhqiAm5df986z1X_7C0n9dey7nCwJk2i0oWRL5NeR09oTUgqeJGC4dGUTXTsk_tvRo3Dcg4mqwoWkI9rl9-_S75I8mLupaTt7LolTXh2cvgbpb2d_CRHdfqgQS1AaKPs5hMCWRcwMaC8NgDpIdKz-rjncHvbqQP1IpUuhDtSMpjDkIqN-DWdmpcDLr-QJ_EsKcZzwjdQWTr97zMdWH-mGGQraecrYfOMs0Fwu-ovivBsuqs65kIy21LAW8-2KrJ4YNT9sDaQYtbUfNq5aThLDPNMptPaKsvzi7xnLEZhVuFO-BQBuTOB8b1NDH2J6jwM38SDb5Q1yst-7ciQcB42JX34bui7mVXF7sc7m5jH0Nu_zAob8hqsV2gnSgl8t7gZK9lrLauROKQVCRV-8wHUrCP39U4tQAuAj8d9nwcchBkR0WLz_MxrFX_U2xmGCKIJfVXoJQ8VYulguCR4Gm7evpEquYReZ5piDaQuVwOVO9wIvmReTsHd1xpv8GRBEyhtXRFMb1R65K-UHvvs9JBzVR1g3lkaIyP0MgHnAHH3-tzLTQfi0ylz2zrp1X_rHLw22mKACueUSRR6cQ1g3EWj3qoXaBwiu33iSHUfQk6-fa4H-fdv-VLwv6z_1_ki8UuRPFHid2my4y5Rr8rkNCIW_iKVcy-8HRQzqQh4XKAUcgv6xjYEeHBZSPVf888CgnRLhqOTU4ApBN-L394k85l4w7otL07trBlayFtzXYy5wV8C2oiQsUnIMynse_W8rtmMBHooVsU6r4VB4xit-3Y3dKYhNJ4sEd0iMbopdAvVzEz4s78Fhyp7LR4JFDcH7M5SoXN1DiCxbnFwlBNz8TJWP2zEyy5cjCk2x_WWZ2HIZAT8lpno275PSO2TLM48d1A0rZ-tEdHYPsiiEGNqVQbFRG0jGeshJa5iknmH-4dUnr_zpuVC_YGL1GzBDH6pK-yNoPvYmSEQ8pDxJ0glqYEeLxx2JDXS1blxq3kxzJbOPKN-_RXUcXxWkPgsHmVMUqql4PCBDj0sAFIibUHMgjophEe7GG8olFoOObsVPSrpFaiszbhuF0hEZdkMZwIORBJpNSB1YruepHGqzSSp0oFwcLR8GkyQh7Sdz6ZsLHI4JesgjjAW9a0XzzT31rEcTW8NbVTIT127dFMePjpQlpuoZlEPg3AJGqh-3nF2nMNyeryTFGpd6yWN-83Lt-OaxTMLVLoeRszDQUw-uJAmEqKD_sCSXB-qsohadmOMWNRdH9HfwzrG1yGq_Ow8zOb4Gxx8pSnqXqBnVKtZc2uT03czCyxIhJQ71t1Z9KiDWDv8thWXoRTiE_t0o_HnXgP5ZP3HjU1tLy5A5nnQ2rD5Puyo0Q_xUtc4N-whDpyBQAOiRSOWFdZ0TnSPiG6SKkTKYYQTEbrsdrdoGrcgG4U8s9KvsECqYN7hwDxvJVqK3D5-khQNVlS-eMlEZVM1WxKzyAjWn8szuSYim8z_TVX1IcG0Zfk-6VMZN8n5NURbARP3OBlqLzPAg-C7n0p8pYzMMDAUgdVpjGvIeSzDio7_bj5hhPUk-sSyF6eWaeYBqReZrFQ-gPEKAyMEeuAdom5A8kBNDzhY6cIxi_42ExyNmZDCQmaL9mKKky_TNN5QMrqb8iJWGmJSQlX4TsRByfX009EWOFGdYgXC_4gTKuKooDa6sdxyZf6l6hvTWt80KnILTZI_PqEvMflXDWNTGZhHVhtkqhZ_7cFafWrg-dJoCUmJWDEb6IqxrwH8BUDcESQIPP5p3ZZ65ZgQIPIlLJpOnxJhNKXAJZqNfYWixm0_RWbhFZQZw2z7mQEYYXEQj3c-IZVcLKhL5qFePUWD1gxPev4xSziYXdF_EXQUcDjkb0OrqZR72McDmRdwq65XB80en5Jwlms5hUpB8VZosWf-R7O3oUnHgCxIKrzNo3JBiuA_Ayh8xK7BSothg2bHiRaG4MHkIU9RoofqwPumP1g06nTT9GgQM6ojutMHruXM3orQvtAW1kaRwaR5_k6ovIva4vm1hJgzgbXTLQsferI_dZdq_1BThXB5m5emLFn2czGaEQeTYZXSq2Ma6O4dn5IOgc6xDH-jyPrxMbL2oEhn3s8saKfrCg9-2NBA1xctdFEnzX6AUT8kig6t-n5stZ5G9yR_19zIIw_RwYe4DuSc_xi-kIDjnahe8XUc5oU0Vh1SFWXvh-GojWe1sWph8iOSU2T7LIG195fbbk0gk2F-s4baampXuErZESjL-366oFHtogZ4-ZRI0w7HbeG1ojaSNmbEDoVX93xxRQojM7QlYRWU3_Z_cebFnN3E1bsQ6Xuap4WrilmTYln-BvVaLogABGHLKs7S1S71QjgUr0f7zq0hqcBUmuXUfXmo9ljPNZD9R_nvLx2kn8Qf041h97e4lEjAm759HebhmtCX9I3w5RAyTJTmKlwKjHLBXL4MIhqPBiBwt0j8lHizOHKbUM2WxU9WGmk7rrKun-oBEyDwZJWoOANEEVhBEDloEO_UZUYSpWHEfco4YlEdikSJUyPTuMhJMc_QmHmW172XSHx7agnk3MRiqLvyjO8EKC3ew99tMWUNfUckbhARPu8XuqRHls9dzDQy49Qbspp0FcrilWi2FRovVCUOPLMrQ6eXcbaDUSnPnmUR6DP_UGFB_RvyrEcVt-TjwsnT4m2qlrlnvH5eEO7wkaU6Q_Z2n5_cKvx98yUPR0B8frfADqGrojbBidz_YKxFdJbqwWKN7ecg2oA6T6V126tSWXQ2hVPXYeS5V0ibJ_pSkTyGWfZszgGWMlKezhMw5AWOpUQJOdKV1dT_RXVEODieWGnwm45kK5qyOZh5G1bvAlm0sosyrtsjUVdxRbRiIS6e01sIYzWjo8voniV1ecKYJkn3wGf2kxv5zM_vnB-ZP0_v9QcVm2dFVmEtGQ_i0SnpQlCSFTXRLhX3B8W57btu_DSIk8kmrHO9P8R6rZgUkcaOcST1dBBmCrfgZ3ZyN8_qo88nDp57e3cV81iZqK81PSxKckMtWbhKalYpTaaVhUoUvrO_5dp_PKIFPlDM9tQ9NgiWNjxQ2nAbpGpxzeRYQj_vuAfsnDbYn8oVFX4xy3VrwG0KRlm8OitGZGEBubFYTiolbsiLsJy1iB4WIAQU8ZT5MVBHTLF58exZFixw-tePTmmRUI49A1fkMC2n2-lFY5Cn1wlJMGrdGmXKAB7o0eDQQsdozDcrGkgkbhcqwcxMHbVF_4zJ0G0iz4MRkTYiTPjfNiumVvsSOFG3qPjYT78DyrnzqDZsBrlB3VlPM66MCJdp10IWOfhQpAGUSaJw4Zvsf2SKPHpV_wUrYdVD4mmyYMRbpazV09UdP0W8quki-4YQ4wSgCrMiFhOoMhPremkUqmlfuaAb2_S0eZfpE7EPp_M6ynP67gTrFBgBGEpY6P1tVJUzw0q3rrOJgeGsGKR3N2pSadJKmEpc3G8cGF8p5IUf39qgaWJZiY7ZZqpZsMC9BbqPR_gE33HrkXTVDLtK2tR0dq_ai1uCPVVDbyBDKrHMdFWarE94QwbCeKVaxQScnF5PExO7dOClwM2tDv_Q"
    }
}
```

Interesting question about the redirect. As I mentioned above, we are doing this process inside an iframe on our end, and the top level is _not_ being redirected, so it still appears to be in-app. However, iframe _is_ being redirected.

So what we start with is:
- Top Window: MyDomain.com
- Initial IFrame: Payments.MyDomain.com

But after initiating the 3ds process using the code above we have:
- Top Window: MyDomain.com
- Iframe: checkoutshopper-test.adyen.com

To me that means that from the context of the perspective of the 3ds process, it _is_ leaving the app, and it's not opening it's own, sub-iframe. Not sure if it's supposed to do that or not, but it's not happening

**Comment by sponglord** [comment]
Thanks, that explains it... this is what we call the "3DS2 in MDFlow". Which is a full `redirect` action from the start... this means that you are moving into another part of our system, away from adyen-web... which is why your `challengeWindowSize` config is being ignored.

In this part of the system the value `'05'` (full size) is used by default.
I'll contact the team responsible for this and find out if it's possible to change/control this

**Comment by dan-drews** [comment]
@sponglord yeah, i kind of figured that may be the issue. It'd be nice if the size can somehow be passed as data to the POST call that is made in the MD flow which kicks off the process.

Is there anything we may be doing that's forcing it to use the Redirect flow instead of some other flow? I know that in the demo page it's working properly, but that seems to be using drop-in instead of createFromAction: https://www.mystoredemo.io/#/checkout

**Comment by sponglord** [comment]
What version of the Checkout API are you making your `/payments` call against?. 
The configuration in the `additionalDetails` (API <= 68) or the `authenticationData` (API > =69) object added to this `/payments` call will influence whether a redirect happens or not. (Ref: https://docs.adyen.com/online-payments/3d-secure/native-3ds2/web-component/#make-a-payment)

**Comment by sponglord** [comment]
Regarding the `challengeWindowSize` - it's also possible to set it in the `/payments` request: https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-additionalData-listOfValues-challengeWindowSize

**Comment by sponglord** [comment]
Yeah, that should work... do you have a PSPReference for a payment?

**Comment by dan-drews** [comment]
Yeah here is the PSP reference: BNB8SFGFTQ266N65

**Comment by sponglord** [comment]
From that reference we can see that the `challengeWindowSize` is being propagated to the relevant system - so I need to contact the team responsible and find out why it's not being picked up

**Comment by sponglord** [comment]
@dan-drews - so apparently something is not working with the mapping of the `authenticationData. threeDSRequestData`

In the meantime though, as a workaround, if you send in `challengeWindowSize` in an `additionalData` object (https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-additionalData-listOfValues-challengeWindowSize) - so `authenticationData` to trigger 3DS2 and `additionalData` to control the challengeWindowSize - this should work

**Comment by dan-drews** [comment]
@sponglord That sounds super promising, but I'm still struggling to make it work. Would you be able to provide a sample of the JSON for additionalData that should trigger this? I've struggled in the past to understand the JSON structure of additional data. Here's what I've tried, with no success. Each of these triggered 3ds as expected but they all triggered the full-screen view. 

```json
// PSP Reference: JKDNHT78T9D4STT5
"additionalData":{
    "challengeWindowSize": "02"
  }
```

```json
// PSP Reference: G4XL4JSXC8PQ7RT5
"additionalData":{
    "3DSecure.challengeWindowSize": "02"
  }
```

```json
// PSP Reference: NRQ2VJSXC8PQ7RT5
"additionalData":{
    "3DSecure": {
        "challengeWindowSize": "02"
    }
  }
```

```json
// PSP Reference: RG4DQ9S62TF92P65
"additionalData":{
    "3DSecure": {
        "challengeWindowSize": "02"
    }
  }
```

```json
// PSP Reference
"additionalData":{
    "threeDSecure.challengeWindowSize": "02"
  }
```

**Comment by sponglord** [comment]
It should just be the first one. But you're right - it's not working... I'm following up with the other team
UPDATE: they're fixing it!

**Comment by dan-drews** [comment]
@sponglord Thank you! I'd like to pass this on to my PM, is it too early to get a timeline for the fix? We are hoping to launch our 3ds integration soon, and we are deciding whether to wait for this to be fixed or just send it as is, and expect some minor usability issues

**Comment by sponglord** [comment]
They've said the fix should be on Test next Thursday (18th April)

**Comment by dan-drews** [comment]
Good morning @sponglord is there an update on this?

Maybe I'm too early, but I think Test has typically deployed by now on Thursdays. I have tested with both authenticationData and additional Data and it did not work

```JSON
"authenticationData":{
    "threeDSRequestData":{
        "challengeWindowSize": "02"
    }
  },
  "additionalData":{
    "challengeWindowSize": "02"
  }
```

Here is the PSP Reference: HHC3TX2WMLC52VT5

**Comment by dan-drews** [comment]
Actually, it looks like it worked on next try

**Comment by sponglord** [comment]
Yeah, it was behind a feature, that got turned on about 4.30pm.
I can also confirm that it is working in both flavours (`authenticationData` & `additionalData`).
I'm just awaiting confirmation that the feature is staying on, and that the fix will be Live on Monday
