### ISSUE TITLE
How to style pseudo classes for the Adyen input fields

### ISSUE THREAD

**Issue by ashrafnazar** [Adyen/adyen-web#2677]
**Is your feature request related to a problem? Please describe.**
I would like to be able to style a pseudo class in `:focus`, for the input fields in the AdyenCheckout instance.

**Describe the solution you'd like**
A way to style pseudo classes, so potentially an `onFocus` property in the `CoreOptions` interface or a way to do the same thing inside the `styles` object, as part of the PaymentMethodOptions generic type.

**Describe alternatives you've considered**
I've attempted to use the second argument (element) inside the `onChange` property within the `CoreOptions` interface, but have not found a way to do so.

**Additional context**
N/A

**Comment by m1aw** [comment]
Hello @ashrafnazar 

What would be the objective here? I ask because we are going to be rolling out CSS variables in V6 and you will be able to customise it that way.
I wonder however if your use case would be covered. Can you share a few more details on what you are trying to accomplish?

**Comment by ashrafnazar** [comment]
Hey @m1aw - it's to match our current designs, so when a user tabs through to an input field, or is on it, then we would like the outline property to change, i.e. it's stroke width and colour. Hope that makes sense

**Comment by m1aw** [comment]
Is it currently not possible just by using CSS?

**Comment by AshNaz87** [comment]
Hey Antonio,

I believe the input field is inside an iframe which makes it tricky to target using CSS, unless I'm missing something

**Comment by ashrafnazar** [comment]
Hi @m1aw - because the input fields are inside an iframe, I don't think it's as simple as updating the CSS. Unless I'm mistaken?

**Comment by ashrafnazar** [comment]
I've been told that I can style the parent element, i.e. the span with the `data-cse` attribute, but unless I do some sort of hack, there isn't a clean way to update the `:focus` state of it

**Comment by DeekshithShetty** [comment]
Hey @ashrafnazar,

This may not be the best way, but I was able to overwrite Adyen css for the focus state

```
.adyen-checkout__field--cardNumber:has(.adyen-checkout__label--focused), 
.adyen-checkout__field__exp-date:has(.adyen-checkout__label--focused),
.adyen-checkout__field--expiryDate:has(.adyen-checkout__label--focused),
.adyen-checkout__field__cvc:has(.adyen-checkout__label--focused),
.adyen-checkout__field--securityCode:has(.adyen-checkout__label--focused),
.adyen-checkout__card__holderName:has(.adyen-checkout__label--focused) {
	// your custom css goes here
	background: var(--color-interaction-background-focused);
}

```

Hope this helps

**Comment by ashrafnazar** [comment]
Hi @DeekshithShetty - are you integrating using Adyen's Drop-in component?

**Comment by DeekshithShetty** [comment]
@ashrafnazar Yes. I am using the Drop-in component

**Comment by ashrafnazar** [comment]
@DeekshithShetty - unfortunately, this won't apply in my case, as my input fields are custom

**Comment by ashrafnazar** [comment]
Comment to keep issue open

**Comment by ribeiroguilherme** [comment]
@ashrafnazar Are you using `create.checkout('securedfields')` in this case? Which version of the library are you using?

**Comment by ashrafnazar** [comment]
@ribeiroguilherme - I'm using v5 and `AdyenCheckout`

**Comment by ribeiroguilherme** [comment]
How are you creating your component? Are you using `create.checkout('securedfields') ` ? And which version of v5 are you using?

**Comment by ashrafnazar** [comment]
The version we are using is `5.67.1` and the method is `.create('securedfields'…`

**Comment by sponglord** [comment]
@ashrafnazar 
Since you are using the "custom card" integration i.e. `.create('securedfields'...)` how your UI looks, is entirely up to you.

You can set an `onFocus` callback [example here](https://github.com/Adyen/adyen-components-js-sample-code/blob/dd5a2925f714f636ebf80d2ea6224a62ce22b286/src/customcard/customCard.js#L44) and do whatever you want to style the elements that act as parents for the iframes.

[In this example](https://github.com/Adyen/adyen-components-js-sample-code/blob/dd5a2925f714f636ebf80d2ea6224a62ce22b286/src/customcard/customCards.config.js#L306) we add/remove a class that controls the border & outline properties of the element.

**Comment by ashrafnazar** [comment]
Example provided is not easy to follow

**Comment by sponglord** [comment]
I've updated the urls for the 2 examples, above.

In short:
- You set a focus handler when you instantiate the custom card component:
```
 window.securedFields = checkout
        .create('securedfields', {
            ...
            onFocus : setFocus,
            ...
```

- In the focus handler you can inspect the passed object to find the html element to which you want to add css classes that will make the input look focused:
```
const setFocus = function(pCallbackObj) {
    const inputEl = pCallbackObj.rootNode.querySelector(`[data-cse="${pCallbackObj.fieldType}"]`);
    
    // Add focus classes
    if (pCallbackObj.focus) {
        if (inputEl.className.indexOf('pm-input-field--focus') === -1) {
            inputEl.className += ' pm-input-field--focus';
        }
        return;
    }

    // Remove focus classes
    if (inputEl.className.indexOf('pm-input-field--focus') > -1) {
        const newClassName = inputEl.className.replace('pm-input-field--focus', '');
        inputEl.className = newClassName.trim();
    }
};
```

Example css class:
```
.pm-input-field--focus {
    border: 1px solid #969696;
    outline: none;
}
```

**Comment by ashrafnazar** [comment]
What if you were using styled components?
