### ISSUE TITLE
Additional localization needs

### ISSUE THREAD

**Issue by huguenin** [Adyen/adyen-web#2679]
**Is your feature request related to a problem? Please describe.**
We have launched a new set of languages on our website, and found that the Adyen SDK does not support these languages. As a result, we have to fall back to English, which is not a great customer experience.

**Describe the solution you'd like**
We would like to add translations for the following locales:

```
bg-bg,
ca-es,
et-ee,
lv-lv,
lt-lt,
sr-rs,
sl-si,
uk-ua,
```
Is this doable on Adyen's side? We could also translate [this file](https://github.com/Adyen/adyen-web/blob/main/packages/lib/src/language/locales/en-US.json) with professional translators ourselves and contribute to this SDK, but would need a confirmation that the translations will indeed be added if we provide them.

**Describe alternatives you've considered**
Forking the library, but it won't change our approach and others can benefit from having the translations, too.

**Comment by m1aw** [comment]
Hello @huguenin 

Thank you for the question. As far if you translating these and creating a PR it wouldn't work for our translation workflow. What happens is that we would need to enable these languages as part of our translation pipeline, since it's likely they will have changes in the future. Therefore this is product decision. 

I have sent this request to product, I will updated you if there's a decision about any of these languages.

That being said what I would recommend is to use these translations as custom translations, you can learn more in the docs: [Web Integration Step 4 > Localisation](https://docs.adyen.com/online-payments/build-your-integration/sessions-flow/?platform=Web&integration=Drop-in&version=5.63.0#localization).

Hope this helps.

**Comment by huguenin** [comment]
Thank you @m1aw @sponglord I appreciate the input! This should be a workable way forward for us. Could you additionally provide guidance on how the localizations for adyen-web are best transferred to adyen-ios and adyen-android, and if these offer similar capabilities? From our research, it seems like the translations are structured differently, and it would be good to know if there are any guidelines on how to re-use localized strings across platforms.

**Comment by sponglord** [comment]
@huguenin 
FYI: In v6 we will be adding the languages: Catalan, Icelandic, Bulgarian, Estonian, Latvian and Lithuanian 
Some of these are languages you've requested - these have coincided with other requests we've had for these localisations.

Regarding the remaining translations (Serbian, Slovenian and Ukrainian) - we have a policy of waiting for multiple requests for a language before we add it.
In the meantime @m1aw detailed how you can add these yourself.

Once the new localisations have been created we will inform the iOS & Android SDK teams and they will be able to add these to their products in a new releases.

**Comment by huguenin** [comment]
Thank you @sponglord we are looking forward to those changes! What I am still not sure about is how we can best tackle localization changes across all three SDKs (web, iOS, Android) - how do you handle this? I'd imagine most of the strings are shared, but I haven't seen a centralized source for the translations. Do you translate for each SDK in isolation? And are the new languages that you've mention also coming for iOS and Android, or only web? What's the expected release date for V6?

**Comment by huguenin** [comment]
@sponglord thanks for the quick response! It would be very beneficial for us if we could implement our translations using a more centralized solution as well; I understand the private repository you've mentioned and the underlying build process are probably not easy to make public and replicate for our customizations. What I would appreciate is if you could share the underlying principles - for example, are the translation keys being used identical across the three platforms/is no further transformation applied to import them into the apps? If so, could the current file be provided? What we would like to achieve is share a single sheet with our localization department to then import the new translations in all three SDKs - without doing double or even triple work.

**Comment by sponglord** [comment]
@huguenin 
>  are the translation keys being used identical across the three platforms/is no further transformation applied to import them into the apps... we would like to achieve is share a single sheet with our localization department to then import the new translations in all three SDKs

I'm afraid that you want is currently not possible - we are 3 _separate_ projects, with 3 separate open-source repos, and 3 different ways of working and implementing. 
We _do_ share a centralised repo for our translations but these strings are then applied & transformed in different way for each projects. Although there have been some discussions on aligning this process - they are very much in their early days; and nothing will be changing around this process any time soon

**Comment by huguenin** [comment]
@sponglord I understand. Thank you for the clarification! I do want to point out this would be an important step forward for Adyen and it would makes things easier on our end, but it's clear this won't be in place today nor tomorrow. With that in mind, I'll close this issue and trust you and the team will keep it in mind as you continue to evolve the platform.
