### ISSUE TITLE
Adyen IDEAL payment issuer selection issue. 

### ISSUE THREAD

**Issue by mohankrishnag82530** [Adyen/adyen-web#2697]
**Describe the bug**
After following all the documentation provided for Drop-In flow with advanced features, [Doc link](https://docs.adyen.com/online-payments/build-your-integration/advanced-flow/?platform=Web&integration=Components&version=5.64.0&tab=node_js_4#how-it-works)
There was an issue in the /payments documentation. It is still referring to old way of calling payments method. it should be checkoutAPI.PaymentsApi.payments(<config object>) but where as in document it is referring checkoutAPI.payments(<config object>) which is throwing out error as payment method doesn't exist. 

I have corrected it by using checkoutAPI.PaymentsApi.payments(<config object>) but now main issue is, when i am selecting IDEAL as the payment type and clicking on pay button API is throwing an error saying "Issuer is required". After following new documentation I can't see an issuer selection page in the entire flow. 

I think old version while using the IDEAL we use to see the dropdown to select the bank, which provides us with the issuer ID to call /paymnets with the details. Right now i am using the version of "@adyen/adyen-web": "^5.65.0",  "@adyen/api-library": "^17.0.0", 
I am not seeing any dropdown for the IDEAL to select the bank. But when we click on the pay button and the making the call to the /payments it is expecting us to send the ISSUER ID. 

I am guessing the documentation for the new version is not updated or something else. 

**To Reproduce**
1. Follow the documentation to create a Adyen payment with help of Drop-In and Advance API.
2. select IDEAL payment and click on the continue to payment.
3. See error "Issuer Id is missing"

**Expected behavior**
As for the documentation live demo should be navigated to IDEAL payment page. 

**Screenshots**
<img width="765" alt="image" src="https://github.com/Adyen/adyen-web/assets/83771615/2843b3c4-2af7-4d03-98cf-9a7cbf9d2ccd">

<img width="1090" alt="image" src="https://github.com/Adyen/adyen-web/assets/83771615/c3451990-3dc3-4e8d-93e7-bf1281f58ef6">

<img width="992" alt="image" src="https://github.com/Adyen/adyen-web/assets/83771615/3676e5c1-1f27-455e-a2b9-20410aa65102">

**Comment by mohankrishnag82530** [comment]
Is there any updated document for the new payment flow? if there is any new document can you please provide it here? Thanks...

**Comment by ribeiroguilherme** [comment]
Hi @mohankrishnag82530 - there is not much to document actually. The iDeal component now became a simple redirect Component, which once the button is clicked, it will redirect you to the iDeal sandbox testing page.

You can check the demo on https://www.mystoredemo.io
