### ISSUE TITLE
Error: ERROR: secured field iframes have failed to load

### ISSUE THREAD

**Issue by jenersigua31** [Adyen/adyen-web#2713]
**Describe the bug**
encountered a script error when trying to create a secured fields.

const cardComponent = checkout
          .create('securedfields', customConfig)
          .mount("#id");

When LastPass is disabled, the Adyen web library functions correctly without any errors. However, with LastPass enabled, the secured field iframes consistently fail to load.
      

**Screenshots**
Issue only occurs when LastPass chrome extension is enabled
![image](https://github.com/Adyen/adyen-web/assets/79560699/eb98921a-023e-4bd3-8bed-b3ee6b62b84e)

Infinite Loading
![image](https://github.com/Adyen/adyen-web/assets/79560699/f45b3805-65c6-4849-86d9-575d9b4c5aef)

Script Error
![image](https://github.com/Adyen/adyen-web/assets/79560699/d3c84fc5-7117-4883-a9d5-8ad78c050082)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 125.0.6422.142

**Comment by mehdi-ghezal** [comment]
Similar issue here with Prestashop module that (I believe) use Adyen-Web package.

The page keep loading with Adyen Frame consuming resources and after some time the form is shown but the secured fields are not usable.

Here the consumption :
<img width="1400" alt="image" src="https://github.com/Adyen/adyen-web/assets/6672333/641b692f-aefe-4e29-a74e-57fbcf299c79">

Here the console message about unusable field
<img width="1123" alt="image" src="https://github.com/Adyen/adyen-web/assets/6672333/17de1a36-6aaf-4be1-b9ca-b6dba70763a6">

**Comment by sponglord** [comment]
@jenersigua31 - I am not able to recreate this issue with the hardware that I have at my disposal.

- I've added LastPass to Chrome (v109.0.5414.120) 
- on a Windows 7 machine. 
- I've then added a credit card to use for autofill 
- and gone to a site running AdyenWeb v 5.60.0

And everything works as expected.

Do you have any more details about your use case?
- What version of AdyenWeb are you using ?
- What are you using LastPass for? Also credit card autofill?

**Comment by jenersigua31** [comment]
@sponglord 
Actually, other user also encountered this issue using other browsers, Firefox, Edge,
But on my end, the issue only occurs when LastPass extension is enabled, 

Im not using credit card autofill. I'm using versions 5.43.0 and 5.66.1,

I just followed the implementation on adyen documentation.
`const customCard = checkout.create('securedfields', {
    // Optional configuration
    type: 'card',
    brands: ['mc', 'visa', 'amex', 'bcmc', 'maestro'],
    styles: {
        error: {
            color: 'red'
        },
        validated: {
            color: 'green'
        },
        placeholder: {
            color: '#d8d8d8'
        }
    },
    // Only for Web Components before 4.0.0.
    // For Web Components 4.0.0 and above, configure aria-label attributes in translation files
    ariaLabels: {
        lang: 'en-GB',
        encryptedCardNumber: {
            label: 'Credit or debit card number field',
            iframeTitle: 'Iframe for secured card number',
            error: 'Message that gets read out when the field is in the error state'
        }
    },
    // Events
    onSubmit: function() {},
    onValid : function() {},
    onLoad: function() {},
    onConfigSuccess: function() {},
    onFieldValid : function() {},
    onBrand: function() {},
    onError: function() {},
    onFocus: function() {},
    onBinValue: function(bin) {},
    onBinLookup: function(callbackObj: CbObjOnBinLookup) {}
}).mount('#customCard-container');`

**Comment by cw-gsilva** [comment]
I've got the same error while executing `checkout.update()` with a new amount. It happens a few seconds after `checkout.update()`, every time and in different environments.

We create the checkout with `AdyenCheckout` and passing `paymentMethodsResponse` from the Adyen API and it mounts multiple payment method components, including givex.

I tried two versions without success:
- 5.55.1
- 5.67.0

We eventually got rid of this error by downgrading it to version 5.16.2

**Comment by a-kharunzha** [comment]
I have a similar issue, but with '.create('dropin')', not secured fields. 
Got it after updating from 4.9 to 5.67 on already working integration, where iframes for credit card fields stopped working because `crypto.subtle` is not defined in the iframe. 
Chrome. 
Going down to version 5.16.2 didn't work

**Comment by a-kharunzha** [comment]
> If the error is about crypto[1] it might be due to your development environment not being a secure context.
Which means for Chrome for example, it needs to be either localhost or https [2].

It is valid for a case if the code missing crypto was executed on my site's page, while it is executed in the iframe of Adyen, which is being loaded over https.

**Comment by sponglord** [comment]
@a-kharunzha 
Are you running a dev environment at a custom _http_ environment when you see this `window.crypto.subtle` error?
By custom http I mean something like `http://mydevenv.com` (as opposed to `http://localhost`)

**Comment by berinaptula** [comment]
Not sure if your issue still persists, but we recently encountered the same problem in the company I work for, and realised that we had the following attribute in Cookiebot:
`script.setAttribute('data-blockingmode', 'auto');`. 

Removing it resolved the issue. Perhaps something to look into :)

**Comment by resool** [comment]
in my case the issue occurs locally when using host another than localhost (edited etc/hosts file). maybe adyen doesnt require https only for "localhost"? idk but more readable error message would be helpful
```
WARNING: securedFields:: the iframe has not configured correctly. Config log= 
Object { a_sfInit: true, z_errors: (1) […], b_type: "card", c_listenerAdded: true, d_handlingConfig: true, e_fieldType: "encryptedCardNumber", f_processedStylesStart: 1752098749208, g_processedStylesStop: 1752098749208, h_beginningKeyGen: true, i_configured: undefined, … }
​
a_sfInit: true
​
b_type: "card"
​
c_listenerAdded: true
​
d_handlingConfig: true
​
e_fieldType: "encryptedCardNumber"
​
f_processedStylesStart: 1752098749208
​
g_processedStylesStop: 1752098749208
​
h_beginningKeyGen: true
​
i_configured: undefined
​
j_renderedField: undefined
​
k_sendingConfigConfirmation: undefined
​
z_errors: Array [ `TypeError: can't access property "importKey", dt.subtle is undefined` ]
​
<prototype>: Object { … }
securedFields.html:175:21
```

**Comment by sponglord** [comment]
@resool - what url are you trying to run your dev environment on?

**Comment by jonathanribas** [comment]
Hello, some of our customers experience this error too with Adyen-Web `6.16.0`.
