### ISSUE TITLE
No focused class for the holder name field

### ISSUE THREAD

**Issue by lauterry** [Adyen/adyen-web#2725]
**Describe the bug**

When the holder name is focused, there is no border color like the other field

**To Reproduce**
Focus the holder name field

**Expected behavior**
I expect the holder name field to have a border color

**Screenshots**

![Capture d’écran 2024-06-25 à 16 00 00](https://github.com/Adyen/adyen-web/assets/1374238/422cb308-f573-4686-82fe-31cd471b2268)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sponglord** [comment]
@lauterry what version of adyen-web are you experiencing this issue in?

**Comment by lauterry** [comment]
Hello

I'm using 5.66.1 and I am implementing Components

**Comment by sponglord** [comment]
@lauterry - do you have a url we can look at, because I cannot recreate your issue. The holderName field always receives special styling when focussed, unless you are somehow overwriting these styles with your own css
![image](https://github.com/Adyen/adyen-web/assets/22219050/b55ba66f-927e-4dc4-aa5a-74773af7d034)

**Comment by ashrafnazar** [comment]
Hi @sponglord - I have the same problem when using the web component. There doesn't seem to be a clean way to apply styling to the input fields in the iframe

**Comment by sponglord** [comment]
@ashrafnazar - this is not the same problem. This ticket refers to the focus state _around_ the input, which is unrelated to the iframe.

However, this link to [Styling card input fields](https://docs.adyen.com/payment-methods/cards/custom-card-integration/#styling) - should give you the information you need to show you what you can style within the actual iframes
