### ISSUE TITLE
[web dropIn]Click the payment button，Always loading

### ISSUE THREAD

**Issue by yuechuZhaowei** [Adyen/adyen-web#2726]
**Describe the bug**
Click the payment button，The pay button always loading.

**Screenshots**
![1719385228282](https://github.com/Adyen/adyen-web/assets/100656621/f5509a35-d1c9-4fd8-b8b8-b1b6838dd1c0)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]--Using phone debugging mode

**Smartphone (please complete the following information):**

**Additional context**
We have contacted your support，he say , "Internal resources have not been transferred".
use https://order.lunchbox.asia/test-diner/#/getAdyenPayRes to test

**Comment by longyulongyu** [comment]
Hi @yuechuZhaowei thanks for reporting! 
The issue was reported and replied to the support team, they will provide the answer soon.
