### ISSUE TITLE
autofill from holdername do not autofill credit card number expired date and CVC

### ISSUE THREAD

**Issue by lauterry** [Adyen/adyen-web#2730]
**Describe the bug**
When I use autofill the credit card form from the holder name, the other fields are not autofilled

**To Reproduce**
1. Go to https://www.mystoredemo.io/#/checkout
2. Have a credit card saved in the chrome
3. Click on the holder name and select the saved credit card to autofill
4. Only the holder name is autofilled. The others fields remains empty

**Expected behavior**
I expect the credit card number, expired dates to be autofilled

**Screenshots**
![Capture d’écran 2024-07-03 à 15 10 51](https://github.com/Adyen/adyen-web/assets/1374238/86a83738-e39a-4231-8d55-38634558087d)

![Capture d’écran 2024-07-03 à 15 10 55](https://github.com/Adyen/adyen-web/assets/1374238/6fa6498a-1941-4f17-83b3-dc5b55393f9e)

**Desktop (please complete the following information):**
 - OS: Maxos
 - Browser chrome
 - Version 126.0.6478.114

**Additional context**
Version   "@adyen/adyen-web": "^5.66.1" implementing components

**Comment by sponglord** [comment]
@lauterry - this is currently the "expected" behaviour. 
It is a consequence of the the fact that the card number, date & security code fields exist as iframes, separate from the holderName field (and so the browser restricts communication between these fields).
UX research has shown that the optimal placement for the holderName field is _after_ these other 3 fields, and that we expect the first shopper interaction to be with the card number field. If you try to autofill from the card number then all the fields get populated as expected.
