### ISSUE TITLE
Empty fields in the iframe in case of errors

### ISSUE THREAD

**Issue by j2vos** [Adyen/adyen-web#2735]
Hello,

In case of errors, I would like to empty the fields (card, security code for giftcard illicado). 

I can't figure out how to clear these fields.

Thanks

**Comment by sponglord** [comment]
@j2vos - this is not functionality that we currently support. 
The card input fields exist as externally served iframes from which we accept encrypted blobs, but, for security reasons, we don't allow content to be sent to be sent to these fields; and this includes telling the fields to clear.

Depending on your implementation it might be possible for you to `unmount` and `remount` the whole card/giftcard component - this would achieve the effect you desire.
(Search for "unmount" on [this page](https://docs.adyen.com/marketplaces/checkout-components/?platform=Web&integration=Components&version=5.60.0#adyencheckout-configuration))
