### ISSUE TITLE
Credit card installments label doesn't render 

### ISSUE THREAD

**Issue by vitalii-koshovyi** [Adyen/adyen-web#2746]
Credit card installments label doesn't render
![image](https://github.com/user-attachments/assets/b443dd94-a82c-48d4-ba6a-5cabe08ee548)

Affected [PR](https://github.com/Adyen/adyen-web/pull/2243) and affected [line](https://github.com/Adyen/adyen-web/pull/2243/files#diff-7aef87da240aa42a88475b93de8cd6ed31bbecec3bd954b6aeb5e8d61f781120R126) 
Issued release https://github.com/Adyen/adyen-web/releases/tag/v5.48.0

Without those changes, everything works fine. I have tested it on v5.47.0
![image](https://github.com/user-attachments/assets/d6cc9747-c15c-4b1a-99a7-250314c9b2c6)

**To Reproduce**
You need to pay with credit card installments enabled:
https://docs.adyen.com/payment-methods/cards/credit-card-installments/?programming_language=js#different-brands

You need to use installmentOptions without plans (with plans everything works fine)
Config example for VISA cards
```
    {
        ...
        paymentMethodsConfiguration: {
           card: {
             installmentOptions: {
               visa: {
                   values: [1, 2, 3],
               },
             showInstallmentAmounts: true
           }
       }
```

**Expected behavior**
The 'Number of installments' label should be rendered
Like here:
![image](https://github.com/user-attachments/assets/d6cc9747-c15c-4b1a-99a7-250314c9b2c6)

**Comment by sponglord** [comment]
@vitalii-koshovyi - this issue has been raised in https://github.com/Adyen/adyen-web/issues/2609 and will be fixed in our next release

**Comment by vitalii-koshovyi** [comment]
@sponglord Thank you!
