### ISSUE TITLE
v6 > paymentMethodComponents > Component for "iDeal" missing

### ISSUE THREAD

**Issue by MiladSadinam** [Adyen/adyen-web#2765]
**Describe the bug**
I am migrating to version 6.0.0. When adding our supported payment methods to the `paymentMethodComponents` parameter of the `Dropin` constructor, I cannot find a suitable component for iDEAL. 

Is this intended?

**Comment by ribeiroguilherme** [comment]
Hi @MiladSadinam ,

Thanks for reaching out. The `iDeal` component on v6 is a `Redirect` component type, and it is already included by default. It is not required to set it in the `paymentMethodComponents` parameter. 

All 'Redirect' type payment methods are included by default and they don't have their own export.

Please let us know if it works for you.

**Comment by MiladSadinam** [comment]
That you for the quick response. Yes, you are right, `iDeal` already works without adding it to `paymentMethodComponents`. A note in documentation of that property would be useful.

Furthermore, the documentation seems to be not correct, as it says that for version v6 there should be `Ideal` available in `@adyen/adyen-web` which is not the case for me.

![image](https://github.com/user-attachments/assets/6c2f7d28-6b30-4abb-94ea-0108c9cfdb11)

-----
Furthermore, when trying to pay with iDEAL, it is not working, showing the following error:

![image](https://github.com/user-attachments/assets/b43719dd-e10c-48a6-8e19-82573f6312a5)

With the following error message in the developer console:
`NETWORK_ERROR Missing payment method details: issuer [This error message is only provided on TEST, this error will be a 500 Internal Error on LIVE.]`

I am aware of the changes going on for iDeal. According to this email, I have removed the issuer list. But, it seems it is still required?

![image](https://github.com/user-attachments/assets/b28e2d27-62a6-4299-874a-42c59378b968)

Or is the "updated" version which does not require the issuers list not available yet? Hope I am not misunderstanding it.

Regards
Milad

**Comment by MiladSadinam** [comment]
I added again the iDeal `issuers` list, but the same error occurs. Do you have an idea what causes the error (Error code `14_004`)? I have no specific configuration for `iDeal` and other redirect payment-methods like `Sofort` work fine.

**Comment by ribeiroguilherme** [comment]
Hi @MiladSadinam ,

You can contact Support to enable the new iDeal flow in your merchant account.

Regarding the docs page, we are going to fix it. Thanks for reporting to us!

**Comment by MiladSadinam** [comment]
Thank you. I will close this issue then.

**Comment by liangie** [comment]
Hi @MiladSadinam, 
I recently encountered the same issue you described and haven’t found a working solution yet. I was wondering if you’ve managed to resolve it? If so, could you share your approach or any helpful resources? I’d greatly appreciate it!

**Comment by MiladSadinam** [comment]
> Hi @MiladSadinam, I recently encountered the same issue you described and haven’t found a working solution yet. I was wondering if you’ve managed to resolve it? If so, could you share your approach or any helpful resources? I’d greatly appreciate it!

I cannot completely confirm the solution, as we had to pause the update because of internal reasons. Did you ask the customer support to activate the new iDEAL flow for your merchant?
