### ISSUE TITLE
Documentation Embed script and stylesheet is empty

### ISSUE THREAD

**Issue by agracia-foticos** [Adyen/adyen-web#2768]
**Describe the bug**
Documentation Embed script and stylesheet is empty
https://docs.adyen.com/online-payments/upgrade-your-integration/migrate-to-web-v6/?tab=embed_script_and_stylesheet_2#import-using-embedded-scripts
**To Reproduce**
![image](https://github.com/user-attachments/assets/0d2a8d8f-cbb0-4b03-8e1b-5aedcf3c7e3b)

**Comment by gsiag** [comment]
Also can't see any reference to how to import types for typescript code in v6
