### ISSUE TITLE
Live endpoints to 6.0.0 not exists

### ISSUE THREAD

**Issue by agracia-foticos** [Adyen/adyen-web#2770]
**Describe the bug**
https://docs.adyen.com/development-resources/live-endpoints/

https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/6.0.0/adyen.js not exists

only exists test

**To Reproduce**
https://docs.adyen.com/development-resources/live-endpoints/

https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/6.0.0/adyen.js not exists

**Comment by m1aw** [comment]
Hello @agracia-foticos 

There's been a change for V6, that domain is no longer used for loading the SDK. The new one is:

```
checkoutshopper-test.cdn.adyen.com/checkoutshopper/sdk/6.0.0/adyen.js
checkoutshopper-live.cdn.adyen.com/checkoutshopper/sdk/6.0.0/adyen.js
```

We are working with the docs team to update this.
