### ISSUE TITLE
on 6.0.1 there is a bug with stencil build Property 'formatProps' in type 'UPI' is not assignable to the same property

### ISSUE THREAD

**Issue by oleksii-loian** [Adyen/adyen-web#2774]
**Describe the bug**
Bug is reproduced on the 6.0.1 version but not reproducing in 6.0.0-beta.1
`TypeScript
Property 'formatProps' in type 'UPI' is not assignable to the same property in base type 'UIElement<UPIConfiguration>'.Type '(props: UPIConfiguration) => { defaultMode: UpiMode; apps: { type: TxVariants; id: string; name: string; }[]; url?: string; paymentData?: string; qrCodeData?: string; ... 37 more ...; paymentMethodType?: string; }' is not assignable to type '(props: UPIConfiguration) => UPIConfiguration'.Call signature return types '{ defaultMode: UpiMode; apps: { type: TxVariants; id: string; name: string; }[]; url?: string; paymentData?: string; qrCodeData?: string; brandLogo?: string; order?: Order; ... 35 more ...; paymentMethodType?: string; }' and 'UPIConfiguration' are incompatible.The types of 'apps' are incompatible between these types.Type '{ type: TxVariants; id: string; name: string; }[]' is not assignable to type 'App[]'.Type '{ type: TxVariants; id: string; name: string; }' is not assignable to type 'App'.Types of property 'type' are incompatible.Type 'TxVariants' is not assignable to type 'UpiType'.`
**To Reproduce**
1. Add the Adyen Checkout as dependency in the stencil web component
2. Build

**Expected behavior**
Build should be proceed.

**Screenshots**
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/024805d9-6424-4204-906a-beb99943177e">

**Comment by longyulongyu** [comment]
Hi @oleksii-loian we released v6.0.2 yesterday, could you try the version and check if your issue is solved?
