### ISSUE TITLE
Missing en-GB translation causes 404 error in console

### ISSUE THREAD

**Issue by PG-RichT** [Adyen/adyen-web#2778]
**Describe the bug**

Having just upgraded to v6 Drop-in we can see an error in the console log as the drop-in code is unable to find the following translation file: https://checkoutshopper-test.cdn.adyen.com/checkoutshopper/sdk/6.0.1/translations/en-GB.json

I can see from the files in https://github.com/Adyen/adyen-web/tree/main/packages/server/translations that it is missing.

**To Reproduce**
1. Set country code of Adyen Drop-in to 'GB'
2. When Drop-in is rendered, you will see an error in the console log

**Expected behavior**
The translation file should be added to the CDN or the Dropin should not request the file if 'GB' is configured.

**Screenshots**
![image](https://github.com/user-attachments/assets/92228e07-4a21-4a26-9ab9-d8ad77f0ac36)

![image](https://github.com/user-attachments/assets/b3549669-3448-421b-98fa-fcb97a16ba7c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 127.0.6533.74

**Comment by ribeiroguilherme** [comment]
Hey @PG-RichT ,

Thanks for reaching out.

That is the intended behavior. We do not officially support an exclusive `en-GB` translation file . In the v5 version we were always doing a fallback to `en-US`.

In v6, we always attempt to fetch the locale, and in case it fails, we fetch the default 'en-US'.  If you want to not see the errors, I suggest to set `en-US` directly.

Cheers!
