### ISSUE TITLE
You must specify a countryCode when initializing checkout

### ISSUE THREAD

**Issue by oleksii-loian** [Adyen/adyen-web#2788]
**Describe the bug**
The issue is due using AdyenCheckout: **You must specify a countryCode when initializing checkout.**, but in the interface CoreConfiguration **Country code** is not required. **Is it bug or a feature?**

We did not find this requirement for Android, but noticed a different update for iOS: "The countryCode property of AdyenSession.Context is now optional to allow not including it in the /sessions request. Because this property isn't meant to be read, this breaking change shouldn't cause any build errors.”

However, in the /session documentation (https://docs.adyen.com/api-explorer/Checkout/latest/post/sessions#request-countryCode), the property is still marked as optional and described as “The shopper's two-letter country code.”

**Expected behavior**
The error should not appear.

**Comment by MartinKei** [comment]
@oleksii-loian - how did you resolve the issue?
