### ISSUE TITLE
Adyen Web Types are missing the TransactionInfo object

### ISSUE THREAD

**Issue by daniel-johns-99** [Adyen/adyen-web#2834]
**Describe the bug**

The TransactionInfo object is missing under the GooglePay Types
https://github.com/Adyen/adyen-web/blob/main/packages/lib/src/components/GooglePay/types.ts

See https://developers.google.com/pay/api/web/reference/object#TransactionInfo for object.

It is exposed under the `transactionInfo` object under the configuration and supports the following fields:

`transactionId`
`displayItems`
`checkoutOption`
`totalPriceLabel`

The support for this object was added here:
https://github.com/Adyen/adyen-web/commit/32f50314c8267b45f532691c2377800b4bd4d9fe

It also needs to be updated in the documentation to show this is available.

**Comment by ribeiroguilherme** [comment]
Hi @daniel-johns-99 .

Which version of the library are you referring to? v5 or v6? Isn't transactionInfo defined [here](https://github.com/Adyen/adyen-web/blob/main/packages/lib/src/components/GooglePay/types.ts#L122)?
