### ISSUE TITLE
ariaLiveSRPane is not being removed from the DOM

### ISSUE THREAD

**Issue by mark-hingston** [Adyen/adyen-web#2835]
**Describe the bug**
The `#ariaLiveSRPane` doesn't seem to be removed from the DOM when the drop-in component is unmounted.

**To Reproduce**
1. Complete a payment using Adyen drop-in
2. The `#ariaLiveSRPane` container remains on the page after the Adyen drop-in component is unmounted.

```html
<div class="sr-panel-holder" id="ariaLiveSRPanel"><div class="adyen-checkout-sr-panel--sr-only" role="log" aria-relevant="additions text" aria-live="polite" aria-atomic="true"><div class="adyen-checkout-sr-panel__msg">Payment Successful</div></div></div>
```

**Expected behavior**
The `#ariaLiveSRPanel` should be removed when the component is unmounted.

**Additional context**
@adyen/adyen-web: 6.0.2

**Comment by sponglord** [comment]
@mark-hingston - the `ariaLiveSRPanel` is a _checkout_ level module and, as such, is not dependent on the presence, or not, of any component level entities (like Dropin, or a specific paymentMethod related component)
