### ISSUE TITLE
countryCode is required?

### ISSUE THREAD

**Issue by jellevdv** [Adyen/adyen-web#2860]
When upgrading to version 6 of the drop-in, the `countryCode` parameter is now mandatory in the `CoreConfiguration`. It seems this is intended to filter the available payment methods. This is odd, considering we already provide the `paymentMethodsResponse` parameter, which includes the list of payment methods. Additionally, we’ve noticed that the `countryCode` doesn’t seem to have any effect, even when we pass random strings. Even providing a valid country code doesn’t change the displayed payment methods at all.

Is it safe to just pass any random string, or could this pose a risk?
Thanks in advance

**Comment by ribeiroguilherme** [comment]
Hi @jellevdv ,

There are some countries that have certain regulations in how the payment methods must be displayed initially. Therefore this field is mandatory so we can make sure that we comply with these regulations.

Regarding passing a random string, I don't advice to do it. We rely on the countryCode in certain payment methods, and that can impact your payment flow.

I hope it is clear!

Cheers

**Comment by jellevdv** [comment]
@ribeiroguilherme Thanks for the info!
