### ISSUE TITLE
Apple Pay billingAddress missing some fields that exist in authorizedEvent.payment.billingContact

### ISSUE THREAD

**Issue by joaopedrodcf** [Adyen/adyen-web#2863]
**Describe the bug**
Using apple pay express `onAuthorized` and getting the fields from the params 

```
onAuthorized: async (
                    {
                        authorizedEvent,
                        billingAddress,
                        deliveryAddress,
                    },
                    actions,
                )
```

The billingAdress will contain only some of the fields that we except and others will be in authorizedEvent.

Example of fields that we expect to exist but are not on billingAdress: `firstName`, `lastName`, `stateOrProvince` 

**To Reproduce**
1. Use adyen web 2.0
2. Create a apple express payment 
3. Use the onAuthorized method and log the values that were input by the customer on the express checkout.

**Expected behavior**
The fields that are available in `authorizedEvent.payment.billingContact` should also be available in the `billingAddress` 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 15
 - Browser Safari
 - Version 6.2.0

**Comment by joaopedrodcf** [comment]
This also happens in google pay

**Comment by ribeiroguilherme** [comment]
Hi @joaopedrodcf 

The `billingAddress` and `deliveryAddress` follows the Adyen API format . `billingAddress` does not expect the fields `firstName` nor `lastName` as described [here](https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-billingAddress).  

The `stateOrProvince` field is optional, and it might be returned depending if the data is available or not. 
- For GooglePay, we expect this value to come from `authorizedEvent.paymentData.info.billingAddress.administrativeArea` ([here](https://github.com/Adyen/adyen-web/blob/main/packages/lib/src/components/GooglePay/utils.ts#L27))
- For ApplePay, we expect this value to come from `authorizedEvent.payment.billingContact.administrativeArea` ([here](https://github.com/Adyen/adyen-web/blob/main/packages/lib/src/components/ApplePay/utils.ts#L48))

It might be that this field is not available for you in the authorized event. Can you confirm that?
