### ISSUE TITLE
Dropin: You support the payment method 'scheme' but this component has not been configured. Make sure to import the Class  'Card' and then pass it in the Dropin's 'paymentMethodComponents' config property if you wish to offer this payment method.

### ISSUE THREAD

**Issue by xyg00** [Adyen/adyen-web#2864]
"vite": "^5.2.8"  "@adyen/adyen-web": "^6.2.0"
 The following error appears according to the official website integration
 [https://docs.adyen.com/online-payments/build-your-integration/sessions-flow/?platform=Web&integration=Drop-in&version=6.2.0](website)
 
 Dropin: You support the payment method 'scheme' but this component has not been configured. Make sure to import the Class  'Card' and then pass it in the Dropin's 'paymentMethodComponents' config property if you wish to offer this payment method.

**Comment by sponglord** [comment]
@xyg00 - what exactly is the issue here?

**Comment by ribeiroguilherme** [comment]
You can read more how to integrate here:
https://docs.adyen.com/online-payments/build-your-integration/advanced-flow/?platform=Web&integration=Drop-in&version=6.2.0#import-drop-in-with-individual-payment-methods
