### ISSUE TITLE
Removing the 3DS from the test card

### ISSUE THREAD

**Issue by sebastian-vass** [Adyen/adyen-web#2871]
**Describe the bug**
[Test cards](https://docs.adyen.com/development-resources/testing/test-card-numbers/#mastercard)
I ran into a problem today with my test card **5555 4444 3333 1111**. The morning tests passed without problems, but a few hours later the tests started crashing. The problem is 3DS secure, which was added as an additional step to this card. As the documentation says this test card should not have 3DS it would be possible to disable it for this card.

**To Reproduce**
1. GET to the payment gateway.
2. Enter payment card viz. screenshot.

**Expected behavior**
This card should not include this additional step.

**Screenshots**
<img width="736" alt="image" src="https://github.com/user-attachments/assets/84643bf9-7b47-4c14-b71f-9da9e81e9088">
<img width="370" alt="image" src="https://github.com/user-attachments/assets/aef82f6d-cb50-4b0a-921f-ad843d68ccd9">

**Additional context**
adyen/adyen-web version:  6.2.0

**Comment by camil-adyen** [comment]
Hey @sebastian-vass, please reach out to support@adyen.com for questions around test cards.
