### ISSUE TITLE
Typo in Icelanding translation

### ISSUE THREAD

**Issue by jureperak** [Adyen/adyen-web#2890]
**Describe the bug**
There is typo in Icelanding translation for:
* "creditCard.expiryDate.label": "Gildisdadgur",
* "giftcard.expiryDate.label": "Gildisdadgur",

**Expected behavior**
* "creditCard.expiryDate.label": "Gildisdagur",
* "giftcard.expiryDate.label": "Gildisdagur",

**Comment by ribeiroguilherme** [comment]
Hi @jureperak - thanks for reaching out.

We are working on it. I will update this thread once the translation is fixed. Cheers
