### ISSUE TITLE
When PayPal window is closed the onCancel event is not triggered.

### ISSUE THREAD

**Issue by emidev98** [Adyen/adyen-web#290]
**To Reproduce**
1. Load the web drop in with PayPal
2. Click the PayPal button
3. Wait for the window to open
4. Close the window
5. BOOM. No event onCancel is send.

**Expected behavior**
As it's explained in the documentation to be triggered the onCancel https://docs.adyen.com/payment-methods/paypal/web-drop-in

**Desktop (please complete the following information):**
 - OS: Windows, Ubuntu
 - Browser Chrome, Firefox, Brave, Edge

**Comment by floflock** [comment]
+1 here! Tested on OSX as well.

JS SDK Version: 3.13.0 (latest)

![2020-09-16_19-24-42 (1)](https://user-images.githubusercontent.com/3831745/93371293-6690e500-f852-11ea-8f46-093abc265a31.gif)

**Comment by pabloai** [comment]
Hi @emidev98,

Thanks for the report.

I was able to reproduce the ~~BOOM~~ issue and I'm working on a fix.
Have nice day, cheers!
