### ISSUE TITLE
Docs outdated for Drop-In Configuration of 3DS - ChallengeWindowSize

### ISSUE THREAD

**Issue by dimitri-dev** [Adyen/adyen-web#2902]
**Describe the bug**
Attempting to set challengeWindowSize prop following the docs is borderline impossible.

The documentation states we should use `threeDS2` object in the `paymentMethodsConfiguration`. [3DS Web Drop-In Configuration](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/web-drop-in/)
```js
paymentMethodsConfiguration: {
	 card: { // Sample Drop-in configuration for 3D Secure
	    hasHolderName: true,
	    holderNameRequired: true,
	    enableStoreDetails: true,
	    name: 'Credit or debit card',
	    billingAddressRequired: true
	 },
	 threeDS2: { // Web Components 4.0.0 and above: sample configuration for the threeDS2 action type
	    challengeWindowSize: '05'
	     // Set to any of the following:
	     // '02': ['390px', '400px'] -  The default window size
	     // '01': ['250px', '400px']
	     // '03': ['500px', '600px']
	     // '04': ['600px', '400px']
	     // '05': ['100%', '100%']
	},
	...
},
```

However, the release notes state we can't set the `challengeWindowSize` parameter anymore. [Release notes v6.0.0 ](https://docs.adyen.com/pt/online-payments/release-notes/?Web+Components%2FDrop-in=&title%5B0%5D=Web+Components%2FDrop-in&version%5B0%5D=6.0.0#releaseNote=2024-07-24-web-componentsdrop-in-6.0.0)
```
The challengeWindowSize configuration parameter can no longer be set inside a threeDS2 object within paymentMethodsConfiguration.
```

**Additional context**
Following the docs, I expected to be able to set challengeWindowSize in the drop-in component. It took a couple of hours of hopeless debugging (trying out various challenge sizes, passing challengeWindowSize and size props, even putting the `threeDS2` object inside of the `card` object) with no avail. If I hadn't come across this file, I wouldn't even figure out that challengeWindowSize still can be set:
https://github.com/Adyen/adyen-web/blob/main/packages/playground/src/pages/Dropin/manual.js#L141

**Summary**
`challengeWindowSize` can be set under the `card` object in `paymentMethodsConfiguration`
e.g.
```js
paymentMethodsConfiguration: {
        card: {
            challengeWindowSize: '03',
            enableStoreDetails: true
        },
	...
}
```

**My ask**
Please update the docs for other poor souls that are encountering the same issue.

TIA

**Comment by sponglord** [comment]
@dimitri-dev 
I've passed this issue on to our Docs team. Thanks for raising it & sorry about the confusion

**Comment by sponglord** [comment]
This has now been updated in [the docs](https://docs.adyen.com/pt/online-payments/release-notes/?Web+Components%2FDrop-in=&title%5B0%5D=Web+Components%2FDrop-in&version%5B0%5D=6.0.0#releaseNote=2024-07-24-web-componentsdrop-in-6.0.0)
