### ISSUE TITLE
ReferenceError: Can't find variable: _AutofillCallbackHandler

### ISSUE THREAD

**Issue by AxelAssoConnect** [Adyen/adyen-web#2903]
**Describe the bug**
We have a lot of events on Sentry regarding payment on Facebook/Instagram internal browser on Apple devices. 
```ReferenceError: Can't find variable: _AutofillCallbackHandler```

**To Reproduce**
I could not reproduce the issue.

**Expected behavior**
We will ignore this error for now but it generates a lot of noise and we would prefer it to be handled directly by the component.

**Screenshots**
![screencapture-assoconnect-sentry-io-issues-3800276324-tags-browser-2024-10-15-18_00_28](https://github.com/user-attachments/assets/f80d884b-e16b-458c-8d55-19546db6a984)
![screencapture-assoconnect-sentry-io-issues-3800276324-tags-device-2024-10-15-18_01_42](https://github.com/user-attachments/assets/0a40ffb3-68bd-4571-9677-caf626ff75f4)

**Additional context**

**Comment by sponglord** [comment]
Hi @AxelAssoConnect 
the variable `_AutofillCallbackHandler` is not part of our SDK

Perhaps the solution here might help: https://stackoverflow.com/questions/72720387/cant-find-variable-autofillcallbackhandler
