### ISSUE TITLE
Google Pay express sessions integration not passing all payment details in v6+

### ISSUE THREAD

**Issue by mstrutt** [Adyen/adyen-web#2907]
## Describe the bug

When using Google Pay Express Component in v6+ with the session API, `googlePayToken` and `googlePayCardNetwork` are missing from the `paymentMethod` object being submitted to `/payments`

Stepping through the code, I can see the information is correctly received from Google Pay in the `onPaymentAuthorized` event [GooglePay.tsx#L113](https://github.com/Adyen/adyen-web/blob/v6.3.0/packages/lib/src/components/GooglePay/GooglePay.tsx#L113) but appear not to persist in the internal state of the component  as when the details are retrieved later: [GooglePay.tsx#L63](https://github.com/Adyen/adyen-web/blob/v6.3.0/packages/lib/src/components/GooglePay/GooglePay.tsx#L63) `this.state` is an empty object and so all the values are `undefined`.

If I put in breakpoints in the browser and use an object attached to the window to pass the values back into `this.state`, then the payment goes through as expected (similar to how our integration worked in v5 of the library).

## To Reproduce

minimal setup of the Google Pay with an `onAuthorized` callback which always calls `actions.resolve()` and no `onSubmit` callback.

1. Click on the Google Pay button
2. Click "Pay"

The payment will fail as with a `14_004` error

## Expected behavior
Payment goes through successfully as both the `googlePayToken` and `googlePayCardNetwork` are supplied to the `/payments` endpoint.

## Screenshots
The `/payments` endpoint failing with no `googlePayToken` or `googlePayCardNetwork` supplied:
<img width="456" alt="Screenshot 2024-10-16 at 14 54 54" src="https://github.com/user-attachments/assets/bbdc720d-def9-47c8-b00f-bd2c54ad26a7">

A breakpoint at https://github.com/Adyen/adyen-web/blob/v6.3.0/packages/lib/src/components/GooglePay/GooglePay.tsx#L63 showing the state is empty:
<img width="292" alt="Screenshot 2024-10-16 at 14 54 24" src="https://github.com/user-attachments/assets/acc91e8a-c236-45ac-b14d-0fb3c5279a7f">

## Desktop
 - OS: Mac OS Sonoma 14.5
 - Browser: Chrome
 - Version: 129.0.6668.91 (Official Build) (arm64)

**Comment by ribeiroguilherme** [comment]
Hey @mstrutt - were you using GooglePay Express with sessions on v5?  We mention in our [documentation](https://docs.adyen.com/payment-methods/google-pay/web-component/express-checkout/) that `Google Pay express checkout is supported only with the Advanced flow`. 

Are you by any chance implementing a custom `onSubmit` event or are you relying on the internals of the library to make the payments call?

**Comment by mstrutt** [comment]
Hi @ribeiroguilherme – Yes I was previously using GooglePay Express with session on v5, which was all working smoothly. Is there a reason for limiting it to the Advanced flow in version 6? When I passed through the correct `googlePayToken`/`googlePayCardNetwork` using breakpoints, the rest of the flow worked well with sessions

I am not using a custom `onSubmit` method, just relying on the internals of the library to make the payments call – which previously worked fine in v5, but does seem to have an issue with state not persisting in v6.

**Comment by ribeiroguilherme** [comment]
The problem with the sessions flow is that you can not patch the amount, meaning that in the express flow, if you update the price within the GooglePay, it won't be reflected in the backoffice once the payments call is done.  Adyen will authorize the initial amount that you used once you created the session and not the new amount.

Are you sure that you are getting the correct authorized amount in the backoffice? I am curious to know how you are patching the amount using sessions flow.

**Comment by ribeiroguilherme** [comment]
Are you using any express capabilities? Seems like you are using GooglePay as a normal payment method

Can you by any chance share the code snippet that you use to create the GooglePay component and the configuration being passed to the AdyenCheckout? So I can try to reproduce on my end your issue.
