### ISSUE TITLE
UPI component returns state as valid, although it is not

### ISSUE THREAD

**Issue by senturkozer** [Adyen/adyen-web#2915]
**Describe the bug**
For UPI intent flow, UPI component returns state as valid, although it is not.

Normally, UPI component returns state as invalid when there are validation errors. Below is an example:

![image](https://github.com/user-attachments/assets/26ca4c04-2955-476a-a682-e73328f23a1b)
![image (1)](https://github.com/user-attachments/assets/34e61482-35d7-4cfe-9b33-329c58aacef9)

However, for intent flow, UPI component returns valid, although no app is selected in the UI.

![image (2)](https://github.com/user-attachments/assets/ab9508da-cfe1-4b46-9c25-656b59ce3b67)

**To Reproduce**
1. Open UPI app with intent flow. Can be tried with a mobile browser.
2. Without selecting any app, submit.
3. See the error

**Expected behavior**
UPI component should return state as invalid when no app is selected in the intent flow.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: Any OS
 - Browser: Mobile
 - Version: @adyen/adyen-web@5.66.0

**Comment by longyulongyu** [comment]
Hi @senturkozer thanks for reporting!
Just to confirm, the issue happens when you are using your own custom pay button, and you are inspecting the state when submitting without selecting any UPI intent app?

**Comment by senturkozer** [comment]
Exactly.

**Comment by longyulongyu** [comment]
Hi @senturkozer could you check if version [5.71.1](https://github.com/Adyen/adyen-web/releases/tag/v5.71.1) fixes the issue?

**Comment by senturkozer** [comment]
Hi @longyulongyu. I checked in my local and it worked as expected.  Thank you.
