### ISSUE TITLE
FPX Online banking Malaysia Component  IssuerList  not displayed

### ISSUE THREAD

**Issue by duhongjun** [Adyen/adyen-web#2923]
**Describe the bug**
i  use adyen drop-in v5 before，the component behavior is correct  with an issuerList select, see the image :
![image](https://github.com/user-attachments/assets/2ad10c25-4d62-4540-b3a7-58efeee7acfb)

and now  our project use component way  to replace drop-in，we use adyen-web v6.2.0 now，here is the code:
![image](https://github.com/user-attachments/assets/917c3c42-d8ee-4059-8f28-00c2795bf41b)
![image](https://github.com/user-attachments/assets/d4dea99f-e53a-42c6-b68b-a726f0d46a90)
![image](https://github.com/user-attachments/assets/c7de204e-5ed3-4cea-b333-4844a6756133)

and in the page,   empty content  is rendered,  see the image:
![image](https://github.com/user-attachments/assets/3519841f-6e14-4d65-b26f-6b36b21a30c6)
 
when i trigger the component submit method and submit the data  to the server，finally the page redirected to https://live.adyen.com/hpp/details.shtml,   and after i selected the bank,  the page next redirect back to our website and get the error below:
![image](https://github.com/user-attachments/assets/5ab9b0d2-07f6-48ac-b096-e140b67c866b) 

Can you give me some help? Thank you

adyen: [v6.2.0]

**Comment by ribeiroguilherme** [comment]
Hi @duhongjun ,

For the `FPX Online banking`, you need to import its own Component. Instead of `new Redirect`, you should do:

```js
const component = new MolPayEBankingMY(checkout);
```
I see that in our documentation it mentions it as `Redirect`. I will give the feedback to the docs team to fix it. 

Can you let me know if the solution above works for you?

**Comment by duhongjun** [comment]
the  issuerList  displayed, but after i select an item from the list of the bank and submit,  the state i got from onSubmit handler is wrong。I compared the parameters of drop-in before with the parameters of components now:
![image](https://github.com/user-attachments/assets/4b07e075-1647-4428-b0a1-3bea6c4007d6)

![image](https://github.com/user-attachments/assets/5663945c-802e-4c77-b074-ed18e30a71b7)
![image](https://github.com/user-attachments/assets/26c40bc9-c040-41ad-ad4d-fa54a5726d0a)

**Comment by duhongjun** [comment]
thank you,   now  the payment  is okay.
