### ISSUE TITLE
Behavioral Differences of Google Pay Between Web and Embedded Webview in React Native App

### ISSUE THREAD

**Issue by vanlethi-dev** [Adyen/adyen-web#2929]
**Describe the bug**

The React JS web application includes a Drop-in payment integration. When accessed directly in a web browser, the payment functionality behaves as expected. However, when this web application is embedded within a React Native app using react-native-webview, differences in behavior are observed on the payment screen. Does I need any config from react native app?

Here is my config in React JS web  :
<img width="542" alt="Screenshot 2024-10-30 at 11 37 16" src="https://github.com/user-attachments/assets/e90e6498-5688-4cc7-ae71-c4e5eed6c43e">

**Smartphone (please complete the following information):**
 - Device: android
 - Browser: Chrome

**Web:**
![Screenshot_2024-10-30-10-11-50-00_abb9c8060a0a12c5ac89e934e52a2f4f](https://github.com/user-attachments/assets/f9c38e4c-5170-44fc-984a-cb753253a052)

**React Native Embedded Webview**

https://github.com/user-attachments/assets/84f8a3ee-d002-4c36-9b97-f3da337c09b7

**Expected behavior**
I would like the embedded payment screen should behave consistently across both platforms

**Comment by m1aw** [comment]
Hello @vanlethi-dev 

Wallet payments, like Google Pay and Apple Pay are not supported inside web views or embedded browsers.

You can take a look at the [Adyen React Native library](https://github.com/Adyen/adyen-react-native), it will call the native integrations for each platform.

**Comment by vanlethi-dev** [comment]
Hi @m1aw , 

I’ve embedded https://www.mystoredemo.io/#/cart in my React Native app. When running it on an iPhone 15, I noticed that Google Pay does not appear within the app, although it does show up when accessed directly through Safari or Chrome. Could you help explain why this difference occurs?

- **In Safari Chrome:** 

![Simulator Screenshot - iPhone 15 Pro Max - 2024-11-11 at 10 45 55](https://github.com/user-attachments/assets/bb924633-7b84-4d48-b3d6-10d63adbf89b)

- **React Native Embedded Webview**

![Simulator Screenshot - iPhone 15 Pro Max - 2024-11-11 at 10 46 00](https://github.com/user-attachments/assets/134ffef0-954b-4a12-b8f8-180254dc09f4)
