### ISSUE TITLE
3DS does not call to additionalDetails after onSubmit

### ISSUE THREAD

**Issue by vunguyen10111995** [Adyen/adyen-web#2931]
**Describe the bug**
Hi everyone,
I got an issue after submitting the card method using 3ds.
After I click submit button, There is a form to input the 'password' character for the 3ds form
My expectation is the onAdditionalDetails will be called after I submit the card, so that the API payment-details can be executed. 

Environment: local environment (localhost:3000)
Adyen version: 6.1.0
Nextjs: v13.2.4

My code:
![image](https://github.com/user-attachments/assets/b0d7135e-b69e-4e0a-81e8-2799c14d17a2)

Evidences:
![image](https://github.com/user-attachments/assets/3c892571-ee98-41df-9645-19bd9aebbf91)
![image](https://github.com/user-attachments/assets/142afc2d-d4e2-4bcc-aad7-887584c5dc5b)
![image](https://github.com/user-attachments/assets/212f4731-c5b4-4160-8c11-c524a32a56a3)

Can anyone can help me?

**Comment by vunguyen10111995** [comment]
Update: I need to wait about 10 minutes, then I see the payment details is called :(

**Comment by vunguyen10111995** [comment]
I have tried to debug, and got that issue:
![image](https://github.com/user-attachments/assets/96fa2e95-e4b1-4a9a-9b23-771acff492fa)

**Comment by ribeiroguilherme** [comment]
Hi @vunguyen10111995 

If you select your filters in the network tab to show   'All' (not only the Fetch/XHR) and then click 'OK', do you see anything in the network tab?

We have an example using [Nextjs here](https://github.com/Adyen/adyen-web/tree/main/examples/nextjs) . There is a README with the instructions in how to run it. You can try it out with your account and see if the challenge works for you there.

**Comment by vunguyen10111995** [comment]
Hi @ribeiroguilherme,
I already checked with "All" tab but cannot see the request for onAdditionalDetails callback. 
I already used the next.js by clonning the adyen-web library and ran it. But those had not worked.
But when I tried to other clientKey, it worked. Did I miss any configuration for this situation?

**Comment by vunguyen10111995** [comment]
### PrepareChallenge3DS2::errorCodeObject:: {errorCode: 'timeout', message: 'threeDS2Challenge: timeout'}
The console error from my browser after 10 minutes since I submit 'password' in 3ds form.

**Comment by sponglord** [comment]
@vunguyen10111995 - what happens in the UI after you enter the word 'password' and press the Pay button?

**Comment by vunguyen10111995** [comment]
I found some issue from the Backend related to the **origin** field. The origin field should match with the current domain for implementation. Thanks guys for support.
