### ISSUE TITLE
onAdditionalDetails not triggred on 5.27 live environment 

### ISSUE THREAD

**Issue by mohcinz** [Adyen/adyen-web#2935]
**Describe the bug**
In the implementation of webcomopenet with version 5.27, the onAdditionalDetails callback is not being triggered for all cases in the live environment.

Specifically, in the India market with UPI, the onAdditionalDetails is not triggered for some orders, but only in the live environment.

  createWebConfiguration = (resp) => {
    this.webComponentConfiguration = {
      locale: resp.configuration.locale,
      environment: resp.configuration.environment,
      clientKey: resp.configuration.clientKey,
      amount: resp.configuration.amount,
      countryCode: resp.configuration.countryCode,
      onAdditionalDetails: this.submitPaymentData,
    }
  }

Observations:

In successful cases, when the onAdditionalDetails method is triggered, logs for /details can be seen on the Adyen Dashboard.
    
![image](https://github.com/user-attachments/assets/ece30e33-9fcd-4ae0-a9a5-740b00597008)

However, for some orders, the onAdditionalDetails callback is not triggered, and the /details endpoint is not called.

![image](https://github.com/user-attachments/assets/2054c4e2-2ede-49f4-bb42-43e029fe6d89)

To Reproduce
This issue happens randomly for some users.

**Expected behavior**
onAdditionalDetails should be triggered 

**Screenshots**

**Desktop (please complete the following information):**
no specific  browsers

**Smartphone (please complete the following information):**
Desktop and mobile

**Additional context**

**Comment by ribeiroguilherme** [comment]
Hi @mohcinz ,

Which payment methods are being impacted by this? Only UPI? Are you using sessions or advanced flow?

**Comment by mohcinz** [comment]
Hi @ribeiroguilherme 
Only UPI is impacted and is implemented through the Advanced flow.
