### ISSUE TITLE
Very slow Apple Pay confirmation for 6.x

### ISSUE THREAD

**Issue by strublos** [Adyen/adyen-web#2941]
**Describe the bug**
On Adyen Components version 6.x Apple Pay has very slow confirmation. Apple Pay overlay screen disappiers after few seconds later, after background success screen show. On version 5.x there is confirmation much more faster. Apple Pay overlay screen disappiers almost at same time as success screen on background.

Configuration for both versions are same, backend process too.

```
{
    "brands": [
        "amex",
        "discover",
        "jcb",
        "mc",
        "visa"
    ],
    "configuration": {
        "merchantId": "******",
        "merchantName": "*****"
    },
    "name": "Apple Pay",
    "type": "applepay",
    "buttonType": "buy"
}
```

**Expected behavior**
Overlay Apple Pay screen disappiers earlier

**Smartphone (please complete the following information):**
- different version iOS and iPhone

**Additional context**
Video for comparison for version 5.69.1 a 6.5.0

https://github.com/user-attachments/assets/0ad60bf7-5654-4743-affd-6c3231b5f075

https://github.com/user-attachments/assets/2fa30864-5e70-4110-b3ad-00d011fdab0a

**Comment by ribeiroguilherme** [comment]
Hi @strublos ,

In your `onSubmit` event, are you performing different async calls or is it taking too long to call the `actions.resolve` with its parameters? The payment overlay will be dismissed once the `onSubmit` code is executed and you resolve the function accordingly.

Just for context: In v5, the payment sheet was being always resolved to be successful right before the `onSubmit` callback is triggered, meaning that the overlay was showing payment successful before the /payments call was made (without knowing the outcome of the payment).

On v6, we adjusted the flow so we wait the execution of the `onSubmit` code  and once the event is resolved, the payment sheet is dismissed with the proper result outcome.

**Comment by strublos** [comment]
Hi @ribeiroguilherme ,
thanks for clue. Adding promise resolving to onSubmit method solved issue.
