### ISSUE TITLE
Google Pay Not Displaying on iPhone in React Native Embedded WebView

### ISSUE THREAD

**Issue by vanlethi-dev** [Adyen/adyen-web#2946]
I’ve embedded https://www.mystoredemo.io/#/cart in my React Native app. When running it on an iPhone 15, I noticed that Google Pay does not appear within the app, although it does show up when accessed directly through Safari or Chrome. Could you help explain why this difference occurs?

- **In Safari Chrome:** 

![Simulator Screenshot - iPhone 15 Pro Max - 2024-11-11 at 10 45 55](https://github.com/user-attachments/assets/bb924633-7b84-4d48-b3d6-10d63adbf89b)

- **React Native Embedded Webview**

![Simulator Screenshot - iPhone 15 Pro Max - 2024-11-11 at 10 46 00](https://github.com/user-attachments/assets/134ffef0-954b-4a12-b8f8-180254dc09f4)

_Originally posted by @vanlethi-dev in https://github.com/Adyen/adyen-web/issues/2929#issuecomment-2467183995_

**Comment by ribeiroguilherme** [comment]
Hey @vanlethi-dev ,

It does not work out of the box using Webviews. You can read more about it [here](https://stackoverflow.com/questions/66003027/react-native-webview-stripe-google-pay) and [here](https://developers.google.com/pay/api/web/support/faq#faq-10). Unfortunately there is nothing we can do from our side for this use-case.

Cheers!

**Comment by vanlethi-dev** [comment]
Hi @ribeiroguilherme, I’ve reviewed the documentation above. It only mentions support for Android, not iOS. From what I understand, Google Pay isn’t supported within webviews on iOS apps. Is that correct?

**Comment by dmengelt** [comment]
Correct. As of today the `isReadyToPay()` API returns `false` for iOS WebViews. We are looking into ways to enable Google Pay for iOS WebViews in 2025.
