### ISSUE TITLE
ACH Component No Longer Renders Billing Address Fields

### ISSUE THREAD

**Issue by cbrindle** [Adyen/adyen-web#2950]
Reason:
Our Adyen Web 6.x ACH component no longer has the ability to display billing address fields. In our previous 5.x versions, using the paymentMehtodsConfiguration.ach.billingAddressRequire: true would render billing address fields to allow a shopper to enter billign address information. A merchant reported this configuration no longer has anhy impact on the ACH components. I took a look at the Github repo (https://github.com/Adyen/adyen-web/blob/44a325f0f387fb827eb1bf7795c0360ef29c43b5/packages/lib/src/components/Ach/types.ts) and see the billingAddressRequired prop is no longer present.

Impact:
Shoppers are no longer able to enter their billing address at the time of payment, which according to our docs, could "The postal address of the shopper. Recommended to increase conversion rates."

Expected Outcome:
When passing the paymentMehtodsConfiguration.ach.billingAddressRequire: *true *parameter, billing address fields should be rendered for our drop-in and components configuration.

**Comment by RedTn** [comment]
Specifically, looks like it was removed here: https://github.com/Adyen/adyen-web/pull/2898/files#diff-a7005f2a55465ca4f35f2e873aaf3bb060d9c7c84b55e507593285e15cef758a

**Comment by camil-adyen** [comment]
Hi @RedTn, ACH doesn't use the billing address downstream. Therefore, we removed it to reduce shopper friction. We'll make sure to update the docs page to avoid confusion. Thank you for flagging!
