### ISSUE TITLE
Native coupon code field not appearing in Apple Pay Payment, even with supportsCouponCode set to true.

### ISSUE THREAD

**Issue by Gurpreet-Dhiman** [Adyen/adyen-web#2954]
**Describe the bug**
The native coupon code field is not appearing in the Apple Pay modal, even after configuring `supportsCouponCode: true` in the Adyen Web SDK configuration. The expected behavior is for the coupon code field to be displayed, allowing users to enter a coupon code during checkout, but this does not occur.

**To Reproduce**
1. Go to the checkout page with Apple Pay integration.
2. Set `supportsCouponCode: true` in the Adyen configuration.
3. Open the Apple Pay modal.
4. The native coupon code field does not appear in the modal.

**Expected behavior**
The coupon code field should appear in the Apple Pay modal when `supportsCouponCode` is set to `true`, allowing users to enter a coupon code to apply discounts.

**Screenshots**
The coupon code field is missing, even though the `supportsCouponCode` configuration is set to `true`.

**Desktop (please complete the following information):**
`@adyen/adyen-web` version: 5.66.1 (or the specific version you're using)
- Browser: Version 18.1 (20619.2.8.11.10)
- OS: macOS Sequoia (version 15.1)
- React version: 18.2.0

**Smartphone (please complete the following information):**

**Additional context**
Even though the configuration parameters `supportsCouponCode` and `couponCode` are **not** mentioned in the official [Adyen Web Component Apple Pay documentation](https://docs.adyen.com/payment-methods/apple-pay/web-component), but can be found in the [Adyen iOS Component Apple Pay documentation](https://docs.adyen.com/payment-methods/apple-pay/ios-component/). This discrepancy may indicate that these parameters are either unsupported or not properly documented for the web component.

**Comment by camil-adyen** [comment]
Hi @Gurpreet-Dhiman, thank you for raising this topic. 

Support for Apple Pay coupons on Web hasn't been requested before. We'll put this topic in our backlog and monitor similar feature requests in the coming period. For now I'll close this issue as we do not expect to pick it up any time soon.
