### ISSUE TITLE
Translation improvement Suggestion: "wechatpay.timetopay" in zh-CN.json

### ISSUE THREAD

**Issue by VicTangg** [Adyen/adyen-web#2995]
**Describe the bug**
In "zh-CN.json" the translation for "wechatpay.timetopay" is "您需要支付 %@", and that sounds like "you need to pay {{a time period}}". It is grammatically incorrect in Chinese..

In "zh-TW.json" the translation for "wechatpay.timetopay" is "您有 %@ 可以支付", the translation sounds much normal.

Similarly, the translation in "zh-TW.json" is much better for "sr.wechatpay.timetopay": "您付款的時間還剩 %#分%# %#秒%#". However, the Chinese characters needs to be converted into Simplified Chinese for "zh-CN.json"

**Expected behavior**
Would you please update the "zh-CN.json" for "wechatpay.timetopay" and "sr.wechatpay.timetopay"? Thanks.

**Screenshots**
<img width="558" alt="image" src="https://github.com/user-attachments/assets/17a7cd34-20f4-4bc7-a30d-a9ae4e083256">

**Comment by longyulongyu** [comment]
Hi @VicTangg I agree with you that translations from zh-TW.json sound better. We will update the translations. 
From the UI, it looks like the merchant is using our v6 sdk? Could you confirm if it's the case?

**Comment by VicTangg** [comment]
Hi @longyulongyu , indeed, this is a net new merchant and they started with the v6 SDK!
