### ISSUE TITLE
Paypal webview crashes when using dynamic zero auth

### ISSUE THREAD

**Issue by nsarno** [Adyen/adyen-web#305]
**Describe the bug**
Paypal webview crashes when using dynamic zero auth ($0 authorization)

Following the documentation here:
https://docs.adyen.com/payment-methods/paypal/web-component

**To Reproduce**
1. Setup the Paypal web component with `intent: "authorize"`
2. Setup the payments API call with a $0 amount and `PreAuth` authorization type
3. Click on the Paypal button
4. See Paypal webview loading then crashing with the following error showing up in the console:

```
Expected intent from order api call to be authorize, got capture. Please ensure you are passing intent=capture to the sdk url.
```

**Expected behavior**
- The Paypal login window should be displayed for a $1 authorization.
- The $1 authorization should be automatically canceled (dynamic zero auth expected behavior) 

Tried in Chrome (85) and other browsers. Not a browser or platform issue.

I also tried to change the intent to capture and remove the pre-auth authorization, no dice.

Appreciate your help!

**Comment by nsarno** [comment]
This is what the payload sent to `/payments` looks like (in our ruby code)

```ruby
{
  merchantAccount: merchant_account,
  reference: reference,
  shopperReference: shopper_reference,
  shopperEmail: shopper_email,
  shopperStatement: shopper_statement,
  paymentMethod: payment_method,
  enableRecurring: true,
  recurringProcessingModel: RECURRING_PROCESSING_MODEL,
  storePaymentMethod: true,
  returnUrl: return_url,
  amount: {
    currency: currency,
    value: 0 # if I replace this with `100`, everything works as expected. But then we don't have dynamic zero auth.
  }
}
```

And this is how I create the Paypal component on the frontend:

```js
const paypalComponent = checkout
  .create("paypal", {
    environment,
    amount: {
      currency,
      value: 0,
    },
    intent: "authorize",
    merchantId,
    onSubmit: (state, component) => {
      const data = {
        returnUrl,
        ...state.data,
      };

      initiatePayment(data, component)
        .then((res) => handleServerResponse(res, component))
        .catch((error) => {
          throw Error(error);
        });
    },
    onCancel: (data, component) => {
      component.setStatus("ready");
    },
    onError: (error, component) => {
      component.setStatus("ready");
    },
    onAdditionalDetails: (state, component) => {
      submitPaymentDetails(state.data, component)
        .then((result) => {
          finalRedirect(result);
        })
        .catch((error) => {
          throw Error(error);
        });
    },
  })
  .mount("#paypal-container");
```

**Comment by pabloai** [comment]
Hi @nsarno,

Thanks for the extensive report!
We're currently investigating this and get back to you once we have a clear answer. Cheers!

**Comment by ribeiroguilherme** [comment]
Hi @nsarno ,

Seems like this issue is stale. I hope you managed to go around this problem. Might be worth to mention that we introduced PayPal ZeroAuth (https://github.com/Adyen/adyen-web/pull/1311) on v5.3.0 .

I am going to close this ticket for now, but feel free to reach out if you still have issues with the library. I can reopen this issue or you can create a new one. Thanks!
