### ISSUE TITLE
Many of your test cards are invalidated

### ISSUE THREAD

**Issue by josefnorlin** [Adyen/adyen-web#327]
**Describe the bug**
When using the test cards found in your documentation many cards don't work, take the first one for instance 3700 0000 0000 002. 
https://docs.adyen.com/development-resources/test-cards/test-card-numbers

**To Reproduce**
You can test this yourself using the checkout component and filling in: 3700 0000 0000 002

**Expected behavior**
It should be valid since it's in your documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/23150232/94105923-a0598100-fe3a-11ea-9a1d-0bb6aadfbe80.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome 
 - Version: 80.0.3987.122 64 bit

**Comment by pabloai** [comment]
Hi @josefnorlin, and thanks for reaching out.

Those are indeed valid test cards, but keep in mind you still need to have those card brands configured in your account. You probably don't want to accept all card brands there are.

For more information about how to add and configure different payment methods, check our [Payment Methods documentation page](https://docs.adyen.com/payment-methods#add-payment-methods-to-your-account). Also feel free to contact our [Support team](https://www.adyen.help/hc/en-us) if you need further help.

Have a nice day, cheers!

**Comment by josefnorlin** [comment]
Thank you @pabloai ! 
The reason why I think this is a bug is that this just started to happen, around the same time we moved over to clientKey but seems to be unrelated. And from what I know we haven't changed anything in the configuration. Amex (which this card in particular is) is still a valid payment method, and the card number have been working great before: 3700 0000 0000 002

**Comment by pabloai** [comment]
Hi again @josefnorlin,

I imagine this is happening in your test environment, right?
And just to know, did you double check if you're using the clientKey for test? Do you see any errors in the console?

Another thing you can try is to check the `brands` array in your Card component by simply doing `myCardComponent.brands`. Is Amex listed there?

I'm not being able to reproduce that behaviour, but if you think it's indeed a bug, of course feel free to reopen the issue!

**Comment by josefnorlin** [comment]
This is confirmed to be clientKey problem since when we moved to originKey everything worked again.

**Comment by josefnorlin** [comment]
Can I reopen the issue or do I have to create a new one?

**Comment by pabloai** [comment]
Ok, thanks for checking.

Do you see any errors in the console? Is the clientKey for test? Is the environment also set to test?

**Comment by josefnorlin** [comment]
No errors in the console. The clientKey is for test yes, the environment is also set for testing.

binLookup?token=test_****************** gives this response:

```
{
   "detectedBrands":["amex"]
   "issuingCountryCode":"NL",
   "requestId":"babede05-3577-49dc-8583-90b090e9dea7"
}
```

**Comment by pabloai** [comment]
Were you able to also check this:

> Another thing you can try is to check the brands array in your Card component by simply doing myCardComponent.brands. Is Amex listed there?

**Comment by josefnorlin** [comment]
@pabloai, I'd love to test that. Could you give me more precise instructions? With myCardComponent, do you mean checkout.brands (which seems not to work)? Or how do I access that?

**Comment by pabloai** [comment]
@josefnorlin, sorry if I wasn't clear.

When you create the card component, do you store it in a variable?

For example
```js
const cardComponent = checkout.create('card', { /* options */}).mount('.contianer');
```
If so, you can simply do `cardComponent.brands` to get an array of the brands the card component is expecting. The idea is to see if Amex is among those brands.

**Comment by josefnorlin** [comment]
I see, tested that now and that array is completely empty.

**Comment by pabloai** [comment]
Thanks for checking.
It seems the Card component is not configured correctly, since it doesn't have a list of brands it should accept.
For this you can make a call to our `/paymentMethods` endpoint and pass the response to the `AdyenCheckout` constructor in the `paymentMethodsResponse`. Alternatively you can pass a `brands` array with the list of brands you want to accept.
For more information please refer to our [Card components docs](https://docs.adyen.com/payment-methods/cards/web-component#show-the-available-cards-in-your-payment-form).
