### ISSUE TITLE
Register custom payment type in DropIn component

### ISSUE THREAD

**Issue by mrkosima** [Adyen/adyen-web#328]
The project I'm working on is using custom giftcards configuration along with other payment methods.

At the moment `DropIn` component supports only [predefined set](https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/components/index.ts) of types.

But my giftcard payment method has a custom type (like `"mygiftcard"`).
So I have to render `Giftcard` component next to DropIn in this case.
That causes some UX issues and complexities in the implementation.

Also It worth to mention that I have a `CustomGiftcard` component with extra functionality, like checking balance.

I'd like to be able develop a custom payment component (maybe extended from `UIElement`?) and to register it `DropIn` component.

**Comment by pabloai** [comment]
Hi again @mrkosima!

I don't think this is something we're planning to support the addition of external components into the Drop-in.
I think the best thing to do on that scenario would be to create your own DropIn-like list and use a component individually for each of the payment methods.

Let us know if there's any other thing we can do to help. Cheers!
