### ISSUE TITLE
Not showing PayPal button correctly

### ISSUE THREAD

**Issue by NoemiSzabados** [Adyen/adyen-web#34]
**Describe the bug**
After updating the latest version of Adyen (3.8.1), we found an issue that the Paypal button not showing correctly every time. We experienced it most of the time when we changed from Credit card to Paypal.  We can also see the issue in your demo shop. [Here is a video](https://www.dropbox.com/s/4k127n8zsls3wjy/pbN0eGDpi7.mp4?dl=0) for better insights.

**To Reproduce**
1. In the drop-in component, choose PayPal as the payment method
2. Change to Credit Card
3. Change back to PayPal

The issue is not always visible, but we experienced it a few times.

**Screenshots**
![image (12)](https://user-images.githubusercontent.com/60874640/84863757-c7ebc100-b075-11ea-9ae4-2adb3c3f230b.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 83.0.4103.106

**Comment by pabloai** [comment]
Hi @NoemiSzabados, and thanks for reaching!
It's hard to know how the PayPal SDK detects the available size, but I'll investigate the issue and try to think for possible ways of fixing it.

**Comment by pabloai** [comment]
Closing this issue as it needs to be fixed in the PayPal SDK.
You can check the status in paypal/paypal-checkout-components#1223
