### ISSUE TITLE
Cannot test 3dsecure 2 credit card without cvc, cannot make CVC not mandatory

### ISSUE THREAD

**Issue by lluishi93** [Adyen/adyen-web#360]
**Describe the bug**
We're trying to test different credit card numbers. In the page below, there are some cards listen. We tried to use the one marked in the screenshot:

https://docs.adyen.com/development-resources/test-cards/test-card-numbers#test-3d-secure-2-authentication
![image](https://user-images.githubusercontent.com/14786440/94723472-15581980-0359-11eb-91c8-372e2b9c67fc.png)

But there's one issue: CVC is always mandatory in the dropin, and I could not find any option to make the dropin recognise when the CVC is mandatory or not, or at least make it not mandatory at all. The only option I found is **hideCVC**, but that's not what we intend to do.

![image](https://user-images.githubusercontent.com/14786440/94723613-505a4d00-0359-11eb-8af6-ea92075a93a5.png)

**To Reproduce**
1. Set up the dropin as you would normally do.
2. Fill the fields with the previously mentioned test credit card.
3. Try to submit the dropin.
4. Verify that the CVC field is marked as incorrect

**Expected behavior**
The dropin should recognise when the CVC is required or not, or at least allow to instantiate the dropin with the CVC not mandatory at front-end level.

**Screenshots**

**Desktop (please complete the following information):**
 - iOS
 - chrome

**Additional context**

**Comment by sponglord** [comment]
Hi lluishi93,
Can you tell me what version of adyen-web you are using? 
Because we cannot recreate this issue. This is what we see when we try to pay with this maestro number:
![image](https://user-images.githubusercontent.com/22219050/94782851-1e360300-03cc-11eb-8b79-fecae1853b7a.png)

**Comment by sponglord** [comment]
This was tested with v3.6.1, v3.13.1 & v3.14.1

**Comment by lluishi93** [comment]
@sponglord we're using the npm package with the following version:
![image](https://user-images.githubusercontent.com/14786440/94783314-ccda4380-03cc-11eb-9e1b-52a7f70fbe2f.png)

How did you set the CVC to optional?

**Comment by lluishi93** [comment]
Could it be related with the supported card types? ATM, we do not provide any array with supported cards, and according to documentation: 

![image](https://user-images.githubusercontent.com/14786440/94784657-c8168f00-03ce-11eb-914b-f01012e20aaf.png)

**Comment by sponglord** [comment]
Indeed - you are not saying that you support maestro. Therefore we cannot recognise the brand and make decisions about whether the cvc is optional or not.
What happens in this case is we say: _"we don't recognise the card brand from this number, but if it validates correctly we'll allow the shopper to try and use it"_. But then of course we treat it as a "regular" credit card (needs date & cvc)

**Comment by lluishi93** [comment]
Ok, so we can close this for now then! TY
