### ISSUE TITLE
[FEAT] Extend AdyenCheckout locale typings

### ISSUE THREAD

**Issue by nklaasse** [Adyen/adyen-web#364]
When configuring `AdyenCheckout` options, the `locale` key is typed from the locales Adyen supports translations for. Since we should be able to add any locale we want, which might required to integrate our own translations, it should be possible to use our own locales beside the supported ones. As an example, using a locale such as `uk-UA` is not possible at this moment.

[https://github.com/Adyen/adyen-web/tree/master/packages/lib/src/language/locales](https://github.com/Adyen/adyen-web/tree/master/packages/lib/src/language/locales)

**Comment by pabloai** [comment]
Hi @nklaasse, thanks for the report.
Good catch, I'll work on a fix.

**Comment by pabloai** [comment]
The fix was merged and will be included in our next release.
Let us know if there's anything else. Cheers!
