### ISSUE TITLE
Dropin not formatting installments correctly

### ISSUE THREAD

**Issue by lluishi93** [Adyen/adyen-web#41]
**Describe the bug**
The dropin is not formatting the installments options correctly. It divides the price per 100. Example:

```js
const adyenCheckout = new window.AdyenCheckout({
      locale: this.ctx.store.getters.locale,
      environment: this.PAYMENT_ENVIRONMENT,
      originKey,
      paymentMethodsResponse: parseToAdyenConfig({ paymentModes, storedCards: this.ctx.store.state.user.creditCards || [] }),
      showPayButton: false,
      paymentMethodsConfiguration: {
        card: {
          amount: { value: 330, currency: 'USD', // Doesn't matter if this is EUR, USD, or MXN, it fails every time...
          hasHolderName: true,
          holderNameRequired: true,
          enableStoreDetails: isLogged,
          hideCVC: false,
          name: this.ctx.store.state.checkout.labels.cardData,
          installmentOptions: installmentConfig?.paymentModes
        }
      }
```

**To Reproduce**
1. Set up the dropin like above
2. Doesn't matter which price or currency you introduce (I've tried with EUR, USD and MXN), the price always gets divided per 100.
3. See the installment options

**Expected behavior**
The price gets formatted correctly, not divided per 100.

**Screenshots**
Output:
![image](https://user-images.githubusercontent.com/14786440/85126005-e0eaa280-b22c-11ea-88b8-50f20bc57580.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser chrome
 - Version 81.0.4044.92

**Additional context**

**Comment by pabloai** [comment]
Hi @lluishi93.

Adyen always uses minor units for amounts.
This means you need to pass `30000` as the value for a $300 amount.
You can learn more about this in our [Currency codes](https://docs.adyen.com/development-resources/currency-codes) page.

Have a nice day, and thanks for reaching.
