### ISSUE TITLE
Cannot test BLIK payment, stays with "Waiting for confirmation" message

### ISSUE THREAD

**Issue by dawidcieszynski** [Adyen/adyen-web#424]
**Describe the bug**
When trying to test BLIK payment I can't process it to the final stage.

**To Reproduce**
1. Start adyen-web project, go to Components->BLIK with a predefined amount of 144.00 (http://localhost:3020/components?amount=14400)
2. Type test BLIK code: 777777
3. Click on "Pay" button
4. See "Waiting for confirmation" message with spinner. It never shows any success or failure message

**Expected behavior**
Expected to see "user declined" refusal reason as described here:
https://docs.adyen.com/payment-methods/blik/web-drop-in
![obraz](https://user-images.githubusercontent.com/7561568/96619739-d4737500-1306-11eb-8b8d-c49b4558e665.png)

**Screenshots**
![obraz](https://user-images.githubusercontent.com/7561568/96619715-cc1b3a00-1306-11eb-8767-2abf3339037d.png)
![obraz](https://user-images.githubusercontent.com/7561568/96619726-d1788480-1306-11eb-93e1-a754020309d1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version 85

**Additional context**
Tried on 3.15.1 in the real site and 3.17.0 adyen-web from the repository (master branch).
Moreover there were no BLIK payments in **Customer Area > Transactions > Payments**.

**Comment by marcperez** [comment]
Hi @dawidcieszynski,

I've just tested this flow and it works fine on my end (the simulated response takes some time before it comes back as refused).
I'd advise you to [contact our support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420), they will be able to help you further.

Thanks!

**Comment by dawidcieszynski** [comment]
Thanks @marcperez 

I've tried on another computer and another network but without success. There are requests for status but all are "pending".
`{"payload":"Ab02b...==","resultCode":"pending","type":"complete"}`

I will contact support team.

**Comment by marcperez** [comment]
Great, thanks @dawidcieszynski !
