### ISSUE TITLE
Is hardcoded '05' size for 3DS 2 Challenge a bug or a feature?

### ISSUE THREAD

**Issue by gytisgreitai** [Adyen/adyen-web#465]
Hi,

[Your docs state](https://docs.adyen.com/checkout/3d-secure/native-3ds2/web-component#3ds2-component): 
`In addition, you can also configure a window size in case the issuer decides to initiate a challenge authentication flow. `

But if we look at the code, we see that size `'05'` is hardcoded for `threeDS2Challenge` component and cannot be overwritten:

https://github.com/Adyen/adyen-web/blob/6f60ffc628fe34616c8fc517283018fdf0060a28/packages/lib/src/core/ProcessResponse/PaymentAction/actionTypes.ts#L32

Is this a bug in the code or a bug in the documentation?

Thanks!

**Comment by marcperez** [comment]
Hi @gytisgreitai,

Thanks for opening this issue. You are right, this value can't be set at the moment. It will be fixed as part of #412.

Hope this helps.

Best,
Marc

**Comment by gytisgreitai** [comment]
Hey, @marcperez 

I see that  https://github.com/Adyen/adyen-web/pull/412 has been merged, but the hardcoded '05' was left as is https://github.com/Adyen/adyen-web/pull/412/files#diff-fd4b71c6e57f487c005bfbff6c2c57a932592ce05cfe35c75ae9014beed3d7beR34 

I've upgraded to 3.18.1, but setting `{ size: '04' }` still has no effect. 

Am I missing something?

**Comment by marcperez** [comment]
Hi @gytisgreitai,

We've updated our default 3DS2 challenge size configuration on our latest release (#620). The new default is size `02` and now it should also let you override that property. This is part of version `3.21.1`.

I'll close this issue, but feel free to reopen if necessary.

Best,
Marc
