### ISSUE TITLE
Dropin Error: adyen.js:1 Uncaught (in promise) TypeError: Cannot read property 'state' of null

### ISSUE THREAD

**Issue by nastikue** [Adyen/adyen-web#546]
**Describe the bug**
If to add setState call inside of onChange, onSubmit or onAdditionalDetails, adyen will fail with error 'Cannot read property 'state' of null' http://prntscr.com/vpscsz

**To Reproduce**
1. Create clear react project
`npx create-react-app test-adyen`
2. Add "@adyen/adyen-web": "^3.18.2", in package.json dependencies
`npm i`
3. Define component state
`const [dropinState, setDropinState] = useState(null);`
4. In App.js create dropin component with minimum config that contain
`onChange: (state) => setDropinState(state)`
Example code for App.js:
```
import React, { createRef, useEffect, useState } from 'react';
import './App.css';
import AdyenCheckout from '@adyen/adyen-web';

function App() {
  const dropinContainer = createRef();
  const [dropinState, setDropinState] = useState(null);

  const onChange = (state) => setDropinState(state);
  const config = {
    environment: "test",
    originKey: 'pub.your_pub_key_here',
    paymentMethodsResponse: {
      paymentMethods: [
        {
          brands: ["mc","visa"],
          details: [
            { key: 'encryptedCardNumber', type: 'cardToken' },
            { key: 'encryptedSecurityCode', type: 'cardToken' },
            { key: 'encryptedExpiryMonth', type: 'cardToken' },
            { key: 'encryptedExpiryYear', type: 'cardToken' },
            { key: 'holderName', optional :true, type: 'text' }
            ],
          name: "Credit Card",
          type:"scheme",
        }
      ]
    },
    onChange,
  };
  useEffect(() => {
    if (dropinContainer) {
      const adyenCheckout = new AdyenCheckout(config);
      adyenCheckout.create('dropin').mount(dropinContainer.current);
    }
  }, [dropinContainer, config]);

  return (
    <div className="App">
      <div ref={dropinContainer} className='dropin-component' data-test-id='dropin-container' />
    </div>
  );
}

export default App;
```

5. Run project, change any field (i.e. card number)

**Expected behavior**
Dropin component works without errors

**Screenshots**
![завантаження](https://user-images.githubusercontent.com/13137535/100226627-e48aff80-2f17-11eb-8060-7d19ef01c4f2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser: Chrome
 - Version: 87.0.4280.66

**Additional context**
error in formatted adyen.js is in line 8523: http://prntscr.com/vpsvq8

**Comment by Lesleyvdp** [comment]
We ran into a similar issue not long ago, it turns out that this happens because of the useEffect that creates the checkout and mounts it is executed multiple times because your useEffect hook has dependencies. We removed our dependencies from the array and that fixed our issue.

**Comment by nastikue** [comment]
> We ran into a similar issue not long ago, it turns out that this happens because of the useEffect that creates the checkout and mounts it is executed multiple times because your useEffect hook has dependencies. We removed our dependencies from the array and that fixed our issue.

It doesn't sound like a solution at all: if I remove dropinContainer from dependencies dropin component won't mount correctly.

**Comment by pabloai** [comment]
Hi @nastikue, and thanks for reaching out.

After seeing the code snippet you shared it seems the problem here is that you're using `createRef`, which will return a new ref on every render. Using `useRef` instead should solve the issue.

I made a quick demo here where you can see it in action.
https://codesandbox.io/s/frosty-hill-tmupv?file=/src/App.js
I'm using the Sepa component instead of the Card component just to simplify the demo, but it's the same thing.

Hope this helps, let us know if there's anything else!

**Comment by nastikue** [comment]
@pabloai thank you for your research, it really helped much: saving to state works after createRef is changed to useRef. There is warning in adyen documentation to avoid DOM element rerenders https://docs.adyen.com/checkout/drop-in-web http://prntscr.com/vthj7b and I found out that similar error can be received if to define a callback inside sibling element, i.e. onClick in button in the below example:
```
<div className="App">
      <div
        ref={dropinContainer}
        className="dropin-component"
        data-test-id="dropin-container"
      />
      <button onClick={()=> console.log('button')}>Button that produces error</button>
</div>
```

I think that these errors handling should be added in adyen to make it clear to developers where the problem is.

**Comment by pabloai** [comment]
Hi @nastikue,

I'm glad that helped. About the warning in the Docs, it's to favor passing a reference to the `mount` method instead of passing a DOM element or a selector string In your example this is done correctly.

Regarding the arrow functions in the JSX props, keep in mind this is a bad practice in React anyway. There's even a lint rule to check this: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

Cheers,
