### ISSUE TITLE
Paypal about:blank window not closed on iOS

### ISSUE THREAD

**Issue by gepdev** [Adyen/adyen-web#552]
**Describe the bug**
After submitting the payment data using the paypal smart button the pop up window stays in loading and it is not closed. 
The action passed from backend is:
`{
type: 'redirect',
paymentData: '',
method: 'GET',
url: 'https://test.adyen.com/hpp/checkout.shtml'
}`
The only way that i had to handle the action from backend is using createFromAction method from adyen components.
I set the status of dropin to ready after action is received but nothing happens.

**Expected behavior**
Close the pop up window after createFromAction and redirection to paypal

**Smartphone (please complete the following information):**
 - Device: iPhone 6s
 - OS: iOS 14.2
 - Browser Safari

**Additional context**
As backend i use magento with magento-adyen 6.6.5 plugin and as front end the PWA using Vuestorefront and adyen-web 3.18.2
***

**Comment by pabloai** [comment]
Hi @gepdev, and thanks for reaching out.

That `action` object doesn't seem to be correct.
The PayPal component should return a `paymentMethod` object which includes the `subtype`:
```json
  "paymentMethod": {
    "type": "paypal",
    "subtype": "sdk"
  }
```
in order to the `/payments` response to contain an action of type `sdk`:
```json
"action": {
  "paymentData": "...",
  "paymentMethodType": "paypal",
  "sdkData": {
    "token": "..."
  },
  "type": "sdk"
}
```
Could you check if this is the case? Is the component returning the `subtype`?

**Comment by gepdev** [comment]
Hi @pabloai, thanks for your reply. 
`action` is of the type redirect which i'm gettind as response of the `V1/adyen/orders/:orderId/payment-status` endpoint from magento api. Consider that i'm using magento pwa type of integration. 
https://docs.adyen.com/checkout/components-web/#step-4-additional-front-end
This is example of the response of the endpoint:
```
{
  "code": 200,
  "result": {
    "threeDS2": false,
    "checkoutAPM": true,
    "threeDSType": "RedirectShopper",
    "resultCode": "RedirectShopper",
    "action": {
      "type": "redirect",
      "method": "GET",
      "url": "https://test.adyen.com/hpp/checkout.shtml?u=redirectPayPal&p=",
      "paymentData": "..."
    },
    "details": [
      {
        "key": "payload",
        "type": "text"
      }
    ]
  }
}
```
With this type of action `paypaDropin.handleAction(action)` throws error as it needs different type of action as in you example. 
So my solution was to handle this redirect action using the method `checkout.createFromAction(action).mount($refs.checkout)`
https://docs.adyen.com/checkout/components-web/#step-4-additional-front-end
And this in my case works but then after redirection to the url `https://test.adyen.com/hpp/checkout.shtml` only in iOS the pop up window doesn't close. All other device types the pop up is closed.
I set `paypalDropin.setStatus('ready')` before executing `createFromAction()` 

Is it ok how i'm doing? Is there any solution/workaround to manage the opened window?

**Comment by pabloai** [comment]
Hi @gepdev,

There was an issue with our API which caused a wrong action object to be returned for PayPal. This was fixed yesterday and should be back to normal. Could you check if your issue was related to this? Let us know if the issue persists.

As stated before, the action type should be `sdk`, and passing the action object to the `handleAction` method should work.
Let us know if this helps, cheers.

**Comment by gepdev** [comment]
Hi @pabloai,
no i have tried with my current configuration but i still have the issue. 
Should I update the magento adyen plugin? Currently I use 6.6.5
Thanks for your help
cheers

**Comment by gepdev** [comment]
Hi @pabloai this is not an issue anymore. Thanks for the support
