### ISSUE TITLE
Credit Card endless loading loop 

### ISSUE THREAD

**Issue by emidev98** [Adyen/adyen-web#567]
**Describe the bug**
Dear Adyen Team we have found an issue with the Credit Card where sometimes fall in an endless loading loop because cannot load the iframes. 

**To Reproduce**
We do not have a specific "follow to reproduce" but we have a stack trace of the error:

`
edp-checkout-page-module-es2015.bc67bb5be7048eccdc49.js:1 GET https://checkoutshopper-live.adyen.com/checkoutshopper/securedfields/{CLIENTKEY}/3.2.6/securedFields.html?type=card&d=aHR0cHM6Ly93d3cuYWxsaWFuemRpcmVjdC5kZQ== net::ERR_CACHE_WRITE_FAILURE 200 (OK)
`
stacktrace noise....
`
edp-checkout-page-module-es2015.bc67bb5be7048eccdc49.js:1 GET https://checkoutshopper-live.adyen.com/checkoutshopper/securedfields/{CLIENTKEY}/3.2.6/securedFields.html?type=card&d=aHR0cHM6Ly93d3cuYWxsaWFuemRpcmVjdC5kZQ== net::ERR_CACHE_WRITE_FAILURE 200 (OK)
`
stacktrace noise....
`
securedFields.html?type=card&d=aHR0cHM6Ly93d3cuYWxsaWFuemRpcmVjdC5kZQ==:149 The devicemotion events are blocked by feature policy. See https://github.com/WICG/feature-policy/blob/master/features.md#sensor-features
`

**Additional context**
We know that it is happening most of the times in Google Chrome but we could not find any way to solve it or to reproduce it based on a pattern. The people that fall in the endless loading loop they refresh the browser and they are able to use the credit card normally. 

The library version is 3.17

Thank you very much.

**Comment by marcperez** [comment]
Hi @emidev98,

Thanks for opening this issue and our apologies for the delayed response! Are you still experiencing this issue? I haven't been able to reproduce it.

If this is still the case, could you please confirm your Google Chrome's version? It would also be relevant to know if you have any extension installed (and if this still happens with those disabled).

**Comment by emidev98** [comment]
Hello @marcperez,

No problem, thanks for your time. Our engineering team investigated the topic but seems like there is no easy way to reproduce the bug (we even disabled all the extensions in the browser). 
Our conclusion was to check the code of the securedfields but when we asked to the Adyen Support Team they declined the access to that code.
Regarding the Google Chrome version I do not remember the specific version but should be some from 80 to 88 version.

**Comment by emidev98** [comment]
@marcperez one of our colleagues reproduced the issue with `Google Chrome Versione 87.0.4280.66 (Build ufficiale) (a 64 bit)`.
We asked to her a lot of question but seems like she was not doing anything "strange" and also she had no extensions in the browser.

**Comment by emidev98** [comment]
We have another colegue that falled in that issue with Google Chrome 88.0.4324.104 (Offizieller Build) (64-Bit)

**Comment by emidev98** [comment]
I could reproduce it myself. I felled in this error with the next warning in the console 
![image](https://user-images.githubusercontent.com/49301655/107779285-6e8f7b00-6d45-11eb-9bc6-0484936fc02f.png)
I followed the [link](https://github.com/w3c/webappsec-permissions-policy/blob/master/features.md#sensor-features) but I could not find very much relevant info

**Comment by emidev98** [comment]
We have detected that this bug was created because of a cache policy that some of our laptops have installed.
I'll procede to close the issue. Thank you for support!

**Comment by marcperez** [comment]
That's good to know, thanks @emidev98!
