### ISSUE TITLE
Credit Card date validation

### ISSUE THREAD

**Issue by emidev98** [Adyen/adyen-web#572]
**Describe the bug**
Dear Adyen Team, we spotted that it's possible to use a invalid date for the date field and it returns that it's valid.
![image](https://user-images.githubusercontent.com/49301655/101054276-02480c80-3589-11eb-8689-625a6cd5f316.png)

**Additional context**
The library version is 3.17

**Comment by sponglord** [comment]
Hi emidev98,
This is, in fact, correct behaviour. The credit card issuer's state that a credit card that is out of date can still be valid as long as it is not _too_ far out of date.
In checkout we check that the expiry date isn't more than 30 years in the future (15 years prior to release v3.8.1) and isn't _more than 3 months in the past_. This is the short answer.
The long answer is that the expiry date can actually be 3, to almost 4, months in the past
- For the past we look at full months, disregarding the current, incomplete month.
So if, for example, the date is March 29: the month is not yet over - so we count 3 months from, and including, the previous full month. So February, January & December 2019.
This means that on March 29, 2020 you could type an expiry date of 12/19 and it would be considered valid. This is almost 4 months in the past.
By April 1, 2020 however when we count 3 full months in the past (March, February, January) then an expiry date of 01/20 will be valid and anything before that won't. This is only 3 months in the past.

**Comment by emidev98** [comment]
Thank you very much for the clarifications!
