### ISSUE TITLE
Paypal fails with Invalid Action v65 // 3.18.2

### ISSUE THREAD

**Issue by steffenmllr** [Adyen/adyen-web#575]
**Describe the bug**
I'm trying to use the drop in solution to handle the paypal flow. This fails with an `Error: Invalid Action`.

<img width="651" alt="invalid_action" src="https://user-images.githubusercontent.com/449563/101276728-33a22180-37af-11eb-816f-360247b6bb5e.png">

**To Reproduce**

The paymentMethod is taken from the `onSumit` call within a `checkout.create('dropin')`

### 1. Payment request
```bash
curl https: //checkout-test.adyen.com/v65/payments \
-H "x-API-key: XXXX" \
-H "content-type: application/json" \
-d '{
    "additionalData": {
        "allow3DS2": true
    },
    "amount": {
        "currency": "EUR",
        "value": 12400
    },
    "billingAddress": {
        "city": "Berlin",
        "country": "DE",
        "houseNumberOrName": "63",
        "postalCode": "10117",
        "street": "Friedrichstrasse"
    },
    "channel": "Web",
    "countryCode": "DE",
    "deliveryAddress": {
        "city": "Berlin",
        "country": "DE",
        "houseNumberOrName": "63",
        "postalCode": "10117",
        "street": "Friedrichstrasse"
    },
    "lineItems": [
        {
            "amountIncludingTax": 11900,
            "description": "An Elephant",
            "id": "some-id",
            "quantity": 1,
            "taxCategory": "high"
        }
    ],
    "merchantAccount": "MyMerchantAccount",
    "origin": "http://localhost:3030",
    "paymentMethod": {
        "subtype": "sdk",
        "type": "paypal"
    },
    "reference": "my-order-id",
    "returnUrl": "http://localhost:3030/checkout/return?oid=my-order-id",
    "shopperEmail": "my@email.com",
    "shopperIP": "::1",
    "telephoneNumber": "0000"
}'
````

### 2. Returns `CartOrderResponse`
```json
  {
    "resultCode": "Pending",
    "action": {        
        "paymentData": "Ab0...",
        "paymentMethodType": "paypal",
        "sdkData": {
            "token": "EC-3.."
        },
        "type": "sdk"
    },
    "details": [
        {
            "key": "token",
            "type": "text"
        }
    ],
    "outputDetails": {
        "token": "EC-3.."
    },
    "paymentData": "Ab0...",
}
```

### 3. Render within React
```tsx
    const setupAdyenPayment = async (orderResponse: CartOrderResponse) => {
        try {
            // eslint-disable-next-line
            // @ts-ignore
            await import('@adyen/adyen-web/dist/adyen.css');

            const AdyenCheckout = await import('@adyen/adyen-web');
            const configuration = {
                locale: config.adyenLocale,
                environment: config.adyenEnv,
                clientKey: config.adyenClientKey,
                translations,
                onAdditionalDetails: async (state: any) => {
                    try {
                        await onSubmitChallenge(state.data);
                    } catch (err) {
                        console.log(err);
                    }
                }
            };
            if (containerRef.current) {
                const checkout = new AdyenCheckout.default(configuration);
                checkout.createFromAction(orderResponse.action).mount(containerRef.current);                
            }
        } catch (err) {
            console.log(err);
        }
    };
```

**Expected behavior**
Should not throw an error but handle paypal

**Desktop (please complete the following information):**
 - OS: osx
 - Browser ff
 - Version: latest

**Comment by pabloai** [comment]
Hi @steffenmllr, and thanks for reaching out.

For the PayPal Component, you have to use the `component.handleAction` method instead of using the `checkout.createFromAction` method.

The reason for this is that the component will create a promise which will be resolved when the action is sent back to it. In other words, once the PayPal button is clicked, it will wait for the data inside the `action` object sent in the `/payments` endpoint response to show the pop-up.

I hope this helps, let us know if there's any other questions.

**Comment by steffenmllr** [comment]
@pabloai Thanks for your reply.

Our current Checkout Layout has a step for Payment (where we mount the drop in, `checkout.create('dropin').mount`), followed by a confirm step (unmounts the payment dropin, calls the `/payment` api on the server after the buy now button is clicked) and a "processing payment step"  which cals `createFromAction`

At this point we want to use the action from the backend to display the paypal popup (or redirect to paypal). Is that even possible or do we need take capture the payment when the user clicks on the paypal button the during the payment step and call your payment endpoint during that phase of the checkout?

Another thing that the documentation was not clear: is it possible to do a express checkout (getting address data from paypal) with your drop in solution /api or do I need to use the paypal component sdk for this?

**Comment by pabloai** [comment]
Hi @steffenmllr,

Unfortunately, the PayPal Smart Payment buttons flow cannot be triggered programatically, as discussed here: paypal/paypal-checkout-components#287

With that in mind, you could hide the button from the Drop-in but you'd need to show it somewhere else on the page (or on a different page later), but it would still need a click from the shopper to trigger the flow.

**Comment by steffenmllr** [comment]
Thanks for the support, we adjusted our checkout flow so it works with paypal

**Comment by steffenmllr** [comment]
@pabloai I might closed this too soon. F

or our pay now flow we need to set the https://developer.paypal.com/docs/api/orders/v2/#definition-order_application_context `shipping_preference` to force Paypal to show the shipping address select. Any idea how this is possible ?

**Comment by ribeiroguilherme** [comment]
Closing this issue as it seems stale. If you still have problems integrating PayPal, I am happy to reopen it and help you out with that!
