### ISSUE TITLE
Paypal not working with custom pay button

### ISSUE THREAD

**Issue by makkan** [Adyen/adyen-web#576]
**Describe the bug**
A promise is created and set in the handleSubmit() function, that promise is later referenced in handleAction()->updateWithAction(). This causes a typeError function can't be resolved if the payment button is overridden. 

**To Reproduce**
1. Create a dropin with showPayButton: false
2. Directly call submit on dropin to enable payment
3. Error will occur since promise is not intialized

**Expected behavior**
Paypal should execute a payment.

**Screenshots**
react_devtools_backend.js:2430 TypeError: this.resolve is not a function
    at t.updateWithAction (adyen.js:8951)
    at t.handleAction (adyen.js:12602)

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Initialize class variables in constructor to avoid wierd side effects.

**Comment by pabloai** [comment]
Hi @makkan,

Unfortunately, the PayPal Smart Payment Buttons integration, which is used in our PayPal Component doesn't support the use of a custom pay button.

The idea of being able to set the `showPayButton` prop as `false` is to have the chance to select PayPal in the Drop-in but to show the button somewhere else in the page using the PayPal Component.

Hope this clarifies the issue. Let us know if you have any other question.

**Comment by makkan** [comment]
Hi @pabloai,

Thanks for the explanation. It could be good to refactor that part so it doesn't fail with a "nullpointer" rather something explaining the issue.
