### ISSUE TITLE
ApplePay - onClick event

### ISSUE THREAD

**Issue by lluzak** [Adyen/adyen-web#589]
**Is your feature request related to a problem? Please describe.**
I need to intercept button click to like i can do with Google Pay.

**Describe the solution you'd like**
Exactly the same as Google Pay button.

**Describe alternatives you've considered**
Rendering button myself and adding logic myself.

**Comment by marcperez** [comment]
Hi @lluzak,

Thanks for opening this issue. We were planning on to adding support for this, but we prioritized it. (See PR #592).
I'll close this ticket, feel free to reopen if you have any more comments or feedback on this.

Hope this helps!
