### ISSUE TITLE
Add card scanning capability to the checkout forms for credit cards 

### ISSUE THREAD

**Issue by ilinkMat** [Adyen/adyen-web#590]
**Is your feature request related to a problem? Please describe.**
Even though the browsers natively offer this feature, this is not consistent across browsers/devices. So on the mobile web when users are prompted with the card form they are very reluctant to type in the card details. And this results in user drop-offs at the checkout forms. 

**Describe the solution you'd like**
Is it possible to add this capability as a feature and make it visible on the form as a card icon? This way we can ensure that the behavior is consistent across devices.

I did come across a few OCR js libraries which can help us build this capability. So wanted to understand if this is a possibility or is this something that is in the works already by the team?

**Comment by marcperez** [comment]
Hi @ilinkMat,

Thanks for your suggestion. This is not something we're planning on to adding at this moment.

That said, some platforms (for example, Safari on iOS), already allow using the camera to autofill card information as a native functionality of the browser. Also, if the shopper already has a card stored in the browser, we support the autofill functionality to fill in the card information automatically.

Hope this helps!
