### ISSUE TITLE
Dispatch an event when the user has entered valid card details

### ISSUE THREAD

**Issue by bitbytebit1** [Adyen/adyen-web#640]
**Describe the solution you'd like**
When using a drop-in with a custom payment button I would like to be able to receive an event indicating that the payment information that has been filled in is valid, when this event is received I would then be able to enable my payment button

**Describe alternatives you've considered**
Don't use a drop-in.

**Comment by pabloai** [comment]
Hi @bitbytebit1, and thanks for reaching out.

In the use case you describe, you would listen to an event, for example an `onValid` and enable your custom Pay button, but what would happen then if the shopper then changes the payment information and the component is not valid anymore? Then you would need to listen to an `onNotValidAnymore` event to disable the Pay button, right?

For this reason, I would recommend to listen to the `onChange` and enable/disable the button depending of the state of the component.

```js
onChange: (state, component) => {
  if (state.isValid) {
    // Enable the Pay button
  } else {
    // Disable the Pay button
  }
}
```
I hope this helps!

**Comment by pabloai** [comment]
Closing the issue, let us know if there's anything else.
