### ISSUE TITLE
IE11: Web drop-in does not display the selected bank icon when using payment method iDeal

### ISSUE THREAD

**Issue by Lesleyvdp** [Adyen/adyen-web#674]
**Describe the bug**
The Adyen Web Drop-in does not display an icon for the selected bank in the iDeal dropdown.

**To Reproduce**
1. Integrate the Adyen Web Drop-in.
2. Ensure you have iDeal as a possible method.
3. Select any bank.

**Expected behavior**
The selected bank icon is displayed to the right of the bank's title.

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/5636166/104739906-963ff300-5747-11eb-87ca-0bd2d2abaca3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Internet Explorer
 - Version 11

**Comment by pabloai** [comment]
Hi @Lesleyvdp,

I've merged your PR, but keep in mind it was pointing to the branch of our next major version. I'll replicate the fix in other branches to also include it in minor and patch versions.

Thanks again for your collaboration and have a nice day.
