### ISSUE TITLE
Web Component: onError callback not called for cardholder name field when submit is called

### ISSUE THREAD

**Issue by TweededBadger** [Adyen/adyen-web#688]
**Describe the bug**
onError callback not called for cardholder name field when submit is called.

**To Reproduce**
1. mount component with the following configuration:
`card: {
        hasHolderName: true,
        holderNameRequired: true
      },`
2. Fill in all fields apart from card holder
3. Trigger submission via component submit() method and log onError function.

**Expected behavior**
Field should be marked as invalid AND onError method should be called

**Actual behavior**
Field is shown as invalid but onError method is not called. (It is called for the other CC fields)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version  87.0.4280.141

**Comment by marcperez** [comment]
Hi @TweededBadger,

Thanks for opening this issue, we will create an internal ticket to align the card holder name field validation with the rest of fields of the card component.

In the meantime, the `onChange` event could be a good fit for your use case. It includes the `isValid` property for every change on the component. More information can be found on the [Adyen Web documentation](https://docs.adyen.com/online-payments/components-web#step-2-add-components).

**Comment by sponglord** [comment]
Hi @TweededBadger 
From components `v4.4.0` - we have aligned how errors are communicated. When a validation error from Secured Fields occurs, we call the `onChange` event sending it an object with an `errors` property. Also present in this object are any non-Secured Fields validation errors i.e. for the cardholder name field

**Comment by marcperez** [comment]
As @sponglord explained, this can now be achieved by using the `onChange` event. We'll keep the `onError` event only for application errors. I'll close the issue. Hope this helped and feel free to reopen this issue if there are still further questions, thanks!
