### ISSUE TITLE
allow shipping changes in paypal component

### ISSUE THREAD

**Issue by fgiust** [Adyen/adyen-web#700]
The paypal component doesn't seem to allow shipping address/option configuration at this moment. Shipping address editing is disabled and there is no way to pass the required callback onShippingChange() as documented here:
https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/#:~:text=The%20Shipping%20Change%20callback%20is,address%20they%20chose%20on%20PayPal.

is this something that can be added/customized someway? Any plan to add this like in other components for supporting express checkout using paypal address book?

**Comment by pabloai** [comment]
Hi @fgiust, and thanks for reaching out.

Our integration with PayPal was built with the regular checkout flow as the main focus. Therefore, it's not possible to update an order after it was created. We could, of course, add the `onShippingChange` callback in our component, but it would only be useful to get the address details. It won't be possible to update the order. Would this still be beneficial for you knowing these limitations?

Let me know, cheers!

**Comment by fgiust** [comment]
Hi @pabloai,
clear. Well, that could be an useful starting point anyway, obviously the desired goal would be having the whole "express checkout" flow implemented :)

we are currently implementing the paypal express flow with adyen using the old integrations (paypal redirect and hpp), so I hope that what was actually feasible with not deprecated integrations would be migrated to the new one soon or later, this is a pretty common requirement nowaday... don't you see any way to implement it with smart buttons today, even with additional integrations using adyen services?

**Comment by pabloai** [comment]
@fgiust the `onShippingChange` event is available from v3.21.0.
That being said, we're not planning to support the Express Checkout flow for PayPal for now, so I'm closing this ticket.
Sorry for the inconveniences. Feel free to reach us out again in the future!
