### ISSUE TITLE
GCASH REDIRECT NOT WORKING SOMETIMES

### ISSUE THREAD

**Issue by JulianErnest** [Adyen/adyen-web#705]
Description:
When checkout container is pressed, it redirects but leads to a different website for gcash:
"https://cdn-psp.marmot-cloud.com/acwallet/alipayconnectcode?code=golcashier1611755292017sandbox&golSandbox=true&pspName=GCASH"
GCASH has been already set as one of payment methods. 
It sometimes works but most of hte time I get redirected to the site listed above. 

Expected behaviour:
It should have led me to the GCASH transaction website right? Sometimes 

Screenshots: 
![image](https://user-images.githubusercontent.com/76834365/106016041-07918580-60fa-11eb-80e2-b2c593f17ef9.png)
and here's one for paymaya proving it worked 
![image](https://user-images.githubusercontent.com/76834365/106016260-3d366e80-60fa-11eb-930f-fdcd3865f893.png)

Desktop:
WINDOWS 10

Browser:
Google Chrome 

Additional context
Tried with PayMaya and the payment process worked fine. Kudos and hope this gets noticed soon

**Comment by marcperez** [comment]
Hi @JulianErnest,

Thanks for reaching. I would advice [contacting our support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420), they'll be able to help you further.

I'll close this issue, since this doesn't seem related to this library.
