### ISSUE TITLE
Billing address country select

### ISSUE THREAD

**Issue by bitbytebit1** [Adyen/adyen-web#725]
**Steps to reproduce**  
1. Under the billing address click "Choose Country"
2. Type "swe"

**Expected Behavior**  
The select should highlight "Sweden"

**Actual Behavior**  
The select does not highlight Sweden

**Possible fixes**  
Use a select element instead of a button and ul (this will also look better on mobile in my opinion)

**Other comments**
Users are also not able to auto fill the form with their address. All other inputs are auto filled but not country

**Comment by marcperez** [comment]
Hi @bitbytebit1,

Thanks for your feedback, sounds like a good suggestion 👍 

We're currently working on improving the usability of our dropdowns by adding a search functionality, which should solve your use case. We will also take into consideration the suggestion on using a select element on mobile.

We'll update this ticket once that is ready. Hope this helps!

**Comment by marcperez** [comment]
Hi @bitbytebit1,

We were able to prioritize this feature (#776) and it will be released on our next major release (v4.0.0). I'll close this ticket, but feel free to reach us if there's any other comments or feedback you'd like to share. Thanks again!
