### ISSUE TITLE
Apple Pay instant error when pressing custom button

### ISSUE THREAD

**Issue by TriPSs** [Adyen/adyen-web#734]
**Describe the bug**
When we render the dropin with `showPayButton` put to false the apple pay directly calls our `onSubmit` when pressed, this casuses the payment the fail directly since no apple pay token exists in the payload.

**To Reproduce**
1. Disable `showPayButton`
2. Render custom button that calls `dropinRef.current.submit()`
3. Enable apple pay
4. Press the custom button
5. Error

**Expected behavior**
We expect the `onSubmit` not to be called when the payment is still in progress, like google pay.

**Smartphone (please complete the following information):**
 - Device: IPhone8
 - OS: IOS14.4
 - Browser: Safari
 - Version: 14.4

**Comment by TriPSs** [comment]
When adding the following to the `onSubmit` we got it working:
```
if (adyenState?.data?.paymentMethod?.type === 'applepay' && !adyenState?.data?.paymentMethod?.applePayToken) {
   console.debug('Apple pay payment does not have token! Cancel onSubmit')
   return
}
```

This does feel hacky though.

**Comment by marcperez** [comment]
Hi @TriPSs,

Thanks for reaching out. We've pushed a change in #1085 that should fix this issue. It'll be released in the next minor version of the library. Hope this helps!
