### ISSUE TITLE
SF 3.3.1 not deployed on Live Env?

### ISSUE THREAD

**Issue by endbay** [Adyen/adyen-web#760]
SF 3.3.1 seems like not available in Live Environment. Receive 404 error im production test.

**Comment by marcperez** [comment]
Hi @endbay,

Thanks for reaching. Apparently there was a timing issue on the deployment, it should be fixed by now.

I'll close this issue, but feel free to reopen or [contact our support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) if the problem persists.
