### ISSUE TITLE
CVC placeholder is stripped to 3 characters

### ISSUE THREAD

**Issue by ColinMorris83** [Adyen/adyen-web#788]
**Describe the bug**
When providing a custom placeholder value to secured fields setup, the value when rendered is always stripped to 3 characters.

**To Reproduce**

Specify placeholder property as part of options passed into checkout.create('securedFields', { options here })

```
placeholders: {
              encryptedCardNumber: 'Enter 16 digits',
              encryptedSecurityCode: '3 digits',
            },
```
When rendered the placeholder for CVV field will be '3 d'

**Expected behavior**

Placeholder should be displayed as '3 digits' as specified in the options.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac BigSur
 - Browser Chrome
 - Version 88

**Comment by sponglord** [comment]
Hi Colin - as it stands we've historically expected a placeholder for the CVC to be a number: '1234'.
This initially gets stripped to 3 characters for most credit cards and in the case that an Amex card type is detected we reinstate the 4th digit.
However, this is not the first time this issue has come up - so maybe it's time to discuss it again with the team...
Any solution would have to involve a "dual branded" approach like:
```
encryptedSecurityCode_3digits: '3 digits',
encryptedSecurityCode_4digits: '4 digits'
```
to cover the Amex scenario

**Comment by sponglord** [comment]
As of `v4.1.0` it is now possible to set 3 & 4 digits versions of the CVC placeholder.
This is done via the translations config in a similar way to how aria-labels are now set - see [this link](https://docs.adyen.com/online-payments/migrate-to-web-4-0-0#aria-labels-in-transaltion-fields)
The keys in question are: 
`creditCard.cvcField.placeholder.3digits` (defaults, in English, to `'3 digits'`)
`creditCard.cvcField.placeholder.4digits` (defaults, in English, to `'4 digits'`)

See full release notes for `v4.1.0` [here](https://docs.adyen.com/online-payments/release-notes#mar-9th-2021)
