### ISSUE TITLE
onSelect handler not triggering in V4.0.0 

### ISSUE THREAD

**Issue by PizzaPete** [Adyen/adyen-web#806]
**Describe the bug**
Since V4.0.0 when selecting a payment option the `onSelect` event is not being triggered.

**To Reproduce**
1. Setup a Dropin component with an `onSelect` handler.
2. Open up your browser and go to the payment panel.
3. Click on a payment option (switch from iDeal to Credit Card for example).
4. See if the `onSelect` handler is being called.

**Expected behaviour**
I expect the `onSelect` handler to be called.

**Screenshots**

**Desktop**
 - OS: MacOS 11.2.2
 - Browser: Chrome
 - Version: 88.0.4324.192

**Additional context**
It did work before migrating to V4.0.0, I might have missed something in the docs, but I see it's still mentioned here: https://docs.adyen.com/online-payments/drop-in-web#step-2-add-drop-in

**Comment by marcperez** [comment]
Hi @PizzaPete,

Thanks for reaching! In v4.0.0, we've reorganized a bit how to configure components. In this case, as this is an exclusive event of Drop-in, we now expect it on the Drop-in configuration object, it would look like this:

```js
checkout.create('dropin', {
  onSelect: () => {}, // Drop-in configuration only has props related to itself, like the onSelect event.
});
```

Please check [our migration guide to v4.0.0](https://docs.adyen.com/online-payments/migrate-to-web-4-0-0#dropin-configuration) to know more about these changes, hope this helps!

**Comment by PizzaPete** [comment]
@marcperez thanks for your reply.
I missed the migration guide, thanks for pointing that out. Got the onSelect working now.

**Comment by marcperez** [comment]
Great! Happy it works now. 
We've just updated our [release notes here on Github](https://github.com/Adyen/adyen-web/releases/tag/v4.0.0) with a link to the migration guide so it's a bit easier to find 👍

**Comment by tbgse** [comment]
hi @marcperez I stumbled upon this because we're working on our migration as well. I noticed that `onSelect` only seems to fire for the selection of the parent payment method itself (e.g. ideal / credit card / paypal etc.) but not when the actual choice of bank (e.g. abn / ing etc.) changes within the ideal payment method. Am I missing something? This used to work before 4.0.0
