### ISSUE TITLE
Can't resolve 'promise/lib/es6-extensions.js' in V4.0.0

### ISSUE THREAD

**Issue by nachogarcia** [Adyen/adyen-web#807]
**Describe the bug**
After trying to update to v4.0.0, the project build results in an error.

```
ERROR in ./node_modules/@adyen/adyen-web/dist/adyen.js
   Module not found: Error: Can't resolve 'promise/lib/es6-extensions.js' in 'node_modules/@adyen/adyen-web/dist'
   @ ./node_modules/@adyen/adyen-web/dist/adyen.js 1:10264-10304
```

We're importing the library with codesplit so we don't compromise our performance, and the CSS as indicated
` const AdyenCheckout = await import('@adyen/adyen-web' /* webpackChunkName: 'adyen' */).then(m => m.default)`
`import '@adyen/adyen-web/dist/adyen.css'`

As a framework we're using nuxt with modern build in client side, babel with @nuxt/babel-preset-app and core.js v3 with proposals.

**Comment by marcperez** [comment]
Hi @nachogarcia,

Thanks for reaching! We haven't been able to reproduce this issue, just to discard an issue with the new ES output and the specific Webpack configuration you're using, could you try the following?

```js
const AdyenCheckout = await import('@adyen/adyen-web/dist/adyen.js' /* webpackChunkName: 'adyen' */).then(m => m.default)`
```
This should load the UMD export (very similar to the one present in `v3.x`). Let us know if this works. Hope this helps!

**Comment by nachogarcia** [comment]
With both imports, the client build works fine; but when it goes to create the modern build (using modules) it breaks.

Promise is set as devDependency not a dependency, maybe it helps. By the way - any reason not to use core-js promise?

**Comment by nachogarcia** [comment]
It works now 👍 

Before
![image](https://user-images.githubusercontent.com/9975630/110505201-3722ad00-80fe-11eb-95ee-a4c6b1d4487b.png)

After
![image](https://user-images.githubusercontent.com/9975630/110505170-2eca7200-80fe-11eb-96fe-293ad3983be0.png)

After, importing directly from '@adyen/adyen-web/dist/es'
![image](https://user-images.githubusercontent.com/9975630/110506212-2e7ea680-80ff-11eb-9487-84f2b80ddd70.png)

Looks like it's not picking the es build. It does with other packages, but it might do with default webpack configs.
