### ISSUE TITLE
Set font styling on credit card, cvc and expiration date inputs

### ISSUE THREAD

**Issue by bitbytebit1** [Adyen/adyen-web#813]
**Is your feature request related to a problem? Please describe.**
We are unable to change the font family, font weight and font size on the inputs inside the iframe.
We would like to change the placeholder styling as well as the text.

**Describe the solution you'd like**
A javascript method we can call or css rules we can use to set the styling

**Comment by marcperez** [comment]
Hi @bitbytebit1,

Thanks for reaching. We have a documentation page on how to style these fields: 

https://docs.adyen.com/payment-methods/cards/custom-card-integration#styling

The card component accepts a configuration property [`styles`](https://docs.adyen.com/payment-methods/cards/web-component#show-the-available-cards-in-your-payment-form) where you can set specific styles for the fields inside of the iframe. Hope this helps!

**Comment by bitbytebit1** [comment]
Does this also work for the drop in? Or is this only for custom card integration?

**Comment by bitbytebit1** [comment]
You must set the style property on paymentMethodsConfiguration.card in order for it to take effect.

**Comment by Barnyclark** [comment]
@bitbytebit1 because the fields are loaded within an iFrame, there is no way to set a custom font. It would be good if there was a way to pass in the font URL to the iFrame so that we can use custom fonts.

**Comment by marcperez** [comment]
Hi,

Due to security constraints, we're not able to load custom fonts in our Secured Fields iFrames. [These](https://docs.adyen.com/payment-methods/cards/custom-card-integration#styling) are the list of the currently supported styles.

I hope this answered your question. I'll close this issue, but feel free to reopen or [contact our support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) if there are any other questions.

**Comment by victorbadila** [comment]
> You can style the iframe elements when using the Custom Card Web Component.

Do I understand correctly then that this does not work for the Adyen drop-in? I looked through the TS definitions for the config option and I found no reference to styles, also no example on how to use this with the drop-in.

**Comment by marcperez** [comment]
Hi @victorbadila,

You can customize the iframe styles on Drop-in too. When creating the main `AdyenCheckout` instance, you'll need to send these styles into the `card` configuration:

```js
const checkout = new AdyenCheckout({
  paymentMethodsConfiguration: {
    card: {
      styles: {
        // options from https://docs.adyen.com/payment-methods/cards/custom-card-integration#styling
      } 
    }
  }
});
```

You can see some live examples here: https://docs.adyen.com/online-payments/drop-in-web/customization?tab=fashion_6#styling-examples

Hope this helps!

**Comment by victorbadila** [comment]
Thanks @marcperez , that answered it
