### ISSUE TITLE
Importing CSS under webpack 5 fails for adyen-web v4

### ISSUE THREAD

**Issue by gareth-canva** [Adyen/adyen-web#832]
**Describe the bug**
Build fails under webpack 5 when importing adyen CSS due to the CSS file not being included in the export map in `package.json`

**To Reproduce**
Any attempt to import `@adyen/adyen-web/dist/adyen.css` under webpack 5 throws an error:
```
ModuleNotFoundError: Module not found: Error: Package path ./dist/adyen.css is not exported from package /Users/garethfoster/foo/node_modules/@adyen/adyen-web (see exports field in /Users/garethfoster/foo/node_modules/@adyen/adyen-web/package.json)
```

For convenience I have made a minimal repro available at https://github.com/gareth-canva/adyen-web-4-export-map-repro, just run `npm run build` or `yarn build` and you should see the error.

**Expected behavior**
Webpack 5 can import the CSS asset without issues.

**Comment by marcperez** [comment]
Hi @gareth-canva,

Thanks for reporting this issue, your reproduction repo was very helpful.
I've just submitted a fix (#837). I'll close the issue for now, but feel free to reopen if there's any other issue/feedback. Hope this helps!
