### ISSUE TITLE
Can't submit Paypal outside of payment form

### ISSUE THREAD

**Issue by TarasVerbniak** [Adyen/adyen-web#879]
Hi!
What's the reason of changes made by this PR [754](https://github.com/Adyen/adyen-web/pull/754)
You broke our logic by that changes.
In our website we're using one submit button for all payment methods and now we can't use it or should look for dirty "workarounds".
According to your documentation - there is possibility to disable submit buttons for each method by putting `showPayButton: false` during `adyen-web` initialisation  and then use just one submit button wherever you wish on page and programatically submit payment form.
Would be great if you can review your changes one more time.
Thanks!

**Comment by pabloai** [comment]
Hi @TarasVerbniak, and thanks for reaching out.

The only change introduced in that PR is an addition of an error message when the `submit` method is called when PayPal is selected. Before the PR, the submit would just fail. The reason for this is that the PayPal SDK doesn't allow the flow to be triggered programatically, as discussed in paypal/paypal-checkout-components#522.

One thing you could do is to indeed set the `showPayButton` prop as `false` to have the chance to select PayPal in the Drop-in but to show the button somewhere else in the page using the PayPal Component.

I hope this clarifies things. Have a nice day, and feel free to reach out again!

**Comment by TarasVerbniak** [comment]
Hi @pabloai
Ok, sorry for not-so-friendly message, I thought it was decision on your project to make these changes.
I've read their (Paypal) answers, sounds pretty weak to be honest :)
In such cases it's always better to just remind developers "It's a bad practice, use built-in button if possible" than just kill such feature.
Anyway, thanks for such quick reply! We'll work on some workaround.

**Comment by tbgse** [comment]
Hi @pabloai just ended up here with a similar issue. I'm wondering - that PayPal Component you are talking about that could be displayed elsewhere - is this part of the Adyen SDK? I've tried to look for it in the docs but cannot find it.

Also, we want to disable our submit button before our TOS were accepted - this is why we initially wanted to use a custom submit button for paypal. Is there any way to programmatically disable the paypal button either in the Drop-in or with the PayPal Component?

**Comment by pabloai** [comment]
Hi @tbgse. Yes, all payment methods shown in the Drop-in can also be used as standalone components. Please refer to the [PayPal components docs page](https://docs.adyen.com/payment-methods/paypal/web-component) for more information.

And about disabling the button, the PayPal component accepts the `onInit` and the `onClick` events, so you can use those to validate the TOS before submitting. There are some examples in the [Validation page](https://developer.paypal.com/docs/checkout/integration-features/validation/) of the PayPal documentation.

Hope this helps!

**Comment by tbgse** [comment]
@pabloai really appreciate your fast answer, i'll look into the docs you've linked here, that should do the trick for us nicely!
