### ISSUE TITLE
Configurable field order for card holder name field

### ISSUE THREAD

**Issue by ColinMorris83** [Adyen/adyen-web#882]
**Is your feature request related to a problem? Please describe.**
We would like to use the drop in card component, but our UX designs want the card holder name to be the first form field rather than the last, meaning we will need to resort to using custom secured fields.

**Describe the solution you'd like**
A configurable setting for the position of the card holder field, e.g. top or bottom

**Describe alternatives you've considered**
Have used custom secured fields

**Comment by pabloai** [comment]
Hi @ColinMorris83, thanks for reaching out.

I just created a PR to allow this, meaning it would be included in our next release, which is planned for next Monday.
I hope this helps, have a nice day!

**Comment by marcperez** [comment]
This has now been released as part of `v4.2.0`. I'll close this issue.
