### ISSUE TITLE
Importing adyen-web in next.js

### ISSUE THREAD

**Issue by trnc-ck** [Adyen/adyen-web#902]
hey,

we are unable to include the adyen web-package in our next.js app, as the following error occurs as soon as we import the lib:

`Server Error

ReferenceError: Element is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source

external%20%22@adyen/adyen-web%22 (1:0) @ eval
> 1 | module.exports = require("@adyen/adyen-web");
`

**Comment by marcperez** [comment]
Hi @trnc-ck,

Thanks for reaching. Could you share how are you installing and importing the library? What version are you using?

**Comment by trnc-ck** [comment]
hey,

we just install your lib using `yarn add @adyen/adyen-web`

and add it like this:
`import AdyenCheckout from '@adyen/adyen-web';`
`import '@adyen/adyen-web/dist/adyen.css';`

we didn't write any further code. the error occurs just using the import. regarding next.js we use the latest version.

**Comment by trnc-ck** [comment]
Ok, we fixed it… You need to load the component dynamically and disable the SSR-feature:
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

Thanks anyway!

**Comment by maheshk06** [comment]
Hi @trnc-ck
Hope you are doing good.

In Next.JS I am getting a similar issue.
I tried what you suggested.

`const AdyenCheckout = dynamic( () => import( '@adyen/adyen-web' ), { ssr: false } );`
throwing an error.
![image](https://user-images.githubusercontent.com/57614818/194690229-c93fd304-576b-4a10-a97c-190c25a60d41.png)

these line are making issues.
`      const checkout = yield call( AdyenCheckout, configuration );
      checkout.createFromAction( action ).mount( '#credit-card-con' );`

![image](https://user-images.githubusercontent.com/57614818/194690284-8cfc04ca-437b-4d8b-9043-5de1eb0788c8.png)

saga file code - 
`import Router, { useRouter } from 'next/router';
import Logger from 'xps-utils/logger';
import { call, select, put } from 'redux-saga/effects';
import { serviceRequest, getPaymentVersion } from 'library/store/payment/service-request';
import { selectTotalGrossAmt, selectBillingAddress, selectSubscriptionItemGrossAmt, selectShouldReAuthorised, selectCustom } from 'library/store/cart/selector';
import { selectPaymentId, selectPaymentDetail, selectActivePayment } from 'library/store/payment/selector';
import { selectRedirectResult } from 'library/store/global/selectors';
import { setCardAuthorized, setMaskedCardDetails, placeOrder } from 'library/store/payment/actions';
import { setPspReference } from 'library/store/payment/actions';
import { fetchData as fetchCart } from '../cart/cart';
import { pageLoading } from 'library/store/global/actions';
import { paymentError } from './payment-error';
import { selectCurrencyCode, selectBrand, selectGlobalConfig, selectLocale } from 'library/store/global/selectors';
import dynamic from 'next/dynamic';
import { useEffect } from 'react';
import AdyenCheckout from '@adyen/adyen-web';
// import AdyenCheckout from '@adyen/adyen-web';

// const AdyenCheckout = dynamic( () => import( '@adyen/adyen-web' ), { ssr: false } );
export async function* makePayment( actionType: { [key: string]: any } = {} ): any {
  try {
    console.log( 'try' );
    const activePayment = yield select( selectActivePayment );
    const shouldReauthorised = yield select( selectShouldReAuthorised );
    // const shouldReauthorised = true;
    if ( !shouldReauthorised ) return true;
    if ( activePayment !== 'Credit Card' ) return null;
    const paymentDetail: any = yield select( selectPaymentDetail );

    let redirectResult;
    const { paypalEncodedValue, adyenEnvironmentType } = yield select( selectGlobalConfig );
    const locale = yield select( selectLocale );
    // const { enable3DS } = yield select(selectAemData);
    const enable3DS = true;

    const {
      submitCreditCard,
      isValid,
      data: {
        paymentMethod: {
          encryptedCardNumber = '',
          encryptedExpiryMonth = '',
          encryptedExpiryYear = '',
          encryptedSecurityCode = '',
          holderName = ''
        } = {}
      } = {}
    } = paymentDetail;

    if ( !submitCreditCard || !isValid ) return null;
    const centAmount = yield select( selectTotalGrossAmt );
    const subscriptionGross = yield select( selectSubscriptionItemGrossAmt );
    const billingAddress = yield select( selectBillingAddress );
    const paymentId = yield select( selectPaymentId );
    const referenceID = localStorage.getItem( 'cartID' );
    const { email } = billingAddress;
    const shopperReference = `${ new Date().getTime() }${ email }`;
    const paymentVersion = localStorage.getItem( 'paymentVersion' ) || '3';
    const currencyCode = yield select( selectCurrencyCode );
    const brand = yield select( selectBrand );
    const returnUrl = window.location.href;
    const redirectUrl = window.location.href;
    const finalAmount = redirectResult ? subscriptionGross : centAmount;
    const custom = yield select( selectCustom );
    const userAgent = navigator.userAgent;
    const { availHeight, availWidth, colorDepth } = screen;
    let payload;
    // 'enable3DS' is an extra security step (handled by Adyen)
    if ( enable3DS ) {
      payload = `{
        "amount": {
          "currency": "${ currencyCode }",
          "value": ${ finalAmount }
        },
        "reference": "${ referenceID }",
        "paymentMethod": {
          "type": "scheme", 
          "holderName": "${ holderName }", 
          "encryptedCardNumber": "${ encryptedCardNumber }",
          "encryptedExpiryMonth": "${ encryptedExpiryMonth }",
          "encryptedExpiryYear": "${ encryptedExpiryYear }",
          "encryptedSecurityCode": "${ encryptedSecurityCode }"
        },
        "returnUrl": "${ redirectUrl }",
        "merchantAccount": "BrevilleECOM",
        "shopperReference": "${ shopperReference }",
        "shopperEmail": "${ email }",
        "recurring": {"contract": "RECURRING"},
        "additionalData": {"authorisationType": "PreAuth"},
        "browserInfo": {
          "userAgent": "${ userAgent }",
          "acceptHeader":"*/*",
          "language":"${ locale }",
          "colorDepth":${ colorDepth },
          "screenHeight":${ availHeight },
          "screenWidth":${ availWidth },
          "timeZoneOffset":-330,
          "javaEnabled":true
        },
        "channel": "web",
        "shopperIP":"${ custom['device-ip-address'] }",
        "deviceFingerprint": "DpqwU4zEdN0050000000000000QGeN51KNea0050271576cVB94iKzBGWmaFg0uDbuBix7RX3az8002vkTBbDITTR00000qZkTE00000J4SreNhVjkdWzFSr2Ibi:40"
    }`;
    }
    else {
      payload = `{
        "amount": {"currency": "${ currencyCode }","value": ${ finalAmount }},
        "reference": "${ referenceID }",
        "paymentMethod": {"type": "scheme", "holderName": "${ holderName }", "encryptedCardNumber": "${ encryptedCardNumber }","encryptedExpiryMonth": "${ encryptedExpiryMonth }","encryptedExpiryYear": "${ encryptedExpiryYear }","encryptedSecurityCode": "${ encryptedSecurityCode }"},
        "returnUrl": "${ returnUrl }","merchantAccount": "BrevilleECOM","shopperReference": "${ shopperReference }","shopperEmail": "${ email }",
        "recurring": {"contract": "RECURRING"},
        "additionalData": {"authorisationType": "PreAuth"}
          }`;
    }
    const data = {
      version: parseInt( paymentVersion ),
      additionalData: {
        allow3DS2: true
      },
      threeDSAuthenticationOnly: false,
      actions: [
        {
          action: 'setCustomField',
          name: 'makePaymentRequest',
          value: payload
        }
      ]
    };

    yield put( pageLoading( true ) );
    const response = yield call( serviceRequest, { url: paymentId, data } );
    const hasError = yield call( paymentError, { response } );

    // exit early if any error
    if ( hasError ) {
      yield put( pageLoading( false ) );
      return;
    }

    // if 3DS security is success then fetch latest cart (payment information)
    // this information is kept in state and additionally used on the order-confirmation route
    yield call( fetchCart );
    const rawResponse = response?.custom?.fields?.makePaymentResponse;
    const maskedCardDetailsRawResponse = response?.custom?.fields?.maskedCardDetails;
    const parsed = JSON.parse( rawResponse ) || {};
    const isAuthorized = parsed.resultCode === 'Authorised' || parsed.resultCode === 'RedirectShopper';
    let pspReference;
    let maskedCardDetailsParsed;
    const action = parsed?.action;
    if ( maskedCardDetailsRawResponse ) {
      maskedCardDetailsParsed = JSON.parse( maskedCardDetailsRawResponse ) || {};
      pspReference = parsed.pspReference;
    }

    if ( action ) {
      pspReference = action['url'].split( 'pspReference=', 2 );
      localStorage.setItem( '3DS_CALLED', 'true' );
      const configuration: any = {
        locale: locale,
        environment: adyenEnvironmentType, // live environment - https://docs.adyen.com/online-payments/components-web#testing-your-integration.
        clientKey: paypalEncodedValue
      };

      const checkout = yield call( AdyenCheckout, configuration );
      checkout.createFromAction( action ).mount( '#credit-card-con' );

    }

    yield put( setPspReference( pspReference ) );
    yield put( setCardAuthorized( isAuthorized ) );
    yield put( setMaskedCardDetails( maskedCardDetailsParsed ) );
  }
  catch ( e ) {
    Logger.requestError( 'Creditcard payment failed', e );
  }
}

/**
 * This method is responsible for submitting additional detail
 * @returns {*}
 */
export function* confirmPayment(): any {
  try {
    yield put( pageLoading( true ) );
    localStorage.setItem( '3DS_CALLED', 'false' );
    const paymentID = localStorage.getItem( 'paymentVersionId' );
    const redirectResult = localStorage.getItem( 'redirectParam' );
    if ( !redirectResult ) return null;

    const detailsObj = { details: { redirectResult } };

    const paymentVersion = yield call( getPaymentVersion, {
      variables: { id: paymentID }
    } );

    const data = {
      version: paymentVersion?.data?.me?.payment?.version,
      actions: [
        {
          action: 'setCustomField',
          name: 'submitAdditionalPaymentDetailsRequest',
          value: JSON.stringify( detailsObj )
        }
      ]
    };
    const response = yield call( serviceRequest, { url: paymentID, data } );
    const hasError = yield call( paymentError, { response } );
    if ( hasError ) {
      return;
    }
    const searchParams = new URLSearchParams( window.location.search );
    searchParams?.delete( 'redirectResult' );
    window.history.pushState( {}, '', 'checkout' );

    const rawResponse = response?.custom?.fields?.submitAdditionalPaymentDetailsResponse;
    const parsed = JSON.parse( rawResponse ) || {};
    const params = {
      termsConditions: searchParams?.get( 'termsConditions' ),
      newsletters: searchParams?.get( 'newsletters' )
    };
    const pspReference = parsed.pspReference;
    const additionalData = parsed?.additionalData;
    yield put( setPspReference( pspReference ) );
    yield put( setMaskedCardDetails( additionalData ) );
    yield put( placeOrder( { params } ) );
  }
  catch ( error ) {
    yield put( pageLoading( false ) );
    console.error( '3DS confirmation failed', error );
  }
}
`

Thanks in Advance :)
