### ISSUE TITLE
Fire event when additional action has loaded successfully

### ISSUE THREAD

**Issue by bitbytebit1** [Adyen/adyen-web#941]
**Describe the bug**
No event is fired when the Swish QR code is ready

**To Reproduce**
On desktop
Select Swish as a payment method
Click pay
A QR code is displayed 

**Expected behavior**
On desktop
Select Swish as a payment method
Click pay
A QR code is displayed 
An event is fired indicating the QR code has loaded successfully 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Desktop

**Additional context**
We would like to scroll the QR code into view, currently we are forced to wait arbitrary amount of time

**Comment by marcperez** [comment]
Hi @bitbytebit1,

Thanks for reaching. This seems like an idea worth exploring.
We will discuss internally and come back to you as soon as possible.

In the meantime, could you maybe tell us a bit more about an example use case where such event could be useful?

**Comment by bitbytebit1** [comment]
Here is an example of how we are getting around this currently.
If dropin.handleAction returned a promise that resolved once the QR code had finished booting up then we could simply wait for it to resolve and perform any additional actions needed then

```onSubmit: (state, dropin) => {
  this.debug && console.log('ADYEN.onSubmit: ', state);
  if (this.ADYEN_DROPIN?.data?.paymentMethod?.type === 'applepay' && !this.ADYEN_DROPIN?.data?.paymentMethod?.applePayToken) {
    console.debug('Apple pay payment does not have token! Cancel onSubmit');
    return;
  }
  this.apiMakePayment(state.data)
    .then((response) => {
      if (response.action) {
        dropin.handleAction(response.action);
        if (response.action.paymentMethodType === 'swish' && response.action.type === 'qrCode') {
          // Here we are forced to wait an abitrary amount of time
          setTimeout(() => {
            this.elems.dropinContainer.scrollIntoView();
          }, 100);
        }
      } else {
        this.redirectToPaymentCompletePage(response);
      }
    })
}```

**Comment by marcperez** [comment]
Thanks for the example @bitbytebit1, that makes sense. We'll discuss internally and update this ticket as soon as possible.

**Comment by sponglord** [comment]
@bitbytebit1 - the next release of adyen-web will contain this PR: #1975 
In keeping with our current policy of providing callbacks that you can add to the configuration for checkout we have added an `onActionHandled` callback (details in the [PR](https://github.com/Adyen/adyen-web/pull/1975))
