### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by RIAEvangelist** [Adyen/adyen-web#943]
**Describe the bug**
A CORS issue is present with the log API while this is not a breaking bug, it is ugly and would cause strict front-end testing to fail.

This is using `"@adyen/adyen-web": "^4.2.1"`

**To Reproduce**
1. Use the adyen-web UMD module

**Expected behavior**
No errors should be produced by using our module.

**Screenshots**

![image](https://user-images.githubusercontent.com/369041/114242145-42f0d180-993f-11eb-9a47-b4358a62b7a8.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: 4.2.1

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all

**Comment by Flyfoxs** [comment]
I have same issue.

**Comment by marcperez** [comment]
Hi @RIAEvangelist / @Flyfoxs,

This error is due to an incorrect `clientKey` or to an incorrectly configured list of allowed origins on the `clientKey` configuration. Please, check the [Client-side authentication](https://docs.adyen.com/development-resources/client-side-authentication)  documentation page for more details on how to create a `clientKey` and how to set a list of allowed origins.

Also, please verify the right environment is being set (`test`/`live`).

If the problem persists, please [contact our support team](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420). 

Hope this helps!

**Comment by Flyfoxs** [comment]
I fix the issue by:
![image](https://user-images.githubusercontent.com/11268302/114531500-89676880-9c7e-11eb-86f3-ff263b06860c.png)

**Comment by marcperez** [comment]
> I fix the issue by:
> ![image](https://user-images.githubusercontent.com/11268302/114531500-89676880-9c7e-11eb-86f3-ff263b06860c.png)

Yes! That's it, happy it all works @Flyfoxs!

**Comment by RIAEvangelist** [comment]
![image](https://user-images.githubusercontent.com/369041/114569687-0b797200-9c2a-11eb-9fce-0a1b429028d7.png)

Thanks for your help. The UI/UX and docs are super confusing about this. I will have to start guessing about what to do here. It seems @Flyfoxs guessed correctly. I can't tell if I need to use the Origin key instead of the client key with the Allowed Origin. The docs say Origin key is deprecated so I am using the client key. I really don't like not explicitly understanding what is going on because it can lead to bugs or potential vulnerabilities.

The Docs are also hard to figure out because when I search for information on CORS I either get nothing or content unrelated to my developer ecom account. I don't think the docs are really consumable and friendly around this unless you already understand the Adyen system or have someone to ask. It would be nice if the Docs were friendly enough and searchable in a way devs wouldn't need to ask for help finding these things.

![cors](https://user-images.githubusercontent.com/369041/114570388-a5411f00-9c2a-11eb-9c39-d15746146ab1.PNG)

Also, for my implementation, I have to use my merchant account, but in the account dashboard under API configuration I do not have any links to the merchant account settings, only the company accounts. This is also super confusing what account am I supposed to use, and why are there so many? Should I be using my merchant account for development or my company account? Since I need to use my merchant account to connect to the API, I expect to see my merchant account in the API settings. This makes me uncomfortable because I feel like I am changing settings on the company account when I just want to change settings on the account I use to connect to the API.

![image](https://user-images.githubusercontent.com/369041/114571512-9313b080-9c2b-11eb-971e-d4cf9faf2834.png)
 
There doesn't seem to be consistent messaging and terminology across the development resources, platforms, docs, and implementations. Things may seem clear to someone who is already familiar with the system, but when you first try integrating, it seems impossible without handholding. And I don't really want my handheld, I want to look things up and do it on my own. In order to allow this sort of experience, I think the developer resources will need to align on a standard and consistent way of talking about our systems and integrations.

**Comment by RIAEvangelist** [comment]
I think this ticket should be left open but renamed to a documentation issue based on the above. It will continue to be experienced by others until there is clear documentation around the issue and the process we have to alleviate the issue.

**Comment by nickcaballero** [comment]
Agreed, I ran into this same issue recently and happened to realize that the origin was missing.

**Comment by RIAEvangelist** [comment]
The docs stuff and CA will end up being brought inhouse to the DevEX / Devadvocacy teams.

For the CORS issue itself though, a nice way to help devs with this would be a 

```js 

try{
    fetch(...)
}catch(e){
    console.log(...info to cors fix..., link);
}

```

Perhaps even a global fetch interface for the class that wrapped all calls in a single handler to document errors. We can use fancy logs to include actual links to make solutions very dev-friendly to reduce the overhead on docs and customer support for this sort of issue.
