### ISSUE TITLE
Module '"../../types"' has no exported member 'AddressSchema'

### ISSUE THREAD

**Issue by LukasDrP** [Adyen/adyen-web#952]
**Describe the bug**
Since 4.2.x i get an error that "AdressScheme" could not get imported:

```
Error: node_modules/@adyen/adyen-web/dist/types/components/Card/types.d.ts:2:10 - error TS2305: Module '"../../types"' has no exported member 'AddressSchema'.

2 import { AddressSchema, BrowserInfo } from '../../types';
```

**To Reproduce**
1. imported adyen web
2. get the Error during complie time

**Expected behavior**
Complile without Errors 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser -
 - Version 4.2.0-4.2.1

**Comment by pabloai** [comment]
Hi @LukasDrP, and thanks for reaching out.

A fix for this issue has been added and will be included in our next patch version.
It seems we were missing the type check in our Github actions. This was also fixed so this shouldn't happen again.
I'm closing this ticket, but feel free to reach us out again in the future. Have a nice day!
