### ISSUE TITLE
Google Pay: onSubmit called twice when using custom pay button

### ISSUE THREAD

**Issue by bitbytebit1** [Adyen/adyen-web#972]
**Describe the bug**
When using Google Pay with a custom pay button the onSubmit method is called twice

**To Reproduce**
Create a drop configured for google pay and "showPayButton" set to false and a onSubmit callback
Call dropin.submit()
Pay via google pay

**Expected behavior**
onSubmit should only be called once

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Tested on drop in version 4.2.1 and 3.21.1

**Comment by marcperez** [comment]
Hi @bitbytebit1,

Thanks for reaching. We were able to reproduce this issue and we released a fix in `v4.3.0`. I'll close this issue, but feel free to reopen if the issue persists. Hope this helps!

**Comment by bitbytebit1** [comment]
@marcperez , any updates on when the 4.3.0 will be released for script?

**Comment by marcperez** [comment]
Hi @bitbytebit1, it should be already live. The [release notes](https://docs.adyen.com/online-payments/release-notes#web-components-4-3-0) will be updated today through the day.
