### ISSUE TITLE
PayPal smart button onSubmit() event

### ISSUE THREAD

**Issue by emidev98** [Adyen/adyen-web#995]
**Describe the bug**
Dear Adyen Team, 

We have seen in one of the most recently releases [3.22.1](https://github.com/Adyen/adyen-web/releases/tag/v3.22.1) tha onSubmit event is not triggered anymore from the web component when the customer click the [PayPal smart pay button](https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/components/PayPal/Paypal.tsx#L86).

How can we do the /makePayment call if the component do not send the onSubmit anymore? Because I have seen that in the documentation is explained the next way: [**When the shopper selects the PayPal Smart Payment button, Drop-in calls the onSubmit event, which contains a state object.**](https://docs.adyen.com/payment-methods/paypal/web-drop-in#make-a-payment)

**Comment by marcperez** [comment]
Hi @emidev98,

Thanks for reaching. The Paypal component should be calling the `onSubmit` event as any other component. The only difference in this case is that it's not possible to programmatically trigger the submit behavior from a custom "Pay" button (`component.submit()`) due to how this specific payment method works.
The change mentioned in `3.22.1` just adds a warning to help debug this use case, but shouldn't block the `onSubmit` event.

If you're experiencing any issues related to this, could you provide us more information on how those events are defined in your application and whether you're using a custom button?

**Comment by emidev98** [comment]
Hello @marcperez, I have seen that the event **onSubmit** of the **dropin** is not triggered when the customer click the PayPal smart button but instead of that the **onSubmit** from the **paypal** component is triggered.

This is how I could make it work (moving the onSubmit from dropin to the paypal component):
```
let config = {
    paymentMethodsConfiguration: {
      paypal: {
        ...
        onSubmit : (state, component) =>{
            // Do POST:/payment
        }
        ...
      }
    }
}
const checkout = new Checkout(config);
```

This is how we had it implemented before (but the event is not working anymore on the **onSubmit** event from dropin when the customer click PayPal):
```
let config = {
    showPayButton: true,
    paymentMethodsConfiguration: {
      paypal: {
        ... 
      }
    }
}
const checkout = new Checkout(config);
checkout.create('dropin', {
    onSubmit: (state, component) => {
        // DO POST:/payment
    }
};
```
We have not overwrite the onSubmit from paypal in our previous implementation, but now seems like we need to overwrite it. 
I guess that's how should work from now, right? Because I got a little bit confused [with the documentation](https://docs.adyen.com/payment-methods/paypal/web-drop-in#make-a-payment).

Thank you very much for the info!

**Comment by ribeiroguilherme** [comment]
Hi @emidev98 ,

Thanks for reaching out to us, and sorry for the delay. The `onSubmit` is defined as parameter of the `new Checkout` object, and it should work as you expected to work. I tested on the current version and it works.  Might be that there was a bug on 3.22.1, but now it seems to be fixed. I am going to close this issue, but feel free to reach out if you need any help!
